amplication/amplication

packages/amplication-server/package-lock.json, packages/amplication-server/package.json, packages/amplication-server/src/core/auth/github.strategy.spec.ts, packages/amplication-server/src/core/auth/github.strategy.ts
=> Fix GitHub Strategy

packages/amplication-client/src/Layout/MainLayout.tsx, packages/amplication-client/src/User/Login.tsx
=> Clear cache on logout

packages/amplication-server/src/core/auth/githubStrategyConfig.service.spec.ts, packages/amplication-server/src/core/auth/githubStrategyConfig.service.ts
- Adds support for providing GitHub client secret in env var
- Add support for providing GitHub scope in env var
- Tests GitHub config service
=> Fix GitHub Login

packages/amplication-data-service-generator/src/resource/test/create-test.ts
Create null values for lookup types
=> Data Service Generator: Fix create test values

packages/amplication-data-service-generator/src/create-data-service.ts, packages/amplication-data-service-generator/src/resource/create-resource.ts
Make data service generator logs to be more informative
=> Improve logs of data service generator

packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts, packages/amplication-data-service-generator/test/seed.ts
=> Move seed outside the generated app

.vscode/settings.json, packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json, packages/amplication-data-service-generator/src/prisma/create-prisma-schema.spec.ts, packages/amplication-data-service-generator/src/prisma/create-prisma-schema.ts
Make Prisma fields optional if they are not required and are not list fields.
Resolves #480
=> Fix generated Prisma schema optional fields

packages/amplication-data-service-generator/src/resource/controller/controller.template.ts, packages/amplication-data-service-generator/src/resource/dto/create-dto.spec.ts, packages/amplication-data-service-generator/src/resource/dto/create-dto.ts, packages/amplication-data-service-generator/src/static/prisma.util.spec.ts, packages/amplication-data-service-generator/src/static/prisma.util.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts
=> DTO One-to-One Lookup Field

packages/amplication-client/src/Entity/DataTypeSelectField.tsx
=> Fix entity field properties

packages/amplication-client/src/App.tsx, packages/amplication-client/src/Components/UserBadge.tsx, packages/amplication-client/src/Entity/NewEntityField.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/util/analytics.ts
New methods to collect user properties:
Collect userId and Sign up date
=> Event tracking

packages/amplication-server/src/core/entity/entity.service.ts
Fix issue with building the sample app
=> Sample app build

packages/amplication-client/src/Application/ApplicationLayout.tsx, packages/amplication-client/src/CommandPalette/CommandPalette.scss, packages/amplication-client/src/CommandPalette/CommandPalette.tsx, packages/amplication-client/src/Layout/MainLayout.scss, packages/amplication-client/src/Layout/MainLayout.tsx, packages/amplication-client/src/Layout/MenuItem.scss, packages/amplication-client/src/Layout/MenuItem.tsx
=> Menu items style

packages/amplication-client/src/Components/TextInput.scss, packages/amplication-client/src/Components/TextInput.tsx
TextInput on error state was missing the red border
=> Fix TextInput error style

packages/amplication-client/src/Components/UserBadge.tsx, packages/amplication-client/src/Entity/NewEntity.tsx
Add missing tooltip to user badge
=> Add user badge tooltip

packages/amplication-client/src/Components/TextInput.scss, packages/amplication-client/src/Entity/NewEntity.tsx
=> Fix entity plural display name

packages/amplication-client/src/Components/ToggleButton.scss
=> Fix toggle button visible in FireFox

packages/amplication-server/src/core/app/app.resolver.ts, packages/amplication-server/src/core/app/app.service.ts, packages/amplication-server/src/core/app/dto/DiscardPendingChangesArgs.ts, packages/amplication-server/src/core/app/dto/PendingChangesDiscardInput.ts, packages/amplication-server/src/core/app/dto/index.ts, packages/amplication-server/src/core/entity/entity.service.spec.ts, packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/schema.graphql
Server side logic for discard changes
=> Discard pending changes

packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/EntityListItem.tsx
=> Entity List style

packages/amplication-client/src/Components/TextField.tsx, packages/amplication-client/src/Components/TextInput.scss, packages/amplication-client/src/Entity/OptionSet.scss, packages/amplication-client/src/style/mixin.scss
=> Option Set - Auto update value based on label

packages/amplication-client/package-lock.json, packages/amplication-client/package.json, packages/amplication-client/src/App.tsx, packages/amplication-client/src/Application/ApplicationLayout.tsx, packages/amplication-client/src/Application/NewApplication.tsx, packages/amplication-client/src/Components/Dialog.scss, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/VersionControl/BuildNewVersion.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/PendingChangesStatus.tsx, packages/amplication-client/src/index.scss
Use Ctrl/Command+Enter on modals to submit-
Use Ctrl/Command+Shift+G to navigate to "Pending Changes"
=> Keyboard Shortcuts

packages/amplication-client/src/CommandPalette/CommandPalette.tsx
Fix he URL for the "publish" command
=> Command palette builds

packages/amplication-server/src/core/deployment/deployment.controller.ts, packages/amplication-server/src/core/deployment/deployment.module.ts, packages/amplication-server/src/core/deployment/deployment.resolver.ts, packages/amplication-server/src/core/deployment/deployment.service.spec.ts, packages/amplication-server/src/core/deployment/deployment.service.ts, packages/amplication-server/src/core/deployment/dto/CreateDeploymentArgs.ts, packages/amplication-server/src/core/deployment/dto/CreateDeploymentDTO.ts, packages/amplication-server/src/core/deployment/dto/Deployment.ts, packages/amplication-server/src/core/deployment/dto/DeploymentCreateInput.ts, packages/amplication-server/src/core/deployment/dto/DeploymentOrderByInput.ts, packages/amplication-server/src/core/deployment/dto/DeploymentWhereInput.ts, packages/amplication-server/src/core/deployment/dto/EnumDeploymentStatus.ts, packages/amplication-server/src/core/deployment/dto/EnumDeploymentStatusFilter.ts, packages/amplication-server/src/core/deployment/dto/FindManyDeploymentArgs.ts, packages/amplication-server/src/core/deployment/dto/FindOneDeploymentArgs.ts, packages/amplication-server/src/core/permissions/permissions.service.spec.ts, packages/amplication-server/src/core/permissions/permissions.service.ts, packages/amplication-server/src/enums/AuthorizableResourceParameter.ts
=> Deployment

packages/amplication-server/src/core/app/app.module.ts, packages/amplication-server/src/core/app/app.resolver.ts, packages/amplication-server/src/core/environment/dto/EnvironmentOrderByInput.ts, packages/amplication-server/src/core/environment/dto/EnvironmentWhereInput.ts, packages/amplication-server/src/core/environment/dto/FindManyEnvironmentArgs.ts, packages/amplication-server/src/core/environment/dto/index.ts, packages/amplication-server/src/core/environment/environment.service.spec.ts, packages/amplication-server/src/core/environment/environment.service.ts, packages/amplication-server/src/schema.graphql
=> App resolve field environments

packages/amplication-server/src/core/entity/entity.service.spec.ts
tested thrown error 'Record not Found' for deleteEntityPermissionField function, in entity.service.ts
=> Added test to check Record not Found in entity service

packages/amplication-server/src/core/app/app.service.spec.ts, packages/amplication-server/src/core/app/app.service.ts, packages/amplication-server/src/core/entity/entity.service.ts
=> Fix sample app

packages/amplication-server/src/core/containerBuilder/containerBuilderRoot.module.ts, packages/amplication-server/src/core/docker/docker.module.ts, packages/amplication-server/src/core/docker/docker.service.ts
Add simple Nest.js wrapper around [dockerode](https://github.com/apocas/dockerode)
=> Docker Service

packages/amplication-server/src/core/build/build.service.spec.ts, packages/amplication-server/src/core/build/build.service.ts
Update the build with created images.
Improve build service tests
=> Save build images in build service

packages/amplication-data-service-generator/src/resource/dto/create-dto.spec.ts, packages/amplication-data-service-generator/src/resource/dto/create-dto.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts
Allow null values only for optional scalar fields
=> Fix DTO Optional Lookup Field

Dockerfile
Extract package sources in an initial stage
=> DRY Dockerfile

packages/amplication-client/src/VersionControl/BuildList.scss, packages/amplication-client/src/VersionControl/BuildList.tsx, packages/amplication-client/src/VersionControl/NextBuild.tsx
=> Build list style

terraform/envs/dev/main.tf, terraform/envs/production/main.tf, terraform/modules/apps_env_baseline/main.tf, terraform/modules/apps_env_baseline/variables.tf
Give editor permission to default compute of platform project
=> Fix Apps ACL

packages/amplication-client/src/VersionControl/BuildNewVersion.tsx, packages/amplication-client/src/VersionControl/NextBuild.tsx
=> Default build message based on last commits

packages/amplication-server/src/core/app/app.resolver.spec.ts
-Add all tests for App Resolver
-Included 2 ready-to-go tests marked with .skip for functions using @UserEntity
=> Add all tests to App Resolver

packages/amplication-data-service-generator/src/static/package.json, packages/amplication-data-service-generator/src/static/prisma/clean.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-deployer/src/gcp/modules/server/main.tf, packages/amplication-server/package.json, packages/amplication-server/prisma/clean.ts
- Create `db:clean` script
- Run `db:clean` in each deploy of apps
=> Clean Deployed App Database on Every Deploy

packages/amplication-server/src/core/entity/constants.ts, packages/amplication-server/src/core/entity/entity.service.spec.ts, packages/amplication-server/src/core/entity/entity.service.ts
=> Entity default permissions

packages/amplication-client/debug.log, packages/amplication-client/src/Components/ProgressBar.tsx, packages/amplication-client/src/Components/Timer.tsx, packages/amplication-client/src/VersionControl/ActionLog.scss, packages/amplication-client/src/VersionControl/ActionLog.tsx, packages/amplication-client/src/VersionControl/Build.tsx, packages/amplication-client/src/VersionControl/Builds.tsx, packages/amplication-client/src/VersionControl/constants.ts, packages/amplication-client/src/style/parameters.scss
Show action log status, timer, and version number 
resolves #466
=> feat(client):action-log

packages/amplication-data-service-generator/README.md
- Add a short summary of the package
- List the technologies used by the generator
- Describe how to test the generator
=> Data Service Generator: Readme

packages/amplication-server/src/core/entity/entity.service.ts
=> Fix - Build uncommitted changes

packages/amplication-container-builder/package-lock.json, packages/amplication-container-builder/package.json, packages/amplication-container-builder/src/builder/InvalidBuildProviderState.ts, packages/amplication-container-builder/src/cloud-build/CloudBuildProvider.ts, packages/amplication-container-builder/src/cloud-build/config.spec.ts, packages/amplication-container-builder/src/cloud-build/config.ts, packages/amplication-container-builder/src/cloud-build/logging.ts, packages/amplication-deployer/package-lock.json, packages/amplication-deployer/package.json, packages/amplication-deployer/src/deployer/InvalidDeployProviderState.ts, packages/amplication-deployer/src/gcp/GCPProvider.spec.ts, packages/amplication-deployer/src/gcp/GCPProvider.ts, packages/amplication-deployer/src/gcp/config.spec.ts, packages/amplication-deployer/src/gcp/config.ts, packages/amplication-deployer/src/gcp/logging.ts
Add tags to cloud builds and improve logging of container builder and deployer
=> Cloud Build Tags and Logs

packages/amplication-client/src/Entity/constants.ts
=> Fix Geographic Location display name

packages/amplication-client/src/Entity/EntityFieldList.tsx, packages/amplication-client/src/Entity/NewEntityField.tsx, packages/amplication-client/src/Permissions/EntityPermissionFields.tsx
=> Update cache with new entity field

packages/amplication-client/src/Permissions/EntityPermissionAction.tsx, packages/amplication-client/src/Roles/NewRole.tsx
=> Update cache with new roles

packages/amplication-client/src/Entity/EntityFieldList.tsx, packages/amplication-client/src/Entity/EntityFieldListItem.tsx, packages/amplication-server/src/core/entity/dto/DeleteEntityFieldArgs.ts, packages/amplication-server/src/core/entity/dto/index.ts, packages/amplication-server/src/core/entity/entity.service.ts
=> Delete entity field

packages/amplication-client/src/Entity/SchemaField.tsx, packages/amplication-data/src/schemas/lookup.json
=> Related entity display name

packages/amplication-client/src/Application/Applications.scss
=> Style applications list

.vscode/tasks.json, packages/amplication-data-service-generator/src/create-data-service.ts, packages/amplication-data-service-generator/src/resource/controller/controller.template.ts, packages/amplication-data-service-generator/src/resource/controller/to-many.template.ts, packages/amplication-data-service-generator/src/resource/module/module.template.ts, packages/amplication-data-service-generator/src/resource/test/create-test.ts, packages/amplication-data-service-generator/src/resource/test/test.template.ts, packages/amplication-data-service-generator/src/static/app.controller.ts, packages/amplication-data-service-generator/src/static/auth/auth.module.ts, packages/amplication-data-service-generator/src/static/auth/auth.service.spec.ts, packages/amplication-data-service-generator/src/static/auth/basic.strategy.ts, packages/amplication-data-service-generator/src/static/auth/basicAuth.guard.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> Fix Generated App Tests

packages/amplication-client/src/Entity/EntityFieldList.tsx, packages/amplication-client/src/Entity/EntityFieldListItem.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/EntityListItem.tsx, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/Entity/NewEntityField.tsx, packages/amplication-client/src/Roles/NewRole.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/index.tsx
Resolves #735 
Bump ApolloClient and replace caching mechanism to work on the cache objects instead of a query
=> Fix client caching issue with new ApolloClient

packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json, packages/amplication-data-service-generator/src/resource/controller/controller.template.ts, packages/amplication-data-service-generator/src/static/app.controller.ts, packages/amplication-data-service-generator/src/static/main.ts, packages/amplication-data-service-generator/src/static/package-lock.json, packages/amplication-data-service-generator/src/static/package.json, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Add Swagger and API tags to controllers to generated apps
=> Data Service Generator: Swagger

packages/amplication-data-service-generator/src/resource/dto/create-dto-module.spec.ts, packages/amplication-data-service-generator/src/resource/dto/create-dto-module.ts, packages/amplication-data-service-generator/src/resource/dto/create-field-class-property.spec.ts, packages/amplication-data-service-generator/src/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/resource/dto/nestjs-swagger.util.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- Add `@ApiProperty()` decorator to DTO properties
=> DSG: Generated DTO Swagger

packages/amplication-server/src/core/entity/entity.service.ts
=> Fix - Compare shows false changes on entity permissions

.vscode/launch.json, packages/amplication-data-service-generator/scripts/generate-test-data-service.ts, packages/amplication-data-service-generator/src/resource/controller/controller.template.ts, packages/amplication-data-service-generator/src/resource/controller/create-controller.ts, packages/amplication-data-service-generator/src/static/errors.ts, packages/amplication-data-service-generator/src/static/prisma.util.spec.ts, packages/amplication-data-service-generator/src/static/prisma.util.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
- Fix generate test data service
- Handle not found in the update and delete methods.
- Add swagger response
=> DSG: Swagger Responses

packages/amplication-server/src/core/app/app.resolver.spec.ts
-Add should create an app test.
-Add should get a pending change test.
=> Add UserEntity related tests to AppResolver

packages/amplication-server/src/core/entity/entity.resolver.spec.ts, packages/amplication-server/src/core/entity/entity.resolver.ts, packages/amplication-server/src/core/entity/entity.service.spec.ts, packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/core/entity/entityVersion.resolver.ts
=> Entity get fields

packages/amplication-server/src/core/entity/entity.service.ts
=> Field display name

packages/amplication-client/src/Components/DataGrid.scss, packages/amplication-client/src/Entity/EntityFieldList.tsx, packages/amplication-client/src/Entity/EntityFieldListItem.tsx, packages/amplication-client/src/Entity/NewEntityField.tsx
Navigate from field list to related entities
=> Navigate to related entity

packages/amplication-server/src/core/organization/organization.resolver.spec.ts
-Add all tests for Organization Resolver
=> Add tests for Organization resolver

packages/amplication-server/src/core/build/build.resolver.spec.ts
-Add all tests for Build Resolver
=> Add all tests for Build Resolver

packages/amplication-server/README.md
@iddan please see that all links are making sense, or maybe you think we should add CLI command instead for any one of them?
=> Update README.md prerequisite installs

packages/amplication-client/src/Components/TimeSince.scss, packages/amplication-client/src/Components/TimeSince.tsx, packages/amplication-client/src/Components/UserAndTime.scss, packages/amplication-client/src/VersionControl/Commit.scss, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/PendingChange.tsx, packages/amplication-client/src/VersionControl/PendingChanges.scss, packages/amplication-client/src/style/css-variables.css
=> Pending changes style

packages/amplication-client/src/Components/Button.tsx, packages/amplication-client/src/Entity/NewEntityField.tsx, packages/amplication-design-system/package.json, packages/amplication-design-system/src/components/Button.tsx, packages/amplication-design-system/src/index.ts
imported Button from Storybook into Client
=> added Button to design system

packages/amplication-server/src/core/auth/auth.service.ts
- Change all ApolloErrors to AmplicationErrors throughout the entire service.
=> Server: Fix No Account Found Logging Error

packages/amplication-server/src/core/build/build.service.spec.ts, packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/deployment/deployment.service.spec.ts, packages/amplication-server/src/core/environment/environment.service.spec.ts
- Add tests for Environment Service
- Add tests for Deployment Service
- Change handleContainerBuilderResult method in Build Service to public
- Add tests for Build Service
=> Server: Auto Deploy Tests

.vscode/settings.json
Add directories that should always be excluded
=> Improve VSCode Exclude

packages/amplication-client/src/Application/ApplicationLayout.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/LastCommit.tsx
Immediately refresh commit list after submit
=> Client: Fix Commit Refresh

packages/amplication-client/config-overrides.js, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/Roles/NewRole.tsx
- Deduplicate styled-components
- Fix name of `NEW_ENTITY_FRAGMENT` fragment
- Remove unused type RouteParams from NewRole
=> Fix client warnings

packages/amplication-client/README.md, packages/amplication-server/README.md
Add instruction to install npm 7 to server and client docs
=> Document npm 7

packages/amplication-client/src/Pages/EntityFieldMultiSelect.tsx, packages/amplication-client/src/Pages/EntityPageForm.tsx, packages/amplication-design-system/src/components/Checkbox/Checkbox.stories.tsx, packages/amplication-design-system/src/components/Checkbox/CheckboxField.scss, packages/amplication-design-system/src/components/Checkbox/CheckboxField.tsx, packages/amplication-design-system/src/components/Checkbox/CheckboxList.stories.tsx, packages/amplication-design-system/src/components/Checkbox/CheckboxListField.tsx, packages/amplication-design-system/src/index.ts
Move CheckboxField and CheckboxListField from client/components to design-system
The checkbox style and display is still not 100%, but it is currently used only in "EntityPage" which is not relevant.
When utilizing either field in a screen, the style should be updated
=> Design system: checkbox

packages/amplication-data-service-generator/src/admin/static/package-lock.json, packages/amplication-data-service-generator/src/admin/static/package.json, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-design-system/package-lock.json, packages/amplication-design-system/package.json
Make fewer packages peer dependencies and add peer dependencies to generated apps
=> Design System: Reduce Peer dependencies

packages/amplication-data-service-generator/src/admin/create-admin.ts, packages/amplication-data-service-generator/src/admin/entity/create-entities-components.ts, packages/amplication-data-service-generator/src/admin/entity/create-entity-components-modules.ts, packages/amplication-data-service-generator/src/admin/entity/create-entity-components.ts, packages/amplication-data-service-generator/src/admin/entity/create-entity-select-components.ts, packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts, packages/amplication-data-service-generator/src/admin/entity/entity-component/create-entity-component.ts, packages/amplication-data-service-generator/src/admin/entity/entity-select-component/create-entity-select-component.ts, packages/amplication-data-service-generator/src/admin/entity/entity-select-component/entity-select-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/new-entity-component/create-new-entity-component.ts, packages/amplication-data-service-generator/src/create-data-service.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
For each entity create a select component and use it when the entity is used in a lookup field of another entity
=> Admin UI : Entity select components

packages/amplication-data-service-generator/src/admin/create-admin.ts, packages/amplication-data-service-generator/src/admin/create-enum-roles.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> DSG: Create enum roles

packages/amplication-data-service-generator/src/admin/create-roles-module.ts, packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts, packages/amplication-data-service-generator/src/admin/entity/create-field-value.ts, packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx, packages/amplication-data-service-generator/src/admin/static/src/user/RoleSelect.tsx, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/tests/entities.ts, packages/amplication-data-service-generator/src/tests/roles.ts, packages/amplication-data-service-generator/src/util/ast.ts
Adds `<RoleSelect />` component and uses it for fields with data type `Roles`.
Resolves #946
=> Admin UI - Role select

packages/amplication-data-service-generator/src/static/docker-compose.yml, packages/amplication-data-service-generator/test/tsconfig.json
- Fix type errors for e2e spec
- Remove image parameter from docker-compose
=> DSG: Fix E2E CI

packages/amplication-data-service-generator/src/admin/app/App.template.tsx, packages/amplication-data-service-generator/src/admin/app/create-app.ts, packages/amplication-data-service-generator/src/admin/entity/entity-index-component/create-entity-index-component.ts, packages/amplication-data-service-generator/src/admin/entity/entity-index-component/entity-index-component.template.tsx, packages/amplication-data-service-generator/src/admin/static/src/auth.ts, packages/amplication-data-service-generator/src/admin/static/src/components/PrivateRoute.tsx, packages/amplication-data-service-generator/src/admin/static/src/use-authenticated.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> Redirect to login if user is not logged in

packages/amplication-data-service-generator/src/admin/entity/entity-component/create-entity-component.ts, packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts, packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/new-entity-component/create-new-entity-component.ts, packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> DSG: Use auto import in components

packages/amplication-data-service-generator/src/admin/entity/entity-component/create-entity-component.ts, packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/new-entity-component/create-new-entity-component.ts, packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx
=> Admin UI breadcrumbs

packages/amplication-data-service-generator/src/admin/app/create-app.ts, packages/amplication-data-service-generator/src/admin/entity/create-field-value.ts, packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts, packages/amplication-data-service-generator/src/admin/entity/entity-list-component/entity-list-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/entity-select-component/entity-select-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/entity-title-component/entity-title-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx, packages/amplication-data-service-generator/src/admin/static/src/Login.tsx, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- Remove unused imports from app
- Move list fields to a constant
- Handle loading and error in title component
- Remove unused error
- Use DTO fields only in entity list
- Display server errors correctly
=> DSG: Fix Admin Build Errors

packages/amplication-data-service-generator/src/server/resource/controller/controller.template.ts, packages/amplication-data-service-generator/src/server/resource/test/create-controller-spec.ts, packages/amplication-data-service-generator/src/server/seed/create-seed.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts
For each datatype add a field for the example entity field and fix code where breaks
=> Test More Fields in default user entity

packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> DSG: Fix creation of enum array DTO fields

packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Add class transformer type decorator for date fields
Resolves #699
=> DSG: Fix Date Fields

packages/amplication-client/src/Entity/EntityFieldForm.tsx, packages/amplication-server/src/core/entity/entity.service.ts
=> Prevent required lookup user

packages/amplication-data-service-generator/src/server/resource/dto/create-entity-dto.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.ts, packages/amplication-data-service-generator/src/server/resource/service/create-service.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/util/field.ts
Remove password field from entity DTO and where input
=> DSG: Remove password field from DTOs

packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts, packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts
=> Admin UI: List column order

packages/amplication-data-service-generator/src/admin/entity/new-entity-component/new-entity-component.template.tsx, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> DSG: Admin UI Redirect After Create

packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/entity-select-component/entity-select-component.template.tsx, packages/amplication-data-service-generator/src/admin/entity/entity-title-component/entity-title-component.template.tsx, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> DSG: Admin UI: Empty Title

packages/amplication-data-service-generator/src/admin/entity/entity-component/entity-component.template.tsx, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> Admin UI: delete button

packages/amplication-design-system/src/components/DataGrid/DataGrid.scss, packages/amplication-design-system/src/components/DataGrid/DataGrid.stories.tsx, packages/amplication-design-system/src/components/DataGrid/DataGrid.tsx
=> Design System: Fix handling of data grid for long titles

packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
=> Client: update poll time

packages/amplication-data-service-generator/README.md
Add missing instructions to data service generator readme
=> DSG: Document Development

packages/amplication-server/src/core/entity/entity.service.spec.ts, packages/amplication-server/src/core/entity/entity.service.ts
- Add assertion for call to find many in delete one test
- Add test for delete one of user entity
=> Server: Entity Service Spec Coverage

packages/amplication-client/src/Application/ApplicationCard.tsx
=> Remove app version display

packages/amplication-client/src/Entity/EntityFieldListItem.tsx, packages/amplication-client/src/Entity/EntityListItem.tsx, packages/amplication-client/src/Entity/constants.ts
=> Delete user button

packages/amplication-client/src/Entity/EntityFieldListItem.tsx, packages/amplication-client/src/Entity/EntityListItem.tsx
=> Align button on grid

packages/amplication-e2e-tester/tests/delete-entity.spec.ts
tests deleting an entity from app using jest-pupeteer
=> add test delete entity

packages/amplication-e2e-tester/tests/functions.ts, packages/amplication-e2e-tester/tests/pending-changes.spec.ts
tests adding new entity to app and check if the change added to the pending changes list using jest-pupeteer
=> E2E Tester: Pending Changes

packages/amplication-client/.prettierignore, packages/amplication-data-service-generator/.eslintignore, packages/amplication-data-service-generator/.prettierignore, packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts, packages/amplication-data-service-generator/src/server/resource/controller/create-data-mapping.spec.ts, packages/amplication-data-service-generator/src/server/resource/controller/create-data-mapping.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/find-many-args.template.ts, packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts, packages/amplication-data-service-generator/src/server/resource/resolver/resolver.template.ts, packages/amplication-data-service-generator/src/server/static/.pretttierignore, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data/.prettierignore, packages/amplication-design-system/.eslintignore, packages/amplication-design-system/.prettierignore, packages/amplication-e2e-tester/.prettierignore, packages/amplication-server/.prettierignore
- Add `@Field()` for one relation in input types
- Add data mapping to resolver
- Fix type of find many args
=> DSG: Fix GraphQL DTOs

packages/amplication-client/src/VersionControl/PendingChange.tsx
removed version from PendingChange component
=> Client: hide entity version in Source Control Panel

packages/amplication-server/src/core/entity/entity.service.spec.ts
Add test for "update" and "delete" pending change
=> Server: Entity service test coverage

packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/EntityListItem.tsx
removed entity version from table
=> Client: Remove Entity Version from table

packages/amplication-client/src/Entity/RelatedFieldDialog.scss, packages/amplication-client/src/Entity/RelatedFieldDialog.tsx
=> Related field dialog

README.md, packages/amplication-container-builder/README.md, packages/amplication-container-builder/package.json
Document the container builder package and add it to the readme
=> Container Builder: Document and add a prepare command for it

packages/amplication-server/src/core/app/app.service.ts, packages/amplication-server/src/core/app/sampleApp.ts, packages/amplication-server/src/core/entity/entity.service.ts
Update sample app with the new relation fields spec
=> Update sample app

packages/amplication-client/src/Layout/MenuItem.tsx
=> Fix menu item title bug

packages/amplication-data-service-generator/.eslintignore, packages/amplication-data-service-generator/src/create-data-service-impl.ts, packages/amplication-data-service-generator/src/create-data-service-worker.js, packages/amplication-data-service-generator/src/create-data-service-worker.ts, packages/amplication-data-service-generator/src/create-data-service.ts, packages/amplication-data-service-generator/src/types.ts, packages/amplication-data-service-generator/src/util/worker-logging.ts, packages/amplication-server/src/core/github/github.service.ts
=> Data service worker

packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.spec.ts, packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.ts, packages/amplication-data-service-generator/src/server/resource/create-dtos.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-create-input.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-create-input.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-entity-dto.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-entity-dto.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-enum-dto.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-input.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-update-input.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-update-input.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-where-unique-input.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-where-unique-input.ts, packages/amplication-data-service-generator/src/server/resource/test/create-controller-spec.ts, packages/amplication-data-service-generator/src/server/seed/create-seed.spec.ts, packages/amplication-data-service-generator/src/server/seed/create-seed.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> Include entity name in enum fields

packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
=> Fix data type CreatedAt

packages/amplication-client/src/Application/ApplicationLayout.tsx, packages/amplication-client/src/Entity/EntityField.tsx
=> Fix pending changes count

packages/amplication-data-service-generator/src/server/static/src/auth/Credentials.ts, packages/amplication-data-service-generator/src/server/static/src/auth/LoginArgs.ts
Add missing ApiProperty and Field decorators
=> Add annotations to Credentials

packages/amplication-client/src/Application/ApplicationHome.tsx
keep the selected inner tab when navigating from and to the Home tab
=> Application home tab URL

packages/amplication-client/src/Application/ApplicationHome.tsx, packages/amplication-client/src/VersionControl/PendingChanges.scss, packages/amplication-design-system/src/components/Toggle/Toggle.scss
- [x ] changes counter - set rounded border
=> Style fixes

packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/Roles/RolesPage.tsx, packages/amplication-client/src/index.scss, packages/amplication-client/src/style/mixin.scss, packages/amplication-design-system/src/components/SelectField/SelectField.scss, terraform/envs/production/terraform.tfvars
Automatically select the first role when opening the roles page
=> Role list - select first role

packages/amplication-client/src/Entity/constants.ts, packages/amplication-client/src/Layout/DarkModeToggle.tsx, packages/amplication-client/src/Layout/ThemeProvider.tsx, packages/amplication-client/src/Layout/WelcomePage.scss, packages/amplication-client/src/Layout/WelcomePage.tsx, packages/amplication-client/src/User/GitHubLoginButton.scss, packages/amplication-client/src/User/GitHubLoginButton.tsx, packages/amplication-client/src/style/dark-css-variables.css, packages/amplication-client/src/style/light-css-variables.css
fix icons for datatype "roles"
=> datatype icons

packages/amplication-client/src/style/mixin.scss, packages/amplication-design-system/src/style/mixin.scss
Update label color to use black60 instead of black40
=> style: labels color

packages/amplication-client/src/Entity/DeleteEntityField.tsx, packages/amplication-client/src/Entity/EntityField.scss, packages/amplication-client/src/Entity/EntityField.tsx, packages/amplication-client/src/Entity/EntityFieldListItem.tsx, packages/amplication-design-system/src/components/Button/Button.scss
New DeleteField component .
it is now used in the field list and in the field form
=> Delete field component

packages/amplication-data-service-generator/src/admin/entity/entity-title-component/create-entity-title-component.ts, terraform/envs/production/main.tf, terraform/envs/production/variables.tf, terraform/modules/manual_deploy/main.tf, terraform/modules/manual_deploy/variables.tf
Do not use fields name "title" as the record title if the field type is lookup
=> fix(dsg): title fields

packages/amplication-client/src/Application/ApplicationHome.tsx, packages/amplication-client/src/Entity/Entity.tsx, packages/amplication-client/src/Entity/EntityFieldLinkList.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Layout/NavigationTabsContext.ts, packages/amplication-client/src/Layout/NavigationTabsProvider.tsx, packages/amplication-client/src/Layout/UseNavigationTabs.ts, packages/amplication-client/src/Pages/Pages.tsx, packages/amplication-client/src/Roles/RolesPage.tsx, packages/amplication-client/src/VersionControl/BuildPage.tsx, packages/amplication-client/src/VersionControl/CommitPage.tsx, packages/amplication-client/src/VersionControl/Commits.tsx, packages/amplication-client/src/VersionControl/PendingChangesPage.tsx
=> fix(client):reset tabs when switching apps

packages/amplication-client/src/Entity/EntityFieldForm.tsx
=> fix(client): allow single characters field names

packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-data-service-generator/src/create-data-service-worker.ts, packages/amplication-data-service-generator/src/create-data-service.ts, packages/amplication-data-service-generator/src/types.ts
=> fix(dsg): handle errors in DSG and reject

packages/amplication-client/src/VersionControl/DiscardChanges.tsx
=> fix(client):remove discarded changes from cache

packages/amplication-design-system/package-lock.json, packages/amplication-design-system/package.json, packages/amplication-design-system/src/components/RadioButton/RadioButtonField.scss, packages/amplication-design-system/src/components/RadioButton/RadioButtonField.stories.tsx, packages/amplication-design-system/src/components/RadioButton/RadioButtonField.tsx, packages/amplication-design-system/src/index.ts
add radio button field to design system
=> feat(design-system): radio button

packages/amplication-scheduler/src/config.schema.json
This addresses https://github.com/amplication/amplication/issues/1245
=> Fix scheduler regex for schedule format

packages/amplication-data-service-generator/src/server/static/README.md
Add missing command to the server's README 
npm run prisma:generate
=> fix(dsg): update server readme

packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts
=> fix(dsg): optional lookup fields on dto

packages/amplication-data-service-generator/src/server/resource/create-resource.ts, packages/amplication-data-service-generator/src/util/entity.ts
=> fix(dsg): entity plural name

packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts
Change organization in test data to be optional so e2e test pass
=> test(dsg):make organization optional

packages/amplication-design-system/package-lock.json, packages/amplication-design-system/package.json
Add formik to devDependencies in order for lerna to be able to build correctly
=> chore(design-system): make formik dev dependency

lerna.json, package-lock.json
=> chore: update lockFileVersion on root package-lock

packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.spec.ts, packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> fix(dsg): add 'references' argument on prisma schema for relation fields

packages/amplication-data-service-generator/src/server/resource/service/service.base.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> DSG: use async functions on serviceBase class

packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts, packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts, packages/amplication-data-service-generator/src/server/resource/create-resource.ts, packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts, packages/amplication-data-service-generator/src/server/resource/resolver/to-many.template.ts, packages/amplication-data-service-generator/src/server/resource/resolver/to-one.template.ts, packages/amplication-data-service-generator/src/server/resource/service/create-service.ts, packages/amplication-data-service-generator/src/server/resource/service/service.base.template.ts, packages/amplication-data-service-generator/src/server/resource/service/to-many.template.ts, packages/amplication-data-service-generator/src/server/resource/service/to-one.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/util/ast.ts
=> DSG: Add relation functions to entityServiceBase

.vscode/settings.json, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> DSG: add @Field on WhereUniqueInput

packages/amplication-data/src/schemas/decimalNumber.json, packages/amplication-data/src/schemas/wholeNumber.json, packages/amplication-server/.env
=> Remove min and max values for numeric fields

packages/amplication-cli/src/models.ts, packages/amplication-client/src/Entity/constants.ts, packages/amplication-client/src/models.ts, packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts, packages/amplication-data-service-generator/src/admin/entity/create-field-value.ts, packages/amplication-data-service-generator/src/models.ts, packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.spec.ts, packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.ts, packages/amplication-data-service-generator/src/server/resource/dto/class-validator.util.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/server/resource/dto/graphql-type-json.util.ts, packages/amplication-data-service-generator/src/server/resource/dto/type-fest.util.ts, packages/amplication-data-service-generator/src/server/seed/create-seed.spec.ts, packages/amplication-data-service-generator/src/server/seed/create-seed.ts, packages/amplication-data-service-generator/src/server/static/package-lock.json, packages/amplication-data-service-generator/src/server/static/package.json, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts, packages/amplication-data/src/data-type-to-schema.ts, packages/amplication-data/src/models.ts, packages/amplication-data/src/schemas/index.ts, packages/amplication-data/src/schemas/json.json, packages/amplication-server/prisma/migrations/20210417052925_data_type_json/migration.sql, packages/amplication-server/prisma/schema.prisma, packages/amplication-server/src/enums/EnumDataType.ts, packages/amplication-server/src/schema.graphql
=> New data type - JSON

README.md
=> Changing Readme.md Line 25

packages/amplication-client/src/VersionControl/BuildStatusIcons.tsx, packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts, packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-where-unique-input.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-where-unique-input.ts, packages/amplication-data-service-generator/src/server/resource/dto/filters.util.ts, packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/create-find-many-args.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/graphql/find-many/find-many-args.template.ts, packages/amplication-data-service-generator/src/server/resource/dto/type-fest.util.ts, packages/amplication-data-service-generator/src/server/static/src/util/BooleanFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/BooleanNullableFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/DateTimeFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/DateTimeNullableFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/FloatFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/FloatNullableFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/IntFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/IntNullableFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/JsonNullableFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/QueryMode.ts, packages/amplication-data-service-generator/src/server/static/src/util/StringFilter.ts, packages/amplication-data-service-generator/src/server/static/src/util/StringNullableFilter.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/util/ast.ts, packages/amplication-data-service-generator/src/version.ts
Add advanced scalar filters to generated APIs queries
Resolves #701
=> DSG: add resource filters

packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-where-input.ts, packages/amplication-data-service-generator/src/server/resource/util/test-data.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts
Do not include non-searchable fields in WhereInput class
=> DSG: searchable fields

packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-server/.env
EntityUpdateInput should have nullable: true for all gql decorator regardless if the field is required or not (for partial updates)
=> Add missing nullable for gql decorators

packages/amplication-data-service-generator/package.json, packages/amplication-data-service-generator/src/admin/static/package-lock.json, packages/amplication-data-service-generator/src/admin/static/package.json, packages/amplication-data-service-generator/src/admin/static/src/data-provider/graphqlDataProvider.ts, packages/amplication-data-service-generator/src/static/README.md, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> Chore/admin UI update apollo client

packages/amplication-client/src/Application/ApplicationCard.tsx
When there are no builds for an app, the lastBuildDate is undefined
=> fix(client): handle invalid time

packages/amplication-client/src/Application/CreateAppFromExcelForm.tsx, packages/amplication-client/src/EntitiesDiagram/EntitiesDiagram.scss, packages/amplication-client/src/EntitiesDiagram/EntitiesDiagram.tsx, packages/amplication-client/src/EntitiesDiagram/EntitiesDiagramEntity.tsx
allow users to delete an entity from the entity diagram
=> Feat(client):remove entity from diagram

packages/amplication-cli/src/models.ts, packages/amplication-client/src/Permissions/EntityPermissionField.tsx, packages/amplication-client/src/Permissions/EntityPermissionFields.tsx, packages/amplication-client/src/Permissions/PermissionsForm.tsx, packages/amplication-client/src/VersionControl/PendingChangeDiff.tsx, packages/amplication-client/src/models.ts, packages/amplication-data-service-generator/src/models.ts, packages/amplication-data-service-generator/src/server/create-grants.spec.ts, packages/amplication-data-service-generator/src/server/create-grants.ts, packages/amplication-data-service-generator/src/types.ts, packages/amplication-data/src/models.ts, packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/models/EntityPermissionField.ts, packages/amplication-server/src/schema.graphql
=> Fix: entity permissions bug

packages/amplication-data-service-generator/package.json, packages/amplication-data-service-generator/src/admin/static/package-lock.json, packages/amplication-data-service-generator/src/admin/static/package.json
=> chore(dsg):bump ra-data-graphql-amplication to 0.0.6

packages/amplication-data-service-generator/src/admin/create-admin.ts, packages/amplication-data-service-generator/src/admin/entity/create-entities-components.ts, packages/amplication-data-service-generator/src/admin/entity/create-entity-components.ts, packages/amplication-data-service-generator/src/admin/entity/entity-show-component/create-entity-show-component.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts, packages/amplication-data-service-generator/src/version.ts
=> Fix(DSG) : Do not generate reference list view for many-to-many relationship

packages/amplication-client/src/Application/CreateAppFromExcel.tsx
=> Fix(client): Prevent duplicate and empty names in the entity diagram

packages/amplication-server/src/core/entity/entity.service.ts
Searchable flag is now true by default
=> fix(server): make searchable true by default

packages/amplication-data-service-generator/src/admin/entity/entity-show-component/create-entity-show-component.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts
=> Fix(admin) : do not generate list view for non-searchable relations

packages/amplication-server/src/core/entity/entity.service.ts
add more special field names :
comments
price
quantity
qty
=> feat(server): create field by name

packages/amplication-data-service-generator/src/admin/entity/entity-list-component/create-entity-list-component.ts, packages/amplication-data-service-generator/src/admin/entity/entity-show-component/create-entity-show-component.ts, packages/amplication-data-service-generator/src/server/resource/controller/create-select.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-entity-dto.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/entities.ts, packages/amplication-data-service-generator/src/util/entity.ts, packages/amplication-data-service-generator/src/version.ts
=> Fix(dsg): add missing relation properties on entity DTO

packages/amplication-data-service-generator/src/server/static/src/auth/auth.resolver.ts, packages/amplication-data-service-generator/src/server/static/src/auth/gqlUserData.decorator.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-server/src/core/github/github.service.ts
=> feat(dsg): user data decorator

packages/amplication-data-service-generator/src/static/.dockerignore
=> fix(dsg):dockerignore admin-ui folder

packages/amplication-server/src/core/auth/auth.controller.ts
=> feat(server):enable github login on dev - redirect back to :3001

packages/amplication-data-service-generator/package.json
=> Issue #1420 - Fixed missing dependency "class-transformer"

packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Herman Ramaniuk fixed #1425 issue
=> #1425 Admin UI: password field is diabled : fixed

packages/amplication-client/src/VersionControl/PendingChangeDiffEntity.tsx
#1675
Added unique field display in compare changes.
=> fix(client): unique field is not displayed in compare changes #1675

packages/amplication-client/src/Entity/EntityFieldListItem.tsx
#1675
Solving the Unique Field Display in Entity List Item.In this Thread.
=> fix(client): Added Unique Field Display in EntitylListItem

packages/amplication-client/src/Application/ApplicationLayout.tsx, packages/amplication-client/src/VersionControl/BuildHeader.scss, packages/amplication-client/src/VersionControl/BuildHeader.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/LastCommit.tsx, packages/amplication-client/src/VersionControl/PendingChangesContext.ts
#1312 
Updating buildID on build fail fixed.
(This is not an optimal solution, but I have come up with a new solution, will push in new PR soon)
=> fix(client): Build errors visibility

packages/amplication-data-service-generator/src/server/resource/test/controller.spec.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/version.ts
use DefaultAuth.Guard in contoller tests
=> feat(dsg): fix controllers test

packages/amplication-client/src/Entity/EntityFieldForm.tsx
(ISSUE 1685) un-proper behaviour in option entity issue resolve.
=> Option entity issue

packages/amplication-client/package.json
=> adding the query-string to package.json

packages/amplication-data-service-generator/src/server/create-dotenv.template.env, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Remove comment from .env based on code review
=> DSG - remove comment from .env

packages/amplication-data-service-generator/scripts/generate-test-data-service.ts, packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
preparation to add more types of e2e testing
=> refctor/(dsg): generate test data service

packages/amplication-data-service-generator/test/data-service-generator.e2e-spec.ts
fixing the error in the e2e test of the dsg
=> fix(dsg): e2e test

packages/amplication-client/src/User/Signup.tsx
=> Submit from

tutorials/deploy-to-digital-ocean-2.md
Add a new tutorial on how to deploy Amplication Server to Digital Ocean.
For issue #1753
=> Add a tutorial on how to deploy the server on Digital Ocean

packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.spec.ts
=> fix(order-by-input): removed console log in test

packages/amplication-data-service-generator/src/server/static/src/auth/auth.service.spec.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/version.ts
=> hotfix(dsg): type-crash

packages/amplication-server/README.md
update the server readme with reference to the automatic setup process
=> Update server README.md

tutorials/deploy-to-azure.md
Added a tutorial on how to deploy Amplication server to Microsoft Azure
=> Add tutorial on how to deploy Amplication server to Microsoft Azure

packages/amplication-data-service-generator/src/server/app-module/create-app-module.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Added basic support for integrating libs like graphql-codegen, graphql-tools, etc.
Changes:
- update create-app-module.ts
- export generated graphql schema to file `schema.graphqls`
=> enhancement(data-service-generator): graphql schema file

.github/workflows/push-validation.yml
=> #1989 Add push-validation.yml to .github/workflows

packages/amplication-data-service-generator/src/server/app-module/create-app-module.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> fix(server): remove the comment

packages/amplication-data-service-generator/src/server/app-module/create-app-module.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> fix(dsg): changing graphql name

packages/amplication-data-service-generator/Dockerfile, packages/amplication-data-service-generator/src/static/Dockerfile
s/direcotry/directory/
s/specifiying/specifying/
=> Fix typos in Dockerfiles

tutorials/demo-app-2.md
Added a file that shows how to create a blogger app with Amplication. This includes a link for the complete app and a youtube link.
For #1754
=> Add the link for the blogger app

.github/workflows/generated-app-tests.yml, .github/workflows/new-issue.yml, .github/workflows/push-validation.yml
=> updated workflows discord webhooks #2207

.github/PULL_REQUEST_TEMPLATE.md
Adding new PR template to the repository
=> feat/1862 add a PR template

packages/amplication-client/package-lock.json, packages/amplication-client/package.json
=> deps(client): update @types/downloadjs

packages/amplication-data-service-generator/src/admin/static/package-lock.json, packages/amplication-data-service-generator/src/admin/static/package.json
=> deps(dsg): admin-ui pluralize update

packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json, packages/amplication-data/package-lock.json, packages/amplication-data/package.json, packages/amplication-deployer/package-lock.json, packages/amplication-deployer/package.json
=> deps(many): update fast-glob

packages/amplication-server/src/core/entity/constants.ts
Issue Number: [#2205 ](https://github.com/amplication/amplication/issues/2205)
On creating an entity, ID's initial unique constraint was false. Hence the issue.
Made it true, so on `getEntity`, the id unique comes true.
=> Fix/2205: Make entity id unique

packages/amplication-client/src/Application/ApplicationLayout.tsx, packages/amplication-client/src/Layout/MenuItemWithFixedPanel.tsx, packages/amplication-client/src/VersionControl/PendingChangesMenuItem.tsx, packages/amplication-client/src/util/teleporter.ts, packages/amplication-server/src/app.module.ts
rename the teleporter name for the new Aside component
=> fix(client):teleporter-name

packages/amplication-server/src/app.module.ts
Issue Number: #2270 
- Exclude graphql route from ServeStatic
=> Fix/2270: Access graphql playground 

packages/amplication-client/src/Layout/MobileMessage.scss, packages/amplication-client/src/Layout/MobileMessage.tsx, packages/amplication-client/src/Layout/WelcomePage.scss, packages/amplication-client/src/Layout/WelcomePage.tsx, packages/amplication-client/src/Workspaces/ApplicationList.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
=> Hot fix/mobile view

CONTRIBUTING.md
=> fix(docs): add details to step 3 and update the clone link

README.md
=> Update to Amplication README

packages/amplication-client/src/App.tsx, packages/amplication-client/src/Components/UserBadge.tsx, packages/amplication-client/src/Layout/MainLayout.tsx, packages/amplication-client/src/Profile/ProfileForm.tsx, packages/amplication-client/src/Profile/ProfilePage.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
Issue Number: #2318 
Upstream branch for PR #2318
=> feat(client):profile page

packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.spec.ts, packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/server/resource/dto/create-input-dto/jsonfield-tests.spec.ts, packages/amplication-data-service-generator/src/tests/server/resource/dto/entity-dto.spec.ts
resolve #2350 
We switch from push to unshift
=> fix(dsg): fixing the genration of api property

packages/amplication-client/src/VersionControl/PendingChange.scss, packages/amplication-client/src/VersionControl/PendingChange.tsx
Issue Number: https://github.com/amplication/amplication/issues/2032
- Add tooltip for deleted entity and make the entity unclickable
=> [# 2032] - Deleted entity show error

.github/workflows/staging-terraform-plan.yml
=> feat(CI\CD): Add workflow for running terraform plan on staging #2377

.github/workflows/staging-prisma-rollback.yaml, package.json, packages/amplication-server/package.json
Issue Number: #2381
Add script to Amplication root project and @amplication/server package.json file for prisma:rollback.
Add additional GH action workflow that will allow rolling back a Prisma migration from staging environment.
=> feat(server): Add Prisma Rollback GH Action and script  #2381

packages/amplication-server/.env
Add placeholders for new GitHub App variables
=> chore(server):add variables placeholders

packages/amplication-client/src/Application/git/dialogs/GitCreateRepo/GitCreateRepo.tsx
Issue Number: https://github.com/amplication/amplication/issues/2386
- Remove validation `onChange` and check in `onBlur`
=> [2386] - create new repository popup shows error message on first keystroke

packages/amplication-client/src/Permissions/EntityPermissionField.tsx
Issue Number: https://github.com/amplication/amplication/issues/2401
- Fix the order of cache modification by finding the updated field and replacing it in the cache.
- Please suggest if other better approaches are available. Would love to discuss other options ❤️
=> [2401] - When role is applied to a field it jumps to the top of the list.

packages/amplication-client/src/Application/ApplicationAuthSettingForm.scss, packages/amplication-client/src/Application/git/GitActions/ExistingConnectionsMenu.scss, packages/amplication-client/src/Application/git/dialogs/GitCreateRepo/GitCreateRepo.scss, packages/amplication-design-system/src/components/Toggle/Toggle.scss, packages/amplication-design-system/src/style/css-variables.scss
Issue Number: #2451 
Changed hard coded RGB color codes to CSS variables
=> fix: change rgb color codes to css variables

CONTRIBUTING.md
=> Issue #2467

packages/amplication-client/src/VersionControl/Commit.scss, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/PendingChanges.scss, packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-client/src/VersionControl/PendingChangesBar.scss
Issue Number: #2526 
Modify styling as per new design
https://user-images.githubusercontent.com/39362422/161438555-70a7ba9d-c122-4335-a570-19fa6aeeb5bc.mov
=> fix: change commit window's css

packages/amplication-client/src/Settings/ApiTokenList.scss, packages/amplication-client/src/Settings/ApiTokenList.tsx
Issue Number: #2563
Added a button to copy new token created to clipboard.
=> feat(client): button to copy new token to clipboard

packages/amplication-data-service-generator/src/server/static/src/util/MetaQueryPayload.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Issue Number: #2588 
Let count type be number
=> fix: count type

packages/amplication-client/src/Entity/EntityFieldListItem.tsx
Fixed position of delete button
Issue Number: #2585 
For consistency of the position of the delete button across the platform
=> fix:(client): fixed the ordering of delete button for consistency

packages/amplication-client/src/Settings/ApiTokenList.tsx
Issue Number: #2563
Code modification for copy token in PR #2587
=> Client - Code cleanup for copy token

packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
Issue Number: Fixes #2599 
Removed unused GraphQL query from Workspace Layout page
=> refactor(client): Removed unused gQL query from WorkspaceLayout

packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts, packages/amplication-data-service-generator/src/server/resource/resolver/to-many.template.ts, packages/amplication-data-service-generator/src/server/resource/resolver/to-one.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> fix 2611 change resource to related entity name

packages/amplication-client/src/VersionControl/CommitList.scss
=> fix:(client) search field is too big in the commit screen

.github/workflows/cd-aws.yml
=> initial CD

packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts, packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts, packages/amplication-data-service-generator/src/server/resource/resolver/resolver.base.template.ts, packages/amplication-data-service-generator/src/server/resource/resolver/to-many.template.ts, packages/amplication-data-service-generator/src/server/resource/resolver/to-one.template.ts, packages/amplication-data-service-generator/src/server/static/src/interceptors/aclFilterResponse.interceptor.ts, packages/amplication-data-service-generator/src/server/static/src/interceptors/aclValidateRequest.interceptor.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Issue Number: #2648 
rename the newly created interceptors:
filterResultInterceptor => aclFilterResponseInterceptor
validateInputInterceptor => aclValidateRequestInterceptor
=> fix(dsg) rename interceptors

packages/amplication-client/package-lock.json, packages/amplication-client/src/Application/git/AuthAppWithGit.scss, packages/amplication-client/src/Application/git/GitActions/GitOrganizationMenuItemContent.scss, packages/amplication-client/src/Application/git/GitActions/GitOrganizationMenuItemContent.tsx, packages/amplication-data-service-generator/src/version.ts, packages/amplication-design-system/src/components/SelectMenu/SelectMenu.scss
Issue Number: #2643 
1. Fix Existing Github Connection Drop Down Padding
2. Align Center Github Avatar, Text, Chevron Icon 
=> fix: dropdown padding and align chevron icon, text and avatar

packages/amplication-client/src/Application/CreateAppFromExcel.scss, packages/amplication-client/src/Application/CreateAppFromExcel.tsx, packages/amplication-client/src/style/mixin.scss
Issue Number: #2635 
Fix create app screen spacing and hover transition effect
=> fix(client): Create app screen spacing and hover effect

helm/charts/amplication/values-common.yaml, helm/charts/amplication/values-dev.yaml, helm/charts/amplication/values-staging-os.yaml
This pr fix and refactor several envs
=> fix(aws): yamels

packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts, packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/version.ts
Issue Number: #2668 
removed unused variables that were missed while merging master into release 0.12.7
=> fix(dsg) remove unused userRoles and rolesBuilder

packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json
fix #2670
This pr update the package
=> fix(dsg): passport

README.md
=> bugfix: discord svg link

packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts, packages/amplication-data-service-generator/src/server/resource/resolver/resolver.base.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Issue Number: #2692 
Remove unused imports from templates
=> fix: remove unused imports

package-lock.json, package.json, packages/amplication-data-service-generator/src/version.ts, script/setup.ts
Issue Number: #2647 
Add Cli Loader using [this package](https://github.com/sindresorhus/ora) in setup script
=> feat: add cli loader in setup script

helm/charts/base/templates/_deployment.tpl
=> fixed typo

helm/charts/base/templates/_deployment_autoscaler.tpl
=> fix base deployment-autoscaling

packages/amplication-server/.env, packages/amplication-server/docker-compose.yml
This pr updates the port in the server's docker-compose to be as previous.
=> [HOTFIX]: db port

README.md
Issue Number: #2753 
Remove wrong title from Readme.md
=> fix(docs): remove wrong title in readme

packages/amplication-data-service-generator/src/static/docker-compose.yml
Issue Number: #2007 
Add DB health check in docker-compose.yml file
=> fix(dsg): add db health check in docker-compose.yml

package-lock.json, packages/amplication-cli/src/models.ts, packages/amplication-data-service-generator/src/version.ts, packages/amplication-data/src/models.ts, packages/amplication-design-system/src/components/MultiStateToggle/MultiStateToggle.scss
Issue Number: #2720 
The code has been modified to remove the divider lines between buttons present at Entities > Permissions. This pull request is opened to reflect the above-made code changes in the original application after it gets merged.
=> fix(client): removal of divider lines between buttons

packages/amplication-data-service-generator/package-lock.json
Issue Number: #2294 
In #2777  I forgot to install get-port with this command `npm i get-port --save-exact` to update package-lock.json
This PR fixes that 
=> fix(dsg): npm i get-port --save-exact 

helm/charts/amplication/values-staging-os.yaml
=> fixing helm staging-os image repository

.github/workflows/scripts/get-service-build-list.py
=> use shorter hashes

LICENSE, ee/LICENSE
Add amplication ee license for and update oss license
=> add amplication ee license and update oss license

ee/packages/amplication-git-pull-service/README.md
Issue Number: #2832
added readme to git-pull-service
=> fix(amplication-git-pull-service) add readme

helm/charts/base/templates/_deployment.tpl, helm/charts/services/amplication-client/values.yaml, helm/charts/services/amplication-git-pull-request-service/values.yaml, helm/charts/services/amplication-git-pull-service/values.yaml, helm/charts/services/amplication-git-push-webhook-service/values.yaml, helm/charts/services/amplication-server/templates/deployment.yaml, helm/charts/services/amplication-server/values.yaml
=> helm: update charts and add resources limits to services

README.md
=> FIX #2731 (issue Doc  Adding System requirements ) changes added system requirement part in readme.md

packages/amplication-git-pull-request-service/src/core/diff/diff.service.ts
=> hotfix: Pull Request is created not with all the files

packages/amplication-server/README.md, script/setup.ts
Issue Number: #2902
When locally setting up amplication.
npm run setup:dev was failing with the following error.
=> fix #2902  onboarding npm run start:db failing

packages/amplication-client/src/Components/BuildSelector.scss, packages/amplication-client/src/Components/BuildSelector.tsx
Issue Number: #2665 
Hotfix => select build list width
=> fix selectMenuModal width

packages/amplication-storage-gateway/src/storage/storage.controller.ts, packages/amplication-storage-gateway/src/storage/storage.service.ts
This pr is the renaming of the storage service
=> refactor(storage)

packages/amplication-server/src/core/deployment/deployment.service.ts, packages/amplication-server/src/core/mail/mail.service.ts
Issue Number: #2955 
fix deployment test file - email notifications
=> added boolean value hard coded false to not trigger email notification

packages/amplication-server/src/core/core.module.ts, packages/amplication-server/src/core/health/health.controller.ts, packages/amplication-server/src/core/health/health.e2e-spec.ts, packages/amplication-server/src/core/health/health.module.ts
Closes #2192
In amplication-server added new health check endpoint `GET /_health/live`, it returns `HTTP 204` (No content) when the server is up and running.
=> feat: add health check endpoint in amplication-server

packages/amplication-prisma-db/prisma/migrations/20220630105056_new_project_hierarchy_nullable_project/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma
Issue Number: #3002 
fix prisma migration of project hierarchy
=> fix prisma migration project hierarchy

packages/amplication-prisma-db/prisma/migrations/20220627163229_app_service/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma
=> refactor(sql)

packages/amplication-data-service-generator/src/create-data-service-impl.ts, packages/amplication-server/src/core/build/build.service.ts
Issue Number: #2984 
return return adminUISettings.generateAdminUI check in createDataServiceImpl function 
- [X ] Tests for the changes have been added
- [X ] `npm test` doesn't throw any error
=> Fix/DSG return adminUISettings.generateAdminUI check

packages/amplication-client/src/Application/appSettings/DirectoriesSettingsForm.tsx
change text of directories page description.
=> 3019 bug directories description

packages/amplication-cli/src/api/resources-create.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Resource/CreateResourceFromExcel.tsx, packages/amplication-client/src/Resource/constants.ts, packages/amplication-client/src/models.ts, packages/amplication-data-service-generator/src/models.ts, packages/amplication-data/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20220707120437_from_app_to_resource/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/block/block.service.spec.ts, packages/amplication-server/src/core/build/build.service.spec.ts, packages/amplication-server/src/core/git/__tests__/git.service.spec.ts, packages/amplication-server/src/core/resource/__mocks__/Resource.mock.ts, packages/amplication-server/src/core/resource/dto/ResourceCreateInput.ts, packages/amplication-server/src/core/resource/resource.resolver.spec.ts, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/sampleResource.ts, packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts, packages/amplication-server/src/models/Resource.ts, packages/amplication-server/src/schema.graphql
closes: #3062 
This pr refactor the name of the type column
=> refactor(server & client): rename resourceType

.github/workflows/cd-aws.yml, helm/charts/amplication/values-alex.yaml
Issue Number: #3041
This PR includes Alex private environment as an example PR for personal dev environments
=> 3041 create custom environment example

.github/workflows/cd-aws.yml, .github/workflows/scripts/deploy-image.sh, .github/workflows/scripts/deploy-valid-image.sh
Add a new job before the deploying process to check if the branch name exists in the repo.
=> FIX: Deploying none existing image tag

.github/workflows/cd-aws.yml, helm/charts/amplication/values-ariel.yaml
Creating a personal cloud environment for Ariel Weinberger
=> Creating a personal environment for Ariel Weinberger

helm/charts/amplication/values-prod.yaml, helm/charts/amplication/values-staging.yaml
The msk-cluster changed, therefor the brokers changed as well and need to be changed.
For staging, it's a fix to correct OAuth.
=> Change Kafka broker IDs to match the new MSK Cluster

packages/amplication-prisma-db/prisma/migrations/20220712143206_disconnect_resource_from_workspace/migration.sql
closes: #3162 
This pr updates the migration 
=> fix(sql): migration fix

packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json, packages/amplication-data-service-generator/src/version.ts
fixes: #3203 
This pr updates the @nestjs/passport package in the DSG to match the one in the generated server
=> DSG version alignment

packages/amplication-data-service-generator/src/server/static/package-lock.json, packages/amplication-data-service-generator/src/server/static/package.json
Issue Number: #3201 
Uninstall `@prisma/client` from dev-dependencies and install it as a dependency
=> Uninstall `@prisma/client` from dev-dependencies and install it as a dependency

packages/amplication-client/src/Project/ProjectPage.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/hooks/useResources.ts, packages/amplication-client/src/Workspaces/queries/resourcesQuery.ts, packages/amplication-client/src/context/appContext.tsx
Issue Number: #3235 
Updated the `getResources` query:
- Search resources by `projectId`
- separate the query to a different file
- create new custom hook name: `useResources`
- added the returned value form this hook to `AppContext`
=> Update `getResources` query

packages/amplication-client/src/Project/ProjectPage.tsx, packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/routes/routesUtil.tsx
Issue Number: #3245 
Add AppMatchRoute and AppRouteProps type and use where needed
=> Add AppMatchRoute and AppRouteProps type

packages/amplication-client/src/Project/WorkspaceSettingsNavigation.tsx, packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts
Issue Number: #3253 
Update workspace members and workspace settings routes to work with the new implementation of our routes
=> Update routes for workspace members and workspace settings

packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/hooks/useResources.ts, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts, packages/amplication-client/src/context/appContext.tsx
=> Project Configuration Resource

packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts
=> Prevent delete for Project Configuration

packages/amplication-client/src/Components/ResourceCircleBadge.tsx, packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Workspaces/ResourceListItem.tsx, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts
=> Implement `ResourceListItem` component

packages/amplication-client/src/Components/ResourceCircleBadge.tsx, packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/Workspaces/ResourceListItem.tsx, packages/amplication-design-system/src/components/HorizontalRule/HorizontalRule.scss, packages/amplication-design-system/src/components/HorizontalRule/HorizontalRule.stories.tsx, packages/amplication-design-system/src/components/HorizontalRule/HorizontalRule.tsx, packages/amplication-design-system/src/index.ts, packages/amplication-design-system/src/style/parameters.scss, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts
=> Update `ResourceList` display format 

packages/amplication-client/src/Entity/Entities.tsx, packages/amplication-client/src/Entity/Entity.tsx, packages/amplication-client/src/Entity/EntityField.tsx, packages/amplication-client/src/Entity/EntityFieldLinkList.tsx, packages/amplication-client/src/Entity/EntityFieldListItem.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/EntityListItem.tsx, packages/amplication-client/src/Entity/EntityRelationFieldsChart.tsx, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/Resource/ResourceHome.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/VersionControl/BuildNewVersion.tsx, packages/amplication-client/src/VersionControl/CommitHeader.tsx, packages/amplication-client/src/VersionControl/CommitListItem.tsx, packages/amplication-client/src/VersionControl/PendingChange.tsx, packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-client/src/routes/resourceEntitiesRoutes.tsx, packages/amplication-client/src/routes/resourceRoutes.tsx, packages/amplication-client/src/routes/routesUtil.tsx
Issue Number: #3246 
update entities components routes
=> update entities components routes

packages/amplication-data-service-generator/src/version.ts, packages/amplication-nest-logger-module/package-lock.json, packages/amplication-nest-logger-module/package.json
=> HOTFIX: missing @nestjs/common package in amplication-nest-logger-module

packages/amplication-client/src/Roles/Role.tsx, packages/amplication-client/src/Roles/RolesPage.tsx, packages/amplication-client/src/routes/resourceRoutes.tsx
Issue Number: #3284 
update roles routes after routes refactor
=> roles routes update 

package-lock.json, package.json
closes: #3272 
This pr update the Lerna version to 5
=> Update Lerna version to 5

packages/amplication-client/src/Workspaces/ResourceListItem.tsx, packages/amplication-client/src/routes/appRoutes.tsx
Issue Number: #3284 
update resource route to resource home
=> Resource route fix=>  navigate to Resource Home 

packages/amplication-client/src/Resource/ResourceHome.tsx, packages/amplication-client/src/Resource/ResourceMenu.tsx, packages/amplication-client/src/Resource/resourceMenuUtils.ts, packages/amplication-client/src/Workspaces/ResourceListItem.tsx, packages/amplication-client/src/Workspaces/hooks/useResources.ts, packages/amplication-client/src/routes/routesUtil.tsx
Issue Number: 3291
Add resource menu to resource home
=> 3291 resource menu

packages/amplication-client/src/CommandPalette/CommandPalette.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader.tsx
=> Fix search functionality in the new project layout

packages/amplication-client/src/Workspaces/ResourceListItem.scss, packages/amplication-client/src/Workspaces/ResourceListItem.tsx, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts, packages/amplication-design-system/src/components/HorizontalRule/HorizontalRule.scss, packages/amplication-design-system/src/components/HorizontalRule/HorizontalRule.tsx, packages/amplication-design-system/src/index.ts
=> update style for `ResourceListItem`

packages/amplication-client/src/Workspaces/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader.tsx
Issue Number: 3308
add temporary sign out icon to header until we'll add it under user icon
=> add sign out icon to header

packages/amplication-client/src/Resource/resourceMenuUtils.ts, packages/amplication-client/src/Resource/serviceSettings/ServiceSettingsPage.tsx, packages/amplication-client/src/Settings/ApiTokenList.tsx, packages/amplication-client/src/VersionControl/BuildPage.tsx, packages/amplication-client/src/VersionControl/CommitList.tsx, packages/amplication-client/src/VersionControl/CommitListItem.tsx, packages/amplication-client/src/VersionControl/CommitPage.tsx, packages/amplication-client/src/routes/resourceRoutes.tsx, packages/amplication-client/src/routes/resourceSettingsRoutes.tsx
Issue Number: #3246 
update resource settings routes
=> update resource settings routes

packages/amplication-client/src/Resource/ResourceMenu.tsx, packages/amplication-client/src/Resource/resourceMenuUtils.ts, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/hooks/useResources.ts
Issue Number: #3310
add old pending changes to new layout box. fix issue with useResource hook and configuration resource.
=> 3310 Add Pending Changes Box To New Layout

packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.scss, packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Resource/create-resource/CreateServiceWizardForm.scss
Issue Number: #3348 
wrap CreateServiceWizard component with modal
=> wrap CreateServiceWizard with Modal component

packages/amplication-data-service-generator/src/admin/static/src/Login.tsx, packages/amplication-data-service-generator/src/version.ts
Links fixed for the api and graphql in login.tsx
=> bug(client): links fixed in the Login.tsx

packages/amplication-client/src/Project/ProjectPage.scss, packages/amplication-client/src/Project/ProjectPage.tsx, packages/amplication-client/src/Project/ProjectSideBar.scss
=> Use `PageContent` component on project page

packages/amplication-client/src/Layout/PageContent.scss, packages/amplication-client/src/Project/ProjectPage.scss, packages/amplication-client/src/Project/ProjectPage.tsx, packages/amplication-client/src/Project/ProjectSideBar.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.scss
=> Format workspace header 

packages/amplication-client/src/Layout/MenuItem.scss, packages/amplication-client/src/Layout/MenuItem.tsx, packages/amplication-client/src/Layout/PageContent.scss, packages/amplication-client/src/Project/ProjectPage.scss, packages/amplication-client/src/Project/ProjectPage.tsx, packages/amplication-client/src/Project/ProjectSideBar.scss, packages/amplication-client/src/Resource/ResourceMenu.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.scss
=> Disable hover for resource dashboard menu item

packages/amplication-prisma-db/prisma/migrations/20220707173037_app_service_to_service_settigns/migration.sql
fixes: #3379 
This PR removes the public schema name and the begin transaction keyword
=> fix(sql): fix the sql command and remove public and begin

packages/amplication-prisma-db/prisma/migrations/20220707173001_add_service_settings/migration.sql, packages/amplication-prisma-db/prisma/migrations/20220707173037_app_service_to_service_settigns/migration.sql
This PR split the migration into two
=> Splitting migration for separated ones

packages/amplication-client/src/style/mixin.scss
=> Fix input width on modals

packages/amplication-prisma-db/prisma/migrations/20220711090906_enum_block_type_add_value/migration.sql, packages/amplication-prisma-db/prisma/migrations/20220711090906_project_resource_block/migration.sql, packages/amplication-prisma-db/prisma/migrations/20220711090910_enum_resource_type_add_value/migration.sql
This PR split one migration with two ADD commands to two separated SQL migrations
=> Split migration of project resource block

packages/amplication-nest-logger-module/README.md
closes: #3353 
This includes the README for the Amplication logger module
=> Adding REAME file to the Amplication logger module

helm/charts/amplication/values-staging.yaml
IMPORTANT!
Changing brokers' endpoints after deletion from terraform.
=> Change brokers endpoints - IMPORTANT!

.github/workflows/delete-namespace.yml, .github/workflows/deploy.yml
=> Add eugene name for namespaces

packages/amplication-client/src/Workspaces/queries/workspaceQueries.ts
Add git organizations to getWorkspace query.
=> Add gitOrganizations to get workspace query

README.md
This PR will fix the broken Code of Conduct link due to a typo.
=> Fixed broken Code of Conduct link

packages/amplication-client/src/VersionControl/PendingChange.scss, packages/amplication-client/src/VersionControl/PendingChange.tsx, packages/amplication-client/src/VersionControl/PendingChanges.scss, packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-design-system/src/components/CircleBadge/CircleBadge.scss, packages/amplication-design-system/src/style/css-variables.scss
Issue Number: #3410 
- pending changes panel - UI
=> Implement pending changes panel - UI

packages/amplication-client/src/VersionControl/BuildSummary.tsx, packages/amplication-client/src/VersionControl/LastCommit.scss, packages/amplication-client/src/VersionControl/LastCommit.tsx, packages/amplication-client/src/VersionControl/PendingChanges.scss, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
Issue Number: #3417 
Implemented the last commit on the pending changes panel
=> Implement last commit

packages/amplication-client/src/Layout/PageContent.scss, packages/amplication-client/src/Project/ProjectSideBar.scss
Closes: #3432
Remove redundant margins from wrapper and label.
=> 3432 Changed side bar body padding

packages/amplication-client/src/Layout/InnerTabLink.scss, packages/amplication-design-system/src/style/css-variables.scss
Closes: #3434 
Changed settings icon size in resource general settings
=> 3434 change settings icon size

packages/amplication-client/src/Workspaces/WorkspaceHeader.scss, packages/amplication-client/src/style/mixin.scss
Closes: #3429 
Change margin in workspace header right part
=> 3429 Change margin in workspace header right part

packages/amplication-client/src/Workspaces/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader.tsx
Closes: #3428
Change highlight in workspace header based on route.
=> 3428 Change highlight in workspace header based on route

packages/amplication-client/src/Resource/code-view/CodeViewExplorer.tsx, packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Roles/NewRole.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/DiscardChanges.tsx, packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts, packages/amplication-client/src/Workspaces/hooks/useResources.ts, packages/amplication-client/src/Workspaces/queries/projectQueries.ts, packages/amplication-client/src/context/appContext.tsx
fix pending changes update on each change in application
=> fix all pending changes update

packages/amplication-client/src/Resource/OverviewTile/OverviewTile.tsx
Issue Number: #3424 
I fixed a typo that was in the dashboard(Next Js to Nest JS)
=> fix(amplication-client): fixed a typo in OverviewTile Next JS => Nest JS

packages/amplication-data-service-generator/src/admin/static/package.json
Issue Number: #2441
- Removed `graphql-tag` and `gql` from dependencies.
- Removed `typescript` from dependency and Added it in devDependencies.
=> fix(data-service-gen): unnecessary dependencies in generate admin-ui

packages/amplication-client/src/Settings/ApiTokenList.tsx
Issue Number: #3444
Better text
```
API tokens are used to authenticate requests to the Amplication API. They are specifically required for Amplication CLI.
Tokens are valid for 30 days following creation or last use. The 30 day expiration period automatically refreshes with each API.
```
=> Improve text and gramamr in the ApiTokenList component

packages/amplication-client/src/Application/git/SyncWithGithubPage.tsx
Issue Number: #3443
The text on the Sync with GitHub screen is a bit hard to understand. It has been rephrased into understandable text.
=> UX: Improved text on "Sync with GitHub" screen

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/documentation.yaml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/troubleshooting.yaml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, packages/amplication-client/src/Application/git/dialogs/GitCreateRepo/GitCreateRepo.tsx
Issue Number: [3188](https://github.com/amplication/amplication/issues/3188)
https://user-images.githubusercontent.com/60089135/185108714-9beafa46-45b1-4623-b375-cecc9b7eb38f.mov
- Add autoFocus on the TextField when click `create new repository`
- 404 link on CODE_OF_CONDUCT.md
=> fix: autoFocus on create new repository

packages/amplication-client/src/Workspaces/WorkspaceSelector.scss, packages/amplication-client/src/Workspaces/WorkspaceSelectorList.tsx
Closes: #3433 
Align create button with list
Changed delimiter 
=> 3433 Workspace selector new design changes

packages/amplication-client/src/Layout/PageContent.scss
=> Add margin to page content tab

helm/charts/base/templates/_deployment.tpl, helm/charts/base/templates/_statefullstate.tpl, helm/charts/services/amplication-server/templates/deployment.yaml, helm/charts/services/amplication-server/templates/secret.yaml
Issue Number: closes #3466 
fix(server) : add conditional to include secret
* fix deployment template
* fix statefulset template
* fix amplication server helm template
* add secret yaml for amplication server
* closes #3466
=> fix(server) : add conditional to include secret

packages/amplication-client/src/Workspaces/WorkspaceHeader.scss
closes: #3430 
This pr make the text in the header change in hover
=> Text hover color

packages/amplication-client/src/Entity/Entity.tsx, packages/amplication-client/src/Entity/EntityFieldList.tsx, packages/amplication-client/src/VersionControl/BuildPage.tsx, packages/amplication-client/src/VersionControl/BuildStatusIcons.tsx, packages/amplication-client/src/VersionControl/BuildSteps.tsx, packages/amplication-client/src/VersionControl/ChangesPage.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/CommitListItem.tsx, packages/amplication-client/src/VersionControl/CommitResourceList.tsx, packages/amplication-client/src/VersionControl/CommitResourceListItem.tsx, packages/amplication-client/src/VersionControl/CommitsPage.tsx, packages/amplication-client/src/VersionControl/LastCommit.scss, packages/amplication-client/src/VersionControl/LastCommit.tsx, packages/amplication-client/src/VersionControl/PendingChange.tsx, packages/amplication-client/src/VersionControl/PendingChangeWithCompare.tsx, packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-client/src/VersionControl/PendingChangesPage.scss, packages/amplication-client/src/VersionControl/PendingChangesPage.tsx, packages/amplication-client/src/VersionControl/hooks/commitQueries.ts, packages/amplication-client/src/VersionControl/hooks/useCommits.ts, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts, packages/amplication-client/src/routes/appRoutes.tsx, packages/amplication-client/src/routes/resourceRoutes.tsx, packages/amplication-design-system/src/components/CircleBadge/CircleBadge.scss, packages/amplication-server/src/core/entity/entityVersion.resolver.ts, packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/schema.graphql
Issue Number: #3499 
- fix commit and build flow 
- fix pending changes state 
- fix pending changes page to show changes for each service 
- fix links (to pending changes, build id...)
- filter project configuration from the build process
- show service changes count
- fix build status icon
Note:
The {x} changes link should leads to the changes that **have been committed** , right now, it shows the files but not as a diff:
=> Continue Commit and Build Flow

packages/amplication-client/src/Application/ApplicationForm.tsx
=> fix/Add descriptive text to the General Settings page #3445

CONTRIBUTING.md
Issue Number: closes #3357 
docs(contributing) : Update prerequisites steps
* Improve branch creation steps
* closes #3357
=> docs(contributing) : Update prerequisites steps

packages/amplication-client/src/Workspaces/WorkspaceHeader/HeaderMenuStaticOptions.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts, packages/amplication-client/src/Workspaces/queries/projectQueries.ts, packages/amplication-client/src/context/appContext.tsx
=> Set an header menu

packages/amplication-client/src/VersionControl/BuildPage.tsx, packages/amplication-client/src/VersionControl/ChangesPage.tsx, packages/amplication-client/src/VersionControl/CommitListItem.scss, packages/amplication-client/src/VersionControl/CommitResourceList.scss, packages/amplication-client/src/VersionControl/CommitResourceList.tsx, packages/amplication-client/src/VersionControl/CommitsPage.tsx, packages/amplication-client/src/VersionControl/DataPanel.scss, packages/amplication-client/src/VersionControl/DataPanel.tsx, packages/amplication-client/src/VersionControl/hooks/commitQueries.ts
Fix commits and builds UI issues
=> Fix commits and builds UI issues

README.md
=> docs: remove call to missing script in README.md

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Issue Number: #3544
When selecting resource the title should be replaced by new selection
=> 3544 - DropDown Title Selection Bug

packages/amplication-client/src/VersionControl/PendingChanges.scss
=> Pending changes background color

packages/amplication-client/src/VersionControl/PendingChanges.tsx
=> Add missing title for pending changes

packages/amplication-client/src/Workspaces/MemberList.tsx
Issue Number: #3550
fix members UI page
=> members page UI fix

packages/amplication-server/src/core/mail/mail.service.ts
Issue Number: #2964 
It would solve the wrong link issue 
=> Updated mail.service.ts

.github/workflows/ci.yml, .github/workflows/delete-namespace.yml, .github/workflows/deploy.yml, .github/workflows/new-issue.yml, .github/workflows/new-pr.yaml, .github/workflows/scripts/deploy-image.sh
From an error I found from deploy yaml we need to update the job runners.
The error:
"This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on December 1st, 2022. For more details, see https://github.com/actions/runner-images/issues/6002"
=> update ubuntu runner

packages/amplication-client/src/Resource/resourceSettings/DirectoriesServiceSettingsForm.tsx, packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts, packages/amplication-git-pull-request-service/src/models.ts
Fix server and admin path to be saved and added to pending changes
=> Fix server and admin path to be saved and added to pending changes

packages/amplication-server/src/core/auth/auth.service.ts, packages/amplication-server/src/core/workspace/workspace.service.spec.ts, packages/amplication-server/src/core/workspace/workspace.service.ts
Issue Number: #3260 
Implement the creation of a new project with project configuration on creating a new workspace
=> Implement the creation of a new project with project configuration on creating a new workspace

packages/amplication-client/src/Workspaces/ResourceListItem.tsx
=> Hide the last commit for project configuration

helm/charts/base/templates/_deployment.tpl
Remove the conditional secrets in the deployment template. the secrets are not part of the charts, so the conditional secrets cause the deployments not to pick up the secrets that are added when we deploy the charts.
=> Hotfix on helm deployment template for release 0.15.0

packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx, packages/amplication-git-service/src/providers/github.service.ts
Issue Number: #3555 
Fix connect project configuration to GitHub when there are no services
=> Fix connect project configuration to GitHub when there are no services

packages/amplication-client/src/Resource/ResourceForm.scss, packages/amplication-server/src/core/auth/auth.service.ts, packages/amplication-server/src/core/workspace/workspace.service.ts
=> fix creaeWorkspace return users

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
=> Fix blog URL on the workspace header

packages/amplication-client/src/Layout/MenuItem.scss, packages/amplication-client/src/Layout/MenuItem.tsx, packages/amplication-design-system/src/style/css-variables.scss
Issue Number:  #2712 
Decreased the font size and changed the background color of icon div based on the figma file shared in the issue
=> side menu icon size change and color of icon

packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.controller.ts
Issue Number: #3316 
All the absolute /src imports inside the `amplication-git-pull-request-service` are replaced with relative paths.
=> Fix: Refactor absolute /src imports to relative in amplication-git-pull-request-service

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Issue Number: #3588 
Fix header menu not to show hr when there are no resources
=> Fix header menu not to show hr when there are no resources

package-lock.json, package.json
closes: #3611 
This PR removes the package @types/ora
=> Removing the @types/ora package

packages/amplication-client/src/VersionControl/BuildStatusIcons.scss, packages/amplication-client/src/VersionControl/LastCommit.scss, packages/amplication-client/src/VersionControl/LastCommit.tsx
Issue Number: #3613 
Fix last commit text and status UI issue
=> Fix last commit text and status UI issue

packages/amplication-client/src/Workspaces/ResourceListItem.scss, packages/amplication-client/src/Workspaces/ResourceListItem.tsx
closes: #3597 
This PR adds not commit yet message
=> Add `No commit yet` empty state for "Last commit"

packages/amplication-client/src/VersionControl/BuildStatusIcons.tsx, packages/amplication-client/src/VersionControl/LastCommit.scss, packages/amplication-client/src/VersionControl/LastCommit.tsx
Issue Number: #3602 
Fix commit loader hanging although the process finished
=> Fix commit loader

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Issue Number: #3579 
fix resource list style
=> fix resource list

packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.scss, packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-design-system/src/components/Modal/Modal.tsx
Issue Number: 
#3439
#3472 
Fix style issues in the service wizard
=> service wizard fix css style

packages/amplication-client/src/VersionControl/CommitData.scss
=> Hotfix commits list status in commits page

helm/charts/base/templates/_deployment.tpl, helm/charts/services/amplication-git-pull-service/templates/deployment.yaml, helm/charts/services/amplication-git-pull-service/values.yaml, helm/charts/services/amplication-server/templates/deployment.yaml, helm/charts/services/amplication-server/values.yaml
Adding a 'resources' block for deployment to achieve HPA resource usage.
=> Adding 'resources' block

packages/amplication-git-pull-request-service/src/core/diff/diff.service.ts, packages/amplication-git-pull-request-service/src/core/pull-request/dto/sendPullRequest.ts, packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.controller.ts, packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.service.ts, packages/amplication-git-pull-request-service/src/services/environmentVariables.ts, packages/amplication-git-pull-request-service/tsconfig.json, packages/amplication-server/src/core/build/dto/sendPullRequest.ts
partly fix #3660 
This PR fix the old build id crash in the first build
=> Fixing a crash that happened in the first PR

packages/amplication-client/src/VersionControl/Commit.scss, packages/amplication-client/src/VersionControl/CommitResourceListItem.scss, packages/amplication-client/src/VersionControl/LastCommit.scss, packages/amplication-client/src/VersionControl/LastCommit.tsx, packages/amplication-client/src/VersionControl/PendingChange.scss, packages/amplication-client/src/VersionControl/PendingChanges.scss, packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss, packages/amplication-client/src/style/mixin.scss, packages/amplication-design-system/src/style/css-variables.scss
Issue Number: #3643 
fix pending changes UI bugs
Except:
- commit id - because I can't reproduce it
- `Go to view code` button - because Ofek is working on a task about the buttons
=> Fix pending changes UI

packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts
Issue Number: #3665 
Fix delete resource connected to GitRepository with override settings.
=> Delete service resource throw an error when it connected to GitRepository with override settings

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss, packages/amplication-client/src/style/mixin.scss, packages/amplication-design-system/src/components/Button/Button.scss, packages/amplication-design-system/src/index.scss
Changed font weight to 400 in links and buttons
=> Change font weight of buttons and links globally

packages/amplication-server/src/core/build/build.service.ts
Issue Number: #3659
Add to the url send to PR workspaceId and projectId
=> Pull request embedded link is broken

packages/amplication-client/src/Entity/Entity.tsx
Closes: #3717 
Added header to right menu with entity name
=> added entity name to right menu

packages/amplication-client/src/VersionControl/LastCommit.scss, packages/amplication-client/src/VersionControl/LastCommit.tsx
=> fix: remove skeleton while building

README.md
Issue Number: #3615
Added additional links and improvised in README.md file
=> feat:added additional links & improvised in README

packages/amplication-client/src/ServiceConnections/ServiceMessageBrokerConnection.tsx, packages/amplication-client/src/ServiceConnections/ServiceMessageBrokerConnectionForm.tsx, packages/amplication-client/src/ServiceConnections/hooks/useServiceConnection.ts, packages/amplication-client/src/ServiceConnections/queries/serviceMessageBrokerConnectionQueries.ts, packages/amplication-client/src/ServiceConnections/topics/ServiceConnectionTopicItem.tsx, packages/amplication-client/src/ServiceConnections/topics/ServiceConnectionTopicItemForm.tsx, packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx, packages/amplication-client/src/ServiceConnections/topics/queries/topicsQueries.ts, packages/amplication-client/src/VersionControl/PendingChange.scss, packages/amplication-client/src/VersionControl/PendingChange.tsx, packages/amplication-client/src/VersionControl/PendingChangeContent.tsx, packages/amplication-client/src/VersionControl/PendingChangeServiceMessageBrokerConnection.tsx, packages/amplication-client/src/Workspaces/queries/projectQueries.ts
This PR makes the logic connection between the client and the server
=> feat(client): add client to server connection to message broker

packages/amplication-client/src/Entity/EntityList.scss, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/EntityListItem.scss, packages/amplication-client/src/Layout/PageContent.scss, packages/amplication-client/src/Project/AddNewProject.scss, packages/amplication-client/src/Project/ProjectList.scss, packages/amplication-client/src/Project/ProjectList.tsx, packages/amplication-client/src/Project/ProjectSideBar.scss, packages/amplication-client/src/Project/ProjectSideBar.tsx, packages/amplication-client/src/Project/WorkspaceSettingsNavigation.scss, packages/amplication-client/src/Project/WorkspaceSettingsNavigation.tsx, packages/amplication-client/src/Resource/git/AppGitStatusPanel.scss, packages/amplication-client/src/Resource/resourceSettings/ServiceSettingsPage.scss, packages/amplication-client/src/Resource/resourceSettings/ServiceSettingsPage.tsx, packages/amplication-client/src/VersionControl/PendingChanges.scss, packages/amplication-client/src/Workspaces/ResourceList.scss, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/Workspaces/ResourceListItem.scss, packages/amplication-client/src/Workspaces/WorkspaceSelector.scss, packages/amplication-client/src/style/mixin.scss, packages/amplication-design-system/src/components/CircleBadge/CircleBadge.scss
Closes: #3748
Right menu:
Made delimiter width 1px.
Set gap from top of the list to 16px.
Made list area scrollable.
Add New Project button is not bold anymore.
Add New Project button was aligned with list elements.
Gap between Add New Project button was aligned with the design.
Left menu:
Used common scroll in left menu.
Project screen:
Removed 100% width from Connect to GitHub button.
=> Align right and left menu with design

packages/amplication-client/src/App.tsx, packages/amplication-client/src/Entity/Entity.tsx, packages/amplication-client/src/Entity/EntityFieldList.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Permissions/PermissionsForm.tsx, packages/amplication-client/src/Resource/EntitiesTile.tsx, packages/amplication-client/src/Resource/NewVersionTile.tsx, packages/amplication-client/src/Resource/RolesTile.tsx, packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.tsx, packages/amplication-client/src/Resource/git/dialogs/GitRepos/GithubRepos.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/Settings/ApiTokenList.tsx, packages/amplication-client/src/User/Login.tsx, packages/amplication-client/src/User/Signup.tsx, packages/amplication-client/src/VersionControl/BuildPage.tsx, packages/amplication-client/src/VersionControl/CommitList.tsx, packages/amplication-client/src/VersionControl/PendingChangeDiffBlock.tsx, packages/amplication-client/src/VersionControl/PendingChangeDiffEntity.tsx, packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-client/src/Workspaces/MemberList.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelector.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelectorList.tsx, packages/amplication-client/src/routes/routesUtil.tsx, packages/amplication-design-system/src/components/CircularProgress/CircularProgress.scss, packages/amplication-design-system/src/components/CircularProgress/CircularProgress.tsx
Issue Number: #3752
Add center style to circularProgress component and change it in all relevant components.
=> Add center style to Circular progress loader 

packages/amplication-code-gen-types/src/index.ts, packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugin-generic.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/plugin-wrapper.ts, packages/amplication-data-service-generator/src/server/create-dotenv.ts, packages/amplication-data-service-generator/src/server/create-server.ts
Refactor to the plugin types based on recent review with @barshimi @morhag90 and @abrl91 
=> Refactor plugin event types

packages/amplication-cli/src/models.ts, packages/amplication-client/src/Plugins/InstalledPlugins.tsx, packages/amplication-client/src/Plugins/PluginsCatalog.tsx, packages/amplication-client/src/Plugins/PluginsCatalogItem.tsx, packages/amplication-client/src/Plugins/hooks/usePlugins.ts, packages/amplication-client/src/Plugins/queries/pluginsQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-data-service-generator/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.ts
Issue Number: #3784
fix plugin order in ui
=> plugin order client

packages/amplication-client/src/Resource/create-message-broker/CreateMessageBroker.scss, packages/amplication-client/src/Resource/create-message-broker/CreateMessageBroker.tsx
Closes: #3763 
Updated message broker creation screen layout, changed description
=> Improved Message Broker Creation Wizard

packages/amplication-client/src/Workspaces/ResourceList.scss, packages/amplication-client/src/Workspaces/ResourceList.tsx
fix: #3802 
fix resource list empty state - use the new empty state component
=> fix resource list empty state

packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-data-service-generator/src/admin/app/create-app.ts, packages/amplication-data-service-generator/src/admin/create-admin.ts, packages/amplication-data-service-generator/src/server/create-server.ts, packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts, packages/amplication-data-service-generator/src/server/resource/create-resource.ts, packages/amplication-data-service-generator/src/server/resource/module/create-module.ts, packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts, packages/amplication-data-service-generator/src/server/resource/service/create-service.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Issue Number: #3766
Fix context original branch pr comments
=> context directory params

packages/amplication-data-service-generator/src/admin/static/Dockerfile, packages/amplication-data-service-generator/src/server/static/Dockerfile
Closes: #3812
Refactor the Dockerfiles as instructed in the scope of the issue.
=> Refactor Dockerfiles of generated server and admin-ui

packages/amplication-code-gen-types/package.json, packages/amplication-code-gen-types/src/code-gen-types.ts, packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/server/create-server.ts, packages/amplication-data-service-generator/src/server/prisma/constants.ts, packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema-module.ts, packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.spec.ts, packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.ts
Issue Number: #3765
Add to create prisma schema module plugin
=> Add to create prisma schema module plugin 

packages/amplication-data-service-generator/src/util/enum-builder.ts
This PR gives us an AST util to easily make an enum AST object
=> Enum AST builder pattern

packages/amplication-client/src/VersionControl/PendingChange.tsx, packages/amplication-client/src/VersionControl/PendingChangeContent.tsx
Issue Number: #3828
Add plugin name to pending changes.
=> plugnin name in pending changes

packages/amplication-client/src/MessageBrokerServices/Item.scss, packages/amplication-client/src/MessageBrokerServices/Item.tsx, packages/amplication-client/src/MessageBrokerServices/ServicesPage.scss, packages/amplication-client/src/MessageBrokerServices/ServicesPage.tsx, packages/amplication-client/src/Resource/resourceMenuUtils.ts, packages/amplication-client/src/routes/resourceRoutes.tsx
Closes: #3770 
Added message broker connected services page
=> 3770 message broker services page

packages/amplication-code-gen-types/package.json, packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts
Issue Number: #3821
Add support async function to plugins.
=> Add support async function to plugins 

packages/amplication-client/src/Topics/TopicList.scss, packages/amplication-client/src/style/mixin.scss
Closes: #3839 
Added scroll to topics list
=> 3839 Add scroll to topics list

packages/amplication-cli/src/models.ts, packages/amplication-client/src/Components/TopicNameField.tsx, packages/amplication-client/src/Topics/NewTopic.tsx, packages/amplication-client/src/Topics/TopicForm.tsx, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-data-service-generator/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/amplication-server/src/core/topic/dto/TopicCreateInput.ts, packages/amplication-server/src/core/topic/topic.service.ts
Closes: #3762 
Added validation for topic name
=> 3762 validate topic name

packages/amplication-data-service-generator/src/create-data-service-impl.ts, packages/amplication-data-service-generator/src/register-plugin.ts
Issue Number: #3826 
Implement default plugins registration
=> Implement default plugins registration

packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/util/prepare-yaml-file.ts
Issue Number: part of #3768 and #3769 
Refactor `prepareYamlFile` - update type and implementation
=> Refactor `prepareYamlFile` - update type and implementation

packages/amplication-data-service-generator/src/create-data-service-impl.ts, packages/amplication-data-service-generator/src/register-plugin.ts
use the prop `npm` to get the package name
=> DSG: use the `npm` prop  to get the package name

packages/amplication-data-service-generator/src/create-data-service-impl.ts
=> DSG: Default plugin per category

packages/amplication-data-service-generator/src/server/constants.ts, packages/amplication-data-service-generator/src/server/docker-compose/docker-compose.db.template.yml, packages/amplication-data-service-generator/src/server/docker-compose/docker-compose.template.yml, packages/amplication-data-service-generator/src/server/static/README.md, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Issue Number: #3856 
Clean up `PostgreSQL` environment variables and docker-compose files
related PR from the Plugins repo: https://github.com/amplication/plugins/pull/2
=> Clean up `PostgreSQL` environment variables and docker-compose files

packages/amplication-client/src/VersionControl/BuildPage.tsx
=> Add polling to build page

packages/amplication-client/src/Topics/TopicList.scss
Closes: #3861 
fixed add new topic field location in topics list
=> fixed add new topic field location in topics list

packages/amplication-data-service-generator/src/create-data-service.ts, packages/amplication-server/src/core/build/build.service.spec.ts, packages/amplication-server/src/core/build/build.service.ts
Issue Number: #3829 
fix message broker build failed message.
=> fix message broker build failed message 

packages/amplication-client/src/Resource/code-view/CodeViewExplorerTree.tsx, packages/amplication-client/src/util/error.ts
Issue Number: #3874
Code view error handling
=> Code view error handling

packages/amplication-client/src/MessageBrokerServices/ServicesPage.tsx
=> 3863 bug report description is missing in message broker service list page

packages/amplication-client/src/Components/CreateResourceButtonItem.tsx, packages/amplication-client/src/Resource/code-view/CodeViewExplorerTree.tsx, packages/amplication-client/src/util/error.ts
=> Create resource button is not clickable

helm/charts/amplication/values-prod.yaml, helm/charts/services/amplication-server/values.yaml
Fixing the values for only prod env.
=> fix server replicas for prod

packages/amplication-client/src/Components/TopicNameField.tsx, packages/amplication-client/src/Topics/TopicForm.tsx
Closes: #3890
Changed topic name button, use it in the form
=> fix topic name field, use topic name field in form

packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json
after resolving issues: #3898 and #3899
I bumped `plugin-auth-basic` `plugin-auth-jwt` and `plugin-db-mysql` versions and published it.
Then, I updated those plugins' new versions on the DSG
=> Update plugins versions on the DSG

packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/NewEntity.tsx
Closes: #3873
Added event on success to new entity that closes the dialog
=> close create dialog after entity created

packages/amplication-client/src/Resource/create-message-broker/CreateMessageBroker.tsx
Issue Number: #3900 
Updated text
=> 3900 ux message broker creation instruction text is confusing

packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json
Issue Number: #3899 
update mysql plugin version
=> update mysql plugin version

packages/amplication-data-service-generator/src/server/static/Dockerfile
=> Fix Dockerfile generated by DSG

packages/amplication-kafka/src/createNestjsKafkaConfig.ts, packages/amplication-server/src/main.ts
=> Add Kafka Client Prefix

packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/create-data-service-impl.ts, packages/amplication-data-service-generator/src/server/create-server.ts
Issue Number: a part of #3854 and #3887
Implement CreateServer plugin event
related pull request form the plugins repository: https://github.com/amplication/plugins/pull/13
=> Implement CreateServer plugin event 

packages/amplication-data-service-generator/src/server/message-broker/topics-enum/createTopicsEnum.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
This PR is part of the fix of https://github.com/amplication/plugins/issues/14
=> Export topic's enum

packages/amplication-data-service-generator/src/server/resource/dto/create-dto-module.ts, packages/amplication-data-service-generator/src/server/resource/dto/graphql-field-decorator/create-graphql-field-decorator.ts, packages/amplication-data-service-generator/src/server/resource/dto/graphql-type-json.util.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/tests/server/resource/dto/create-input-dto/jsonfield-tests.spec.ts, packages/amplication-data-service-generator/src/tests/server/resource/dto/entity-dto.spec.ts
closes: #3987 
This PR change the graphql decorator of json from json object to json values
=> Update import for graphql json

packages/amplication-data-service-generator/src/server/static/src/auth/jwt/base/jwt.strategy.base.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
closes: #4019
This PR copies the existing plugin logic to the default code generation
=> JWT creation logic

packages/amplication-client/src/VersionControl/useBuildWatchStatus.tsx
closes: #4023 
This PR remove the onComliation function from the use query 
=> Remove on completed function

packages/amplication-client/src/Entity/EntityFieldList.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/Topics/TopicList.tsx, packages/amplication-client/src/Workspaces/MemberList.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/util/pluralize.ts
=> fix: pluralize text based on count

packages/amplication-code-gen-types/package.json, packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/server/app-module/create-app-module.ts, packages/amplication-data-service-generator/src/server/create-server.ts
This PR is part of the solution for adding the KafkaModule to the AppModule this is the dsg side changes
=> Add app module hooks

tutorials/social-posts.md
Issue Number: #4031
Have made the posts about my experience of contributing in amplication
=> Added posts about my exp in amp

tutorials/social_post.md
Issue Number: #4031 
Advocacy: Twitter Thread and Linkedin Post talking about Amplication.
- [ ✔️] Tests for the changes have been added
- [✔️ ] `npm test` doesn't throw any error
=> Advocacy: Twitter Thread and Linkedin Post talking about Amplication

tutorials/blog-post.md
A pull request for the issue #4006 
Writing article on medium for amplication.
hactoberfest.
Issue Number: #4006 
=> Medium Post - Amplication

tutorials/_social-post.md
Issue Number: #4031 
Added Details of Twitter And Linkedin Posts
=> Added Posts About Amplication

tutorials/social_posts.md
Issue Number: https://github.com/amplication/amplication/issues/4031
PR Details
Have made the posts about my experience of using  amplication
=> Added a file with links to social media posts about amplication

tutorials/amplication-intro.md
Issue Number: #4006 
Blog on Amplication and it's need
=> Created Blog for Amplication

packages/amplication-client/src/Workspaces/ResourceListItem.scss, packages/amplication-client/src/Workspaces/ResourceListItem.tsx
=> Show repo name on Resource List Item

packages/amplication-cli/README.md, packages/amplication-cli/src/commands/entities/index.ts, packages/amplication-cli/src/commands/resources/info.ts, packages/amplication-cli/src/commands/resources/update.ts, packages/amplication-server/src/core/build/utils/BuildFilesSaver/BuildFilesSaver.spec.ts, packages/amplication-server/src/core/resource/resource.resolver.spec.ts, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resourceRole/resourceRole.resolver.spec.ts, packages/amplication-server/src/core/resourceRole/resourceRole.service.spec.ts
- correct grammar on `resources` and `resource` word
- (this is also for hacktoberfest 😄 )
=> fix: correct grammar on resources, resource word

tutorials/Amp_Introduction.md
Issue Number: #4006 
Created a blog post about amplication and how to create a first project.
=> Created a blog post on Amplication

tutorials/youtube_video.md
Issue Number: https://github.com/amplication/amplication/issues/4007
- add a youtube video
=> chore(tutorials): add a youtube video link

README.md
Fixing Grammatical Errors on lines 75, 111,  129 and 135 to make the Readme easier to undertsand and read.
=> Propose some Grammatical changes in the README

packages/amplication-client/src/style/mixin.scss
Issue Number: #4101
When running the client, i have noticed the following deprecation warnings being thrown:
<details>
<summary><code>npm start</code></summary>
```sh
Starting the development server...
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($size, 3)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
246 │     border: $size/3 solid transparent;
│             ^^^^^^^
╵
src/style/mixin.scss 246:13       scrollbars()
src/Layout/PageContent.scss 25:5  root stylesheet
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div(-$size, 3)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
251 │     margin: -$size/3; …
```
=> Fixed sass deprecation warnings

packages/amplication-data-service-generator/src/version.ts, packages/amplication-server/src/core/queue/queue.service.ts
Issue Number: #4010 
Showing the empty repo resolve message only when needed and not for any git error.
Note: For further different resolve messages, a function can be created mapping a resolve message to a particular error. I have used a simple ternary operation for now.
=> fix(server): More information in PR error message.

packages/amplication-client/src/Components/NameField.tsx, packages/amplication-client/src/Components/TopicNameField.tsx
Issue Number: #4015
Replaced the native `div` with Formik `ErrorMessage` component. There is a lot of refactoring can be done on these components. However, for the time being, these are the minimal changes that can be applied to resolve the issue.
=> mv div ErrorMessage

packages/amplication-client/src/Workspaces/ResourceList.tsx
=> fix: loading state while navigating between projects

tutorials/significance of amplication blog.md
=> blog created on amplication

packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/server/resource/module/create-module.ts
Issue Number: #4138 
add CreateEntityModule and CreateEntityModuleBase events to DSG
=> 4138 CreateEntityModule & CreateEntityModuleBase events

packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/server/package-json/create-package-json.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
Issue Number: #3959 
rename `CreatePackageJson` to `CreateServerPackageJson`
=> rename `CreatePackageJson` to `CreateServerPackageJson`

.github/actions/get-services-hash/.prettierrc, ee/packages/amplication-git-pull-service/.prettierrc, ee/packages/amplication-git-push-webhook-service/.prettierrc, packages/amplication-cli/.prettierrc, packages/amplication-git-pull-request-service/.prettierrc, packages/amplication-git-service/.prettierrc, packages/amplication-prisma-db/.prettierrc, packages/amplication-server/.prettierrc
Issue Number: Fixes #3268 
This PR adds the `$schema property` to all the `.prettierrc` files available in the repository.
=> Issue 3268: Added $schema property for all .prettierrc files

packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Update the DSG with the new plugins and code gen types versions
=> Update the DSG with the new plugins and code gen types versions 

tutorials/social_post_2.md
Close https://github.com/amplication/amplication/issues/4031
- Add social post
=> chore(tutorials): add social post

tutorials/Amplication-Intro.md
Added my video to amplication github repo
=> Added my video

tutorials/My_amplication_blog.md
Close #4006 
Created a blog/tutorial on what is Amplication and how to get started with it !
=> Created My amplication blog

tutorials/social_post_chirag8023.md
=> Create two social posts about amplication

package-lock.json, package.json
Close #2932
I have Fixed  The package.json and package-lock.json
=> Fix : package.json / package-lock.json

packages/amplication-data-service-generator/src/server/static/Dockerfile
Close #4027 
fix generated app `Dockerfile`
The result:
=> fix generated app `Dockerfile`

packages/amplication-data-service-generator/src/admin/static/src/Login.tsx, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close #4202 
Fix generated app `admin-ui` compilation error
=> Fix generated app `admin-ui` compilation error

tutorials/blog-post-2.md
Add blog post about my experience with Amplication as part of the hacktoberfest.
=> chore:add blog post

CODE_OF_CONDUCT.md
Close #4177 
Updated the link to Contributor Covenant Website in [Attribution](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md#attribution) section of CODE_OF_CONDUCT.md which was not linked properly. Above mentioned issue has SS of the problem.
=> docs: Update CODE_OF_CONDUCT.md

packages/amplication-client/src/Entity/EntityFieldLinkList.scss, packages/amplication-client/src/Entity/EntityFieldLinkList.tsx, packages/amplication-client/src/Resource/resourceSettings/ProjectConfigurationSettingsPage.scss, packages/amplication-client/src/Resource/resourceSettings/ProjectConfigurationSettingsPage.tsx
issue: #3933 
Fixed padding between options on entity page and Project Configuration Settings Page
=> fix(side-menu-padding): padding between the sidemenu options fixed

packages/amplication-client/src/Entity/EntityForm.tsx, packages/amplication-client/src/Profile/ProfileForm.tsx, packages/amplication-client/src/Project/NewProject.tsx, packages/amplication-client/src/Resource/ResourceForm.tsx, packages/amplication-client/src/Roles/NewRole.tsx, packages/amplication-client/src/Roles/RoleForm.tsx, packages/amplication-client/src/Workspaces/WorkspaceForm.tsx, packages/amplication-client/src/Workspaces/hooks/workspace.ts, packages/amplication-client/src/util/formikValidateJsonSchema.ts
Close #4012 
Using `ajv-errors` to have custom user friendly messages for field error messages
=> Updated field error messages to be more user friendly

tutorials/Medium-blog-post.md
=> added the link to my Amplication blog

tutorials/social_post_gokul.md
Close #4031 
Added Social Post links
=> Social Media Advocacy

README.md
Close https://github.com/amplication/amplication/issues/4210
=> docs (Readme): Convert logo to clickable Link

packages/amplication-client/src/Resource/OverviewTile/OverviewTile.tsx
=> Fix | Update the instruction text on the Service Dashboard

nx.json, package.json, packages/amplication-data-service-generator/src/util/enum-builder.ts, packages/amplication-git-pull-request-service/tests/diff/diffset-mapper.spec.ts, packages/amplication-server/scripts/check-graphql-schema.ts, script/setup.ts
Close #4252 
- fixed compilation error which made the build step fail.
=> fix compilation errors

packages/amplication-client/src/Entity/EntityFieldLinkList.tsx, packages/amplication-client/src/Layout/InnerTabLink.scss, packages/amplication-client/src/VersionControl/CommitListItem.tsx, packages/amplication-data-service-generator/README.md, packages/amplication-design-system/src/components/CircularProgress/CircularProgress.scss
Close #4211 
fix innerTabLink to have padding when hover and add __row to commitListItem className to fix gap problem
=> fix(client): commitListItem className

package.json
This PR updates the main build script from Lerna to NX
=> Update the main build script

tutorials/blog-posts-by-shabana.md, tutorials/social-media-post-shabana.md
Adding my contribution to promoting and spreading amplication.
In accordance with issue #4006
Uploaded my blog post and social media post to promote amplication and share my experience learning about the tool so far.
=> Upload Blog Post #4006

tutorials/blog-posts-by-shabana.md, tutorials/social-media-post-shabana.md
In accordance with the Issue #4031
Added Social Media Post link
=> Upload Social Media Post

tutorials/bella_blogpost.md
=> blog submission

tutorials/Amplication-Intro-Blog.md
Close #4006 
Added my blog post: https://dev.to/learnearnfun/introduction-to-amplication-4k2i
=> Added my Blog Post

.github/workflows/ci-nx-all.yml, .github/workflows/ci-nx.yml, packages/amplication-server/project.json
Fix nx ci steps to use the correct base branch as well as fix the amplication-server project.json format.
This will fix the failure on the `npx nx workspace-lint` 
=> fix: nx ci jobs

packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/server/resource/create-resource.ts, packages/amplication-data-service-generator/src/server/resource/test/create-controller-spec.ts
Close #4291 
Added `CreateEntityControllerSpec` plugin event.
(a description for the docs will be provided soon)
=> Added `CreateEntityControllerSpec` plugin event

helm/charts/amplication/values-staging.yaml
=> change fsap

.vscode/settings.json
Close #4329 
Add a path of the prettier config file
=> set the config path in vscode

helm/charts/amplication/values-alex.yaml, helm/charts/amplication/values-amit.yaml, helm/charts/amplication/values-ariel.yaml, helm/charts/amplication/values-common.yaml, helm/charts/amplication/values-eugene.yaml, helm/charts/amplication/values-mor.yaml, helm/charts/amplication/values-prod.yaml, helm/charts/amplication/values-shimi.yaml, helm/charts/amplication/values-staging.yaml, helm/charts/services/amplication-client/values.yaml
Fix leftover environment variable changes for client application after migration nx react.
=> Fix: env variables for client app

README.md
Minor improvement on the Getting started with local development
=> fix: improve local development configuration instructions

packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/server/resource/resolver/create-resolver.ts
Close #[issue-number] #4358 (#4136)
=> create resolver module events

helm/charts/amplication/values-prod.yaml, helm/charts/dsg-runner-infra/values/prod.yaml
=> correct prod configurations

helm/charts/dsg-runner-infra/values/prod.yaml
=> switch fsap in pv

packages/amplication-data-service-generator/src/server/auth/user-info/user-info.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close #4389
fix user import from UserInfo
=> fix user import from UserInfo

packages/amplication-client/src/Resource/ResourceHome.scss
Close #3649
- Increase top banner height to 180px
- change text color to `--black5`
=> fix(client): project configuration UI

packages/amplication-code-gen-types/package.json, packages/amplication-code-gen-types/src/code-gen-types.ts, packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/src/tests/create-data-service-with-kafka.spec.ts
Close #4425 
Fix code gen types export
=> Fix code gen types export

packages/amplication-data-service-generator/src/server/swagger/swagger.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close #1853 
Add SwaggerCustomOptions Type to swagger.template.ts
=> [BUG] add type of swaggerSetupOptions in swagger.template.ts

packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts, tsconfig.base.json
=> select new project when adding new one

packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts, packages/amplication-data-service-generator/src/server/auth/token/create-token-payload-interface.ts, packages/amplication-data-service-generator/src/server/auth/user-info/create-user-info.ts, packages/amplication-data-service-generator/src/server/create-server.ts
Close #4459
create new events for `CreateUserInfo` and `CreateTokenPayloadInterface`
=> create new events for `CreateUserInfo` and `CreateTokenPayloadInterface`

docker-compose.dev.yml
Close: #4430
Add health check on postgresql container for local development environment.
=> chore: add health check on postgresql

packages/amplication-client/src/User/Login.tsx
Close #4438 
This PR adds a title meta to the login page with https://www.npmjs.com/package/react-helmet package
=> fix(client): add title for login page

packages/amplication-data-service-generator/src/server/auth/create-constants/create-constants.template.ts, packages/amplication-data-service-generator/src/server/auth/create-constants/create-constants.ts, packages/amplication-data-service-generator/src/server/create-server.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
Close #4473
fix auth constants mock user
=> fix auth constants mock user

CONTRIBUTING.md
=> Open to community

packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/util/paths.ts
Close #4404 
This PR adds a redirect to the commit page when building a new build
=> Redirect to commits when build

packages/amplication-design-system/src/components/CodeEditor/CodeEditor.tsx
=> Bug code view stringify string

.husky/pre-commit
Close #4384
Add support for `nvm` node installation in git tools. https://github.com/nvm-sh/nvm 
=> chore: add support for nvm in git pre commit hook

packages/amplication-data-service-generator/src/util/get-user-id-type.ts
Close: #4515 
set `CUID` as a default id type when it returns a null or undefined
=> fix - default id type

packages/amplication-data-service-generator/src/admin/create-dotenv.ts, packages/amplication-data-service-generator/src/create-dotenv.ts, packages/amplication-data-service-generator/src/server/create-dotenv.ts
Close: #4525
Convert serviceSettings parameter into a dictionary.
=> fix serviceSettings parameter send to replacePlaceholdersInCode function

packages/amplication-data-service-generator/project.json, packages/amplication-data-service-generator/src/server/create-server.ts, packages/amplication-data-service-generator/src/version.ts
Close #4468 
add DSG vestion to logs page
=> feat(dsg): add DSG version to logs page

helm/charts/amplication/values-prod.yaml
=> change storage request

helm/charts/dsg-runner-infra/templates/sensor.yaml, packages/amplication-data-service-generator/src/create-data-service-impl.ts
=> add try/catch to main dsg process

packages/amplication-server/.env
Close: #4565 
This PR lines up the env values
=> fix env values in server

nx.json
Close: #4568 
Configure Nx to not cache generate and check.
=> chore(nx): update cacheable operations

packages/amplication-data-service-generator/project.json
=> add remove:generated to test data service

.github/workflows/deploy.yml
Close: #4340 
This PR introduces a new trigger for the deploy workflow that will activate on successful termination of `CI Nx Affected` workflow in `next` branch.
As an outcome, every time the HEAD of `next` branch changes (new commits / merged pull requests), the deploy workflow will be triggered saving developers from manually trigger the job.
Changes in actions have been tested here: https://github.com/overbit/amplication/actions where Deploy fails due to missing secrets. 
=> chore: automate next deployment

.github/workflows/ci-nx.yml, .github/workflows/deploy.yml
Close: #4340 
Fix reusable deploy to work as both reusable and manually triggered.
To see the change in action, a modified version of the workflow is running here as pull_request triggered https://github.com/overbit/amplication/actions/runs/3647785805 
and here manually 
https://github.com/overbit/amplication/actions/runs/3647787738
=> chore(ci): fix ci automatic deploy on next

.github/workflows/deploy.yml
Close: #4597
Add support for `push` and `pull_request` events in Deploy workflow
=> chore(ci): update deploy ci to support both push and pull_request events

.github/workflows/deploy.yml
Close: #4597
Fix leftover variables 
=> chore: fix leftover variable in deploy job

helm/charts/dsg-runner-infra/templates/sensor.yaml
=> update dsg version

packages/amplication-client/src/Plugins/hooks/usePlugins.ts
Close: #1959 
update mongo-db plugin version to latest
=> update mongo-db plugin version

package-lock.json, package.json, packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json
This PR update versions for our packages
=> Update the package versions

packages/amplication-data-service-generator/src/server/auth/user-info/user-info.template.ts, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/amplication-data-service-generator/src/version.ts
Close: #4609 
Fix import of user model in user info
=> Fix import of user model in user info

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
This PR adds v in the version display
=> Add v for version

packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/util/paths.ts
Close: #4633
This PR redirects you directly to the entity page on the creation
=> fix(client): entity redirect

packages/amplication-client/src/Entity/NewEntityField.tsx, packages/amplication-design-system/src/components/TextInput/TextInput.tsx
Close: #4635 
This PR rerenders the input component with an autofocus change
=> Rerender after auto focus change

helm/charts/dsg-runner-infra/templates/sensor.yaml, packages/amplication-data-service-generator/package-lock.json, packages/amplication-data-service-generator/package.json, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #4644 
Update Postgres plugin version
=> Update Postgres plugin version

packages/amplication-client/src/ServiceConnections/ServiceConnectionsList.tsx
Close: #4283
remove messageborkerlist from useEffect dependency array
=> fix (client) remove messageborkerlist from useEffect

packages/amplication-client/src/Components/CommitMessage.tsx, packages/amplication-client/src/Components/CommitSelectorItem.tsx, packages/amplication-client/src/VersionControl/CommitData.tsx
Close: #4561 
Commits with no message displayed `"No Commit Message"` as a fallback, which isn't very helpful. This PR addresses this by improving the message with a commit ID. 
=> Improve Commits with No Message

README.md
Close: #4658 
Added a note under step number 5 of setting up dev local environment as suggested in #4658
=> added a note under step number 5 in setting up local dev environment

packages/amplication-design-system/src/components/CodeEditor/CodeEditor.tsx
Close: #4581
fix code view syntax highlighting
=> fix code view syntax highlighting

packages/amplication-data-service-generator/src/admin/entity/entity-title-component/entity-title-component.template.tsx, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #4655 
Fix admin-ui entity title return value when using auto-increment id
=> Fix admin-ui entity title return value when using auto-increment id

packages/amplication-client/src/App.tsx, packages/amplication-client/src/User/CompleteInvitation.tsx, packages/amplication-client/src/User/Login.tsx
=> Hotfix/4535 bug report invitation link to a workspace doesn't work

helm/charts/dsg-runner-infra/templates/sensor.yaml
=> update dsg sha before deploying to next

helm/charts/amplication/Chart.lock, helm/charts/amplication/Chart.yaml
Close: #4699
Update the postgresql helm dependency to a newer version, because the old version was not available anymore.
- old version: 10.16.2
- new version: 10.9.13
=> chore: update the postgresql helm dependency to a new version

libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json, libs/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
I accidentally remove the plugins from the DSG
=> Add missing plugins

libs/data-service-generator/src/server/prisma/create-prisma-schema-fields.ts
This PR adds a missing update that was not added in the previous PR
=> Add missing update

helm/charts/amplication/values-common.yaml
Close: #4699
Changes made regarding the version bump of the postgresql helm chart also broke the way our values.yaml provided the credentials/config.
=> fix: change values provided to the postgresql chart to enable db connections

helm/charts/dsg-runner-infra/templates/sensor.yaml
This PR is fixing the region in the sensor
=> Update sensor image

helm/charts/dsg-runner-infra/templates/sensor.yaml
=> fix(dsg): fix sensor configuration for new dsg runner

libs/data-service-generator/package.json, packages/amplication-data-service-generator-runner/project.json
Partial: https://github.com/amplication/amplication/issues/4610
=> Fix the dsg packages

helm/charts/dsg-runner-infra/templates/sensor.yaml
=> Update sensor sha

packages/amplication-data-service-generator-runner/Dockerfile
Partial: #4610
Fix DSG runner docker image by installing the dependency during the docker build process
=> Fix dsg runner Dockerfile

helm/charts/dsg-runner-infra/templates/sensor.yaml, libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json, libs/data-service-generator/project.json, libs/data-service-generator/src/version.ts
=> Update the dsg version

packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/hooks/useResources.ts, packages/amplication-client/src/context/appContext.tsx, packages/amplication-server/src/core/resource/resource.module.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/core/topic/topic.service.ts
Close: #4216 
create default topic for message broker
https://user-images.githubusercontent.com/39680385/208304568-5082602e-865e-43d5-8a9a-72cd7828654b.mov
=> implement default topic for message broker

libs/data-service-generator/src/create-data-service.ts, libs/data-service-generator/src/server/resource/create-dtos.ts
This PR refactors some DSG functions to make debugging easy.
Part of https://github.com/amplication/amplication-infrastructure-next/issues/28
=> Refactor some DSG functions

.github/workflows/ci-nx-all.yml, .github/workflows/ci-nx.yml
Partial: #4610 
Fix ci cache new node_modules 
=> chore(ci): add code-gen-util packages to cache

packages/amplication-server/project.json
=> fix(server): copy prisma binaries

ee/packages/amplication-git-push-webhook-service/src/git-organization/git-organization.module.ts
Close: #4704
Fix missing provider from webhook nestjs git-org module 
=> Fix webhook application failing during startup

helm/charts/dsg-runner-infra/templates/sensor.yaml, libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json, libs/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: https://github.com/amplication/plugins/issues/36
update Postgres plugin version in the DSG
=> update Postgres plugin version in the DSG

packages/amplication-git-utils/src/git/dto/remote-git-repository.ts, packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/git/git.types.ts, packages/amplication-git-utils/src/git/github.service.ts, packages/amplication-git-utils/tests/git/git.constants.ts, packages/amplication-server/src/core/git/__mocks__/GitRepo.ts, packages/amplication-server/src/core/git/__mocks__/GitRepos.ts, packages/amplication-server/src/core/git/dto/objects/RemoteGitRepository.ts
Partial: #4691
This PR adds get repository function
=> Default branch 

packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/git/git.types.ts, packages/amplication-git-utils/src/git/github.service.ts
Partial: https://github.com/amplication/amplication/issues/4691
=> Add isBranchExist function

packages/amplication-git-utils/src/git/dto/branch.ts, packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/git/git.types.ts, packages/amplication-git-utils/src/git/github.service.ts
Partial: https://github.com/amplication/amplication/issues/4691
=> Adds getBranch method

packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
Close: #4763 
This PR add the following parameters on all BI events - workspaceId, projectId, resourceId
=> Common analytics data

packages/amplication-git-pull-request-service/src/pull-request/dto/create-git-commit.dto.ts, packages/amplication-git-pull-request-service/src/pull-request/pull-request.service.ts, packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/git/git.types.ts, packages/amplication-git-utils/src/git/github.service.ts
Partial: https://github.com/amplication/amplication/issues/4691
=> Add some null checks

packages/amplication-git-utils/src/git/github.service.ts
This PR aline the head default
=> fix head typo

packages/amplication-git-pull-request-service/src/pull-request/dto/create-pull-request.args.ts, packages/amplication-git-pull-request-service/src/pull-request/pull-request.service.ts
=> fix: remove unused

packages/amplication-git-utils/src/git/github.service.ts
This PR adds loggs data for the git pull request flow
=> Add logs and data for the git pull request

packages/amplication-git-utils/src/git/github.service.ts, packages/amplication-server/src/core/build/build.service.ts
=> Add logs to the pull request logic

packages/amplication-git-utils/src/git/github.service.ts
=> fix github

helm/charts/dsg-runner-infra/templates/sensor.yaml, libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json, libs/data-service-generator/src/version.ts
Close: part of #4752 
Update the DSG version with the rollback of Prisma client for the generated code (publish new version)
=> Update DSG version with the rollback of prisma client for the generated code

packages/amplication-client/src/Purchase/PurchasePage.scss, packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/WorkspaceList.tsx, packages/amplication-client/src/Workspaces/WorkspaceListItem.scss, packages/amplication-client/src/Workspaces/hooks/useWorkspaceSelector.ts, packages/amplication-client/src/Workspaces/hooks/workspace.ts, packages/amplication-client/src/Workspaces/queries/workspaceQueries.ts, packages/amplication-client/src/context/appContext.tsx
Close: #4772 
Add workspace list to purchase page
=> Add workspace list

packages/amplication-server/src/core/billing/billing.service.ts, packages/amplication-server/src/core/build/build.service.ts
Partial: https://github.com/amplication/amplication/issues/4590
=> Add dynamic pull request mode

packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-server/src/core/billing/ProvisionSubscriptionDto.ts, packages/amplication-server/src/core/billing/billing.controller.ts, packages/amplication-server/src/core/billing/billing.service.ts
=> added billing period selection

helm/charts/dsg-runner-infra/templates/sensor.yaml, libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json, libs/data-service-generator/src/version.ts, package-lock.json, package.json
=> Chore/release 1.2.0

packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts, packages/amplication-client/src/routes/appRoutes.tsx, packages/amplication-client/src/routes/routesUtil.tsx
=> support purchase main route

helm/charts/dsg-runner-infra/templates/sensor.yaml
=> update sdg image version

packages/amplication-server/src/core/billing/BillingFeature.ts, packages/amplication-server/src/core/project/project.service.ts
=> ignore validation for code generation

libs/data-service-generator/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/amplication-server/src/core/build/build.service.ts
Close: #4813 
This PR change the way we get the workspace id
=> Update workspace id

helm/charts/amplication/values-prod.yaml, helm/charts/dsg-runner-infra/values/prod.yaml
=> Merge master to next

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/routes/routesUtil.tsx
=> add upgrade button to workspace page

packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/routes/routesUtil.tsx
Part of #4812
Hiding the banner until the task will be implemented
=> Disable Stigg on pages

packages/amplication-git-utils/src/git/github.service.ts, packages/amplication-git-utils/src/utils/amplication-ignore-manger.ts
=> Fix the amplication ignore crash

packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
=> fix upgrade button state

packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts, packages/amplication-client/src/routes/routesUtil.tsx
=> Bug/back button doesn't get you to main page

packages/amplication-server/src/core/project/project.resolver.ts
=> add project resolver logs, await for commit

packages/amplication-client/src/User/Login.tsx, packages/amplication-client/src/Workspaces/hooks/useCurrentWorkspace.ts, packages/amplication-client/src/routes/routesUtil.tsx
=> redirect to purchase from login

packages/amplication-client/src/Purchase/PurchasePage.tsx
Close: #4837 
Add key prop to StiggProvider component in order to refresh Purchase workspace
=> Add key prop to StiggProvider component

packages/amplication-git-utils/src/git/github.service.ts, packages/amplication-git-utils/src/git/github/AccumulativePullRequest.ts, packages/amplication-git-utils/src/git/github/github-create-tree.ts
Close: #4840
Fix Github create three implementation
=> Fix Github create three  implementation

packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/errors/ValidationError.ts
=> added custom validation error

packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts, packages/amplication-client/src/routes/routesUtil.tsx
=> fix purchase redirect

packages/amplication-git-utils/src/git/github.service.ts
=> fix 'author.service.ts' file is overridden

packages/amplication-git-utils/src/git/github.service.ts
=> fix(pr): takes the `.amplicationignore` file from default branch

libs/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, libs/data-service-generator/src/tests/appInfo.ts
part of #4857 
added  the `.gitignore` to the snapshot tests
=> Add gitignore to snapshot tests

helm/charts/amplication/values-prod.yaml, helm/charts/dsg-runner-infra/values/prod.yaml
=> merging master to next

libs/data-service-generator/src/admin/app/create-app.ts, libs/data-service-generator/src/server/app-module/create-app-module.ts, libs/data-service-generator/src/server/auth/create-constants/create-constants.ts, libs/data-service-generator/src/server/auth/guards/createDefaultGuard.ts, libs/data-service-generator/src/server/auth/token/create-token-payload-interface.ts, libs/data-service-generator/src/server/auth/token/createTokenSerivceTests.ts, libs/data-service-generator/src/server/auth/token/createTokenService.ts, libs/data-service-generator/src/server/auth/user-info/create-user-info.ts, libs/data-service-generator/src/server/message-broker/topics-enum/createTopicsEnum.ts, libs/data-service-generator/src/server/resource/controller/create-controller.ts, libs/data-service-generator/src/server/resource/module/create-module.ts, libs/data-service-generator/src/server/resource/resolver/create-resolver.ts, libs/data-service-generator/src/server/resource/service/create-service.ts, libs/data-service-generator/src/server/seed/create-seed.ts, libs/data-service-generator/src/server/swagger/create-swagger.ts, libs/data-service-generator/src/util/ast.spec.ts, libs/data-service-generator/src/util/ast.ts, libs/data-service-generator/src/util/nestjs-code-generation.spec.ts, package.json
Close: #4868 
This PR improves the performance of the linting pre-commit hook by running code format and code lint fix on affected projects instead of on all of them
=> Chore: improve pre commit hook

packages/amplication-client/src/Purchase/PurchasePage.tsx
Close: #4888 
Fix purchase page plan component displayed twice.
=> fix(client): purchase page duplicated component bug

packages/amplication-server/src/core/billing/billing.service.ts
=> correct desired usage calculation

.github/workflows/ci-nx.yml
=> fix(ci): ci nx affected not generating docker image with branch name tag

.github/workflows/ci-nx.yml
Fix issues related to missing inputs on push events https://github.com/amplication/amplication/actions/runs/3885458060/jobs/6629599688#step:12:43
=> chore(ci): fix nx affected workflow docker tag logic

libs/data-service-generator/src/util/get-entity-id-type.ts, packages/amplication-data-service-generator-runner/project.json
Close: part of #4515
Fix: destructuring id type + fix precommit hook in dsg runner
=> Fix: destructuring id type

libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json, libs/data-service-generator/src/version.ts, package-lock.json, package.json
bumping versions before the release
=> chore: release 122

helm/charts/dsg-runner-infra/templates/sensor.yaml
Close: #4906 
Fix dsg job ImagePullPolicy
=> fix(dsg): job image policy for dsg runner jobs

packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/git/git.types.ts, packages/amplication-git-utils/src/git/github.service.ts
Close: #4887
This PR extracts the logic of the files from the github service to the git manager
=> Extract the files logic from `github.service.ts`

libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json
Close: #4681 
Update mongo-db version in DSG dependencies.
=> bump mongo-db version

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
=> Fix/4913 bug report first click on the upgrade button doesn't do anything

packages/amplication-server/src/core/project/project.service.ts
=> pass entities per service limitation correctly

packages/amplication-design-system/src/components/TextInput/TextInput.scss
Close: #4652
added `width: fit-content` to a div to fix the error icon going out of project-name input field
`src/components/TextInput/TextInput.scss`
Before this change: 
After this change: 
- [ x] Tests for the changes have been added
- [ x] `npm test` doesn't throw any error
=> [BUG FIX] Project name error

helm/charts/amplication/values-prod.yaml
Close: #4936 
Change the client application component to use the maintenance page image instead, so that no changes can be made to the database during the migration process.
=> [migration] move to the maintenance page on the client application component

packages/amplication-server/src/core/build/build.service.ts
=> fix(server): remove legacy dsg logger

packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/queue/queue.service.ts
=> fix(server): kafka client emit silently fails

.github/workflows/security.yml
Close: #4903 
Fix reference to security.yml 
=> Update security.yml reference 

packages/amplication-server/src/main.ts
Close: #4958 
This PR change the options of the class validator
=> Change back the default of class-validator

packages/amplication-design-system/src/components/TextInput/TextInput.scss
Close: #4961 
Following incorrect fix in https://github.com/amplication/amplication/pull/4756, we revert the fix and reopen https://github.com/amplication/amplication/issues/4652
=> fix(client) textbox width

.vscode/settings.json, packages/amplication-server/.env, packages/amplication-server/src/core/billing/billing.service.ts, packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/project/project.service.spec.ts, packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/core/workspace/workspace.resolver.ts, packages/amplication-server/src/core/workspace/workspace.service.spec.ts, packages/amplication-server/src/core/workspace/workspace.service.ts
=> fix server in local dev env when billing is not configured

.github/workflows/release.yml
Close: #4968 
Fix the deployment issue to next due to workflow_run github context
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
=> chore(ci): fix deployment of next branch

libs/data-service-generator/package.json, libs/data-service-generator/src/index.ts, libs/data-service-generator/src/version.ts, packages/amplication-data-service-generator-runner/Dockerfile, packages/amplication-data-service-generator-runner/project.json, packages/amplication-data-service-generator-runner/src/dynamic-package-installation.ts, tsconfig.base.json
Close: #4974 
This PR removes the old and wrong way to import DSG create-log code
=> Remove wrong way of import DSG code

packages/amplication-data-service-generator-runner/project.json
Fix https://github.com/amplication/amplication/actions/runs/3938024850/jobs/6736223858
=> fix refactor

.github/workflows/ci.yml
Close: #4780 
Avoid duplicated executions of ci workflow on `next` changes when a PR is open.
=> chore(ci): fix duplicated execution of ci workflow on next

packages/amplication-client/src/Purchase/PurchasePage.tsx
=> correct privacy policy

packages/amplication-data-service-generator-runner/src/dynamic-package-installation.ts, packages/amplication-data-service-generator-runner/src/main.ts, packages/amplication-data-service-generator-runner/src/utils/DynamicPackageInstallationManager.ts
This PR fix a problem with the plugin meta logs
Partly: #4624
=> Fixed a problem that logs dont show up

packages/amplication-client/src/App.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/context/appContext.tsx, packages/amplication-client/src/hubSpotChat.scss, packages/amplication-client/src/hubSpotChat.tsx, packages/amplication-client/src/util/analytics-events.types.ts
=> add hubspot chat widget to our application

libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json, libs/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/amplication-data-service-generator-runner/src/main.ts
Related issue:  https://github.com/amplication/amplication-infrastructure-next/issues/28 
Rollback dynamic installation logic.
=> refactor(runner-dsg): remove dynamic installation logic

.github/workflows/deployment.template.yml
Close: #5011 
Related to #5012, this PR contains a quick workaround fix to avoid failure in deployment workflow due to affected projects that should not be deployed
=> chore(ci): fix for release workflow for local-dsg-runner

packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/util/analytics-events.types.ts
Close: #5025
Add a BI event to identify when a user starts an authenticated session
=> feat(client):track workspace selected

package-lock.json, package.json
This PR bumps the version of the main package.json
=> chore: bump package json version

libs/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
This PR fixes https://github.com/amplication/amplication/actions/runs/3985121654 by updating the snapshot
=> fix(dsg): update snapshot

libs/data-service-generator/src/prepare-context.ts, libs/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, libs/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
This PR fix the null check for fk holder
=> fix(dsg): fix default pointer

docker-compose.dev.yml, package.json
Close: #4893 
Bump the Kafka related containers to the latest version to improve local development environment performance.
As part of this change, a new script for cleaning up the local environment has been added too.
=> chore: update local environment kafka container image

packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-server/src/core/workspace/dto/ProvisionSubscriptionInput.ts, packages/amplication-server/src/schema.graphql
=> validate redirect state, allow nullable success and cancel urls

packages/amplication-client/src/Purchase/PurchasePage.tsx
=> pricingpageclose event not triggered

.github/workflows/deployment.production.yml
Close: #4966 
**Blocker**: this pull request requires that pull request #5021 is merged first and also includes the name suggested in the comments, namely `nx.template.yml` instead of `nx-affected.template.yml`.
This pull request introduces a new workflow that is meant to bridge the gap between the implementation of argocd image update and the current implementation after migration (i.e. manual changes on the production manifests). It first determines the previous git tag/release based on the one that triggered the workflow, after which it check which apps are affected and deployed in the form of container (i.e. provides output `affected-dockerable`). These affected components are then packaged and pushed to a container registry, and the last jobs takes care of changing the image tag of …
=> feat: introduce workflow for doing a release to production

.github/workflows/ci.yml, .github/workflows/deployment.production.yml, .github/workflows/release.template.yml
Close: https://github.com/amplication/amplication/issues/5011
Using workflow templates every secret need to be passed to the template from the calling workflow for security reasons.
This PR fix the issue that prevent workflow to successfully run due to missing secrets.
=> fix(ci): missing secrets definition in template workflows

packages/amplication-client/src/VersionControl/Commit.tsx
=> add reason to PassedLimitsNotificationView event

packages/amplication-client/src/Purchase/PurchasePage.tsx
=> pricingpagectaclick wrong type sent by the event

libs/data-service-generator/package-lock.json, libs/data-service-generator/package.json, libs/data-service-generator/src/server/create-grants.ts
Related to : [#4943](https://github.com/amplication/amplication/issues/4943)
Replace the external dependency that contains an invalid index.d.ts ([line 9](https://www.npmjs.com/package/@extra-set/difference?activeTab=explore)) with the magic of ts! 
=> refactor(dsg): to not use @extra-set/difference dependency

packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/hubSpotChat.scss, packages/amplication-client/src/util/analytics-events.types.ts
=> show chat on contact us click
