amplication/amplication

- packages/amplication-server/src/filters/GqlResolverExceptions.filter.spec.ts
- packages/amplication-server/src/filters/GqlResolverExceptions.filter.ts
Correct gql resolver exceptions filter to include stacktrace for unknown errors
> Server: Stack traces for unknown errors

- production.cloudbuild.yaml
Cloud run doesn't understand non-exact docker image identifiers from another project.
This PR saves the resolves the image identifier and saves it to Terraform's variables file.
> Fix Cloud Build Production

- packages/amplication-client/src/Entity/DataTypeSelectField.tsx
- packages/amplication-client/src/Entity/EntityField.tsx
- packages/amplication-client/src/Entity/EntityFieldForm.tsx
When a user select another field - do not reset the properties to default in order to show the saved properties values
> Show saved properties on selected field change

- packages/amplication-server/src/core/entity/entity.service.spec.ts
- packages/amplication-server/src/core/entity/entity.service.ts
Extract the logic from EntityService.CreateVersion to a new function EntityService.CloneVersionData
The new function will be used in these cases:
- Commit - to copy data from version 0 to the new version
- Discard Changes - to copy data from the last version to version 0
> Refactor - entity version clone data

- packages/amplication-data-service-generator/src/create-data-service.ts
Ignore TypeScript compilation output files when copying static files to generated apps
> Remove Compiled Files From Generated Apps

- packages/amplication-data-service-generator/src/resource/dto/create-dto.spec.ts
- packages/amplication-data-service-generator/src/resource/dto/create-dto.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Make DTO fields always definitive to comply with the type returned by the controller.
```diff
class Example {
@IsString()
@IsOptional()
-  field?: string | null;
+  field!: string | null;
}
```
> Data Service Generator: Fix DTO Optional Fields

- packages/amplication-data-service-generator/src/static/main.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Enable CORS in generated apps by default, later we should allow users to define their own policy.
> Data Service Generator: Enable CORS for generated app

- packages/amplication-data-service-generator/src/resource/controller/controller.template.ts
- packages/amplication-data-service-generator/src/resource/controller/to-many.template.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Use namespace imports in controller templates to prevent clashes between user-created identifiers and code.
Resolves #832
> DSG: Use namespace imports in controller template

- terraform/modules/apps_env_baseline/main.tf
- terraform/modules/cd/main.tf
- terraform/modules/cloud_build_default_service_account/main.tf
- terraform/modules/cloud_build_default_service_account/variables.tf
- terraform/modules/env_baseline/main.tf
- terraform/modules/manual_deploy/main.tf
Replace our `cloud_build_default_service_account` Terraform module with Terraform's recommended `google_project_service_identity` to obtain Cloud Build service account.
See: https://github.com/hashicorp/terraform-provider-google/issues/7522
> Terraform: Use google_project_service_identity to get cloud build service account

- packages/amplication-data-service-generator/src/create-data-service.ts
- packages/amplication-server/src/core/build/build.service.ts
For testing purposes the create admin was disabled when called from the server. This PR removes this behaviour.
> DSG: Remove option to not create admin

- packages/amplication-data-service-generator/Dockerfile
- packages/amplication-data-service-generator/src/static/Dockerfile
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Disable npm install audit and funding options to reduce the installation time and logs emitted when building Docker containers
> DSG: Disable npm install extra features

- README.md
Ading banner to join instead of link.
Before merge confirm PR on site repo, it use an image located on the asset folder.
> add discord banner to readme

- packages/amplication-data-service-generator/src/server/resource/resolver/to-many.template.ts
- packages/amplication-data-service-generator/src/server/resource/resolver/to-one.template.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- Do not require to pass args to resolve one-to-one relations
- Correct use of UserRoles decorator in to-one and to-many
> DSG: Fix to-one resolve field

- packages/amplication-server/src/core/entity/entity.service.spec.ts
- packages/amplication-server/src/core/entity/entity.service.ts
- Use `findFirst()` instead of `findMany()` when looking for a single object
- Improve error messages
- Add documentation
- Reduce repetition when looking for existing field
- Fix example user in entity service test and acquire lock behaviour in tests
> Refactor entity service

- packages/amplication-client/src/Layout/WelcomePage.tsx
Changed "as" to "us":
"amplication is an open-source project and you can send as" was changed to "amplication is an open-source project and you can send us"
> Text suggestion PR

- packages/amplication-container-builder/src/cloud-build/config.spec.ts
- packages/amplication-container-builder/src/cloud-build/config.ts
- packages/amplication-deployer/src/gcp/config.spec.ts
- packages/amplication-deployer/src/gcp/config.ts
Temp fix to resolve current high load on GCP Build service
This value should be moved to an external param 
We should look for another platform to execute build as each Google Cloud project is granted quota to run ten builds at a time
https://cloud.google.com/cloud-build/quotas
> gcp machine type

- .github/workflows/ci.yml
Resolves #1285 
[x] - Remove build docker for amplication/scheduler. The scheduler is not used on the cloud only no local deployment
[x] - Remove cache action. Container build time with and without cache is the same. Total execution time is faster without cache.
> chore: remove cache and scheduler from GitHub Action

- packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.spec.ts
- packages/amplication-data-service-generator/src/server/resource/dto/create-field-class-property.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Relation property on entity DTO should always be optional since the developer may request just the parent object without the child object (online Input DTO where it must be required when the field is required)
> DSG: make relation property on entity DTO optional

- packages/amplication-data-service-generator/package-lock.json
- packages/amplication-data-service-generator/package.json
- packages/amplication-data-service-generator/src/server/static/package-lock.json
- packages/amplication-data-service-generator/src/server/static/package.json
Downgrade from prisma@2.20.1 to prisma@2.19.0 to resolve conflict with TypeGraphQL
https://github.com/MichalLytek/typegraphql-prisma/issues/92
> Chore: downgrade Prisma to 2.19 in generated app

- packages/amplication-server/src/core/deployment/deployment.service.spec.ts
- packages/amplication-server/src/core/deployment/deployment.service.ts
Limit the number of "destroy" actions per cycle not to block the build queue and to avoid exhausting the resources limit
> Limit the number of destroy actions per cycle

- packages/amplication-data-service-generator/src/server/resource/dto/graphql/order-by-input/order-by-input.ts
- packages/amplication-data-service-generator/src/server/resource/resolver/to-many.template.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
resolves #1218 
The delete mutation returns the deleted object.
When the entity has a to-many relation the resolveField function throws an error since the deleted object does not exist
> fix: return empty array when parent resource does not exist

- Dockerfile
- packages/amplication-data-service-generator/Dockerfile
The change by Renovate causes an error in the staging environment. Reverting back to previous values
```
{
"textPayload": "Uncaught signal: 6, pid=1, tid=1, fault_addr=0.",
"insertId": "60e970dc000914bda3928896",
"resource": {
"type": "cloud_run_revision",
"labels": {
"service_name": "cloudrun-srv",
"location": "us-east1",
"revision_name": "cloudrun-srv-7bv9q",
"configuration_name": "cloudrun-srv",
"project_id": "amplication"
}
},
"timestamp": "2021-07-10T10:05:16.595100299Z",
"severity": "ERROR",
"labels": {
"instanceId": ""
},
"logName": "projects/amplication/logs/run.googleapis.com%2Fvarlog%2Fsystem",
"receiveTimestamp": "2021-07-10T10:05:16.599293597Z"
}
```
> fix(deps): update node.js back to previous values before changes by renovate

- packages/amplication-data-service-generator/src/admin/static/package.json
Revert changes made by Renovate that caused the DSG e2e test to fail
- DSG e2e is not included in the CI before merge to decrease the CI run time. We should include the e2e test on PRs created by Renovate
> fix(deps): dsg mui version

- packages/amplication-data-service-generator/src/admin/entity/entity-title-component/entity-title-component.template.tsx
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
adding recorde.id as a backup to the record.TITLE because the select of react admin not allow null
> fix(dsg): add default title to Entity title component admin-ui

- .gitignore
- packages/amplication-client/src/Application/ApplicationForm.tsx
No warning is shown when the user renames the app's name as same as that of the other app
https://github.com/amplication/amplication/issues/2080
> bug(apmlication-client): no error message rename to an existing app name

- packages/amplication-server/Dockerfile
GH Issue: https://github.com/amplication/amplication/issues/2165
This PR separates `amplication`/server` into its own container image. The following improvements have been made...
1. Reduces image size from 2.45G+ to 984 MB
2. Reduces build time from 550+ Seconds to 330 Seconds.
Report from [Dive](https://github.com/wagoodman/dive)
```
Image name: 5d1f79b669c278d2a14a0b9805f5d21ffc972a3df9834f03fe8f6a0fca275f4f
Total Image size: 984 MB
Potential wasted space: 17 MB
Image efficiency score: 99 %
```
How to build the container image...
1. Go to root dir of amplication
2. run ` docker build -f packages/amplication-server/Dockerfile .` (This is telling Docker to set to the current context `.` and specifying the location of the dockerfile) 
3. run `docker run -p 3000:3000 <docker image sha>` …
> feat(server): Add @amplication/server Dockerfile

- packages/amplication-client/src/VersionControl/BuildSteps.tsx
Issue Number: #2244 
wrong download icon in build screen
> fix(server): wrong download icon in build screen

- packages/amplication-design-system/src/components/Tooltip/Tooltip.scss
- packages/amplication-design-system/src/style/css-variables.scss
Issue Number: #2323
Added tooltip text color so that tooltip text can be visible in light theme mode
> fix(client): tooltip text not visible in light mode

- packages/amplication-client/src/Application/git/AuthAppWithGit.tsx
- packages/amplication-client/src/Application/git/GitActions/RepositoryActions/RepositoryActions.scss
- packages/amplication-client/src/Application/git/GitActions/RepositoryActions/RepositoryActions.tsx
This pr cancel the reset of the git organization in the ui
> fix(client): cancel organization reset

- packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
- packages/amplication-data-service-generator/src/admin/entity/entity-create-component/create-entity-create-component.ts
- packages/amplication-data-service-generator/src/admin/entity/entity-edit-component/create-edit-entity-component.ts
- packages/amplication-data-service-generator/src/admin/entity/react-admin.util.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- packages/amplication-data-service-generator/src/version.ts
fix #2225 
we should delete https://github.com/amplication/amplication/pull/2354
On admin UI, added the ability to make a reference between two entities in a form of many to many (one to many from the entity perspective).
For example,  an order can have many products and a product can be in many orders.
An order with its products
A product with its orders
To make it works I added the following block code on the edit entity and create entity files (post and tag for the example):
```
<ReferenceArrayInput
source="tags"
reference="Tag"
parse={(value: any) => value && value.map((v: any) => ({ id: v }))}
format={(value: any) => value && value.map((v: any) => v.id)}
>
<SelectArrayInput optionText={TagTitle} />
</ReferenceArrayInput>
```
> fix(dsg) admin ui added m2m relation

- packages/amplication-data-service-generator/package-lock.json
- packages/amplication-data-service-generator/package.json
- packages/amplication-data-service-generator/src/admin/static/package-lock.json
- packages/amplication-data-service-generator/src/admin/static/package.json
fix: #2426 
This pr is updating the ra-data-graphql-amplication to version 0.0.12 that have a new and updated tests
> Update ra-data-graphql-amplication test's

- packages/amplication-data-service-generator/src/server/resource/test/controller.spec.template.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- packages/amplication-data-service-generator/src/version.ts
Issue Number: #2387 
- This fixes issue #2387 wherein HTTP status code for not found is added directly instead of referencing the enum HttpStatus. 
- This also updates the corresponding Jest snapshot for the test.
- The `version` field in `packages/amplication-data-service-generator/src/version.ts` seems to have been auto-updated during the build process and I kept it for the reason that it matches the version in the corresponding package.json file.
> fix(dsg): use HttpStatus.NOT_FOUND in controller test for testing 404s

- packages/amplication-client/src/Layout/SupportMenu.scss
Issue Number: #2431 
Changed background and hover colours for the support menu.
> fix(client): Change colors

- packages/amplication-client/src/Application/git/dialogs/GitCreateRepo/GitCreateRepo.scss
Width of create git repo dialog in error state remains same as in without error state
Issue Number: #2385 
https://user-images.githubusercontent.com/39362422/158685825-af285714-c1c1-4582-af14-ff7c5a5ae76c.mov
> fix:  width fix when error shown in git create repo

- packages/amplication-design-system/src/components/TextInput/TextInput.scss
Issue Number: #2019
Solves this issue - disabled input has an hover state behaving
> Bug 2019 - Disabled input has an hover state behaving

- packages/amplication-data-service-generator/src/server/static/src/decorators/api-nested-query.decorator.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- packages/amplication-data-service-generator/src/util/text-file-parser.ts
- packages/amplication-design-system/src/components/CircleBadge/CircleBadge.tsx
- packages/amplication-design-system/src/components/UserAndTime/UserAndTime.tsx
- packages/amplication-design-system/src/components/UserAvatar/UserAvatar.tsx
- packages/amplication-server/src/core/auth/auth.service.ts
- script/setup.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
resolved #2493 
the problem was the pluralized utility function.
The source attribute of ReferenceArrayInput expect to get an unpluralized version of the entity
(maybe after the change we did on ra-data-graphql-amplication package because I remember that before it didn't work with the unpluralized version)
> feat(dsg admin ui saved changes on m2m relation

- packages/amplication-data-service-generator/src/admin/entity/create-field-input.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- packages/amplication-data-service-generator/src/version.ts
fix #2505 
changed the source attribute so that it will not depend on the relation entity name, but on the field name.
> hotfix(dsg) react admin ui fix source attribute

- packages/amplication-data-service-generator/src/admin/static/src/Login.tsx
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
An API call to MaterialUI was outdated which would error in the browser console and make the UI look weird. I changed the code that to me seemed to be the code that affected it. It fixed it for me in my generated project anyway. Haven't written a test for this and I think this would be a hard one to test too. Wasn't sure about updating the snap files, so let me know if I need to change anything
Fixes #2520
Issue Number: 2520
> fix(data-service-gen): update outdated/deprecated code

- packages/amplication-client/src/Settings/ApiTokenListItem.scss
Issue Number: #2516
Fix api token text overflowing out of container
> fix(client): api token text container

- packages/amplication-data-service-generator/package-lock.json
- packages/amplication-data-service-generator/package.json
- packages/amplication-data-service-generator/src/admin/static/package-lock.json
- packages/amplication-data-service-generator/src/admin/static/package.json
- packages/amplication-server/src/util/jsonHelper.ts
- packages/amplication-server/src/util/sendServerLoadEvent.ts
fix: https://github.com/amplication/ra-data-graphql-amplication/issues/12
now when creating updating nested entities it gets updated (as before), but when it is an array of primitives like user roles (which is also not a relation nested input) - it is filtered out.
order and its products
user with his orders and roles
> deps(dsg): update ra

- packages/amplication-data-service-generator/src/server/resource/controller/controller.base.template.ts
- packages/amplication-data-service-generator/src/server/resource/controller/to-many.template.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Issue Number: #2654 
moved useGuards to the top of the controller instead of every route handler (like it is on our resolvers)
> feat(dsg) move use guards to the top of the controller

- packages/amplication-client/src/index.scss
Issue Number: [#2650](https://github.com/amplication/amplication/issues/2650)
Adds a CSS rule to the body element of the Amplication client to improve the readability of the text.
- [-] Tests for the changes have been added
> Add font smoothing to improve readability

- .gitignore
fix #2672 
This pr add the .server-id to gitognore
> fix(main): add .server-id to gitignore

- packages/amplication-prisma-db/prisma/migrations/20220509210537_public_routes_for_version_13/migration.sql
- packages/amplication-prisma-db/prisma/schema.prisma
Issue Number: #2708 
add public to EnumEntityPermissionType on the schema and run migration
> add public to EnumEntityPermissionType on the schema and run migration

- packages/amplication-data-service-generator/package.json
Issue Number: #2294 
Rolled back get-port version to 5.1.1 because 6.0.0 is pure ESM and not compatible with amplication
> fix(dsg): rollback get-port version to 5.1.1

- .dockerignore
- packages/amplication-server/Dockerfile
closes: #3023 
The dockerignore file includes *.md files and we added the static folder as a must include 
> Fix a bug where generated markdown files were ignored

- packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.spec.ts
- packages/amplication-data-service-generator/src/server/prisma/create-prisma-schema.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/entities.ts
- packages/amplication-data-service-generator/src/version.ts
Issue Number: #2578 
When setting 1:1 relation and running the generated app, prisma schema was generated in a wrong way.
According to Prisma: _"In a one-to-one relation, the side of the relation without a relation scalar (the field representing the foreign key in the database) must be optional"_
The code was generated without the "?" meaning: required.
Another issue: the side of the relation **with** the foreign key must be `@unique`
The profile relation field of the User model references the id field of the Profile model.  In this case, you need to mark the field with the @unique attribute, to guarantee that there is only a single Profile connected to each User.
> Fix Prisma one to one relation

- packages/amplication-data-service-generator/src/version.ts
- packages/amplication-git-pull-request-service/src/core/pull-request/dto/GitCommit.ts
- packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.service.ts
- packages/amplication-git-service/src/services/git.service.ts
- packages/amplication-server/src/core/build/build.service.ts
- packages/amplication-server/src/core/build/dto/GitCommit.ts
closes: #3192 
Currently, we have an issue where the base branch is statically defined as `main`. This does not work for many users who choose to use different names, such as `master`.
This PR makes it so we use the target GitHub repo's base branch instead.
> Use repo's default base branch for Amplication PRs

- packages/amplication-data-service-generator/src/server/static/package-lock.json
- packages/amplication-data-service-generator/src/server/static/package.json
close: #3195 
This pr updates the @nestjs/passport package to 8.2.2 that supports the passport@6.0.0
The nestjs documents: https://github.com/nestjs/passport/releases/tag/8.2.2
> fix(dsg): update lock and @nestjs/passport

- packages/amplication-cli/src/properties.ts
fixed issue: #2865 
[CLI docs](https://docs.amplication.com/docs/cli/) says that the server URL's default should be server.amplication.com, but it's still app.amplication.com.
> CLI - fix `AMP_SERVER_URL` value

- packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx
- packages/amplication-client/src/User/Signup.tsx
- packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
- packages/amplication-client/src/Workspaces/hooks/useCurrentWorkspace.ts
- packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts
- packages/amplication-client/src/Workspaces/hooks/useWorkspaceSelector.ts
- packages/amplication-client/src/routes/appRoutes.tsx
- packages/amplication-server/src/core/auth/auth.service.spec.ts
- packages/amplication-server/src/core/auth/auth.service.ts
Issue Number: #3215
After the change in the app routing and build new service wizard, we needed to update the route path, so it will get to the new create service wizard page with the rights values (workspace and project ids).
> update route sign-up path to go to service wizard

- packages/amplication-client/src/Workspaces/hooks/useCurrentWorkspace.ts
Issue Number: #3255 
Fix singin route - when the user is authenticated and tries to navigate through the URL to `/login`, he/she will be redirected to `currentWorkspace/currentProject`
> Fix signin route

- packages/amplication-server/src/core/project/project.resolver.ts
- packages/amplication-server/src/core/project/project.service.ts
Issue Number: #3288
When querying a project/projects, the resources field returned as null, I added the project resolver, removed the field to resources
> Added project resolve field to a resource

- packages/amplication-prisma-db/prisma/migrations/20220802100436_create_project_commit_releation_and_move_commit_data_from_resource_to_project/migration.sql
- packages/amplication-prisma-db/prisma/migrations/20220802102413_remove_resource_commit_releation/migration.sql
- packages/amplication-prisma-db/prisma/schema.prisma
Issue Number: #3283 
create 2 migrations:
1. add `project` as a foreign key to Commit and update the commits data on Project from Resource
2. remove the relation between Resource and Commit + set `projectId` to not null on Commit
> Create new relation Project-Commit and remove the relation Resource-Commit

- packages/amplication-client/src/Resource/git/AppGitStatusPanel.scss
- packages/amplication-client/src/Resource/git/AppGitStatusPanel.tsx
closes #3066 
Setting the width property of the button to 100%
> Set the connect to GitHub button to full width

- packages/amplication-client/src/Workspaces/NewWorkspace.tsx
Issue Number: #1868
**Required Info.**
- For creating the new workspace, Formik library is used.
- And, a prop validateOnMount was used in order to validate the text input to disable the Create Workspace button.
**What is causing Issue**
- As mentioned in issue, when user click the cross button to close the Dialog, user see the error message, which is not a good UX.
- Its happening because when text field gets blurred, it validates the value, which is wrong in case of empty.
- And, validateOnMount also forcefully cause validation on blur along with its validation on mount.
**Solution**
- Since, after removing the validation on Blur doesn't affect the UX, so in this PR:
1. added validationOnBlur=false
2. removed the validationOnMount
3. And, added a condition to check length of values in …
> fix: error on closing the new workspace Dialog without any name

- packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts
Issue Number: #3552
when switching to settings or members  routes under workspace. if you refresh you get undefined as workspace on url
> fix bug of redirect

- packages/amplication-git-service/src/services/git.service.ts
- packages/amplication-server/src/core/git/git.provider.service.ts
Issue Number: #3566 
trim repo name and replace spaces with "-" so the name will be equal to Github repo name
> fix repoName spaces and under-score

- packages/amplication-client/src/Components/CommitSelector.scss
- packages/amplication-client/src/Components/CommitSelector.tsx
- packages/amplication-client/src/Components/CommitSelectorItem.scss
- packages/amplication-client/src/Components/CommitSelectorItem.tsx
- packages/amplication-client/src/Components/ResourceSelectorItem.tsx
- packages/amplication-client/src/VersionControl/CommitData.scss
- packages/amplication-client/src/VersionControl/CommitData.tsx
- packages/amplication-client/src/VersionControl/CommitListItem.scss
- packages/amplication-client/src/VersionControl/CommitListItem.tsx
- packages/amplication-client/src/VersionControl/CommitResourceListItem.tsx
- packages/amplication-client/src/VersionControl/hooks/commitQueries.ts
- packages/amplication-client/src/style/mixin.scss
- packages/amplication-client/src/util/truncatedWithEllipsis.ts
- packages/amplication-design-system/src/components/UserAvatar/UserAvatar.scss
Issue Number: #3586 
Fix UI issues on code view selectors:
- create a new component, `CommitData`, consisting of the user badge, commit message and commit timestamp. This component is also used on the commits page.
- Truncate String with Ellipsis with css
> Fix UI issues on code view selectors

- packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.scss
- packages/amplication-client/src/routes/appRoutes.tsx
- packages/amplication-client/src/routes/resourceEntitiesRoutes.tsx
- packages/amplication-client/src/routes/resourceRoutes.tsx
- packages/amplication-client/src/routes/resourceSettingsRoutes.tsx
- packages/amplication-client/src/routes/routesUtil.tsx
Issue Number:  #3619 
Fix the new routes, so the relevant  paths will have analytics
> Analytics stop work after routes refactor in most of the pages 

- packages/amplication-git-pull-request-service/src/core/pull-request/pull-request.service.ts
- packages/amplication-git-service/src/__tests__/services/git.service.spec.ts
- packages/amplication-git-service/src/contracts/IGitClient.ts
- packages/amplication-git-service/src/providers/github.service.ts
- packages/amplication-git-service/src/services/git.service.ts
closes: #3640 
This PR removes the build id directory from the amplication ignore logic
> Remove build id from path

- packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx
Refactor the condition on the SyncWithGitHubPage to use the ProjectConfiguration as the test case, so all other future resource types will work properly 
> Refactor `SyncWithGithubPage`

- packages/amplication-server/src/app.module.ts
Added return `void` type for the function `onApplicationShutdown` inside `packages/amplication-server/src/app.module.ts`.
> fix(amplication-server): added return type for function onApplicationShutdown

- packages/amplication-client/src/VersionControl/PendingChange.tsx
- packages/amplication-client/src/VersionControl/PendingChanges.tsx
Issue Number: #3704 
Remove resourceId param from PendingChange component, since it is already included in the `change` object
> Remove resourceId param from PendingChange component 

- helm/charts/services/amplication-client/values.yaml
- helm/charts/services/amplication-git-pull-request-service/values.yaml
- helm/charts/services/amplication-git-pull-service/values.yaml
- helm/charts/services/amplication-git-push-webhook-service/values.yaml
- helm/charts/services/amplication-server/values.yaml
- helm/charts/services/amplication-storage-gateway/values.yaml
Currently our resource usage is set at `2.0Gi` for memory and `1` for CPU.
In fact, the `t3.medium` EC2 instances we are running on, while they have 4GB and 2CPU on paper, have some reserved amounts. The actual allocatable resources are  and `3.6Gi` memory and `1.9` CPU.
This essentially means that each Node can only run one instance, and that each Node runs at around 45% redundancy.
This PR adjusts the values to be half the allocatable values, which should reduce our cloud resource consumption by (hopefully) dramatically.
> Adjust Kubernetes resource usage

- packages/amplication-data-service-generator/src/version.ts
- packages/amplication-design-system/src/components/MultiStateToggle/MultiStateToggle.scss
- packages/amplication-design-system/src/style/css-variables.scss
Closes #2733 
This is the new page screenshot:
Not sure if I had to add radius to all sides of the button, let me know if there is any issue with this PR.
> fix #2733: No border radius on the buttons in the permission tab

- packages/amplication-client/src/VersionControl/PendingChangeWithCompare.tsx
- packages/amplication-client/src/VersionControl/hooks/commitQueries.ts
- packages/amplication-client/src/VersionControl/hooks/useCommits.ts
Issue Number: #3773 
Align the GET_COMMITS query to get the resource object from the change, and not from the origin type. 
(like in query: GET_PENDING_CHANGES_STATUS).
> (client): fix commits broken URL

- packages/amplication-data-service-generator/src/server/create-dotenv.ts
- packages/amplication-data-service-generator/src/server/create-server.ts
Part of issue: #3768 
In this PR I added another parameter to `createDotEnvModule` function. 
This function is responsible for creating the `.env` file of the generated server folder.
Now, when we call this function with an empty array, we will get the same `.env` file, but if we call it with:
```
[
{KAFKA_BROKERS: "["localhost:9092"]"},
{KAFKA_CLIENT_ID: "client-queue"},
{KAFKA_GROUP_ID: "server-group"},
]
```
The following env variables will be appended to the `.env` file
```
KAFKA_BROKERS="["localhost:9092"]"
KAFKA_CLIENT_ID='client-queue'
KAFKA_GROUP_ID='"server-group'
```
@morhag90 I need `createDotenvModule` event
> refactor(dsg) added addtionalVariables param to create dotenv module

- packages/amplication-data-service-generator/src/server/create-dotenv.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Added the missing return that caused an empty line in the generated `.env` file
> Fix the first empty line in the generated `.env` file

- packages/amplication-server/src/decorators/authorizeContext.decorator.ts
- packages/amplication-server/src/decorators/injectContextValue.decorator.ts
- packages/amplication-server/src/decorators/roles.decorator.ts
Added missing return type `CustomDecorator<string>` for the functions in the decorators folder in amplication-server. 
> fix: added missing return type for the functions in decorators folder

- packages/amplication-client/src/Project/AddNewProject.tsx
- packages/amplication-client/src/Project/ProjectList.scss
- packages/amplication-client/src/Project/ProjectList.tsx
- packages/amplication-client/src/Project/ProjectSideBar.scss
- packages/amplication-client/src/Project/ProjectSideBar.tsx
- packages/amplication-client/src/Workspaces/WorkspaceSelector.scss
Issue Number: #3831 
The issue was that styles which were intended for add new project button was applied to create new workspace button due to poor style specification and wrong add new project button placement in DOM.
The solution is to place add new button correctly, apply styles to the button specifically.
There is also icon alignment fix in workspace selector as a part of proper boycotting.  
> 3831 bug report text is not centered on create workspace button

- packages/amplication-client/src/Workspaces/WorkspaceFooter.tsx
Issue Number: #3811 
- when the user is in the context of a service (resource), the open with GitHub button opens the last pull request (last build)
- in a context of  project, the open with GitHub button opens the repository URL that is connected to the **project**.
> Fix open pull request on GitHub button

- packages/amplication-client/src/ServiceConnections/ServiceConnectionsPage.tsx
- packages/amplication-client/src/routes/resourceRoutes.tsx
Issue Number: #3893
When the service broker page loads, the first service broker from the list will be selected.
> Message Broker page - the first topic is not selected

- packages/amplication-data-service-generator/src/server/auth/token/basicToken.service.spec.template.ts
- packages/amplication-data-service-generator/src/server/auth/token/basicToken.service.template.ts
- packages/amplication-data-service-generator/src/server/auth/token/jwtToken.service.spec.template.ts
- packages/amplication-data-service-generator/src/server/auth/token/jwtToken.service.template.ts
- packages/amplication-data-service-generator/src/server/static/src/auth/jwt/base/jwt.strategy.base.ts
- packages/amplication-data-service-generator/src/server/static/src/auth/jwt/jwt.strategy.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
This PR removes the `@ts-ignore` and comment from the auth files to prevent line dropping
> Remove the `@ts-ignore` from the auth strategy

- packages/amplication-server/src/core/queue/queue.service.ts
Issue Number: Resolves #4010 
When generating a new app with an empty git repository (no README.md), the build fails with a Git Repository is empty message. These changes are to improve this error message by appending: ```To fix this, commit a README.md file and re-build.```
> Add more information to PR error message to make it actionable 

- packages/amplication-design-system/src/components/Panel/Panel.scss
Fixes border and horizontal rule disappearing when the user hovers over a ResourceListItem.
Closes: #3935
> fix: #3935 ResourceListItem Wrong Hover Effect

- package-lock.json
There were 8 vulnerabilities (4 moderate, 4 high)
I am surprised any body has not taken care of it 
I did npm audit 
fix the package-lock.json
Things taken care of in these changes are
ansi-regex  3.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw fix available via `npm audit fix`
node_modules/log-update/node_modules/ansi-regex
cross-fetch  <=2.2.3 || 2.2.5 || 3.0.0 - 3.1.4 || >=3.2.0-alpha.0 Severity: high
Incorrect Authorization in cross-fetch - https://github.com/advisories/GHSA-7gc6-qh9x-w6h8 Depends on vulnerable versions of node-fetch
fix available via `npm audit fix`
node_modules/cross-fetch
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an …
> Corrected package-lock.json

- packages/amplication-code-gen-types/src/plugin-events-params.ts
- packages/amplication-data-service-generator/src/server/resource/controller/create-controller.ts
- packages/amplication-data-service-generator/src/util/ast.ts
Issue Number: #4156 
rename and change the type of the event params:
`CreateEntityControllerParams ` and `CreateEntityControllerBaseParams `:
`templatePath` (type `string`) => `template` (type `namedTypes.File`)
> fix create controller and create controller base event params

- packages/amplication-code-gen-types/src/plugins-types.ts
Issue Number: #4147 
fix `CreateAuthModules` and `CreateAdminModules` event name to start with a capital letter
> Fix inconsistent event name capital letter

- packages/amplication-data-service-generator/scripts/copy-files.ts
fix generated app failure by adding `json` to the admin UI global directory
> Fix copy admin UI template package json to `dist`

- packages/amplication-client/src/VersionControl/Commit.scss
- packages/amplication-client/src/VersionControl/PendingChanges.scss
Fixes #4042 
Fixed the styling issue where the last commit details were getting partially hidden
> style: Fixed last commit details getting partially hidden

- .github/workflows/ci-nx.yml
- packages/amplication-data-service-generator/src/version.ts
- script/setup.ts
This PR changes the default behavior of the `setup:dev` script to not clean by default. This behavior suggested by @yuval-hazaz to shorten the setup time.
To use the clean option just run `npm run setup:dev -- --clean`
> `setup:dev` script not longer clean by default

- packages/amplication-client/src/Resource/OverviewTile/OverviewTile.tsx
Close #4231 
Overview/Reason:
Amplication no longer want to support the ability to download the code directly from the Amplication platform. So to improve onboarding it was needed to update the instruction text and remove mentioning "download the code".
Old text:"Your Amplication-generated resource is ready. We created it using the
amazing open-source technologies. Push the auto-generated code to
GitHub or download the source-code and take it to the moon with your
coding skills."
New text :"Your Amplication-generated resource is ready. 
We created it using amazing open-source technologies.
Push the auto-generated code to GitHub and take it to the moon with your coding skills."
Content Reference: @GreenMachine01 
IMPORTANT: Please review the …
> Updated instruction text on the Service Dashboard.

- ee/packages/amplication-git-pull-service/Dockerfile
- ee/packages/amplication-git-pull-service/webpack.config.js
This PR is fixing the use of `npm ci` in the docker file instead of `npm I` because we don't use the ci any more; we don't need the package-lock also
> Update Dockerfile for git-pull-service in Nx

- packages/amplication-data-service-generator/src/server/static/Dockerfile
Add slash in Docker file
Close #4188
Using Cloud build the Docker build process fails with the following error:
Step 17/19 : COPY --from=base /app/tsconfig* .
When using COPY with more than one source file, the destination must be a directory and end with a /
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
This issue is related to https://github.com/amplication/amplication/issues/3914
I could find the solution explained [in this Stackoverflow thread](https://stackoverflow.com/questions/53650492/when-using-copy-with-more-than-one-source-file-the-destination-must-be-a-direct)
Adding a slash in the end worked for me to not fail the build.
So the proposed solution is to generate a Dockerfile with
COPY --from=base /app/tsconfig* ./
instead …
> fix(data-service-gen): add slash in dockerfile

- packages/amplication-client/src/Resource/git/AppGitStatusPanel.tsx
Fixes #3585 
Fixed the last sync date showing up incorrect value.
This was especially in the case when syncing was never done in the first place.
> fix: updated incorrect last sync date

- packages/amplication-prisma-db/.gitignore
- packages/amplication-prisma-db/prisma/schema.prisma
- packages/amplication-prisma-db/project.json
- packages/amplication-prisma-db/src/index.ts
- packages/amplication-prisma-db/src/prisma.service.ts
This PR is a sub-fix to the running of the server on the new nx tool set.
We change the generation location to let the webpack build process bundle the Prisma SDK into the package code.
> Updating the client generation target

- docker-compose.dev.yml
Add health check on kafka container to avoid issues where `kafka-init-topics` fails to run when the `kafka` containers takes more then 30s to start.
> refactor: add health check on kafka container

- packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts
Fixes #4043 
The issue has been fixed where pending changes of older project were retained in a newly started project with no pending changes.
The issues seemed to be the check being done in the `usePendingChanges` hook.
Currently the changes were not updated if the changes length was zero. This was causing the issue.
> fix: Update pending changes not refreshing on new project

- nx.json
This PR adds the `postbuild` script to the NX `cacheableOperations` list, this PR will fix https://github.com/amplication/amplication/actions/runs/3558419819/jobs/5977089186
The solution has provided by @arielweinberger
> Add `postbuild` script to NX cache list

- packages/amplication-code-gen-types/src/plugin-events-params.ts
- packages/amplication-data-service-generator/src/admin/create-admin.ts
- packages/amplication-data-service-generator/src/admin/package-json/create-package-json.ts
- packages/amplication-data-service-generator/src/server/create-server.ts
- packages/amplication-data-service-generator/src/server/package-json/create-package-json.ts
Close #4447
update create package json event with a new parameter: `fileContent` in order to have the ability to read the file content while developing a plugin
> update create package json event

- ee/packages/amplication-git-pull-service/project.json
- ee/packages/amplication-git-push-webhook-service/project.json
- nx.json
- packages/amplication-build-manager/project.json
- packages/amplication-client/project.json
- packages/amplication-data-service-generator/project.json
- packages/amplication-git-pull-request-service/project.json
- packages/amplication-server/project.json
- packages/amplication-storage-gateway/project.json
Close: #4344 
Manually telling Nx about the dependencies between your projects is helpful, but as your repo grows it becomes difficult for a person to keep track of all the dependencies that are introduced. If you miss a dependency, the guarantees of the affected command are voided. 
This PR leverage nx plugins capabilities to automatically detect project dependencies without us manually implicitly defining them.
As a result of this change, we can clearly see that we manually added a dependency that did not really exist.
Use `npx nx graph` to visualize the current graph and `npx nx affected:graph --base=next` for visualizing the affected projects.
IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed …
> chore(nx): add support for auto detected dependencies in nx workspace

- packages/amplication-client/src/ServiceConnections/topics/TopicsList.tsx
Close #4283 
added refetch to fetch only the topics of the message broker after creation
> added refetch to fetch only the topics of the message broker after creation

- packages/amplication-data-service-generator/src/server/package-json/package.template.json
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- packages/amplication-data-service-generator/src/version.ts
Close: #4531
Update NestJS packages in the `package.json` of the generated server, to the latest 8 versions (`8.4.7`) in order to fix the vulnerabilities.
> Fix server vulnerabilities

- .github/workflows/ci-nx.yml
Close: #4429 
Update ci affected workflow to only be triggered on actions against a pull request. 
This will fix the scenario where CI workflow triggered by push on `next` branch will end not running any build due to Nx not detecting any changes that will affect projects due to the comparison of the HEAD of the `next` branch against itself.
> chore: fix ci affected to work on next to master PR

- .github/workflows/ci-nx.yml
Close: https://github.com/amplication/amplication/issues/4340
PR Details
Fix deploy step by passing the secrets to the reusable `Deploy` workflow 
[
To see the change in action, a modified version of the workflow is running here as pull_request triggered https://github.com/overbit/amplication/actions/runs/3647785805
and here manually
https://github.com/overbit/amplication/actions/runs/3647787738](https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow) 
> chore(ci): fix ci deploy trigger secrets

- packages/amplication-data-service-generator/src/server/resource/service/to-many.template.ts
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/amplication-data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #4582
In the new version of Prisma, the return type in  one-to-many relation has changed to 
`PrismaPromise<Array<OrderGetPayload<T>>| Null>`
In our API, when there are no results, we return an empty array and not null.
We reached out to Prisma on Slack, and they gave us the two options:
- use `findUniqueOrThrow` instead of `findUnique`
- add a `!` before  `.orders()`  => ` await findUnique(...)!.orders(...)`
We decided to go with the first solution.
> Fix Prisma one-to-many relation compilation errors

- docker-compose.dev.yml
Close: #4673 
fix docker-compose-dev env variable
> fix docker-compose-dev env variable

- packages/amplication-data-service-generator/src/prepare-context.ts
Close: #4679
serverDirectories.authDirectory field in the context has the wrong path
> fix authDirectory path

- helm/charts/dsg-runner-infra/templates/sensor.yaml
- libs/data-service-generator/package.json
- libs/data-service-generator/project.json
- libs/data-service-generator/src/util/read-static-modules.ts
- libs/data-service-generator/src/version.ts
Close: #4733 
This PR remove the node_modules ignore path from the static files reader
> Remove node modules from static reader

- helm/charts/dsg-runner-infra/templates/sensor.yaml
- libs/data-service-generator/package-lock.json
- libs/data-service-generator/package.json
- libs/data-service-generator/src/version.ts
Close: #4750 
This PR updates the version 
The error #4750  happened because that in the publishing of the DSG we ran `build` instead of `postbuild` that include the `files copy` we need to automated that #4730 
> Update DSG version

- helm/charts/amplication/values-next.yaml
- helm/charts/amplication/values-staging.yaml
Close: #4535 
Added variables for the `next` and `staging` environment to be able to send emails via sendgrid on those environments aswell. The API key is currently specified via the AWS Secrets Manager.
> Add configmap variables for sendgrid to next and staging

- packages/amplication-git-utils/src/git/github.service.ts
Close: #4860 
This PR returns the .amplicationignore from the default branch if not have base
> fix(pr): amplication ignore

- .github/workflows/ci-nx.yml
Close #4880 
Currently, nx-set-shas actions is configured from `github.base_ref` but unfortunately this variable is not defined for `push` events. This PR default the value of main-branch-name to `github.event.repository.default_branch` to avoid any errors due to undefined variables.
> Chore: fix ci affected workflow on push to master 

- packages/amplication-server/src/core/queue/queue.service.ts
Close: #4947 
The current Nestjs implementation seems to have a bug that will prevent the first event emitted to be successfully send.
Bug: https://github.com/nestjs/nest/issues/10449 
> fix(server): issue where first kafka event emitted fails silently

- .github/workflows/release.yml
Related: #4974
Fix the docker tagging logic to not add the default branch name as a tag on `workflow_run` event.
New issue has been added to the docker-metadata repo: https://github.com/docker/metadata-action/issues/259 
> chore(ci): fix docker master tag issue

- libs/data-service-generator/package-lock.json
- libs/data-service-generator/package.json
- libs/data-service-generator/src/version.ts
- packages/amplication-code-gen-types/package.json
part of #4992 - a quick fix, but not a solution 
- Update code-gen-types dependency: `prisma-schema-dsl-type`
- `Update data-service-generator` dependency - lock the Postgres version to `1.1.7`, which is before the change of using webpack.
> chore(dsg): update dependencies

- .github/workflows/ci.yml
Reverts amplication/amplication#4986 since it prevents pull_request events for all branches
> Revert "chore(ci): fix duplicated execution of ci workflow on next"

- packages/amplication-server/.env
part of https://github.com/amplication/amplication/issues/4564
align the value of DSG_LOG_TOPIC with the value we use in the build manager in order to see the build logs when we run the local DSG runner
> refactor(server) align the value of DSG_LOG_TOPIC with the value we use in the build manager

- libs/data-service-generator/package-lock.json
- libs/data-service-generator/package.json
- libs/data-service-generator/src/prepare-context.ts
- libs/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- libs/data-service-generator/src/version.ts
- packages/amplication-data-service-generator-runner/src/main.ts
- packages/amplication-data-service-generator-runner/src/utils/Tarball.ts
- packages/amplication-data-service-generator-runner/src/utils/defaultPlugins.ts
Close: #5003 
- return the dynamic installation back => related PR: https://github.com/amplication/amplication/pull/5010/files
- install the requested version instead of the latest
- check if a version was provided and if not, install the latest - this check should be removed when we implement the plugin setting that uses the plugin API to select a version.
- moved the default plugins logic from the DSG lib to the DSG runner
- publish new DSG version
> Fix(dsg-runner): dynamic installation install the provided version

- package-lock.json
- package.json
- packages/amplication-client/src/Permissions/EntityPermissionAction.tsx
- packages/amplication-client/src/Permissions/EntityPermissionField.tsx
- packages/amplication-server/src/core/entity/entity.service.ts
Related to : [#4943](https://github.com/amplication/amplication/issues/4943)
Replace the external dependency that contains an invalid index.d.ts ([line 9](https://www.npmjs.com/package/@extra-set/difference?activeTab=explore)) with the magic of ts! 
> refactor: client and server to not use @extra-set/difference dependency

- packages/amplication-client/src/Components/CreateResourceButtonItem.tsx
This error `validateDOMNesting(...): cannot appear as a descendant of...` no longer shows up in the browser console.
Fixes https://github.com/amplication/amplication/issues/5032
>  🐛 Bug Report: fix React error on client

- libs/util/code-gen-utils/package-lock.json
- libs/util/code-gen-utils/package.json
- libs/util/code-gen-utils/src/lib/imports/appendImports.spec.ts
- libs/util/code-gen-utils/src/lib/imports/appendImports.ts
- libs/util/code-gen-utils/src/lib/imports/index.ts
- libs/util/code-gen-utils/src/lib/index.ts
This pull request add new function that append the imports to the end of the imports section
> feat(code-utils): add append imports function

- packages/local-dsg-runner/.env
- packages/local-dsg-runner/README.md
- packages/local-dsg-runner/src/code-gen/code-gen.controller.ts
Close: #5084
Add a new env variable to allow auto removal of exited DSG containers locally.
> feat(local-dsg): add option to auto remove exited local dsg containers

- nx.json
Close: #4984 
Add a new Read-Only access token to NxCloud to allow consuming the shared distributed nx cache. On the other pipelines, Nx will use the R/W access token stored as Action Secret
> chore: enable nx distributed cache

- packages/amplication-server/src/core/entity/constants.ts
part of: #4431 
related comment: https://github.com/amplication/amplication/issues/4431#issuecomment-1423991692
the first issue that was raised there:
Remove password fields from the user entity
> fix(server): remove password fields from user entity

- packages/data-service-generator/src/utils/dynamic-installation/Tarball.ts
Close: #5163 
Adding warnings in the build log for application generated with deprecated plugins
> feat(dsg): add warning for DSG builds that are using deprecated plugins

- packages/amplication-client/src/Purchase/PurchasePage.tsx
Close: #4892 
The issue pertained to the page title not changing when the user clicked purchase and displayed the purchase modal. I used the PageContent existing layout to change the title when the modal was displayed. An alternative solution was to call the Helmet component directly but I thought this way is cleaner.
- No tests needed for the change.
- No errors from existing tests.
> Fix 4892 - Change Page Title when showing Purchase Modal

- packages/amplication-plugin-api/src/pluginVersion/npm-plugin-version.service.ts
Close: #5163 
Fix the issue where when npm doesn't return deprecated for a package, the undefined string was stored in db. 
> fix(plugin-api): deprecated wrongly stored in db

- codegen.yml
- package.json
- packages/amplication-cli/src/models.ts
- packages/amplication-client/src/models.ts
- packages/amplication-code-gen-types/src/models.ts
- packages/amplication-git-pull-request-service/src/models.ts
- packages/amplication-server/project.json
- packages/data-service-generator/src/models.ts
Close: #5230 
Changes to the server were not resulting in models being updated. This PR updates the server build flow to generate the models.ts for the needed services and remove the typeName generated properties from the models.
From now on, running `npx nx build amplication-server` graphql schema generation and models generation will be triggered as shown in the task dependency graph
> chore(server): fix codegen configuration

- .github/workflows/nx.template.yml
Close: #5243 
Skipping the nx sha step when we force nx to ignore it to calculate the affected projects. 
> fix(ci): fix prod deployment step to compare with master

- packages/amplication-client/src/authentication/authentication.ts
- packages/amplication-client/src/util/cookie.ts
Close: #5274
Update the auth logic that was preventing the user to switch between workspaces. The initial issue was due to the client being unable to clear the jwt cookie since it was set for the top domain.
> fix(client): issue preventing workspace switch

- packages/amplication-git-pull-request-service/src/pull-request/pull-request.service.ts
- packages/amplication-git-utils/src/git/git-factory.ts
- packages/amplication-git-utils/src/git/git.service.ts
- packages/amplication-git-utils/src/git/github.service.ts
- packages/amplication-server/src/core/git/git.provider.service.ts
Close: #5308 
This pull request switches the git utils to use the amplication logger instead of the console.log
> refactor(git-utils): switch to amplication logger

- packages/amplication-git-utils/src/git-provider.interface.ts.ts
- packages/amplication-git-utils/src/git/git.service.ts
- packages/amplication-git-utils/src/git/github.service.ts
- packages/amplication-git-utils/src/types.ts
Close: #5297 
This pull request add the token to the git clone action 
> fix(git-utils): using a generated token for a clone process

- packages/amplication-build-manager/src/build-runner/build-runner.controller.ts
Close: #5031 
In the file `packages/amplication-build-manager/src/build-runner/build-runner.controller.ts`, I replaced the function name from `onCreatePRRequest` to `onCodeGenerationRequest` as the `CODE_GENERATION_REQUEST_TOPIC ` event is triggered on code generation request and not on PR request
> Fix(client): Update code generation request function name in build manager

- package-lock.json
- package.json
- packages/amplication-server/src/core/account/account.resolver.spec.ts
- packages/amplication-server/src/core/auth/auth.resolver.spec.ts
- packages/amplication-server/src/core/build/build.resolver.spec.ts
- packages/amplication-server/src/core/commit/commit.resolver.spec.ts
- packages/amplication-server/src/core/entity/entity.resolver.spec.ts
- packages/amplication-server/src/core/project/project.resolver.spec.ts
- packages/amplication-server/src/core/resource/resource.resolver.spec.ts
- packages/amplication-server/src/core/resourceRole/resourceRole.resolver.spec.ts
- packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts
- packages/amplication-server/src/tests/nestjs-apollo-testing.ts
Close: #5379 
This pull request removes all `apollo-server-testing` from Amplication.
> fix(server): remove `apollo-server-testing`

- docker-compose.dev.yml
Fixes: #5076 
Add the missing docker environment variable 
``` diff
environment:
POSTGRES_USER: ${POSTGRESQL_USER}
POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
+     POSTGRES_DB: ${POSTGRESQL_DB_NAME}
```
update the healthcheck command to use the docker variable instead of the environment variable
```diff
healthcheck:
+      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
```
> fix: Local development environment print errors on startup

- packages/amplication-server/src/core/build/build.resolver.spec.ts
- packages/amplication-server/src/core/build/build.resolver.ts
- packages/amplication-server/src/core/commit/commit.resolver.spec.ts
- packages/amplication-server/src/core/commit/commit.resolver.ts
- packages/amplication-server/src/core/user/user.service.spec.ts
- packages/amplication-server/src/core/user/user.service.ts
Close: #4846
Fix server logic to return user's commits (regardless its deleted status)
> fix(server): commits resolver issue due to deleted users

- packages/amplication-server/migration-scripts/git-organization-provider-properties.ts
Close: #5458
I decided to go with option 2: 
- create a `migration.ts` file => `git-organization-provider-properites.ts`
- run it locally while I had in the database and empty object in the providerProperties column
- run it locally while in the providerProperties column I had `{github: {installationId: <installationId>}}` (this is what we have now in production for new users)
On both cases I got what I expect to: `{installationId: <installationId>}`
> feat(server): create prisma migration script for git provider properties

- packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts
- packages/amplication-server/src/core/git/git.provider.service.ts
Part of: #5261 
fix the refresh token calculation
> Fix(server): bitbucket refresh token calculation

- .github/dependabot.yml
fix: #5384
This pull request update the settings of the dependabot to ignore react
> chore: update dependabot to ignore react

- packages/amplication-server/migration-scripts/git-organization-provider-properties.ts
Close: #5561 
added a filter to the migration script to find and update only git organization that their provider properties field is `{}` , meaning no data
I ran it on my local data base that contains data in this field and it didn't change the data the data (the last row is the most important)
> fix(server): change git organizatin provider properties migration

- package-lock.json
- package.json
- packages/amplication-client/src/Entity/EntityFieldLinkList.tsx
Close: #5512 
This pull request returns the cache logic to the entity field link list.
This is a hotfix to the problem that has been happened by the pr #5400 issue #5512 that affects the UI.
> hotfix(client): update cache of entity field list

- .github/workflows/e2e.yml
- .github/workflows/nx.template.yml
- .github/workflows/release.template.yml
Close: #5568 
Fix the issue reported, due to CI cache being generated without including cypress dependencies.
The solution is to fix the cypress bin into the cached node_modules folder https://docs.cypress.io/guides/references/advanced-installation#Binary-cache
> chore(e2e): fix issue due to cypress missing in CI cache

- packages/amplication-code-gen-types/package.json
- packages/amplication-code-gen-types/src/plugins-types.ts
Relates: #5499 
Migrate `code-gen-types` library to use amplication logger interface
> chore(code-gen-types): update DSG context to use ILogger interface instead of winston logger

- packages/amplication-code-gen-types/package.json
- packages/amplication-code-gen-types/src/plugins-types.ts
Close: #5560 
In order to simplify the logging experience of plugins and include more details to the DSG build log, the PR improve the logger type exposed in the context and its documentation.
> feat(code-gen-types): improve dsg context logger type

- packages/amplication-code-gen-types/package.json
- packages/amplication-code-gen-types/src/dsg-resource-data.ts
- packages/amplication-server/src/core/build/build.service.ts
- packages/data-service-generator/src/create-data-service.ts
- packages/data-service-generator/src/dsg-context.ts
- packages/data-service-generator/src/generate-code.ts
- packages/data-service-generator/src/tests/create-data-service-custom-path.spec.ts
- packages/data-service-generator/src/tests/create-data-service-numeric-user-id.spec.ts
- packages/data-service-generator/src/tests/create-data-service-with-kafka.spec.ts
- packages/data-service-generator/src/tests/create-data-service-without-graphql.spec.ts
- packages/data-service-generator/src/tests/create-data-service-without-restApi.spec.ts
- packages/data-service-generator/src/tests/create-data-service.spec.ts
- packages/data-service-generator/tests/e2e/postgres-basicAuth/data-service-generator.e2e.spec.ts
Close: #5625 
Add log information in the entry of the DSG run. 
Test case:
Run local amplication=>  run the following services: server/client/build-manager/local-data-service-generator-controller. 
generate and build an app => 
look at the console log and see the new parameters added: resourceId and buildId:
> feat(server/dsg): add log informarion to DSG run

- .vscode/extensions.json
This pull request adds the `grammarly` extension and the `material-icon-theme` extension
> feat: add recommended extensions

- packages/amplication-client/src/Resource/git/ServiceWizardConfigurationGitSettings.tsx
Close: #5692
Init GitHub settings when clock on override option
> fix(client): init repo values when override project settings

- packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx
- packages/amplication-client/src/Resource/create-resource/ServiceWizard.tsx
- packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx
Close: #5670
Remove the close button in the onboarding process.
Test case:
Assign with a new user => Make sure the close button doesn't appear in the onboarding process.
> fix(client): remove close button in onboarding process

- packages/amplication-git-utils/src/providers/git.service.ts
- packages/amplication-git-utils/src/providers/github/github.service.ts
- packages/amplication-git-utils/src/types.ts
Partial: [#5648](https://github.com/amplication/amplication/issues/5648)
Fix the logic that chech for the commits from the old amplication github app by updating the email pattern.
> fix(git-utils): git log pattern for amplication app bot 

- libs/schema-registry/src/lib/code-generation-failure/value.ts
- packages/amplication-build-manager/src/build-logger/build-logger.controller.ts
- packages/amplication-build-manager/src/build-logger/dto/OnCodeGenerationLogRequest.ts
- packages/amplication-build-manager/src/build-runner/build-runner.controller.ts
- packages/amplication-build-manager/src/build-runner/dto/CodeGenerationFailure.ts
- packages/amplication-build-manager/src/build-runner/dto/CodeGenerationRequest.ts
- packages/amplication-build-manager/src/build-runner/dto/CodeGenerationSuccess.ts
Close: #5694 
Move build manger to kafka producer and schema registry
⚠️  Based on #5696 
> refactor(server): move build manger to kafka producer and schema registry

- libs/schema-registry/src/lib/create-pr-request/value.ts
- packages/amplication-cli/src/models.ts
- packages/amplication-client/src/Resource/git/dialogs/GitRepos/GithubRepos.tsx
- packages/amplication-client/src/models.ts
- packages/amplication-code-gen-types/src/models.ts
- packages/amplication-git-pull-request-service/src/models.ts
- packages/amplication-git-pull-request-service/src/pull-request/pull-request.service.ts
- packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.spec.ts
- packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts
- packages/amplication-git-utils/src/providers/git.service.ts
- packages/amplication-git-utils/src/providers/github/github.service.ts
- packages/amplication-git-utils/src/types.ts
- packages/amplication-git-utils/tests/providers/git.constants.ts
- packages/amplication-prisma-db/prisma/migrations/20230405132558_add_group_name_to_repository/migration.sql
- packages/amplication-prisma-db/prisma/schema.prisma
- packages/amplication-server/src/core/build/build.service.ts
- packages/amplication-server/src/core/git/dto/enums/EnumGitProvider.ts
- packages/amplication-server/src/core/git/dto/inputs/ConnectGitRepositoryInput.ts
- packages/amplication-server/src/core/git/dto/inputs/CreateGitRepositoryBaseInput.ts
- packages/amplication-server/src/core/git/dto/inputs/CreateGitRepositoryInput.ts
- packages/amplication-server/src/core/git/dto/inputs/RemoteGitRepositoriesWhereUniqueInput.ts
- packages/amplication-server/src/core/git/dto/objects/PaginatedGitGroup.ts
- packages/amplication-server/src/core/git/dto/objects/RemoteGitRepository.ts
- packages/amplication-server/src/core/git/git.provider.service.ts
- packages/amplication-server/src/core/resource/resource.service.spec.ts
- packages/amplication-server/src/models/GitOrganization.ts
- packages/amplication-server/src/models/GitRepository.ts
- packages/amplication-server/src/schema.graphql
- packages/data-service-generator/src/models.ts
Close: #5699 
This PR standardise the naming for repository group and add support to persist the group name into the repository record to allow the creation of PRs.
⚠️  Based on #5697. To be merged after that PR
> feat(server):  persist repository group for a repository

- libs/schema-registry/src/lib/create-pr-request/value.ts
- packages/amplication-git-pull-request-service/src/pull-request/pull-request.service.ts
- packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.spec.ts
- packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts
- packages/amplication-git-utils/src/providers/bitbucket/requests.ts
- packages/amplication-git-utils/src/providers/git.service.ts
- packages/amplication-git-utils/src/providers/github/github.service.ts
- packages/amplication-git-utils/src/types.ts
- packages/amplication-server/src/core/build/build.controller.ts
Close: #5440 
- Made groupName and git reference parameters of get file to make easier to understand logic
- default GetFile to collect file from HEAD of default branch if git reference is not passed
> fix(git-utils): getfile logic and parameters 

- packages/amplication-client/src/Resource/git/dialogs/GitRepos/GithubRepos.tsx
- packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts
- packages/amplication-git-utils/src/providers/bitbucket/bitbucket.types.ts
- packages/amplication-git-utils/src/providers/bitbucket/requests.ts
Close: #5701
fix pagination for bitbucket get repositories
https://api.bitbucket.org/2.0/repositories/barletza?page=1&pagelen=1
https://api.bitbucket.org/2.0/repositories/barletza?page=2&pagelen=1
https://user-images.githubusercontent.com/39680385/232045342-a6cd5463-7dd6-4879-a75d-a515836f3cab.mov
> fix(git-utils): get repositories pagination

- packages/amplication-client/src/Resource/git/GitActions/RepositoryActions/GithubSyncDetails.tsx
Close: #5722 
Fix project configuration resource => gitRepository settings. 
Show the project git repository details instead the current resource gitRepository details. 
Test case:
Create a new account and go over the onboarding process (choose an empty repo to get an error in the build process). 
After the build fails => go to resource home and refresh the page.
Goto create a new service. 
In the git Repository selection, you need to see by default the project configuration settings.
> Fix project gitReposiotry settings

- packages/amplication-client/src/Resource/git/ServiceConfigurationGitSettings.tsx
- packages/amplication-client/src/Resource/git/ServiceWizardConfigurationGitSettings.tsx
Close: #5786 
Remove the disabled toggle condition to allow, in any case, the override git settings in the service configuration. 
Test case:
Go to service => git settings => try to override the git settings. (make sure that the toggle is always enabled: with git organization and without one).
> fix(client): Remove disabled toggle condition.

- packages/amplication-client/src/Resource/create-resource/ServiceWizard.tsx
Close: #5735 
The continue button name is always "Continue" and doesn't change according to the current step. 
Test case:
Open the service wizard and create a new service => 
Ensure the continue button name doesn't change to "Create service" in the last step.
> fix(client): fix continue button name in all wizard steps

- packages/amplication-server/src/core/resource/resource.service.ts
Close: #4008 
The fix is so simple, **index** limitation was removed `index < 10` which will allow the user to create unlimited message-brokers.
see the image, showing the message brokers that were created with index greater than **9**
- [yes] Tests for the changes have been added
- [yes] `npm test` doesn't throw any error
> fix(client): remove index limitation

- packages/data-service-generator/src/server/resource/dto/create-field-class-property.ts
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #5437 
Fix id must be an integer number error on rest API. 
Test case: 
Generate a new service with at least one entity with Id of type AUTO_INCREMENT
Follow the readme for starting the server with docker-compose
perform a request to GET the entity by id like http://localhost:3000/api/customers/1
Observe the response
> fix(dsg): fix error: id must be an integer number on API

- packages/amplication-server/src/core/resource/resource.service.ts
Close: #5930 
Fix the error message when trying to create a new service broker. 
Test case:
Create a new service broker.
> fix(server): create service broker fails

- packages/amplication-client/src/Resource/ResourceHome.scss
- packages/amplication-client/src/Resource/ResourceHome.tsx
- packages/amplication-client/src/Resource/ResourceNameField.scss
- packages/amplication-client/src/Resource/ResourceNameField.tsx
Close: #4457 
- Added Edit icon when hovered on the Resource name
- Added a bright overlay on the banner on hover
https://user-images.githubusercontent.com/74011196/227755309-abcbe4e2-bf8b-43fc-9b5e-f1a0d4b2adf2.mov
> feature(client): Add edit icon and bright overlay on the banner

- libs/util/logging/src/lib/cli-format.spec.ts
- libs/util/logging/src/lib/cli-format.ts
- libs/util/logging/src/lib/logging.getFormat.spec.ts
- libs/util/logging/src/lib/logging.spec.ts
- libs/util/logging/src/lib/logging.ts
- libs/util/nestjs/logging/src/logger.service.ts
- packages/amplication-git-pull-request-service/src/app.module.ts
- packages/amplication-git-pull-request-service/src/env.ts
- packages/amplication-git-pull-request-service/src/main.ts
- packages/amplication-git-pull-request-service/src/pull-request/pull-request.controller.ts
- packages/amplication-git-pull-request-service/src/pull-request/pull-request.service.ts
- packages/amplication-server/src/core/build/build.service.ts
Close: #5961
Add additional metadata (`buildId`, `resourceId`, and `userId` where available) to log entries that are related to the code generation process to simplify the log consumption.
This changes will help investigating https://github.com/amplication/amplication/issues/5944  
> fix(logging): issue related to missing metadata in logs and add additional build info to related log entries

- packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts
Close: #5978
fix open with bitbucket broken link
The source of the problem was that we got the organization from a query that didn't return the `useGroupingForRepositories` and that's why we got `${organizationName}/${repositoryName}`
```
const {
name: organizationName,
useGroupingForRepositories,
provider,
} = organization;
// if the provider supports grouping for repositories, we use the group name, but we need to make sure it exists first,
// otherwise we use the organization name
let repositoryFullName = "";
if (useGroupingForRepositories) {
repositoryFullName = groupName ? `${groupName}/${repositoryName}` : null;
} else {
repositoryFullName = `${organizationName}/${repositoryName}`;
}
```
IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/ma …
> fix(client): add missing property to the query

- packages/amplication-plugin-api/prisma/migrations/20230511100847_/migration.sql
- packages/amplication-plugin-api/prisma/schema.prisma
- packages/amplication-plugin-api/src/pluginVersion/base/PluginVersion.ts
- packages/amplication-plugin-api/src/pluginVersion/npm-plugin-version.service.ts
- packages/amplication-plugin-api/src/pluginVersion/pluginVersion.service.ts
Close: #5851
Roll back the new configuration for system settings after deciding to use the same file for those configurations.
> fix(plugin-api): rollback systemSettings

- packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx
Close: #6001 
add optional chaining for `build` as its an optional field
> fix(client): add optional chaining for build

- packages/amplication-client/src/Resource/git/dialogs/GitRepos/GithubRepos.tsx
Close: #6016 
show the  "create repository" button from the select repository modal only if the organization type is Organization and not User
GitHub User
GitHub Organization
> fix(client): show the "create repository" button from the select repository modal only if the organization type is Organization and not User

- libs/ui/design-system/src/lib/components/LimitationNotification/LimitationNotification.scss
- libs/ui/design-system/src/lib/components/LimitationNotification/LimitationNotification.tsx
- libs/ui/design-system/src/lib/index.ts
- packages/amplication-client/src/Resource/git/GitActions/GitProviderConnection.scss
- packages/amplication-client/src/Resource/git/GitActions/GitProviderConnection.tsx
Close: #5995
- design system - add new component to limit notfication to handle contact us for enterprise
- client - use the new component to open the link in a new tab and without concatinate the link to the window location that the use came from (amplication wizard or git sync page)
https://github.com/amplication/amplication/assets/39680385/71715bcb-5980-4457-87f2-dcd3ba29be3e
> Refactor(client): refactor bitbucket lock tooltip text

- packages/amplication-cli/src/models.ts
- packages/amplication-client/src/Resource/git/AuthResourceWithGit.tsx
- packages/amplication-client/src/Resource/git/AuthWithGit.tsx
- packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/CreateGitFormSchema/CreateGitFormSchema.spec.ts
- packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/CreateGitFormSchema/CreateGitFormSchema.ts
- packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.tsx
- packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/WizardGitCreateRepo.tsx
- packages/amplication-client/src/Resource/git/dialogs/GitRepos/GithubRepos.tsx
- packages/amplication-client/src/models.ts
- packages/amplication-code-gen-types/src/models.ts
- packages/amplication-git-pull-request-service/src/models.ts
- packages/amplication-server/src/core/git/dto/inputs/CreateGitRepositoryBaseInput.ts
- packages/amplication-server/src/core/git/git.provider.service.ts
- packages/amplication-server/src/schema.graphql
- packages/data-service-generator/src/models.ts
Close: #5994
- change the property to `isPublic` for the client and set it to `true`, so the toggle will be checked by default
- handle the conversion (negate the value of isPublic) in the server
> Refactor(client): UX of create public-private repo

- packages/amplication-client/src/Entity/EntityField.tsx
- packages/amplication-client/src/Entity/NewEntityField.tsx
- packages/amplication-client/src/util/analytics-events.types.ts
- packages/amplication-server/src/core/entity/entity.service.ts
- packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.service.ts
Close: https://github.com/amplication/private-issues/issues/4
move entity field events from client to server
> feat(server): Move entity field BI events to server

- packages/data-service-generator/tests/e2e/plugins.ts
Related: #5837 
In order to properly run e2e with the breaking changes implemented as part of #5845 we need to temporary configure the e2e to use the `beta` plugins that have been already updated.
> test(dsg): e2e update plugin version config

- packages/amplication-client/src/Layout/WelcomePage.tsx
> #6240 - Changed Second discord link in WelcomePage

- packages/amplication-client/src/Workspaces/WorkspaceForm.tsx
…Workspace'
Close: #6242
The workspace setting page had a typo, `w` in `workspace ID` in small letters.
Now fixed to: **`Workplace ID`**
> fix: enforce naming in the workspace settings

- packages/data-service-generator/src/server/package-json/package.json
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #6121 
This solution represent a temporary solution until we refactor the DSG to understand difference between `imports` and `imports types`. 
Types, i.e. types from `type-fest` like `JsonValue`, should be imported as `import type {} from ""` to avoid needing the dependency at runtime. 
This pr configure `type-fest` as dependency  instead of devDependency to unblock any user that run the service installing only the production dependencies
> fix(dsg): add `type-fest` as dependency 

- package.json
- packages/amplication-cli/src/models.ts
- packages/amplication-client/src/models.ts
- packages/amplication-code-gen-types/src/models.ts
- packages/amplication-git-pull-request-service/src/models.ts
- packages/data-service-generator/src/models.ts
Related #6454 
#6454 updated the `@graphql-codegen/typescript`   module leaving the repository with an out of date set of generated models. This PR align the other codegen dependency and update the models to match the new version.
More details https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1687159967878
> chore(deps-dev): bump @graphql-codegen/cli from 3.0.2 to 4.0.1

- packages/amplication-client/src/Entity/EntityERD/EntitiesERD.tsx
This fixes the issue [#6741 ](https://github.com/amplication/amplication/issues/6741), by forcing apollo to refetch when viewing the ERD again, instead of using cached version.
> fix(client): ERD view is not showing properly the entities after updates #6741

- packages/amplication-client/src/Resource/SyncWithGithubTile.tsx
- packages/amplication-client/src/Resource/git/AppGitStatusPanel.tsx
- packages/amplication-client/src/Resource/resourceMenuUtils.ts
- packages/amplication-client/src/Workspaces/WorkspaceFooter.tsx
Close: #6592
Regarding issue no #6592, I have changed the "git-sync" icon with the "pending_changes" icon as mentioned in the issue.
Please review and suggest changes
> fix(client): updated the generic Git icon

- packages/amplication-server/src/core/entity/entity.service.ts
Close: #7113 
This PR addresses the GitHub issue that allows users to rename the 'User' entity without restrictions while ensuring compatibility with existing authentication mechanisms and integrations. The code changes include modifications to the EntityService class. The following changes were made:
- Removed the code block for preventing to rename the 'User' entity
> feat(server): Allow renaming of 'User' entity

- packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Close: #7222 
Previously tooltip was used which showed the message on hover, currently that has been removed hence fixing the issue.
Screen Recording has been attached for reference.
https://github.com/amplication/amplication/assets/62256588/2bd031eb-79ed-42fe-b840-18b155f9d248
> fix(client): On Hover version number not displayed

- packages/amplication-client/src/Resource/git/GitSyncNotes.tsx
> fix: Removed the "The selected repository must not be empty" notification from the service wizard

- .github/workflows/e2e.yml
- package-lock.json
- package.json
- packages/data-service-generator/package.json
- packages/data-service-generator/src/server/docker-compose/docker-compose.template.yml
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- packages/data-service-generator/tests/e2e/data-service-generator.e2e.spec.ts
Close: #7334
This PR consists of 3 changes:
1. This PR introduce a dynamic wait time before starting e2e tests  based on the actual state of the docker-compose stack instead of a static timeout. 
With this change, the test run time will also be reduce as it won't need to always wait for 30 seconds before running the actual tests. 🚀
2. Update docker-compose to v2
3. ⚠️ During the investigation, I've noticed that another reason for these e2e tests to fail was the following:
In order to fix this, in the most simple way, this PR adds a restart policy to the docker-compose stack `server` service to avoid the situation were server failed to start, due to race condition with the migration service, and stayed dead.
With the new policy, if `server` starts and fails due to migrations not being …
> test(dsg): fix flacky e2e tests

- packages/data-service-generator/scripts/create-input-json.ts
- packages/data-service-generator/src/create-data-service.ts
- packages/data-service-generator/src/dynamic-package-installation.ts
- packages/data-service-generator/src/tests/create-data-service-custom-path.spec.ts
- packages/data-service-generator/src/tests/create-data-service-numeric-user-id.spec.ts
- packages/data-service-generator/src/tests/create-data-service-with-auth-jwt.spec.ts
- packages/data-service-generator/src/tests/create-data-service-with-grpc.spec.ts
- packages/data-service-generator/src/tests/create-data-service-with-kafka.spec.ts
- packages/data-service-generator/src/tests/create-data-service-without-admin-ui.spec.ts
- packages/data-service-generator/src/tests/create-data-service-without-graphql.spec.ts
- packages/data-service-generator/src/tests/create-data-service-without-restApi.spec.ts
- packages/data-service-generator/src/tests/create-data-service-without-server.spec.ts
- packages/data-service-generator/src/tests/create-data-service.spec.ts
- packages/data-service-generator/src/tests/dynamic-plugin-installation-path.ts
- packages/data-service-generator/src/tests/mock-data-plugin-installations.ts
- packages/data-service-generator/src/tests/pluginInstallation.ts
Co-authoring: Mor
Close: #7519
Due snapshot tests running parallel and the fact that dsg is download and extracting the plugins on each run, the flacky issue was due to the collision between one test downloading a plugin that was already in use by another test.
This PR fix the issue introducing dynamic plugin installation path directory per test to avoid collisions.
> test(dsg): refactor snapshot testing mock data for plugin installations

- .github/workflows/release.production.yml
Close: #7552
Exclude `local-data-service-generator-controller` label from production release workflow. This label is for a new feature that allows users to create and run local data services from Amplication, which do not need to be deployed to production.
> ci: fix release notes generator picking dsg changes 

- packages/amplication-build-manager/src/build-job-handler/build-job-handler.module.ts
- packages/amplication-build-manager/src/build-job-handler/build-job-handler.service.spec.ts
- packages/amplication-build-manager/src/build-job-handler/build-job-handler.service.ts
- packages/amplication-build-manager/src/build-logger/build-logger.module.ts
- packages/amplication-build-manager/src/build-runner/build-runner.module.ts
- packages/amplication-build-manager/src/build-runner/build-runner.service.spec.ts
- packages/amplication-build-manager/src/build-runner/build-runner.service.ts
- packages/amplication-build-manager/src/types.ts
Close: #7550
This pull request fix the issue reported in #7550. The cause being the logic that handle the status reporting only working for builds that were split in multiple jobs. 
> fix(build-manager): support for old `data-servivce-generator` versions that don't support build split

- packages/amplication-build-manager/src/build-job-handler/build-job-handler.service.spec.ts
- packages/amplication-build-manager/src/build-job-handler/build-job-handler.service.ts
- packages/amplication-build-manager/src/build-logger/build-logger.controller.spec.ts
- packages/amplication-build-manager/src/build-logger/build-logger.controller.ts
Close: #7554
This pull request adds a new feature to the build manager that allows logging messages from different domains (Server or AdminUI) in a single build. It implements a new method to extract the domain name from the jobBuildId, and modifies the controller and the tests to use this method and prefix the log messages with the domain name.
Result:
> test(build-manager): add tests for build log when build is split

- packages/amplication-server/webpack.config.js
Close: #7563
Update Prisma version and ignore source map warnings. This pull request updates the Prisma version to the latest release and adds a webpack rule to ignore source map warnings from the generated-prisma-client library in the `amplication-server` package.
> chore(server): ignore webpack sourcemap errors for prisma generated client

- package-lock.json
- package.json
Part of: amplication/private-issues#108
In order to provision a customer with a plan, skip the trial, and have a strong solution, we need to upgrade the Stigg SDK version that we are using.
Without it, the solution is to provision a customer, and then provision a subscription with a plan and `{skipTrial:true}`.
The property `skipTrial` is about to be deprecated, and the new version doesn't contain breaking changes.
> chore(server): update stigg sdk version

- docker-compose.dev.yml
Close: #7749
Replace the dev compose service kafka-ui with redpanda kafka GUI to allow devs to consume/produce JSON formatted messages.
- [] Tests for the changes have been added
> chore: update docker compose dev to use redpanda instead of kafka ui to allow consuming/producing json format messages

- libs/util/logging/src/lib/logging.spec.ts
- libs/util/logging/src/lib/logging.ts
Close: #7768
Fix issue related to duplicated error logs being fired on error.
> fix(util-logging): issue related to double error logs recorded

- packages/amplication-server/src/core/build/build.service.ts
Close: #7801 
The DSG is not using the entities of "other" resources. 
We send an empty list, and if there will be need, we can fill the list with the relevant data in the future
> fix(server):do not pull the entities list for other resources

- libs/util/git/src/git.constants.ts
- libs/util/git/src/providers/github/github.service.ts
- packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.scss
- packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.tsx
- packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/WizardGitCreateRepo.tsx
- packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/constants.ts
Fixes: #6051 
This PR adds proper information while naming repositories.
> feat: add proper info while repository naming

- .github/workflows/nx.template.yml
Close: #7876
Configured bun version on nx ci workspace to v1.0.15 as suggested in here: https://github.com/oven-sh/bun/issues/8010
https://github.com/oven-sh/setup-bun
> chore: use bun version 1.0.15 in ci nx template to avoid dependencies install issues

- .github/workflows/ci.yml
- .github/workflows/deployment.production.yml
- .github/workflows/deployment.static.template.yml
- .github/workflows/e2e.yml
- .github/workflows/nx.template.yml
- .github/workflows/release.dsg.production.yml
- .github/workflows/release.production.yml
- .github/workflows/release.template.yml
Update the following github actions to use the supported node version (v20) instead of the deprecated v16
- actions/cache
- SimenB/github-actions-cpu-cores
> chore: update cache & cpu cores actions to use Node 20

- .github/workflows/deployment.container.template.yml
- .github/workflows/deployment.production.yml
- .github/workflows/deployment.static.template.yml
- .github/workflows/nx.template.yml
- .github/workflows/release.template.yml
Close: #7893
Update the following github actions to use the supported node version (v20) instead of the deprecated v16
- oven-sh/setup-bun
- https://github.com/aws-actions/configure-aws-credentials
> ci: update aws-credentials & setup-bun actions to use Node 20

- packages/amplication-client/src/Entity/EntityField.tsx
- packages/amplication-client/src/Entity/EntityFieldForm.tsx
- packages/amplication-client/src/Entity/constants.ts
- packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx
- packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceAuth.tsx
- packages/amplication-client/src/Resource/create-resource/wizard-pages/interfaces.ts
- packages/amplication-server/src/core/entity/constants.ts
- packages/data-service-generator/src/tests/entities.ts
Close: #7492
Restrict users options on authentication entities specific field types like `Username` and `Password`.
In the specific, users won't be able to modify the unique flag as it will default to:
- Username: `unique=true`
- Password: `unique=false`
> feat(client): disable unique flag for auth entity specific field types

- packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx
- packages/amplication-server/src/core/resource/resource.service.ts
Close: #7933
Adds a delay before using ReactFlowInstance.fitView to allow async operations to complete
add useRef and useEffect to clear the reference to the timeout instance to avoid memory leaks 
Bonus 😄 : adds animation duration for the fitView() function to allow a smooth transition  
> Feat(client): model organizer fit view with delay

- packages/amplication-client/.eslintrc.json
Close: #7777 
Add warnings for ES-LINT on missing deps for react hooks 
> Chore(client): warning on exhaustive deps

- packages/amplication-server/src/core/auth/auth.module.ts
- packages/amplication-server/src/core/auth/auth.service.spec.ts
- packages/amplication-server/src/core/auth/auth.service.ts
- packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.types.ts
Fixes: https://github.com/amplication/private-issues/issues/131
Added new tracking event for StartEmailSignup. (step 2 of https://github.com/amplication/private-issues/issues/131)
> chore(server): add start signup email event

- packages/amplication-client/src/ModuleActions/ModuleActions.tsx
- packages/amplication-client/src/Resource/git/GitActions/RepositoryActions/RepositoryForm.tsx
Close: #7949 
Add showTooltip={false} to components that are using the render function.
> fix(client): add showTooltip={false} to components that are using the render function

- packages/amplication-server/jest.config.ts
- packages/amplication-server/src/core/account/account.service.spec.ts
- packages/amplication-server/src/core/account/account.service.ts
- packages/amplication-server/src/core/auth/auth.controller.spec.ts
- packages/amplication-server/src/core/auth/auth.controller.ts
- packages/amplication-server/src/core/auth/auth.module.ts
- packages/amplication-server/src/core/auth/auth.service.spec.ts
- packages/amplication-server/src/core/auth/auth.service.ts
- packages/amplication-server/src/core/auth/oidc.middleware.ts
Fixes: amplication/private-issues#131
consolidate auth throgh OIDC and JWT generation in auth service.
> refactor(server): move oidc logic to service instead of leaving it in controller

- packages/data-service-generator/src/server/resource/service/create-service.ts
- packages/data-service-generator/src/server/resource/service/service.base.template.ts
- packages/data-service-generator/src/server/resource/service/to-many.template.ts
- packages/data-service-generator/src/server/resource/service/to-one.template.ts
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
- packages/data-service-generator/src/utils/ast.spec.ts
- packages/data-service-generator/src/utils/ast.ts
Close: #8005 #8004 
This PR adds support for dynamic imports in service.base.ts files.
This feature is required for Custom Actions phase 2, where custom function may need imports for default and custom DTOs which may conflict with the imports from Prisma namespace.
In order to support that, we changed two things: 
1. The names of the entities imported from Prisma were changed using an alias to PrismaEntity, e.g. PrismaCustomer - this will allow importing DTOs from ./base/[DTO].ts with no conflict
2. instruct the dynamic import mechanism to ignore qualified names like Prisma.CreateCustomerArgs, and to ignore IDs that appear in the import declarations
IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md) file for detailed …
> feat(dsg): allow dynamic imports in service.base.ts

- packages/amplication-client/src/Components/RedesignResourceButton.tsx
Close: #7972
Replace the select menu with a button if there are only one/zero resources.
> feat(client):  replace the select menu with a button if there are only one/zero resources

- packages/data-service-generator/src/server/resource/service/create-service.ts
Close: #8128 
use bigint for parentId param for relations on the service.base.ts 
> fix(dsg):use bigint for relation functions

- ee/packages/git-sync-manager/src/models.ts
- packages/amplication-cli/src/models.ts
- packages/amplication-client/src/models.ts
- packages/amplication-code-gen-types/src/code-gen-types.ts
- packages/amplication-code-gen-types/src/models.ts
- packages/amplication-git-pull-request-service/src/models.ts
- packages/amplication-server/src/core/moduleDto/dto/EnumModuleDtoType.ts
- packages/amplication-server/src/core/moduleDto/moduleDto.resolver.ts
- packages/amplication-server/src/core/moduleDto/moduleDto.service.spec.ts
- packages/amplication-server/src/core/moduleDto/moduleDto.service.ts
- packages/amplication-server/src/schema.graphql
- packages/data-service-generator/src/models.ts
- packages/data-service-generator/tests/e2e/data-service-generator.e2e.spec.ts
- packages/data-service-generator/tests/e2e/data/base/modules.ts
Close: #8123
Add support for creation of custom DTO of type "Enum"
> feat(server):custom DTO Enums

- libs/util/nestjs/tracing/src/lib/tracing.ts
- package-lock.json
- package.json
Close: #8154
As sandbox tracing seems off and the only change was prisma v5, we are trying to remove this dep.
> chore(tracing): remove prisma instrumentation

- .github/workflows/release.template.yml
Close: #8169
Fix the issue related to release pipeline to be skipped.
When only client is affected, since it is not released as a container, it will not be present in the `affected package:container`, but currently the `deploy:static` was dependent on the `package` step that was never run for the client app.
> chore(ci): fix ci release template

- packages/data-service-generator/tests/e2e/plugins.ts
Close: #8203
Fix dsg e2e tests requirements to use always the latest version of all the plugin used in the tests
> test(dsg): fix auth-core plugin version to latest in dsg e2e tests

- packages/amplication-client/src/ModuleActions/ModuleAction.tsx
Close: #8222
Disable and toggle and other fields in the Action Form when the entire Custom Action Module is disbaled
> fix(client):disable default actions

- packages/notification-service/src/notification-packages/previewUserGenerationCompleted.ts
- packages/notification-service/src/util/novuService.ts
- packages/notification-service/src/util/novuTypes.ts
Close: #8220
Allow using the overrides property in Novu API to use custom template when sending emails from SendGrid via Novu
> feat(Notifications): Support custom SendGrid Templates 

- packages/data-service-generator/src/server/package-json/package.json
- packages/data-service-generator/src/server/resource/service/service.base.template.ts
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-disabled-module.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-default-actions.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #8180
This pr contains two fixes:
- improve args type for the count methods in generated resource base services to match the expectations
- fix findMany methods in generated resource base services to not error with TS v5.4+ (More info about new TS intersection of constrained types behaviour here: https://github.com/microsoft/TypeScript/pull/56515)
> fix(dsg): type issues related to ts v5.4+ changes

- packages/data-service-generator/src/server/static/nest-cli.json
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-disabled-module.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-default-actions.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap
- packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #[8044](https://github.com/amplication/amplication/issues/8044)
Updated nest-cli settings to automatically copy the Swagger folder during project build
> fix(dsg): Update nest cli to copy swagger assets during build

- packages/amplication-client/src/ModuleActions/ModuleActionForm.tsx
- packages/amplication-client/src/ModuleDto/NewModuleDto.tsx
- packages/amplication-client/src/ModuleDto/NewModuleDtoEnum.tsx
- packages/amplication-client/src/ModuleDto/NewModuleDtoEnumButton.tsx
- packages/amplication-client/src/ModuleDto/NewModuleDtoSelectButton.tsx
- packages/amplication-client/src/ModuleDto/hooks/useModuleDto.tsx
- packages/amplication-client/src/ModuleDtoProperty/DtoPropertyTypesSelectField.scss
- packages/amplication-client/src/ModuleDtoProperty/DtoPropertyTypesSelectField.tsx
- packages/amplication-client/src/Modules/ModulesToolbar.tsx
- packages/amplication-client/src/Modules/NewModuleChild.tsx
Part of: https://github.com/amplication/amplication/issues/8227
> feat(client):add navigation and child creation for Type Selector

- packages/amplication-server/src/core/UsageInsights/usageInsights.service.ts
Close: #8300 
Fix issue related to empty array
> fix(server): issue related to join[]

- packages/amplication-server/scripts/generate-graphql-schema.ts
Close: #8329
This change alters the schema generation script to remove its dependency on Kafka by mocking Kafka-related functionalities, allowing it to function without needing Kafka connections.
> fix(server): update graphql schema generation script to not depend on kafka

- packages/amplication-server/src/core/assistant/assistant.resolver.ts
- packages/amplication-server/src/core/assistant/assistant.service.spec.ts
- packages/amplication-server/src/core/assistant/assistant.service.ts
- packages/amplication-server/src/core/billing/billing.service.mock.ts
> Test(Server): Test assistant service

- package-lock.json
- package.json
- packages/amplication-client/src/Assistant/Assistant.scss
- packages/amplication-client/src/Assistant/Assistant.tsx
- packages/amplication-client/src/Assistant/AssistantChatInput.tsx
Close: #8390
- Allow the user to use enter to submit the message while using shift + enter for a new line
- expand the height of the text input when writing a multi-line message
- Enable the text input even when the button is disabled (chat is processing) - to allow the use to start writing the next message without waiting for the end of the response (do not allow submit)
> feat(client):improve chat ux

- packages/amplication-client/src/Entity/EntityList.scss
- packages/amplication-client/src/Entity/EntityList.tsx
- packages/amplication-client/src/Modules/ModulesToolbar.scss
- packages/amplication-client/src/Project/ProjectList.tsx
- packages/amplication-client/src/Resource/PluginsTile.scss
- packages/amplication-client/src/UsageInsights/UsageInsights.tsx
- packages/amplication-client/src/UsageInsights/UsageInsightsDataBox.scss
- packages/amplication-client/src/UsageInsights/UsageInsightsDataBox.tsx
- packages/amplication-client/src/VersionControl/Commit.scss
- packages/amplication-client/src/VersionControl/Commit.tsx
- packages/amplication-client/src/Workspaces/ResourceList.tsx
> style(client):arrange content when Jovu is open

- packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx
Close: #8407 
This pull request resolves the issue when the user gets the error `subscription is null` when trying to develop the application locally. This fixes this issue by checking for the subscription status with the `subscription?.status` expression in the `FeatureIndicatorContainer.tsx` file
> fix(client): fix subscription null issue

- packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx
Close: https://github.com/amplication/private-issues/issues/172
Add the end text for disabled features: 
And not: 
> fix(client): add the end text for disabled features

- packages/amplication-client/src/Components/FeatureIndicator.tsx
- packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx
- packages/amplication-client/src/Resource/break-the-monolith/BtmButton.tsx
Close: https://github.com/amplication/private-issues/issues/172
Update the end text for the disabled feature. 
> fix(client): end text content for disabled

- packages/amplication-server/src/core/entity/entity.service.spec.ts
- packages/amplication-server/src/core/entity/entity.service.ts
Close: #8426 #8425 
When creating relation fields:
- Find the related entity even when the field name includes "id" suffix 
- Create the relation entity without the suffix ID when the data type is lookup 
- Find the related entity even when the entity was created with a plural form name
> feat(server):improve entity name lookup

- packages/amplication-client/src/Assistant/AssistantChatInput.tsx
- packages/amplication-client/src/Entity/NewEntityField.scss
Close: #8427 
Scope the hotkeys hooks in the assistant chat on the form instead of the textbox to enforce scoping
> fix(client):scope chat enter hook

- .github/workflows/ci.yml
- .github/workflows/release.template.yml
Fixes: https://github.com/amplication/amplication-cluster-configuration/issues/221
Fix issue related to github.event.repository.default_branch not being populated for template ci (using trigger `workflow_call`)
> chore(ci): fix issue related to github default_branch not being populated in templates

- packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.spec.ts
- packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.ts
Close: #8461
Valiadte whether a plugin is already installed before installing a new plugin, and throw an error when needed
> feat(server):validate duplicate plugins

- package-lock.json
- package.json
- packages/amplication-client/src/Assistant/hooks/useAssistant.tsx
- packages/amplication-server/src/core/assistant/assistant.service.spec.ts
- packages/amplication-server/src/core/assistant/assistant.service.ts
Close: #8482 
- Update SDK to the latest version to support GPT 4o
- Use messageId to identify different responses on the same prompt
- Prevent the user from sending more prompts between messages as long as Jovu is still processing 
> Feat(server): Use GPT 4o and support multiple responses per prompt

- libs/util/code-gen-types/package.json
- libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts
- libs/util/code-gen-types/src/dotnet-plugin-events.types.ts
- libs/util/code-gen-types/src/dotnet-plugins.types.ts
Close: #8513
Add support for new ProgramFile event for dotnet generation. 
It plays a similar role to the nodejs CreateMainFile event
> feat(code-gen-types): add new dotnet event for programcs generation

- packages/amplication-server/src/core/entity/entity.service.spec.ts
- packages/amplication-server/src/core/entity/entity.service.ts
Close: #8521 
Alter the requested name when creating a field of an entity instead of throwing an exception.
This behavior helps Jovu but will also impact creation from other sources like the UI
This only changes the name of the entity and field and leave the display name and plural display name as it is
The behavior on update left the same and it will still throw an error when trying to update the name to a reserved one.
> feat(server):alter reserved name on creation

- packages/amplication-server/src/core/assistant/assistantFunctions.service.spec.ts
- packages/amplication-server/src/core/assistant/assistantFunctions.service.ts
- packages/amplication-server/src/core/entity/constants.ts
- packages/amplication-server/src/core/entity/entity.resolver.ts
- packages/amplication-server/src/core/entity/entity.service.ts
- packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.spec.ts
- packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.ts
- packages/amplication-server/src/core/resource/resource.service.spec.ts
- packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/private-issues/issues/191
1. When jovu creates a new entity with the name "User" or "Users" (or any upper or lower case version of that) - we create the default user entity with all the default fields, and set it as the auth entity, and we also let jovu know that we created the default fields (so it will not try to create the same fields again)
- if another auth entity already exist we create the new entity as a regular entity with the requested name
2. When jovu installs a plugin that requires auth entity, 
- if there is already auth entity - all good (probably it alreadt created an entity with the name "User" or in case we are working on an existing service).
- if there is no auth entity - and the name "User" is available - we create a new user …
> Feat(server): handle auth entity for jovu

- libs/util/code-gen-types/package.json
- libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts
- libs/util/code-gen-types/src/dotnet-plugin-events.types.ts
- libs/util/code-gen-types/src/dotnet-plugins.types.ts
Close: #8528
Removing the event that handle the docker-compose dev creation. This won't be necessary as the docker-compose event will generate a file that can be used for starting only the dependencies or dependencies with the service leveraging docker compose profiles:
https://docs.docker.com/compose/profiles/
> chore(code-gen-types): remove dotnet plugin redundant event

- libs/util/code-gen-types/package.json
- libs/util/code-gen-types/src/dotnet-plugin-events.types.ts
Close: #8574 
add codeBlock type to LoadStaticFiles PluginEventType.
> fix(code-gen-types): add codeBlock type to LoadStaticFiles PluginEventType

- libs/util/code-gen-types/package.json
- libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts
- libs/util/code-gen-types/src/dotnet-plugin-events.types.ts
- libs/util/code-gen-types/src/dotnet-plugins.types.ts
Close: #8577 
CreateResourceDbContextFile to pascal case.
> fix(code-gen-types): CreateResourceDbContextFile to pascal case

- packages/amplication-client/src/Assistant/hooks/useAssistant.tsx
Close:https://github.com/amplication/private-issues/issues/188
The issue probably happens when the last message in the stream is not processed last - so, instead of setting the state based on the current value on each message, we only set it to True when sending the request, and set it back to false when we get the relevant variable from the server 
> fix(client):fix jovu send button state

- packages/amplication-server/src/core/resource/resource.service.spec.ts
- packages/amplication-server/src/core/resource/resource.service.ts
- packages/amplication-server/src/core/workspace/workspace.service.ts
Close: https://github.com/amplication/amplication/issues/8612
Rewrite the logic for creating a git repository when creating a resource. 
Simplify the logic of the function createResource(), so:
1. We use a single object for git repository data. Instead of using a separate parameter, we are using the property from the `CreateOneResourceArgs` object 
2. Remove the `wizardType` parameter.
3. Add a new `updateProjectGitRepository` 
4. Inherit the project git settings unless gitRepository.isOverrideGitRepository is true or updateProjectGitRepository is true
> fix(server):create resource with git

- libs/util/dsg-utils/src/lib/entity-util.spec.ts
- libs/util/dsg-utils/src/lib/entity-util.ts
- packages/amplication-server/src/core/moduleAction/moduleAction.service.spec.ts
- packages/data-service-generator/src/tests/modules.ts
- packages/data-service-generator/tests/e2e/data/base/modules.ts
Close: #8636
This PR updates  the default meta action endpoint path. 
It does NOT contain DB data migration for already created meta actions
> fix(server): default API `meta` endpoint path

- libs/schema-registry/src/lib/create-pr-request/key.ts
- packages/amplication-server/src/core/build/build.service.ts
Close: #8593
This PR add resourceId to the create-pull-request-request topic key to allow:
- for prs per service: sync-manager to process pr requests in parallel as they won't collide
- for prs per project: sync-manager to process pr request in FIFO order per repository
> feat(server): update create pr topic schema to allow parallel consumption of PRs touching difference repository branches

- packages/amplication-client/src/Purchase/PurchasePage.tsx
Close: #8679
Add a default return URL for the purchase process when no specific return URL is provided from the calling page
> fix(client):fix default purchase return url

- packages/amplication-server/src/core/build/build.service.ts
> fix(server): first PR commit body

- libs/ui/design-system/src/lib/components/Button/Button.scss
- libs/ui/design-system/src/lib/components/Button/Button.tsx
- packages/amplication-client/src/Components/TitleAndIcon.tsx
- packages/amplication-client/src/VersionControl/BuildGitLink.tsx
- packages/amplication-client/src/VersionControl/CommitResourceList.tsx
- packages/amplication-client/src/VersionControl/CommitResourceListItem.scss
- packages/amplication-client/src/VersionControl/CommitResourceListItem.tsx
- packages/amplication-client/src/VersionControl/LastCommit.tsx
- packages/amplication-client/src/VersionControl/hooks/useCommits.ts
- packages/amplication-client/src/VersionControl/useBuildGitUrl.tsx
- packages/amplication-client/src/Workspaces/WorkspaceFooter.tsx
- packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
- packages/amplication-server/src/core/build/build.controller.ts
Close:  
https://github.com/amplication/amplication/issues/8524
https://github.com/amplication/amplication/issues/8506
- Improve the UX to let the user get to their code on git 
- highlight the link to the PR on the build list
- redesign the build list to focus on the status, show the last message, and error
- update the view code button on the side panel to send the user to the PR when there is a single service, or to the build list when there are multiple builds
> feat(client):improve the UX to get to the generated code 

- packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx
Fixes: https://github.com/amplication/private-issues/issues/192
Open pr dialog only from gitSync page.
> fix(client): open pr dialog only from gitSync page

- packages/data-service-generator/src/server/custom-module/custom-resolver/create-resolver-custom-actions.ts
- packages/data-service-generator/src/server/resource/resolver/create-resolver-custom-actions.ts
- packages/data-service-generator/src/utils/create-graphql-args-decorator.ts
Close: https://github.com/amplication/private-issues/issues/211
Add stringLiteral("args") for primitive input type in resolver.
> fix(dsg): add stringLiteral("args") for primitive input type in resolver

- packages/amplication-server/src/core/moduleDto/moduleDto.service.ts
Add validation to dto properties when creating a new DTO - validate that props of type DTO reference an existing DTO (correct dtoId)
Fixes: https://github.com/amplication/private-issues/issues/217
> fix(server): add validation to dto properties when creating a new DTO

- packages/amplication-server/src/core/entity/entity.service.ts
Fix the method `getEntitiesByVersions` to return the fields ordered alphabetically.
This method is called from `build.service.getOrderedEntities` which is called from `build.service.getDSGResourceData`
Close: #8789
> fix(server): always sort the entity fields alphabetically when creating the DSGResourceData

- packages/amplication-server/src/core/project/project.service.ts
part of #8811 
Do not build resource types that are not services
> feat(server):only build services

- ee/packages/git-sync-manager/src/private-plugin/private-plugin.service.ts
> fix(git-sync):throw error when a private plugin is missing

- libs/util/git/src/providers/git-cli.ts
Close: https://github.com/amplication/amplication/issues/8866
replace fs.rm() with fs-extra.remove() in order to delete the file and silently ignore if it does not exist
> fix(git-sync):remove the file or silently ignore if it does not exist

- packages/amplication-client/src/VersionControl/CommitsPage.tsx
Close: #8864 
Show a loading message while commit list is loading
> fix(client):show loading state in commit list

- packages/amplication-server/src/core/resource/resource.service.spec.ts
- packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/amplication/issues/8769
For new projects, which are not connected already to a git repo - when creating the first service, connect the repo to the project and inherit in the service
> fix(server):create project git repo for new projects

- libs/util/code-gen-types/src/schemas/lookup.json
Close: https://github.com/amplication/amplication/issues/8886
Use empty string for the default value of fkFieldName to prevent the validation error 
> fix(client):use empty string for default value for fkFieldName

- packages/amplication-client/src/Layout/RouteWithAnalytics.tsx
- packages/amplication-client/src/routes/resourceEntitiesRoutes.tsx
- packages/amplication-client/src/routes/resourceTabRoutes.tsx
- packages/amplication-client/src/routes/routesUtil.tsx
- packages/amplication-client/src/util/usePageTracking.ts
Close: https://github.com/amplication/private-issues/issues/6 https://github.com/amplication/amplication/issues/6050 
Use the <RouteWithAnalyticsContent component to record the page view with useEffect 
Standardize the page event name - and remove the regex from the url
> fix(client):avoid duplicate page events and standardize page name

- libs/ui/design-system/src/lib/components/DataGrid/DataGrid.tsx
- libs/ui/design-system/src/lib/index.ts
- packages/amplication-client/src/Workspaces/ResourceGitRepo.tsx
- packages/amplication-client/src/Workspaces/ResourceLastBuildVersion.tsx
- packages/amplication-client/src/Workspaces/ResourceListDataColumns.tsx
- packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts
Close: https://github.com/amplication/amplication/issues/8930
Show the code gen version in the resource list and add support to sort non-string solumns
> feat(client):show code gen version in resource list

- packages/amplication-client/src/Components/CreateResourceButton.tsx
- packages/amplication-client/src/PrivatePlugins/PrivatePlugin.tsx
- packages/amplication-client/src/PrivatePlugins/PrivatePluginGitSettings.tsx
- packages/amplication-client/src/PrivatePlugins/PrivatePluginList.scss
- packages/amplication-client/src/PrivatePlugins/PrivatePluginList.tsx
- packages/amplication-client/src/PrivatePlugins/PrivatePluginsPage.tsx
- packages/amplication-client/src/Project/ProjectPage.tsx
- packages/amplication-client/src/Resource/git/ServiceConfigurationGitSettings.tsx
- packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
- packages/amplication-client/src/Workspaces/hooks/useResources.ts
- packages/amplication-client/src/context/appContext.tsx
- packages/amplication-client/src/routes/appRoutes.tsx
- packages/amplication-client/src/routes/resourceTabRoutes.tsx
- packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts
- packages/amplication-server/src/core/resource/dto/ResourceWhereInput.ts
Close: https://github.com/amplication/amplication/issues/8932
Move the private plugins' settings to a separate tab on the project page. 
> feat(client):move private plugins to project tabs

- .vscode/settings.json
- packages/amplication-client/src/Platform/ProjectPlatformPage.tsx
- packages/amplication-client/src/Project/ArchitectureConsole/ApplyChangesNextSteps.tsx
- packages/amplication-client/src/Resource/constants.ts
- packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx
- packages/amplication-client/src/Resource/create-resource/constants.ts
- packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx
- packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceNextSteps.tsx
- packages/amplication-client/src/Resource/create-resource/wizardResourceSchema.ts
- packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx
- packages/amplication-client/src/ServiceTemplate/hooks/useServiceTemplate.ts
- packages/amplication-client/src/VersionControl/Commit.tsx
- packages/amplication-client/src/VersionControl/CommitButton.tsx
- packages/amplication-client/src/VersionControl/CommitsPage.tsx
- packages/amplication-client/src/VersionControl/CreateCommitStrategyButtonItem.tsx
- packages/amplication-client/src/VersionControl/DiscardChanges.tsx
- packages/amplication-client/src/VersionControl/PendingChanges.tsx
- packages/amplication-client/src/VersionControl/PendingChangesList.tsx
- packages/amplication-client/src/VersionControl/PendingChangesPage.tsx
- packages/amplication-client/src/VersionControl/hooks/useCommits.ts
- packages/amplication-client/src/Workspaces/DeleteResourceButton.tsx
- packages/amplication-client/src/Workspaces/ResourceGitRepo.tsx
- packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
- packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts
- packages/amplication-client/src/Workspaces/queries/projectQueries.ts
Part of: https://github.com/amplication/amplication/issues/8935
- Support the new param ResourceTypeGroup for pending changes and commits 
- Add dynamic default behavior for the commit button to prevent from large build processes when not needed
- When there are pending changes - build only the services with pending changes
- When there is a single service - build the single service (using the ALL option)
- When there are multiple services - let the user choose which service 
> feat(client):resource type group - split commit to two groups of resource types

- packages/amplication-client/src/Project/ProjectList.scss
- packages/amplication-client/src/Project/ProjectListItem.tsx
- packages/amplication-client/src/Resource/constants.ts
- packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx
- packages/amplication-client/src/Resource/resourceSettings/DirectoriesServiceSettingsForm.tsx
- packages/amplication-server/src/core/resource/serviceTemplate.service.ts
Part of: https://github.com/amplication/amplication/issues/8935
Use a new placeholder for {{SERVICE_NAME}} on the template settings, and replace with the actual service name when creating a service from template
> feat(server):use dynamic dir name for services created with templates

- packages/amplication-client/src/Components/CreateResourceButton.tsx
- packages/amplication-client/src/Entity/EntityList.tsx
- packages/amplication-client/src/ServiceTemplate/NewServiceFromTemplate.tsx
- packages/amplication-client/src/ServiceTemplate/NewServiceFromTemplateDialogWithUrlTrigger.tsx
- packages/amplication-client/src/Workspaces/ResourceList.tsx
- packages/amplication-client/src/util/useUrlQuery.tsx
Part of: https://github.com/amplication/amplication/issues/8935
Add an option to create a service from a template in the resource list
> feat(client):create service from template dialog

- packages/amplication-client/src/PrivatePluginVersion/PrivatePluginVersionCodeField.tsx
- packages/amplication-client/src/PrivatePluginVersion/PrivatePluginVersionForm.scss
- packages/amplication-client/src/PrivatePluginVersion/PrivatePluginVersionForm.tsx
part of Close: https://github.com/amplication/amplication/issues/8990
Add json fields to edit the settings and configurations fields
> feat(client):add settings fields on private plugin version

- packages/amplication-server/src/core/build/build.resolver.spec.ts
- packages/amplication-server/src/core/build/build.resolver.ts
- packages/amplication-server/src/core/build/build.service.ts
- packages/amplication-server/src/core/project/project.resolver.spec.ts
- packages/amplication-server/src/core/resource/resource.resolver.spec.ts
- packages/amplication-server/src/core/resource/resource.service.spec.ts
part of https://github.com/amplication/amplication/issues/8997
Recalculate the build status of old builds with lazy data migration.
The default value of the new field is Unknown - so use the @FieldResolver to recalculate and update the build status when the status is Unknown, otherwise return the status already saved in the DB
> fet(server):recalc build status

- libs/schema-registry/src/index.ts
- libs/schema-registry/src/lib/plugin-notify-version/index.ts
- libs/schema-registry/src/lib/plugin-notify-version/key.ts
- libs/schema-registry/src/lib/plugin-notify-version/value.ts
- packages/amplication-build-manager/src/build-runner/build-runner.controller.ts
- packages/amplication-build-manager/src/build-runner/build-runner.service.ts
- packages/amplication-build-manager/src/build-runner/dto/NotifyPluginVersion.ts
- packages/amplication-prisma-db/prisma/migrations/20241002062702_/migration.sql
- packages/amplication-prisma-db/prisma/migrations/20241002063144_/migration.sql
- packages/amplication-prisma-db/prisma/schema.prisma
- packages/amplication-server/src/core/build/build.controller.ts
- packages/amplication-server/src/core/build/build.service.spec.ts
- packages/amplication-server/src/core/build/build.service.ts
- packages/amplication-server/src/core/build/dto/BuildPlugin.ts
Close: https://github.com/amplication/amplication/issues/9021
Add new model to save the plugin versions used in build 
> Add infra for messages to notify plugin versions used in build process

- ee/packages/git-sync-manager/src/models.ts
- libs/util/code-gen-types/src/models.ts
- packages/amplication-cli/src/models.ts
- packages/amplication-client/src/Project/ProjectPage.tsx
- packages/amplication-client/src/Workspaces/ResourceListDataColumns.tsx
- packages/amplication-client/src/Workspaces/WorkspaceLayout.scss
- packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx
- packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts
- packages/amplication-client/src/models.ts
- packages/amplication-server/src/core/resource/resource.resolver.ts
- packages/amplication-server/src/core/resource/serviceTemplate.service.ts
- packages/amplication-server/src/schema.graphql
- packages/data-service-generator/src/models.ts
part of [#8942](https://github.com/amplication/amplication/issues/8942)
set the template version on service creation and show the template version on the catalog
> feat: Set template version on service creation

- ee/packages/git-sync-manager/src/models.ts
- libs/util/code-gen-types/src/models.ts
- packages/amplication-cli/src/models.ts
- packages/amplication-client/src/models.ts
- packages/amplication-prisma-db/prisma/migrations/20241005072219_migration/migration.sql
- packages/amplication-prisma-db/prisma/schema.prisma
- packages/amplication-server/src/core/outdatedVersionAlert/dto/EnumOutdatedVersionAlertStatus.ts
- packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts
- packages/amplication-server/src/schema.graphql
- packages/data-service-generator/src/models.ts
Close: #9005
Change the status of previous unhandled alerts to canceled when creating new alerts for the same objects
> feat(server):cancel previous alerts when creating new alerts for the same objects

- packages/amplication-client/src/PrivatePluginVersion/PrivatePluginVersionForm.tsx
Close: #9002 
Remove deprecated toggle.
> fix(client): remove deprecated toggle

- packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts
Close: https://github.com/amplication/amplication/issues/9088
do not load alerts for deleted services
> fix(server): do not load alerts for deleted services

- .vscode/launch.json
- ee/packages/git-sync-manager/jest.config.ts
- ee/packages/git-sync-manager/src/private-plugin/private-plugin.service.ts
- libs/util/git/src/git-client.service.ts
Close: https://github.com/amplication/amplication/issues/9349
When using blueprints to create plugins, avoid conflicts on the git-sync service by cloning to seperate folders and clearn up after download
> fix(git-sync):avoid conflict when pushing code to the private plugins repo, and cleanup after download

- libs/ui/design-system/src/lib/components/SelectField/SelectField.scss
- libs/ui/design-system/src/lib/components/SelectField/SelectField.tsx
- libs/ui/design-system/src/lib/components/Text/Text.tsx
- libs/ui/design-system/src/lib/components/TextInput/TextInput.scss
- libs/ui/design-system/src/lib/components/TextInput/TextInput.tsx
- libs/ui/design-system/src/lib/style/css-variables.scss
- packages/amplication-client/src/Blueprints/BlueprintSelectField.tsx
- packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldLink.tsx
- packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldMultiSelect.tsx
- packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldSelect.tsx
- packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldText.tsx
- packages/amplication-client/src/Resource/create-resource-page/CreateResourceForm.tsx
- packages/amplication-client/src/Resource/create-resource-page/CreateResourceFormResourceSettings.tsx
- packages/amplication-client/src/Resource/git/GitActions/RepositoryActions/RepositoryActions.scss
- packages/amplication-client/src/style/mixin.scss
Close: https://github.com/amplication/amplication/issues/9579
- Show the list of fields in a single column
- Show tooltip next to custom properties
- Show the blueprint description after selection
- Reset the initial value of the form after blueprint selection to allow correct behavior of validation 
- Hide the resource properties panel when there are no properties
> feat(client):improve resource creation UX

- packages/amplication-client/src/routes/appRoutes.tsx
Close: https://github.com/amplication/amplication/issues/9619
Move the new-resource route to be a sub route of Project home to allow access to the resource context with the permissions object
> fix(client):move new-resource form to the project context to access the permissions

- packages/amplication-client/src/Workspaces/InviteMember.tsx
Signed-off-by: Itai Nathaniel <itainathaniel@gmail.com>
Close: #9664
It clears the email input after inviting the submitted email
> fix(client): Clear email input after sending invite

- packages/amplication-client/src/OutdatedVersionAlerts/OutdatedVersionAlertList.tsx
- packages/amplication-client/src/OutdatedVersionAlerts/hooks/outdatedVersionAlertsQueries.ts
Close: #9718 
- Enhance OutdatedVersionAlertList to display project name when viewing tech debt at workspace level
- Update GraphQL fragment to include project details
- Conditionally render project column based on current route
> feat(client): Add project column to workspace tech debt view
