amplication/amplication

packages/amplication-client/src/Project/NewProject.tsx
**Before**
https://www.loom.com/share/05d02de629e049e5ac8d1a24339ce6d9
**After**
https://www.loom.com/share/6075c370190b48bdbfce2d55093c4498
Fixes https://github.com/amplication/amplication/issues/3956
=> 🐛 Bug Report: Popup cannot be closed - UI Issues

packages/amplication-client/src/Entity/RelatedEntityFieldField.tsx
https://www.loom.com/share/c32941a99a3c4997b15b75fd0337605a
https://www.loom.com/share/79bd5a003cc84f638ff949c4b0d4b9dd
=> fix: relation diagram doesn't appear when setting a field from type lookup (related entity)

packages/amplication-client/src/Permissions/EntityPermissionAction.scss, packages/amplication-client/src/Permissions/EntityPermissionFields.scss
Fixes https://github.com/amplication/amplication/issues/2730
=> 🐛 Bug Report: Entities - Add button need padding

.github/workflows/release.template.yml
Part of #4943 
Part of the DSG refactoring needs to be merged to `master` to become active since it is part of the release template.
Needs to be merged before #5086 
=> chore(ci): add docker build args with git_ref

packages/amplication-client/scripts/inject-variables.spec.ts, packages/amplication-client/src/404/NotFoundPage.spec.tsx, packages/amplication-client/src/App.tsx, packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/util/analytics.ts
=> add version to all BI events

.github/workflows/README.md, packages/amplication-build-manager/project.json, packages/amplication-client/project.json, packages/amplication-data-service-generator-runner/project.json, packages/amplication-git-pull-request-service/project.json, packages/amplication-server/project.json, packages/amplication-storage-gateway/project.json
Close: #5109
Fix the issue where affected application deployment step was always skipped
=> ci: fix deployment step

packages/amplication-data-service-generator-runner/project.json
=> ci: configure DSG runner as not deployable

packages/.amplicationignore
This pull request remove file that accidentally got inside
=> fix: remove an .amplication ignore file

packages/amplication-git-utils/src/GitProvider.ts, packages/amplication-git-utils/src/IGitProvider.ts, packages/amplication-git-utils/src/git/git-factory.ts, packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/git/github.service.ts, packages/amplication-git-utils/src/types.ts
=> refactor(git-util):  extract GitProvider interface in its own file

packages/amplication-plugin-api/src/main.ts, packages/amplication-plugin-api/src/plugin/base/plugin.resolver.base.ts
=> 5134 useglobalpipes configuration

packages/amplication-client/src/Layout/InnerTabLink.scss, packages/amplication-client/src/Layout/PageContent.scss, packages/amplication-client/src/VersionControl/CommitBuildsStatusIcon.scss, packages/amplication-client/src/VersionControl/CommitData.scss, packages/amplication-client/src/VersionControl/CommitListItem.scss
closes https://github.com/amplication/amplication/issues/3638
**Before**
https://www.loom.com/share/1b63a8f78d304253aaff9cf3eb8306b4
**After**
https://www.loom.com/share/e83e45d3db5e46e2acf889a9cbb07f30
=> Bug Report: Commit page - Wrong padding between selection

packages/amplication-design-system/src/index.ts
=> correct exports from design system

packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx
=> 5142 version dropdown doesnt work

packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx
=> fix save issue

packages/amplication-client/src/Layout/PageContent.scss, packages/amplication-client/src/VersionControl/CommitBuildsStatusIcon.scss, packages/amplication-client/src/VersionControl/CommitData.scss, packages/amplication-client/src/VersionControl/CommitList.scss, packages/amplication-client/src/VersionControl/CommitList.tsx, packages/amplication-client/src/VersionControl/CommitListItem.scss, packages/amplication-design-system/src/components/CircularProgress/CircularProgress.scss
=> align commit list according to design

packages/amplication-build-manager/src/build-logger/build-logger.controller.ts, packages/amplication-build-manager/src/build-runner/build-runner.controller.ts, packages/amplication-build-manager/src/queue/queue.service.ts, packages/amplication-server/src/core/queue/queue.service.ts
converted observable to promise 
added await for promise when emit is called
Close: #4947
=> Catch error issued by kafka client so build status can be updated correctly

packages/amplication-server/migration-scripts/install-auth-core-plugin.ts
Close: #4431 
Update plugin npm name in migration script
=> fix(server): update npm package name

packages/amplication-git-utils/src/GitProvider.ts, packages/amplication-git-utils/src/git-provider.interface.ts.ts, packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/git/github.service.ts, packages/amplication-git-utils/src/types.ts
Close: #5143 
This pull request collect all the amplication's commits from the default branch
=> feat(git-utils): getting all amplication commits before creating the branch

packages/amplication-data-service-generator-runner/src/main.ts
Part of: #5003 
Pass the plugin installation with the default plugins to the dsg
=> fix(dsg): pass the plugin installation with the default plugins to the dsg

.github/workflows/release.template.yml, .gitignore, ee/packages/amplication-git-pull-service/project.json, ee/packages/amplication-git-push-webhook-service/project.json, package-lock.json, package.json, packages/amplication-build-manager/project.json, packages/amplication-client/project.json, packages/amplication-git-pull-request-service/project.json, packages/amplication-plugin-api/project.json, packages/amplication-server/project.json, packages/amplication-storage-gateway/project.json, packages/data-service-generator/Dockerfile, packages/data-service-generator/project.json, packages/data-service-generator/src/server/create-server.ts
Related to #5172
This PR standardises the approach to docker build arguments in amplication packages by exposing GIT_REF_NAME and GIT_SHA as docker build args.
It also updates DSG to use the env var above in the DSG build log.
=> chore(dsg): update docker nx plugin and env variables 

package-lock.json, package.json, packages/amplication-code-gen-types/package.json, packages/amplication-code-gen-types/project.json
Close: #5154  
Fix for https://github.com/amplication/amplication/actions/runs/4145083429/jobs/7169148170#step:10:206.
As part of this work, @amplication/code-gen-types package beta has been published too. 
=> fix(dsg): dependencies issue that prevent DSG to build in a docker container

jest.preset.js
Fixes amplication/amplication-infrastructure-next/issues/74
Add testing reporting to GitHub by leveraging jest reporter https://jestjs.io/blog/2022/04/25/jest-28#github-actions-reporter 
=> chore: add jest test reporting for GitHub actions to all nx projects

packages/amplication-git-pull-request-service/Dockerfile
Close: #5198 
Adds a specific version of git to the container image of the `git-pull-request-service`.
=> chore: add a specific git version to the dockerfile

.github/workflows/security.yml
Close: #5210 
This pull request changes the way the security workflow is triggerd.
=> fix: change security workflow triggers

package-lock.json, package.json, packages/amplication-code-gen-types/package.json
Update package.json to version 1.3.0
=> chore: bump version

packages/amplication-git-utils/src/git/git-client.ts, packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/types.ts
Close: #5204 
This pull request extract the diff between the current state of the amplication branch to the latest amplication commit
=> feat(git-utils): extract the diff content

packages/amplication-git-utils/src/git/git-client.ts, packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/types.ts
Close: #5204 
This pull request run a post commit process 
=> feat(git-utils): post commit process

.github/workflows/deployment.production.yml
Close: #5243 
Added action that tags the image with the repository name & copied over the build_args strategy from the release workflow.
=> fix(workflow): add action for creating the tag properly

scripts/setup.ts
Close: #5249
Remove codegen run from the setup script since it is now handled by nx server build dependency
=> chore: fix setup script

packages/amplication-client/src/Project/NewProject.tsx
https://www.loom.com/share/57be56fd96c54edd87e0330ac1fe91af.
=>  🐛 Bug Report: Wrong design for error with project name #4560

packages/amplication-client/src/authentication/authentication.spec.ts, packages/amplication-client/src/authentication/authentication.ts, packages/amplication-client/src/index.tsx, packages/amplication-client/src/util/cookie.spec.ts, packages/amplication-client/src/util/cookie.ts, packages/amplication-server/src/core/auth/auth.controller.spec.ts, packages/amplication-server/src/core/auth/auth.controller.ts
Fixes: https://github.com/amplication/amplication-infrastructure-next/issues/69
Update the GitHub auth flow to fix a potential security vulnerability. 
The new flow is explained [here](https://github.com/amplication/amplication-infrastructure-next/issues/69#issuecomment-1441584632)
=> fix(client/server): auth vulnerability

packages/amplication-git-utils/src/git/git-client.ts, packages/amplication-git-utils/src/git/git.service.ts
Close: #5266
This pull request use the 3way merge method and by that apply the diff all the time even in conflicts
=> Fix(git-utils): patch apply fail

packages/amplication-code-gen-types/package.json, packages/amplication-code-gen-types/src/plugin-events-params.ts, packages/amplication-code-gen-types/src/plugin-events.ts, packages/amplication-code-gen-types/src/plugins-types.ts
Close: #5264 
Remove unused plugin events: CreateUserInfo and CreateTokenPayloadInterface
=> fix(gen-types): remove unused plugin events

packages/amplication-git-utils/src/git-provider.interface.ts.ts, packages/amplication-git-utils/src/git/github.service.ts, packages/amplication-git-utils/src/types.ts
Close: #5276 
This pull request add commentOnPullRequest function
=> feat(git-utils): comment on pull request method

packages/amplication-git-utils/src/constants.ts, packages/amplication-git-utils/src/git-provider.interface.ts.ts, packages/amplication-git-utils/src/git/git.service.ts, packages/amplication-git-utils/src/git/github.service.ts, packages/amplication-git-utils/src/types.ts
Close: #4885 
this pull reqeust change the way we comment and changing the title and the body of the pull requests that we open
=> feat(git-utils): comment on a pull request the data

package-lock.json, package.json, packages/amplication-plugin-api/src/app.module.ts
Close: #5290 
Fix missing DI registration on plugin api and bump version.
=> fix(plugin-api): plugin api fail to start

packages/amplication-git-pull-request-service/Dockerfile
=> 5292 bug report cant install git library during git pull request service docker build

packages/amplication-git-pull-request-service/Dockerfile
Close: #5297 
Add configuration - username and email - to the dockerfile of the git-pull-request-service
=> chore(git-pull-request-service): add username and email config for git

packages/amplication-git-utils/src/git/git.service.ts
Close: #5305 
This pull request deal with the first time of amplication commit
=> fix(git-utils): usecase - amplication's first commit

packages/data-service-generator/src/utils/dynamic-installation/Tarball.ts
Close: #5300 
fix undefined version
=> hotfix(dsg): fix undefined version

packages/amplication-git-utils/src/git/git.service.ts
Close: #5313
This pull request missing symbols
=> fix(git-utils): fix the email of amplication diff

.vscode/launch.json, libs/util/nestjs/logging/README.md, libs/util/nestjs/logging/tests/utils/index.ts, libs/util/nestjs/logging/tests/utils/logger.mock.ts, libs/util/nestjs/logging/tsconfig.lib.json, packages/amplication-server/project.json, packages/amplication-server/src/core/resource/resource.resolver.spec.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/core/serviceTopics/serviceTopics.service.ts, packages/amplication-server/src/core/topic/topic.service.ts, tsconfig.base.json
Close: #5303
Update message broker deletion process to delete all relative reference blocks
=> fix(server): message broker deletion referenced data  

packages/amplication-prisma-db/.env, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-prisma-db/project.json
Close: #5330
Refactor how we generate the prisma clients in order to rely on the nodejs path management instead of the OS path management. 
=> chore: refactor prisma generation client process to work also on Windows

packages/amplication-git-utils/src/git/git-client.ts, packages/amplication-git-utils/src/git/git.service.ts
Close: #5338 
This pull request clean the changed files before applying a new diff
=> fix(git-utils): clean changes before diff apply

packages/data-service-generator/src/utils/dynamic-installation/defaultPlugins.ts
Close: #5345 
This pull request adds the mongo db plugin to the db category
=> fix(dsg): add mongo to plugin category

packages/amplication-client/src/Resource/git/AuthResourceWithGit.tsx, packages/amplication-client/src/Resource/git/GitActions/ExistingConnectionsMenu.tsx
part of: #4648 
fix git integration button
before:
after:
=> feat(client): fix git integration button

packages/amplication-client/src/Purchase/PurchasePage.tsx
Close: #5320 and #5358
This pull request fixes an error with the price track event
=> fix(client): price event

package-lock.json, package.json, packages/amplication-code-gen-types/package.json
Close: next release 1.4.2
bump version for release
=> chore(amplication): bump version for release

packages/amplication-prisma-db/prisma/migrations/20230227180208_add_provider_properties_json_field_to_git_organization_model/migration.sql, packages/amplication-prisma-db/prisma/migrations/20230308144711_add_provider_properties_column_to_git_organization_model/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma
Close: #5371
delete the wrong migration and create a new one
=> fix(prisma-db): fix prisma migration

package-lock.json, package.json
=> chore: remove unused package `@apollo/gateway`

packages/amplication-client/src/Layout/PageContent.scss
Close: #5022 
The scrollbar gutter is not supported by Safari browser, hence changed it with the required padding.
=> fix(client): #5022 fixed scrollbar-gutter with padding

packages/amplication-cli/src/models.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/amplication-git-pull-request-service/src/pull-request/pull-request.service.ts, packages/amplication-git-utils/src/git-provider.interface.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts, packages/amplication-git-utils/src/providers/git.service.ts, packages/amplication-git-utils/src/providers/github/github.service.ts, packages/amplication-git-utils/src/types.ts, packages/amplication-server/src/core/git/dto/inputs/GitGroupInput.ts, packages/amplication-server/src/core/git/git.provider.service.ts, packages/amplication-server/src/core/git/git.resolver.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
part of: #5261
refactor git provider properties
=> Refactor(git-utils): git provider properties

packages/local-data-service-generator-controller/src/code-gen/code-gen.controller.ts
Related: #5417 
As part of updating the documentation it appeared obvious that  the local dsg devex was not the best. This PR allow the local-dsg-controller to proxy the dsg stdoud and stderr to improve the developer experience like shown below:
=> feat(local-dsg): allow local-dsg-controller to proxy DSG stdout and sterr to increase devex

.github/dependabot.yml
Close: #5384 
This pull request turn on dependabot to update our npm packages ones a week
=> chore: turn on dependabot

packages/amplication-client/src/Components/CreateResourceButton.scss, packages/amplication-client/src/Components/CreateResourceButton.tsx, packages/amplication-client/src/Components/CreateResourceButtonItem.scss, packages/amplication-client/src/Components/CreateResourceButtonItem.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss, packages/amplication-design-system/src/components/SelectMenu/SelectMenu.scss
=> Fix: Wrong UI - Resource drop down

README.md, package.json
=> docs: update setup instructions for local dev env

packages/amplication-server/src/core/account/account.service.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.service.ts
=> fix: Add missing user data on signup event

packages/amplication-client/src/Resource/ResourceNameField.scss, packages/amplication-client/src/Resource/ResourceNameField.tsx
Close: #4457 
Fixing feedback from @GreenMachine01 in [here](https://github.com/amplication/amplication/issues/4457#issuecomment-1470429848)
https://user-images.githubusercontent.com/74011196/225969223-9be63c6e-3a47-4b87-a8d0-ea72c0094a64.mov
=> feature(client): Update error display logic with a tooltip

packages/amplication-client/src/Workspaces/ResourceListItem.tsx
Close: #5452 
Added condition for deleting resource according to resourceType in delete confirmation modal.
=> added condition for deleting resource according to recourceType #5452

package.json
Close: #5476 
Remove duplicated service to avoid issue reported here https://github.com/amplication/amplication/issues/5476#issuecomment-1478316712
=> chore: fix root script for serving git related services

.github/workflows/e2e.yml, .github/workflows/nx.template.yml, libs/ui/design-system/README.md
Close: #5523 
Fix the issue that was preventing the e2e test ci to run properly.
This PR also contains a small doc update to force a change in another library (used to test the ci)
=> chore(ci): fix workflow for e2e testing

packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.spec.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts, packages/amplication-git-utils/src/providers/bitbucket/requests.ts, packages/amplication-git-utils/src/providers/git.service.ts, packages/amplication-git-utils/src/types.ts
Close: #5520 
get the first commit for the provided branch
=> Feat(git-utils): get first commit on branch

packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
=> changed contact us chat trigger, added downgrade chat trigger

packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts
=> disable sync of free customers to stripe

packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.spec.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.types.ts, packages/amplication-git-utils/src/providers/bitbucket/requests.ts, packages/amplication-git-utils/src/providers/git.service.ts, packages/amplication-git-utils/src/types.ts
Close: #5543 
create a comment on a pull request
=> Feat(git-utils): comment on pull request

packages/amplication-client/src/Purchase/PurchasePage.scss
=> fix(client):  fix current plan text color

packages/amplication-build-manager/.eslintrc.json, packages/amplication-build-manager/src/build-runner/build-runner.controller.ts
=> refactor(build-manager): move to amplication logger

packages/amplication-client/src/Components/NameField.tsx, packages/amplication-client/src/Entity/EntityForm.tsx, packages/amplication-client/src/util/formikValidateJsonSchema.ts, packages/amplication-server/src/core/entity/entity.service.ts
Reverts amplication/amplication#5595
=> Revert "Fix/5565 bug report entity name validation rules are inconsistent"

packages/amplication-git-utils/src/git-provider.interface.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts, packages/amplication-git-utils/src/providers/git-cli.ts, packages/amplication-git-utils/src/providers/git.service.spec.ts, packages/amplication-git-utils/src/providers/git.service.ts, packages/amplication-git-utils/src/providers/github/github.service.ts, packages/amplication-git-utils/src/types.ts, packages/amplication-server/src/schema.graphql
Relate: #5648
Simplify code in preparation to refactoring 
=> refactor(git-utils): git service services naming

packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.spec.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.types.ts, packages/amplication-git-utils/src/providers/bitbucket/requests.ts, packages/amplication-git-utils/src/providers/git.service.ts, packages/amplication-git-utils/src/types.ts
Close: #5654 
- get  a pull request list and filter by branch name
- create a pull request
=> feat(git-utils): get and create pull request

package-lock.json, package.json, packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/git/git.provider.service.ts, packages/amplication-server/src/core/git/git.resolver.ts, packages/amplication-server/src/core/project/project.resolver.spec.ts, packages/amplication-server/src/core/project/project.resolver.ts, packages/amplication-server/src/core/project/project.service.spec.ts, packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts, packages/amplication-server/src/core/workspace/workspace.resolver.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.service.ts
=> fix(server): add missing events

.github/dependabot.yml, packages/data-service-generator/.eslintrc.json, packages/data-service-generator/project.json, packages/data-service-generator/src/admin/package-json/.npmrc, packages/data-service-generator/src/admin/package-json/create-package-json.ts, packages/data-service-generator/src/admin/package-json/package.json, packages/data-service-generator/src/server/package-json/.npmrc, packages/data-service-generator/src/server/package-json/create-package-json.ts, packages/data-service-generator/src/server/package-json/package.json
Close: #5663 
This pull request changes the `package.templat.json` files to `package.json` files in order to apply dependabot on them.
=> feat(dsg): update packages in generate code

packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx
Close: #5685
Add settings to DB plugin installation.
=> fix(client): add settings to db plugins

packages/amplication-git-pull-request-service/Dockerfile
Close: #5648 
Removing redundant git configuration from dockerfile since we are now configuring the git cli at runtime here https://github.com/amplication/amplication/pull/5653/files#diff-045ad92d579607f503463c05f08ddd15fc7363bdcc9766e0330c2c87878613c0R16-R19
=> chore(pull-request-service): remove redundant git config

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceName.tsx
=> fix(client):prevent multiple events

packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Resource/create-resource/ServiceWizard.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGenerationSettings.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGithubSync.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceAuth.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceDatabase.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceName.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceNextSteps.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceRepository.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceWelcome.tsx, packages/amplication-client/src/util/analytics-events.types.ts
=> fix(client): trigger wizard page event from wizard

packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts
=> fix(server): user account ID for event

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.scss, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx
Close: #5710 
Fix click button "View my code" link => goto pr url.
=> Fix/Onboarding: Broken GitHub url in view my code button

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceNextSteps.tsx
Close: #5750 
Fix undefined resource => use resource from props and the createResource from the appContext instead of the currentResource 
Test case:
Create a new service and click on I'm done button.
=> fix(client): resource undefined

packages/amplication-client/src/Resource/create-resource/wizardResourceSchema.ts
Close: #5717 
Fix base directory default value.
=> fix(client): baseDir default value

packages/amplication-client/src/Resource/create-resource/wizardResourceSchema.ts
Close: #5734 
Fix the last step name to "Finish."
=> fix(client): change last step name to Finish

packages/amplication-client/src/Entity/ConfirmationDialogFieldList.tsx, packages/amplication-client/src/VersionControl/ActionLog.scss
=> fix(client): show build log scrollbar

packages/amplication-client/src/Resource/create-resource/WizardProgressBar.tsx, packages/amplication-client/src/Resource/create-resource/wizardProgressBar.scss
Close: #5760
Fix the error message for the unique key in the progress bar component and cleanup code.
=> fix(client): remove extra element in wizard progress bar

packages/amplication-client/src/Plugins/PluginsCatalogItem.tsx
Close: #5537 
This pull request changes the wrong link value in the UI.
=> fix(client): change wrong plugin link

packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/util/analytics-events.types.ts, packages/amplication-server/src/core/project/project.service.ts
=> fix: commit event

packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/models/index.ts
Close: #5440 
Update tracking event to provide the correct git provider 
=> fix(server): update event to use dynamic git provider

packages/amplication-server/src/core/git/git.provider.service.ts
part of: #5440 
simplify createGitClient and getGitProviderProperties usage
=> refactor(server): simplify createGitClient and getGitProviderProperties usage

packages/amplication-client/src/Resource/create-resource/CreateServiceLoader.tsx
Close: #5737
remove un relevant description from createService loader
Test case:
Create a new service and make sure that the loader presents the updated design by Figma.
=> fix(client): remove unrelevant description from createService loader

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.scss, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx
Close: #5719 
Fix title css according to Figma.
=> fix(client): fix title css according to Figma.

packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.scss, packages/amplication-client/src/Resource/create-resource/ServiceWizard.tsx
Close: #5740 
Fix the close button style. 
Test case:
Open the service wizard (click on create service button). 
Make sure that the close button is aligned with Figma CSS.
=> fix(client): fix close button style

package-lock.json, package.json
This pull request bumps the amplication's version in the `package.json`
=> chore: bump amplication's version

package.json
Close: #5604 
I checked import of the packages `stylus` and `stylus-loader`, and uninstalled from `package.json` and checked whether it affected project design or not.
- command executed
- `npm uninstall -D stylus-loader`
- `npm uninstall -D stylus`
=> refactor: remove stylus and stylus-loader package

packages/amplication-client/src/User/Signup.tsx
Close: #5496 
Add isFromInvitation check in the signup component to know if a route to the workspace is needed. 
Test case: 
Get an invitation to an existing user workspace as **a new user**. => signup and make sure that you get to the workspace page.
=> feat(client): add isFromInvitation check for route to workspace

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGithubSync.tsx
Close: #5721
Typo fixing. 
Test case: 
Go to service wizard => git repository step => make sure that git is written with a big letter: "Git."
=> fix(client): name fixing

packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Resource/create-resource/ServiceWizard.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceWelcome.tsx, packages/amplication-client/src/util/analytics-events.types.ts
Close: #5752, #5761, #5755, #5774, #5773
=> Wizard bi events

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceRepository.tsx, packages/amplication-client/src/Resource/create-resource/wizardResourceSchema.ts
Close: #5717 
Fix base dir to always contain "./" and remove it from tree files. 
Test case: 
Goto service wizard => repository selection step:
1. the default value of base dir should be: "./"
2. It cannot be deleted.
3. In the file tree, you don't see the: "./"
=> fix(client): base dir value

packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx
Close: #5536 
Fix selected version is undefined when I try to save plugin settings. 
Test case: 
Go to install plugin settings => try to change the settings and click save button.
=> fix(client): selected version is undefined

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceAuth.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceDatabase.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/ImgSvg.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/LabelDescriptionSelector.tsx
Close: #5718 
Fix slow image loading. 
Test case:
Go to service wizard => navigate between steps and see that the images loading is o.k .
=> fix(client): slow image loading

ee/packages/amplication-git-pull-service/project.json, ee/packages/amplication-git-push-webhook-service/project.json, packages/amplication-build-manager/project.json, packages/amplication-plugin-api/project.json
=> Change default NestJS ports on project.json for all services using the default 9229 port

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGithubSync.scss, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGithubSync.tsx, packages/amplication-client/src/Resource/git/AuthWithGit.tsx, packages/amplication-client/src/Resource/git/GitActions/ExistingConnectionsMenu.scss, packages/amplication-client/src/Resource/git/GitActions/RepositoryActions/RepositoryActions.scss, packages/amplication-client/src/Resource/git/GitActions/WizardNewConnection.tsx, packages/amplication-client/src/Resource/git/GitSyncNotes.tsx, packages/amplication-client/src/Resource/git/ProjectConfigurationGitSettings.scss, packages/amplication-client/src/Resource/git/ProjectConfigurationGitSettings.tsx, packages/amplication-client/src/Resource/git/ServiceConfigurationGitSettings.scss, packages/amplication-client/src/Resource/git/ServiceWizardConfigurationGitSettings.tsx, packages/amplication-server/src/core/resource/resource.service.ts
Close: #5872 
Add new flows to GitHub's connections according to feat request: #5872 
Tests:
Follow issue 5872
=> feat(client/server): add new flows to github connection on service wizard

.devcontainer/devcontainer.json
Close: #5826 
This PR is linked to this GitHub issue [#5826](https://github.com/amplication/amplication/issues/5826). Adds GitHub codespaces and remote devcontainer support to amplication repository
=> feat: added devcontainer config file for github codespaces and remote dev environments

.github/workflows/fork-to-branch.yml
Close: #5901 
Adds back the workflow for the fork to branch setup.
=> chore(workflows): add back fork to branch workflow

packages/amplication-client/src/Resource/create-resource/ServiceWizard.tsx
FIxes https://github.com/amplication/amplication/issues/5741
https://www.loom.com/share/5dd7633e92c4439faaec4ab9fa320f4d
https://www.loom.com/share/1ac1e1d1b17148a9840e95cefbe7cb2d
---
=> 🐛 Bug Report: After clicking "Back" the "Back" CTA in the previous step will remain Purple 

packages/amplication-client/src/Layout/MenuItem.tsx
=> Fix(client): amplication icon's label that leads to homepage doesn't disappear after clicking

packages/data-service-generator/src/admin/static/README.md, packages/data-service-generator/src/admin/static/src/Login.tsx, packages/data-service-generator/src/server/static/README.md, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #5911 
Standardize the `readme.md` of the generated services.
- server: https://github.com/amplication/amplication/tree/docs/generated-services-readme/packages/data-service-generator/src/admin/static
- admin: https://github.com/amplication/amplication/tree/docs/generated-services-readme/packages/data-service-generator/src/server/static
=> feat(data-service-generator): standardize generated services documentation

packages/amplication-client/src/hubSpotChat.tsx
=> fix(client): hubspot auto close

.vscode/launch.json, packages/data-service-generator/src/create-data-service.ts, packages/data-service-generator/src/generate-code.ts, packages/data-service-generator/src/logging.ts, packages/data-service-generator/src/prepare-context.spec.ts, packages/data-service-generator/src/prepare-context.ts
Close: #5936 
This PR brings the following fix:
- broken code generation due to entity named with an uncountable noun
- some dsg log entries not showing resource and build id
=> fix(dsg): issue related to entity named with uncountable nouns

packages/amplication-client/src/VersionControl/LastCommit.tsx
https://www.loom.com/share/435fb32f6e934f54b618a66c49947532
---
=> 🐛 Bug Report: Wrong tooltip in the last commit sha 

packages/amplication-client/src/Resource/git/GitActions/GitProviderConnectionList.tsx, packages/amplication-client/src/util/BillingFeature.ts, packages/amplication-server/src/core/billing/billing.types.ts, packages/amplication-server/src/core/git/git.provider.module.ts, packages/amplication-server/src/core/git/git.provider.service.ts
=> add Stigg to bitbucket feature

packages/amplication-client/src/Layout/PageContent.scss
=> 🐛 Bug Report: gap between the middle and the right parts of the screen 

packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceAuth.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceDatabase.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/ImgSvg.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/LabelDescriptionSelector.tsx
=> preload png icons for wizard

libs/schema-registry/src/lib/create-pr-failure/value.ts, libs/schema-registry/src/lib/create-pr-request/value.ts, libs/schema-registry/src/lib/create-pr-success/value.ts, packages/amplication-client/src/Resource/OverviewTile/OverviewTile.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx, packages/amplication-client/src/VersionControl/BuildSteps.tsx, packages/amplication-client/src/Workspaces/WorkspaceFooter.tsx, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts, packages/amplication-git-pull-request-service/src/pull-request/pull-request.controller.ts, packages/amplication-server/src/core/build/build.service.ts
Close: #5970
fix all git providers remaining text issues
=> Refactor(client): git providers remaining text issues

packages/amplication-client/src/VersionControl/BuildSteps.tsx, packages/amplication-client/src/Workspaces/hooks/useResources.ts, packages/amplication-server/src/core/build/build.service.ts
Close: #5977
fix resource page failed to load
=> Fix(client): resource page failed to load

packages/amplication-cli/src/models.ts, packages/amplication-client/src/Resource/git/AuthResourceWithGit.tsx, packages/amplication-client/src/Resource/git/AuthWithGit.tsx, packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/CreateGitFormSchema/CreateGitFormSchema.spec.ts, packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/CreateGitFormSchema/CreateGitFormSchema.ts, packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.tsx, packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/WizardGitCreateRepo.tsx, packages/amplication-client/src/Resource/git/dialogs/GitDialogsContainer.tsx, packages/amplication-client/src/Resource/git/dialogs/GitRepos/GithubRepos.tsx, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts, packages/amplication-git-utils/src/providers/github/github.service.ts, packages/amplication-git-utils/src/types.ts, packages/amplication-server/src/core/git/dto/inputs/CreateGitRepositoryBaseInput.ts, packages/amplication-server/src/core/git/git.provider.service.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: #5968
fix the mismatch between the client and server regarding the creation of public/private repo
public:
private:
=> Fix(client): bitbucket public repo

packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/WizardGitCreateRepo.tsx
Close: #5969
Fix create repository on service wizard UI issues
IT IS STILL NOT PERFECT, BUT IT'S BETTER THAN IT WAS, AND WE CAN FIX THE OTHER ISSUES AFTER THE RELEASE
=> Fix(client): create repo on service wizard UI issues

packages/amplication-git-utils/src/git-provider.interface.ts, packages/amplication-git-utils/src/providers/bitbucket/bitbucket.service.ts, packages/amplication-git-utils/src/providers/git-cli.ts, packages/amplication-git-utils/src/providers/git.service.ts, packages/amplication-git-utils/src/providers/github/github.service.ts, packages/amplication-git-utils/src/types.ts
Close: #5983
- fix the issue with the promise in getTokenUrl
- fix escaping in gitAuthor
- fix naming for better understanding
- fix the issue with remote origin branch name
=> Fix(git-utils): push to GitHub fails

libs/util/logging/src/lib/logging.spec.ts, libs/util/logging/src/lib/logging.ts, libs/util/nestjs/logging/src/logger.service.ts, packages/amplication-plugin-api/.eslintrc.json, packages/amplication-plugin-api/src/plugin/github-plugin.service.ts, packages/amplication-plugin-api/src/plugin/plugin.service.ts, packages/amplication-plugin-api/src/pluginVersion/npm-plugin-version.service.ts, packages/amplication-plugin-api/src/pluginVersion/pluginVersion.service.ts
Close: #6004
Fix logger library error object handling and update plugin api to fully leverage the logging lib
=> fix(plugin-api): logging to use lib and fix error props

packages/amplication-plugin-api/prisma/migrations/20230516105602_/migration.sql, packages/amplication-plugin-api/prisma/schema.prisma, packages/amplication-plugin-api/src/pluginVersion/base/PluginVersion.ts, packages/amplication-plugin-api/src/pluginVersion/npm-plugin-version.service.ts, packages/amplication-plugin-api/src/pluginVersion/pluginVersion.service.ts
Close: #5851 
Add configuration settings field.
=> feat(plugin-api): add configuration field to settings file.

.github/workflows/README.md, .github/workflows/ci.yml, .github/workflows/deployment.production.yml, .github/workflows/deployment.template.yml, .github/workflows/nx.template.yml, .github/workflows/release.template.yml, ee/packages/amplication-git-pull-service/project.json, ee/packages/amplication-git-push-webhook-service/project.json, nx.json, packages/amplication-build-manager/project.json, packages/amplication-client/project.json, packages/amplication-git-pull-request-service/project.json, packages/amplication-plugin-api/project.json, packages/amplication-server/project.json, packages/amplication-storage-gateway/project.json, packages/data-service-generator/project.json, packages/data-service-generator/src/admin/package-json/package.json, packages/data-service-generator/src/server/package-json/package.json, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap, packages/local-data-service-generator-controller/project.json
Fixes : https://github.com/amplication/amplication-infrastructure-next/issues/50
Addition to: #5975 
Adds support for building and publishing a static website - in this case for the `client`-component. This also incorporates reworking the affected setup by standardizing the naming convention of `deploy` & `package.
=> refactor(client): refactor to static website deployment & workflow changes

packages/amplication-client/src/Workspaces/InviteMember.scss
Fixes: https://github.com/amplication/amplication/issues/6033
---
=> Bug Report: UI/UX - Error Message Alignment and Search Field Width Adjustment

packages/data-service-generator/src/generate-code.ts, packages/data-service-generator/src/utils/get-file-encoding.ts, packages/data-service-generator/src/utils/read-static-modules.ts
=> Fix/4040 static assets are not copied correctly in generated apps admin UI

package-lock.json, package.json, packages/data-service-generator/src/server/package-json/package.json, packages/data-service-generator/src/server/static/src/tests/health/health.service.spec.ts, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> As a dev - I want to finish the remove of nestjs-prisma from generated code

packages/amplication-build-manager/jest.config.ts, packages/amplication-build-manager/src/build-logger/build-logger.controller.spec.ts, packages/amplication-build-manager/src/build-runner/build-runner.controller.spec.ts, packages/amplication-build-manager/src/build-runner/build-runner.service.spec.ts
Close: #5147
In order to facilitate any future code refactoring, we would like to add unit tests to cover logic defined in `amplication-build-manager`.  
The tests should cover the most run code branches ie:
* `build-runner.service.ts`,
* `build-runner.controller.ts`,
* `build-logger.controller.ts`
=> test(build-manager): provide unit tests

packages/amplication-server/src/core/build/build.service.ts
Close: #5997 
Fix pull request comment URL
Before:
After:
=> Fix(server):  pull request comment URL

README.md
fix(documentation): fix typo (server -> serve)
=> fix(documentation): fix typo (server -> serve)

packages/amplication-client/src/Resource/git/GitActions/ExistingConnectionsMenu.scss
Fixes https://github.com/amplication/amplication/issues/6011
https://www.loom.com/share/50b36bf5620b45e39909148bb9f83b82
---
=> 🐛 Bug Report: Wrong text design in select git org dropdown

package-lock.json, package.json
Close: #6189
This pull request adds the `yargs` package to the dev dependencies
=> fix: add missing `yargs` package

packages/amplication-build-manager/README.md
Close: #6236
Updated the discord link in the readme.md file under `amplication/packages/amplication-build-manager/`
=> #6236 - updating discord link under `amplication/packages/amplication-build-manager/README.md`

packages/amplication-client/README.md
=> changed discord link from projects/amplication/packages/amplication-client/README.md 

packages/amplication-client/src/Layout/WelcomePage.tsx
Close: #6239 
Updated the discord link in welcome page
=> updated discord link - Solves #6239

packages/amplication-client/src/Layout/WelcomePage.tsx
Close: #6239
Fixed both the links on welcome.tsx page
=> Update Discord URL in the welcome page

.github/workflows/deployment.production.yml, .github/workflows/nx.template.yml, .github/workflows/release.template.yml
Close: #6411
Improve workflows performance by fixing the cache configuration where needed and remove it from the `nx.template`.
Before: 2min and 45sec - https://github.com/amplication/amplication/actions/runs/5400063284/jobs/9808004395
After: 45sec - https://github.com/amplication/amplication/actions/runs/5400088806/jobs/9808062247
=> chore(ci): fix cache configuration for release deployment and nx templates

packages/amplication-client/src/Resource/OverviewTile/OverviewTile.tsx
=> Revert "🐛 Bug Report: Service Overview shows bad information"

libs/util/git/src/providers/git-cli.ts
Part of: #6351
Reorder GitCli methods by name
=> refactor(git): reorder gitcli methods

package.json
Reverts amplication/amplication#6383
=> Revert "chore(deps-dev): bump @storybook/builder-vite from 0.2.7 to 7.0.23"

packages/amplication-client/src/Resource/resourceSettings/GenerationSettingsForm.tsx
modified:   packages/amplication-client/src/Resource/resourceSettings/GenerationSettingsForm.tsx
Close: #6230 
Service settings not reloading issue solved.
=> Service Settings not saved solved

package.json
Reverts amplication/amplication#6854
=> Revert "chore(deps): bump @mui/material from 5.14.7 to 5.14.8"

.github/workflows/release.production.yml
Reverts amplication/amplication#6966
=> Revert "fix(ci): add force push for release production commit step"

packages/amplication-server/src/core/entity/reservedNames.ts
ISSUE-:#7292
Closes: #7294 
Added "field" to the RESERVED_NAMES array in the server.
=> Added:the word "field" to the reserved words.

README.md
Close: #7372
I have noticed a small grammar mistake in **README.md** file inside section "**Contributing**"
"**please create a bugreport.**"  should be "**please create a bug report.**"
screenshot
=> Update README.md - fixed small grammar mistake inside  section "Contributing".

packages/data-service-generator/src/server/secrets-manager/static/base/secretsManager.service.base.spec.template.ts, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #7457
Fix generated tests that were always failing.
=> fix(dsg): failing generated test for secret manager base provider

packages/amplication-build-manager/src/build-runner/build-runner.service.ts, packages/amplication-server/src/core/build/build.controller.ts
Close: #7473
In this PR, a fix for bad formatted kafka events for failed code generation and add a temporary to the server that will skip processing bad formatted failed code generation events.
=> fix(build-manager): from producing bad kafka event for failed code generation

packages/amplication-plugin-api/prisma/migrations/20231123104044_remove_user_entity/migration.sql, packages/amplication-plugin-api/project.json
Close:  #7451
Add leftover from #7453
=> fix(plugin-api): nx target for prisma db clean and add delete user migration

packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap
Close: #7567
Update snapshots of `auth-jwt` plugin after the change for custom actions
=> fix(dsg): update jwt snapshot after updating the plugin with custom actions

packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts, packages/amplication-server/src/core/billing/billing.service.types.ts, packages/amplication-server/src/core/git/git.provider.service.ts, packages/amplication-server/src/core/project/project.service.ts
Close: https://github.com/amplication/private-issues/issues/85
Add new limitation checks to the build /commit
=> feat(server): update limitation checks on the commit action

packages/amplication-server/src/core/project/project.service.spec.ts, packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts
Part of: https://github.com/amplication/private-issues/issues/76
- check if billing is enabled
- block the creation of a service and a project when the user exceeded his plan usage
- changed `isUnderLimitation` on the resource service to returns always true for now
=> Feat(server): end of trial block create service and project based on license

packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts, packages/amplication-server/src/core/project/project.service.spec.ts, packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/errors/BillingLimitationError.ts, packages/amplication-server/src/errors/graphql/graphql-billing-limitation-error.ts, packages/amplication-server/src/filters/GqlResolverExceptions.filter.spec.ts, packages/amplication-server/src/filters/GqlResolverExceptions.filter.ts
Close: https://github.com/amplication/private-issues/issues/75
Enhance the billing limitation graphql error including the originating billing entitlement that was causing the limitation error. 
=> chore(server): enhance billing limitation error details

packages/amplication-client/src/Resource/git/GitActions/GitProviderConnection.tsx
part of: https://github.com/amplication/private-issues/issues/77
https://github.com/amplication/private-issues/issues/77#issuecomment-1854223267
=> fix(client): github button

packages/amplication-client/.env, packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Purchase/PromoBanner.tsx, packages/amplication-client/src/Workspaces/hooks/useUpgradeButtonData.ts
Close: #7646
- set billing disabled by default in client
- fix places that depends on subscription to return default free plan state
=> fix(client): check if billing not enabled and return free plan state

packages/amplication-client/src/Resource/git/GitActions/GitProviderConnection.tsx, packages/amplication-client/src/Resource/git/GitActions/GitProviderConnectionList.tsx
Close: https://github.com/amplication/private-issues/issues/102
Update aws code commit git provider connection component to follow the current UX
=> fix(client): aws code commit button style

packages/amplication-client/.env
part of: https://github.com/amplication/amplication/issues/7646
add the billing client key
=> fix(client): billing key

.gitignore, .nxignore, packages/gpt-gateway-admin/.env, packages/gpt-gateway-admin/Dockerfile, packages/gpt-gateway-admin/package-lock.json, packages/gpt-gateway-admin/package.json, packages/gpt-gateway-admin/project.json, packages/gpt-gateway-admin/scripts/entrypoint.sh, packages/gpt-gateway-admin/scripts/inject-variables.js, packages/gpt-gateway-admin/src/Login.tsx, packages/gpt-gateway-admin/src/data-provider/graphqlDataProvider.ts, packages/gpt-gateway-admin/src/env.ts, packages/gpt-gateway-admin/tsconfig.app.json, packages/gpt-gateway-admin/tsconfig.json, packages/gpt-gateway-admin/tsconfig.spec.json
Close: https://github.com/amplication/private-issues/issues/104
This PR is configuring the `gpt-gateway-admin` for deployment:
- add nx configurations for `gpt-gateway-admin`
- add scripts to allow environment interpolation at container start time 
=> chore(gpt-gateway-admin): fix configurations to allow deployment to cloud environments

packages/amplication-client/src/Components/CreateResourceButton.tsx, packages/amplication-client/src/Components/FeatureIndicator.tsx, packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/ModuleActions/ModuleActionsEnabled.tsx, packages/amplication-client/src/Project/AddNewProject.tsx, packages/amplication-client/src/Resource/codeGeneratorVersionSettings/CodeGeneratorVersionForm.tsx, packages/amplication-client/src/Resource/git/GitActions/GitProviderConnection.tsx, packages/amplication-client/src/Workspaces/InviteMember.tsx
Close: https://github.com/amplication/private-issues/issues/94
update tooltip text for enterprise trial
=> refactor(client): change tooltip text for enterprise trial

libs/schema-registry/src/lib/user-build/value.ts, packages/amplication-server/src/core/build/build.service.ts
=> add resource name to build complete message

packages/amplication-client/src/Components/FeatureIndicator.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/NewEntityField.tsx, packages/amplication-client/src/Roles/NewRole.tsx
part of: https://github.com/amplication/private-issues/issues/94
=> Fix(client): enterprise tooltip text and alignment

packages/amplication-server/src/core/entity/entity.service.spec.ts, packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/core/subscription/subscription.service.ts
Part of: https://github.com/amplication/private-issues/issues/90
- emit update project and resource licensed field on promotional entitlement
- refactor logic of blocked features on service, such as add entity, add entity field, add role - checking first if the project is not licensed because if the project is not licensed, the resurce (service) should not be licensed
- update entity tests
=> refactor(server): emit update project and service licensed field on promotional entitlement

packages/amplication-server/src/core/subscription/subscription.service.ts
part of: https://github.com/amplication/private-issues/issues/90
- fix stigg webhook promotional entitlement emittion
- add debug logger
=> fix(server): stigg webhook promotionalEntitlement and add debug logging

packages/amplication-server/src/core/subscription/dto/UpdateStatusDto.ts, packages/amplication-server/src/core/subscription/subscription.service.ts
part of: https://github.com/amplication/private-issues/issues/90
=> fix(server): add debug logging for subscription

packages/amplication-server/src/core/subscription/subscription.service.ts
Part of: https://github.com/amplication/private-issues/issues/90
cleanup subscription debug logging
=> chore(server): cleanup subscription debug logging

packages/amplication-client/src/Plugins/PluginTree.tsx, packages/amplication-client/src/Plugins/PluginsCatalog.tsx, packages/amplication-client/src/Plugins/PluginsCatalogItem.scss, packages/amplication-client/src/Plugins/PluginsCatalogItem.tsx
=> fix categories chip on plugins items

packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap
Close: https://github.com/amplication/amplication/issues/7711
=> fix(dsg): update snapshots

packages/amplication-client/src/ModuleActions/ModuleActionsDisabled.tsx, packages/amplication-client/src/ModuleActions/ModuleActionsEnabled.tsx
Close: https://github.com/amplication/amplication/issues/7715
=> fix(client): custom action indicator for enterprise not in trial

packages/amplication-client/src/Plugins/PluginsCatalogItem.scss, packages/amplication-client/src/Plugins/PluginsCatalogItem.tsx
=> fix(client): fix L&F for plugins page according to design

ee/packages/git-sync-manager/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/data-service-generator/src/models.ts
=> feat(amplication): update models

packages/amplication-client/src/Plugins/PluginsCatalogItem.tsx
=> fix installed plugins refresh

packages/amplication-client/.env.production, packages/amplication-client/src/util/analytics.ts
=> fix(client): HF back to segment analytics

packages/amplication-server/src/core/block/block.service.ts, packages/amplication-server/src/core/block/blockType.service.spec.ts, packages/amplication-server/src/core/block/blockType.service.ts, packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.ts
=> cancel merge settings

packages/amplication-prisma-db/prisma/manual-data-migrations/20231228_fix_entity_field_id_searchable.sql
=> chore(db): add data migration to fix non searchable Id entity fields

packages/amplication-client/src/Plugins/hooks/usePlugins.ts
=> fix pluginId bug

packages/amplication-server/src/core/entity/reservedNames.ts
part of: https://github.com/amplication/private-issues/issues/108
=> fix(server): add app as reserved word

packages/gpt-gateway/src/main.ts
Close: #7741
Fixes issue related to application logger not being properly configured in cloud environments
=> fix(gpt-gateway): application logger

packages/data-service-generator/src/admin/static/Dockerfile, packages/data-service-generator/src/admin/static/configuration/nginx.conf
=> chore(client): align port configuration admin ui

ee/packages/git-sync-manager/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/private-issues/issues/116
=> chore: add missing models.ts field

packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/core/moduleAction/moduleAction.service.spec.ts, packages/amplication-server/src/core/moduleAction/moduleAction.service.ts
=> Fix(server): update default actions on relation type change

packages/amplication-client/src/Components/UserBadge.tsx, packages/amplication-client/src/Profile/ProfileForm.tsx, packages/amplication-client/src/Profile/accountQueries.ts, packages/amplication-server/src/core/account/account.service.ts, packages/amplication-server/src/core/user/user.service.spec.ts, packages/amplication-server/src/core/user/user.service.ts
Close: https://github.com/amplication/private-issues/issues/114
- use the preview email for preview users
- refacotor current "user" (account) and create hook + use the right data for previeww user analytics
=> refactor(server+client): analytics for preview user

libs/util/billing-types/src/lib/billing-feature.types.ts, packages/amplication-client/src/Components/CreateResourceButton.tsx, packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Components/LicenseIndicatorContainer.scss, packages/amplication-client/src/Components/LicenseIndicatorContainer.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/NewEntityField.tsx, packages/amplication-client/src/Project/AddNewProject.tsx, packages/amplication-client/src/Roles/NewRole.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelectorList.tsx, packages/amplication-client/src/Workspaces/hooks/useUpgradeButtonData.ts
Close: https://github.com/amplication/private-issues/issues/112
- update `FeatureIndicatorContainer` to handle logic around preview plans
- create a new component `LicenseIndicatorContainer` to manage boolean entitlement types that blocks features and for the licensed property indicator on projects and services
- refactor the components that use the license property to use the component
- use the new component for block build and workspace creation
=> Feat(client): preview account limitations UI

libs/util/billing-types/src/lib/billing-feature.types.ts, packages/amplication-server/src/core/project/project.service.spec.ts, packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/core/workspace/workspace.resolver.ts, packages/amplication-server/src/core/workspace/workspace.service.spec.ts, packages/amplication-server/src/core/workspace/workspace.service.ts
Close: https://github.com/amplication/private-issues/issues/112
- block creation of a workspace
- block commit (build) 
- both "create workspace" and "build" are boolean entitlements that if the `hasAccess` is true - that means that it needs to be blocked.
- block invite a member based on usage (metered entitlement). That was already implemented but just a small refactoring - moving the logic to a separated function and check for the current usage and the limit instead of the hasAccess.
=> Feat(server): preview account limitations

packages/gpt-gateway-admin/project.json
Close: #7770
Configure `gpt-gateway-admin` nx install target to NOT BE CACHABLE to avoid issues related to installed deps and cache
=> chore(gpt-gateway-admin): avoid caching project install target to avoid cache issues

packages/gpt-gateway-admin/.env, packages/gpt-gateway-admin/src/pages/Dashboard.tsx, packages/gpt-gateway/providers/openai/openai.service.ts, packages/gpt-gateway/src/conversationType/conversationType.resolver.ts, packages/gpt-gateway/src/conversationType/conversationType.service.ts, packages/gpt-gateway/src/conversationType/dto/GetConversation.dto.ts, packages/gpt-gateway/src/conversationType/dto/GetConversationInput.dto.ts
Close: #7722
This PR introduce a new mutation to facilitate manual ai prompt testing.
Additional instructions regarding how to perform some promt testing, are available here: https://www.notion.so/amplication/Debugging-GPT-Gateway-prompt-c4686162615c4a6f9a21629447e01098
=> chore(gpt-gateway-admin): add conversation trigger through graphql for debugging purposes

packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/auth/auth.service.ts
Close: https://github.com/amplication/private-issues/issues/119
=> fix(server): remove redundant code

packages/amplication-client/src/ModuleActions/ModuleActionsDisabled.tsx, packages/amplication-server/.env
Close: https://github.com/amplication/private-issues/issues/118
=> chore: update contact us email to a new link

packages/amplication-server/src/core/auth/auth.service.ts
Close: https://github.com/amplication/private-issues/issues/121
on a preview account, while we bootstrapping the new user, set the generate admin-ui to false and the path to an empty string (it can't be null)
=> refactor(server): update admin-ui settings for preview account to false

packages/data-service-generator/src/server/resource/service/create-service.ts
Close: https://github.com/amplication/amplication/issues/7790
remove the logic that removes the action on the service when the user disabled it
=> fix(dsg): remove the logic that removes the action on the service when the user disabled it

packages/data-service-generator/src/server/resource/service/create-service.ts
Part of: https://github.com/amplication/amplication/issues/7790
=> fix(dsg): use the right logger

packages/data-service-generator/src/server/resource/grpc-controller/create-grpc-controller.ts, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap
Close: #7795 
map methods names by context entityActionsMap values.
=> fix(DSG): map methods names by context entityActionsMap values.

packages/amplication-code-gen-types/package.json, packages/amplication-code-gen-types/src/plugins.types.ts, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap
Close: #7795
add entityActions field to context.
=> fix(code-gen-types): add entityActions field to context

libs/schema-registry/src/index.ts, libs/schema-registry/src/lib/ai-conversion-complete/value.ts, libs/schema-registry/src/lib/ai-conversion-start/value.ts, packages/amplication-prisma-db/prisma/migrations/20240110135527_add_break_the_monolith_tables/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/gpt-gateway/src/conversationType/conversationType.resolver.ts, packages/gpt-gateway/src/conversationType/conversationType.service.ts, packages/gpt-gateway/src/conversationType/dto/GetConversation.dto.ts, packages/gpt-gateway/src/kafka/kafka.controller.ts, packages/gpt-gateway/src/kafka/kafka.producer.service.ts, packages/gpt-gateway/src/kafka/topics.ts
Close: https://github.com/amplication/private-issues/issues/110
Add actionId to ai conversation topics to enable polling support on server 
=> feat(gpt-gateway): add actionid to ai conversation topics 

packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Components/LicenseIndicatorContainer.tsx, packages/amplication-client/src/Workspaces/InviteMember.tsx
Close: https://github.com/amplication/private-issues/issues/123
=> fix(client): preview account tooltips

packages/amplication-server/src/core/auth/auth.controller.ts, packages/amplication-server/src/core/auth/auth.service.ts
=> redirect auth0 signup to welcome page on Amplication

packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/private-issues/issues/125
=> fix(server): send git organization name and not repo name

packages/amplication-server/src/core/workspace/workspace.service.ts
Close: https://github.com/amplication/amplication/issues/7835
`usageLimit` is undefined when you don't have limitation on a metered entitlement.
so when it's undefind we return ture (can invite), otherwise, we calculate the usage and limit
=> fix(server): can invite member claculation

packages/data-service-generator/src/prepare-context.ts, packages/data-service-generator/src/server/resource/controller/create-controller.ts, packages/data-service-generator/src/server/resource/resolver/create-resolver.ts, packages/data-service-generator/src/server/resource/service/create-service.ts, packages/data-service-generator/src/server/resource/test/create-controller-spec.ts, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-disabled-module.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-default-actions.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/create-data-service-with-disabled-module.spec.ts
=> Feat(DSG): do not generate actions for disabled modules

packages/amplication-server/src/core/ai/prompt-manager.service.spec.ts, packages/amplication-server/src/core/ai/prompt-manager.service.ts, packages/amplication-server/src/core/ai/prompt-manager.types.ts
Close: #7821
Update prompt input generation
=> chore(server):  update prompt input and output types

packages/amplication-server/src/core/serviceSettings/serviceSettings.service.ts
Related: https://github.com/amplication/amplication/pull/7805
- Put comment in proper place as told :- https://github.com/amplication/amplication/pull/7805#discussion_r1451717135
=> chore: put comment in proper place

packages/amplication-server/src/core/auth/auth.module.ts, packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/workspace/workspace.service.spec.ts
Part of: #7839
Cleanup dependencies after this refactoring: https://github.com/amplication/amplication/pull/7838
=> refactor(server): remove unused dependencies providers and mocks

packages/amplication-server/src/core/block/block.service.ts, packages/amplication-server/src/core/block/block.util.spec.ts, packages/amplication-server/src/core/block/block.util.ts
=> fixed bug on mergeAllSettings

packages/amplication-client/src/Plugins/PluginTree.tsx, packages/amplication-client/src/Plugins/PluginsCatalog.tsx, packages/amplication-client/src/Plugins/PluginsCatalogItem.tsx, packages/amplication-client/src/routes/resourceTabRoutes.tsx, packages/amplication-client/src/routes/routesUtil.tsx
=> fix bug/two plugin routes had been render on the same page

packages/amplication-client/src/Entity/EntityList.tsx
Close: #6549 
There may be no installed plugins in a newly generated PR. Therefore, the following lines give an error:- 
https://github.com/amplication/amplication/blob/ba64ad704d4eb4b9492928f9ca6fe9f8e2e73c21/packages/amplication-client/src/Entity/EntityList.tsx#L82-L86
[![Check Video](https://cdn.loom.com/sessions/thumbnails/faf8d5e742b84b3c98c11e0b5893590d-with-play.gif)](https://www.loom.com/share/faf8d5e742b84b3c98c11e0b5893590d?sid=4910ffca-3aac-4c65-a197-07cbcb8b4f17 "Check Video")
=> fix: there may be no plugins installed

packages/amplication-server/src/core/workspace/workspace.controller.ts, packages/amplication-server/src/core/workspace/workspace.service.ts
Close: https://github.com/amplication/private-issues/issues/129
=> chore(server): add chunk size to data migration

libs/ui/design-system/src/lib/components/CollapsibleList/CollapsibleList.scss, libs/ui/design-system/src/lib/components/CollapsibleList/CollapsibleList.stories.tsx, libs/ui/design-system/src/lib/components/CollapsibleList/CollapsibleList.tsx, libs/ui/design-system/src/lib/components/CollapsibleList/CollapsibleListItem.scss, libs/ui/design-system/src/lib/components/CollapsibleList/CollapsibleListItem.tsx, libs/ui/design-system/src/lib/index.ts, packages/amplication-client/src/VersionControl/PendingChange.scss, packages/amplication-client/src/VersionControl/PendingChange.tsx, packages/amplication-client/src/VersionControl/PendingChangeContent.tsx, packages/amplication-client/src/VersionControl/PendingChangeServiceTopics.tsx, packages/amplication-client/src/VersionControl/PendingChanges.scss, packages/amplication-client/src/VersionControl/PendingChanges.tsx, packages/amplication-client/src/VersionControl/PendingChangesList.scss, packages/amplication-client/src/VersionControl/PendingChangesList.tsx, packages/amplication-client/src/VersionControl/PendingChangesListGroup.scss, packages/amplication-client/src/VersionControl/PendingChangesListGroup.tsx, packages/amplication-client/src/Workspaces/hooks/usePendingChanges.ts
=> feat(client):group pending changes by type

libs/util/billing-types/src/lib/billing-feature.types.ts, packages/amplication-client/src/Entity/EntityList.tsx
=> bug(client): remove irrelevant entity count warning message

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Close: https://github.com/amplication/private-issues/issues/117
=> chore(client): update tooltip text

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Part of: https://github.com/amplication/private-issues/issues/117
=> fix(client): do not logout preview account on generate code

.github/workflows/nx.template.yml
=> chore: fix nx ci template install step

.github/workflows/nx.template.yml
=> chore: update bun install to leverage default behaviours

packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/queries/modelsQueries.ts
Close: #7693 
reload localStorage when projectId changed,
=> fix(client): reload localStorage when projectId changed

packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx
Close: #7890 7890
Remove the reload for projectId changed.
=> fix(client): localStorage refresh crashed

.github/workflows/deployment.container.template.yml, .github/workflows/deployment.static.template.yml
=> ci: fix aws-credentials action version

packages/amplication-server/jest.config.ts, packages/amplication-server/src/core/auth/auth.service.spec.ts
Fixes: https://github.com/amplication/private-issues/issues/105
add tests for new business email flow feature
=> test(server): add tests for new business email flow feature

.github/workflows/ci.yml
Close: #7896
fix the obsoleted command option --all
https://github.com/amplication/amplication/actions/runs/7724892203/job/21057989007#step:9:14
=> ci: fix the obsoleted command option --all

libs/ui/design-system/src/lib/components/Snackbar/Snackbar.scss, libs/ui/design-system/src/lib/components/Snackbar/Snackbar.tsx, libs/ui/design-system/src/lib/index.ts
=> Feat snackbar style

packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx
=> feat(client):model organizer messages

packages/amplication-server/src/core/resource/resourceBtm.service.spec.ts, packages/amplication-server/src/core/resource/resourceBtm.service.ts
Close: https://github.com/amplication/amplication/issues/7913
filter out services with no data models from the prompt result (btm recommendation)
=> fix(server): filter out services with no data models

tutorials/event-management-application.md
This Pull Request introduces an exciting addition to the project, transforming it into an Event Management application.
=> Addition of New Tutorial - Event Management

packages/amplication-client/src/Project/ArchitectureConsole/CreateResource.tsx
=> chore(client): remove service description for new services created in the Architecture screen

libs/ui/design-system/src/lib/components/Snackbar/Snackbar.stories.tsx
=> chore(design-system): allow playing with snackbar types in storybook

packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/queries/modelsQueries.ts
Part of: https://github.com/amplication/amplication/issues/7901
=> fix(client): usage of start redesign mutation

packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Components/RedesignResourceButton.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ArchitectureConsole.tsx
Close: #7949
Update the tooltip message for full enterprise and for trial.  
=> fix(client): update title for full enterprise

packages/amplication-server/src/core/resource/resource.service.ts
Close: #7892
Connect gitRepository to a created service from Architecture by project configuration settings.
=> fix(server): connect gitRepository to created service from Architecture

packages/amplication-server/src/core/auth/auth.controller.ts, packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/auth/auth.service.ts, packages/amplication-server/src/core/auth/types.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.types.ts
Fixes: amplication/private-issues#131
Added new tracking event for CompleteEmailSignup. (step 3 of amplication/private-issues#131)
:warning: This PR depends on id token custom claims implemented here https://github.com/amplication/auth0/pull/14 
=> chore(server): add complete signup email event

packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx
part of: https://github.com/amplication/amplication/issues/7949
add check for the subscription plan in order to make sure that is full enterprise (without trail)
=> fix(client): feature indicator container text and link text

packages/amplication-server/src/core/prismaSchemaParser/prismaSchemaParser.service.spec.ts, packages/amplication-server/src/core/prismaSchemaParser/schema-utils.ts
Close: https://github.com/amplication/amplication/issues/7724
Fix relations with name that also have the same field name and handle the self relation in a differnet way.
`created_by_user` field name exists on both models and have the same relation name. This PR fixes the error described in the issue.
```schema
model Users {
id                   String              @id @default(cuid()) @map("_id")
created_by_user      crm_Opportunities[] @relation(name: "created_by_user_relation")
assigned_opportunity crm_Opportunities[] @relation(name: "assigned_to_user_relation")
}
model crm_Opportunities {
id               String  @id @default(cuid()) @map("_id")
assigned_to      String?
created_by       String?
assigned_to_user Users?  @relation(name: "assigned_to_user_relation", fields: [assigned_to], …
```
=> fix(server): relation name with the same field name

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
=> chore(client): notification button should follow the notification URL for all notification types

packages/amplication-server/src/core/resource/resource.service.ts
Close: #7968 
Update service settings values according to the original resource.
=> feat(server): improve serviceSettings =>

libs/util/billing-types/src/lib/billing-addons.types.ts, packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts
Close: https://github.com/amplication/private-issues/issues/137
=> feat(server): add BTM addon for trial users

packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/private-issues/issues/138
=> fix(server): recreate movedEntitiesByResource after targetServiceId was updated

packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap
Close: #7668
Update snaphost testing to match new generated code related to the latest version of auth plugins
https://github.com/amplication/plugins/pull/315
=> test(dsg): update snapshot

libs/ui/design-system/src/lib/components/ConfirmationDialog/ConfirmationDialog.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.scss, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/queries/modelsQueries.ts
Close: #7820 
adding name collision validation when moving an entity to another service.
=> feat(client): adding name collision validation when moving an entity to another service

packages/amplication-server/src/core/entity/entity.service.ts
Close: #7956 
add Id to fieldName for one relation side.
=> fix(server): add Id to fieldName for one relation side

packages/amplication-client/src/Project/ArchitectureConsole/CreateResource.tsx
Close: #7962 
add info message in create service dialog
=> feat(client):add info message in create service dialog

packages/amplication-client/src/Project/ArchitectureConsole/ModelsTool.tsx
Close: #7961 
update fetch changes dialog message.
=> refactor(client): update fetch changes message

packages/amplication-client/src/Project/ArchitectureConsole/ApplyChangesNextSteps.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/PendingChanges.tsx
Close: #7959 
Add commit limit validation in BTM.
=> feat(client): commit validation BTM

packages/amplication-client/src/Project/ArchitectureConsole/nodes/modelGroupNode.tsx
Close: #7964
remove drag btn from modelGroup
=> fix(client): remove drag btn from modelGroup

ee/packages/git-sync-manager/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Resource/break-the-monolith/BreakTheMonolith.tsx, packages/amplication-client/src/Resource/break-the-monolith/queries.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/amplication-server/src/core/resource/dto/BreakServiceToMicroservicesResult.ts, packages/amplication-server/src/core/resource/resourceBtm.service.spec.ts, packages/amplication-server/src/core/resource/resourceBtm.service.ts, packages/amplication-server/src/core/resource/resourceBtm.types.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/private-issues/issues/141
- update ai user prompt based on the requirements
- update the result based on the requirements
- update modles and client
- update tests
=> refactor(server+client): update ai user prompt and results to client

packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx
Close: #7960 
Add auth-entity validation when trying to move it to another service.
=> feat(client): add auth-entity validation

packages/amplication-client/src/Resource/break-the-monolith/CreateBTMPreviewEnvironmentPage.tsx, packages/amplication-client/src/Resource/break-the-monolith/CreateEntitiesFormPredefinedSchema.tsx, packages/amplication-client/src/Resource/break-the-monolith/SelectPreviewEnvPage.tsx, packages/amplication-client/src/User/SignupPreviewAccount.tsx, packages/amplication-client/src/User/hooks/useSignupPreviewAccount.ts, packages/amplication-client/src/routes/appRoutes.tsx, packages/amplication-client/src/routes/resourceRoutes.tsx
Close:
https://github.com/amplication/private-issues/issues/147
https://github.com/amplication/private-issues/issues/148
=> feat(client): Preview env flow

libs/ui/design-system/src/lib/components/Panel/Panel.scss, libs/ui/design-system/src/lib/components/Panel/Panel.stories.tsx, libs/ui/design-system/src/lib/components/Panel/Panel.tsx
Close: https://github.com/amplication/amplication/issues/8020
=> feat(design-system): add top border with theme color to panels

libs/ui/design-system/src/lib/components/FlexItem/FlexItem.scss, libs/ui/design-system/src/lib/components/List/List.scss, libs/ui/design-system/src/lib/components/Panel/Panel.scss, libs/ui/design-system/src/lib/components/Panel/Panel.stories.tsx, libs/ui/design-system/src/lib/components/Panel/Panel.tsx
=> feat(design-system):non clickable footer for panels

packages/amplication-client/src/VersionControl/Commit.tsx
=> chore(client): change commit button text

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/util/analytics-events.types.ts
Close: https://github.com/amplication/private-issues/issues/133
=> feat(client): add temporary MWC banner

packages/amplication-server/src/core/user/dto/NotifyUseFeatureAnnouncementInput.ts, packages/amplication-server/src/core/user/user.controller.ts, packages/amplication-server/src/core/workspace/dto/CreateWorkspacesResourcesDefaultCustomActionsMigrationInput.ts, packages/amplication-server/src/core/workspace/workspace.controller.ts
Close: #7969
Fix API params to body param
=> fix(server): fix API params to body param

packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.scss, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx
Close: #7960
Change the auth-entity error message description.
=> refactor(client): change the auth-entity error message description.

packages/amplication-client/src/Project/ArchitectureConsole/CreateResource.tsx
=> chore(client): change order of text in the dialog

packages/notification-service/src/app.controller.ts
=> chore(notifications): add handler for the feature announcement topic

packages/amplication-server/src/core/user/user.service.ts
Add the missing data from prisma into the notification
Close: #7969 
=> fix(server): add relevant data to notification message

packages/amplication-client/src/VersionControl/PendingChanges.tsx
Close: https://github.com/amplication/private-issues/issues/152
=> refactor(client): preview ueer - hide commit

packages/amplication-server/src/core/user/user.service.ts
=> fix(server): filter our deleted projects

libs/ui/design-system/src/lib/components/Panel/Panel.scss, libs/ui/design-system/src/lib/components/Panel/Panel.stories.tsx, libs/ui/design-system/src/lib/components/Panel/Panel.tsx
=> fix(client):revert panel changes for clickable footer

packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizerToolbar.tsx, packages/amplication-client/src/Project/ArchitectureConsole/hooks/useModelOrganizer.tsx, packages/amplication-client/src/Resource/break-the-monolith/BtmButton.tsx
Part of: https://github.com/amplication/amplication/issues/7819
In the Break the Monolith with AI - add a confirmation dialog before loading the recommendation result to inform the user that continuing with this process can override existing data that has not persisted yet.
=> client(client): add confirmation dialog for btm button

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceBanner.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Close: https://github.com/amplication/private-issues/issues/133
=> feat(client): add option to override local storage key for workspace banner

packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/auth/auth.service.ts
Close: https://github.com/amplication/amplication/issues/8026
Move the logic that convert the preview user to a regular new user with a free trial from `completeSignupPreviewAccount` to `loginOrSignUp` because the "conversion" should be only after the user actually clicks on the reset password link from the email
=> refactor(server): preview user - complte signup after reset password

packages/amplication-server/src/core/resource/resourceBtm.service.spec.ts, packages/amplication-server/src/core/resource/resourceBtm.service.ts
Close: https://github.com/amplication/amplication/issues/8029
=> feat(server): add limitatin for break the monolith with gpt

packages/amplication-client/src/Resource/break-the-monolith/BtmButton.tsx
=> feat(client):btm confirmation on changes only

packages/amplication-client/src/Resource/break-the-monolith/BreakTheMonolith.scss
Close: https://github.com/amplication/amplication/issues/8087
move the loader to the middle of the page
=> fix(client): loader position after break the monolith full screen

packages/amplication-client/src/Resource/break-the-monolith/BtmButton.tsx, packages/amplication-client/src/Resource/break-the-monolith/SelectPreviewEnvPage.tsx
Close: https://github.com/amplication/amplication/issues/8086
- remove the close button from the modal after breaking a monolith
- remove the close button from the modal only for preview users after break a monolith
=> fix(client): remove close button from modal for preview user

packages/amplication-client/src/Resource/break-the-monolith/CreateEntitiesFormPredefinedSchema.scss, packages/amplication-client/src/Resource/break-the-monolith/CreateEntitiesFormPredefinedSchema.tsx
Close: https://github.com/amplication/amplication/issues/8074
Update the description text on the "choose a monolith to break" page based on requirements.
=> fix(client): description on choose a monolith to break

packages/amplication-client/src/Resource/break-the-monolith/CreateEntitiesFormPredefinedSchema.tsx, packages/amplication-client/src/User/hooks/useSignupPreviewAccount.ts
Close: https://github.com/amplication/amplication/issues/8072
1. disable the Break button after clicking
2. disable revisiting the schema page after the button is clicked
=> Fix(client): disable break and revisit after click

packages/amplication-client/src/Resource/break-the-monolith/BreakTheMonolith.scss, packages/amplication-client/src/Resource/break-the-monolith/BreakTheMonolith.tsx
Close: https://github.com/amplication/amplication/issues/8073 https://github.com/amplication/private-issues/issues/149
=> feat(client):show the description of new services in the BTM results 

packages/amplication-server/src/core/gpt/gpt.service.spec.ts, packages/amplication-server/src/core/gpt/gpt.service.ts, packages/amplication-server/src/core/gpt/gpt.types.ts, packages/amplication-server/src/core/resource/constants.ts, packages/amplication-server/src/core/resource/resourceBtm.resolver.ts, packages/amplication-server/src/core/resource/resourceBtm.service.spec.ts, packages/amplication-server/src/core/resource/resourceBtm.service.ts, packages/amplication-server/src/core/userAction/userAction.resolver.spec.ts, packages/amplication-server/src/core/userAction/userAction.resolver.ts, packages/amplication-server/src/core/userAction/userAction.service.ts
Fixes: https://github.com/amplication/private-issues/issues/155
- Fix issue related to storing of gpt responses. These responses are string and they should not be stored as parsed JSON (otherwise errors will happen)
- Improve error message for bad formatted ai suggestions
- refactor resourcesBtm service to not use userActionService dependency
=> chore(server): improve error handling in ai suggestion flow

packages/amplication-client/src/Resource/break-the-monolith/hooks/useBtmService.ts
Close: #8092
Stop polling in case of exceptions
=> fix(client): ai suggestion infinite polling in case of errors

packages/gpt-gateway/providers/openai/openai.service.ts, packages/gpt-gateway/src/template/template.service.spec.ts, packages/gpt-gateway/src/template/template.service.ts
Close: #8091
Fix type and handling of custom template params and add fallback to default in case of bad input.
=> fix(gpt-gateway): template custom params issue

packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx
Close: #8113
Fix issue related to missing subscription prop on current workspace.
This PR is intentially targeting `master` to allow contributors to keep running local app.
=> fix(client): issue related to undefined subscriptionPlan on current workspace

packages/data-service-generator/src/server/create-main/main.with-bigint.template.ts, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-disabled-module.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-default-actions.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> fix(dsg):add missing ts-ignore comment

packages/amplication-client/src/ModuleActions/ModuleActions.tsx, packages/amplication-client/src/ModuleActions/ModuleActionsAndTypes.tsx, packages/amplication-client/src/ModuleDto/ModuleDto.tsx, packages/amplication-client/src/ModuleDto/ModuleDtos.tsx, packages/amplication-client/src/ModuleDto/NewModuleDto.tsx, packages/amplication-client/src/ModuleDto/NewModuleDtoEnum.tsx, packages/amplication-client/src/ModuleDto/hooks/useModuleDto.tsx, packages/amplication-client/src/ModuleDto/queries/moduleDtosQueries.ts, packages/amplication-client/src/ModuleDtoProperty/ModuleDtoProperty.tsx, packages/amplication-client/src/Modules/ModulesHeader.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizerToolbar.tsx, packages/amplication-client/src/Resource/ResourceOverview.tsx, packages/amplication-client/src/VersionControl/PendingChangeContent.tsx
=> feat(client):custom DTO Enums

ee/packages/git-sync-manager/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/code-gen-types.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-git-pull-request-service/src/models.ts, packages/amplication-server/src/core/moduleDto/dto/CreateModuleDtoEnumMemberArgs.ts, packages/amplication-server/src/core/moduleDto/dto/DeleteModuleDtoEnumMemberArgs.ts, packages/amplication-server/src/core/moduleDto/dto/ModuleDto.ts, packages/amplication-server/src/core/moduleDto/dto/ModuleDtoEnumMember.ts, packages/amplication-server/src/core/moduleDto/dto/ModuleDtoEnumMemberCreateInput.ts, packages/amplication-server/src/core/moduleDto/dto/ModuleDtoEnumMemberUpdateInput.ts, packages/amplication-server/src/core/moduleDto/dto/ModuleDtoUpdateInput.ts, packages/amplication-server/src/core/moduleDto/dto/UpdateModuleDtoEnumMemberArgs.ts, packages/amplication-server/src/core/moduleDto/dto/WhereEnumMemberUniqueInput.ts, packages/amplication-server/src/core/moduleDto/moduleDto.resolver.ts, packages/amplication-server/src/core/moduleDto/moduleDto.service.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
=> feat(server):module DTO Enum members

packages/amplication-client/src/ModuleDto/ModuleDto.tsx, packages/amplication-client/src/ModuleDto/queries/moduleDtosQueries.ts, packages/amplication-client/src/ModuleDtoEnumMember/DeleteModuleDtoEnumMember.tsx, packages/amplication-client/src/ModuleDtoEnumMember/ModuleDtoEnumMember.tsx, packages/amplication-client/src/ModuleDtoEnumMember/ModuleDtoEnumMemberForm.tsx, packages/amplication-client/src/ModuleDtoEnumMember/ModuleDtoEnumMemberList.tsx, packages/amplication-client/src/ModuleDtoEnumMember/NewModuleDtoEnumMember.scss, packages/amplication-client/src/ModuleDtoEnumMember/NewModuleDtoEnumMember.tsx, packages/amplication-client/src/ModuleDtoEnumMember/hooks/useModuleDtoEnumMember.tsx, packages/amplication-client/src/ModuleDtoEnumMember/queries/moduleDtosEnumMemberQueries.ts, packages/amplication-client/src/ModuleDtoProperty/ModuleDtoPropertyList.tsx
=> feat(client):module DTO Enum members

libs/ui/design-system/src/lib/components/FlexItem/FlexItem.scss, libs/ui/design-system/src/lib/components/FlexItem/FlexItem.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.scss, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/PreviewUserBTMModal.tsx, packages/amplication-client/src/Resource/break-the-monolith/BreakTheMonolith.tsx
Close: #8079 
Add preview user dialog for BTM AI flow.
=> feat(client): add preview user dialog for BTM AI flow

packages/amplication-client/src/Components/EntityContextMenuButton.scss, packages/amplication-client/src/Components/EntityContextMenuButton.tsx, packages/amplication-client/src/Project/ArchitectureConsole/nodes/modelNodeBase.tsx
Close: #8104
Show entity context menu only for draggable nodes / remove selected icon.
=> refactor(client): show entity context menu only for draggable nodes / remove selected icon.

packages/amplication-server/src/core/resource/resourceBtm.resolver.ts, packages/amplication-server/src/core/resource/resourceBtm.service.spec.ts, packages/amplication-server/src/core/resource/resourceBtm.service.ts
=> chore(server: remove Auth entity from AI results suggestion

packages/amplication-client/src/Project/ArchitectureConsole/PreviewUserLoginModal.tsx, packages/amplication-client/src/Project/ProjectPage.scss, packages/amplication-client/src/Project/ProjectPage.tsx, packages/amplication-client/src/Workspaces/hooks/useProjectSelector.ts, packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/auth/auth.service.ts
Close: #8080
Add Dialog for Preview user first login after a signup.
=> Feat/8080 => Add Dialog for Preview user first login after a signup

packages/amplication-client/src/Resource/break-the-monolith/CreateEntitiesFormPredefinedSchema.tsx
Close: #8111 
Fix fields not shows in BTM bug > replace history.push with window.history.forward();
=> fix(client): fields not shows in BTM

packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/auth/auth.service.ts
Related to: https://github.com/amplication/private-issues/issues/139
=> feat(server): allow remembering that a user was once a preview user

packages/amplication-client/src/Entity/ImportPrismaSchema/EntitiesImport.tsx
Part of: https://github.com/amplication/amplication/issues/7815
show the right log when an error occurs.
=> fix(client): new import flow error message

packages/amplication-client/src/User/CompletePreviewSignup.tsx
Close: https://github.com/amplication/private-issues/issues/156
=> chore(client): fix text colors

packages/amplication-server/src/core/auth/auth.service.ts
=> fix(server): fix the firstname and lastname properties of preview users

packages/amplication-client/src/Project/ArchitectureConsole/PreviewUserBTMModal.tsx
=> chore(client): update preview user BTM text colors

packages/amplication-client/src/Resource/break-the-monolith/BreakTheMonolith.scss, packages/amplication-client/src/Resource/break-the-monolith/BreakTheMonolith.tsx
=> chore(client): update the BTM results "cards" screen to new UX requirements

packages/amplication-client/src/Project/ArchitectureConsole/ArchitectureConsole.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizer.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizerPreviousChangesExistConfirmation.tsx, packages/amplication-client/src/Resource/break-the-monolith/BreakTheMonolith.tsx, packages/amplication-client/src/Resource/break-the-monolith/BtmButton.tsx, packages/amplication-client/src/Resource/break-the-monolith/CreateEntitiesFormPredefinedSchema.tsx
Close: https://github.com/amplication/private-issues/issues/159  
https://github.com/amplication/private-issues/issues/160
Add confirm changes dialog messages for manual/AI process.
=> feat(client): add confirm changes dialog messages for manual/AI process.

libs/ui/design-system/src/lib/components/Button/Button.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ModelsGroupsList.tsx
=> fix(client): fix ModelOrganizer icon position

packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizerControl.tsx
=> fix(client): fix model organizer controls icon position

packages/amplication-client/project.json
=> chore(client): remove redundant nx target

packages/amplication-client/src/Components/FeatureIndicator.tsx, packages/amplication-client/src/Project/ArchitectureConsole/PreviewUserLoginModal.tsx, packages/amplication-client/src/User/Login.tsx, packages/amplication-client/src/Workspaces/hooks/useUpgradeButtonData.ts
Close: https://github.com/amplication/private-issues/issues/162
=> chore(client): update trial length texts to 7 days

packages/data-service-generator/package.json
Close: #8076
Fix linting issue due to the upgrade
=> chore(dsg): fix linting

packages/amplication-server/src/core/auth/auth-utils.ts, packages/amplication-server/src/core/auth/auth.module.ts, packages/amplication-server/src/core/auth/auth.resolver.spec.ts, packages/amplication-server/src/core/auth/auth.resolver.ts, packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/auth/auth.service.ts, packages/amplication-server/src/core/auth/previewUser.service.spec.ts, packages/amplication-server/src/core/auth/previewUser.service.ts, packages/amplication-server/src/core/idp/auth0.service.ts, packages/amplication-server/src/core/idp/idp.module.ts, packages/amplication-server/src/core/idp/types.ts
Close: https://github.com/amplication/amplication/issues/8177
- Extract the functionality related to Auth0 to a seperate service `Auth0Service` under a new `IdpModule`
- Extract the functionality related to PreviewUser to a separate service `PreviewUserService` under the existing  `AuthModule`
=> refactor(server): IDP module

packages/data-service-generator/src/server/package-json/package.json, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: https://github.com/amplication/amplication/issues/8180
pin ts version in the generated app: ` "typescript": "5.3.*"`
=> hotfix(dsg): ts version

packages/data-service-generator/.eslintrc.json, packages/data-service-generator/src/server/package-json/package.json, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-disabled-module.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-default-actions.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
=> fix(dsg): pin TS version and update snapshots

packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizerToolbar.tsx
=> chore(client): remove architecture tab beta indicator

packages/amplication-client/src/OnboardingPreview/OnboardingPreview.scss, packages/amplication-client/src/OnboardingPreview/OnboardingPreview.tsx, packages/amplication-client/src/OnboardingPreview/OnboardingPreviewSuccess.tsx, packages/amplication-client/src/OnboardingPreview/constants.ts
Close: https://github.com/amplication/private-issues/issues/164
=> feat:onboarding preview fixes

packages/amplication-plugin-api/src/plugin/plugin.service.ts
=> create new api on plugin api for categories and ranks

packages/amplication-client/src/ModuleActions/NewModuleAction.tsx, packages/amplication-client/src/ModuleDto/NewModuleDto.tsx, packages/amplication-client/src/ModuleDto/NewModuleDtoEnum.tsx, packages/amplication-client/src/Modules/NewModuleChild.scss, packages/amplication-client/src/Modules/NewModuleChild.tsx
=> feat(client): Generic component for new children for modules

packages/amplication-server/src/core/entity/constants.ts
Close: #8209
Add an email field as part of the default User entity.
=> feat(server):default email field

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx
=> fix(client): refetchLastCommit after onboarding in done

packages/amplication-client/src/OnboardingPreview/OnboardingPreview.tsx, packages/amplication-client/src/Plugins/hooks/usePlugins.ts
=> Preview onboarding plugin settings

packages/amplication-server/src/core/entity/constants.ts
=> fix(server): default email field must be unique in auth entity

packages/amplication-client/src/OnboardingPreview/constants.ts
=> fix(client): fix title of GCP plugin option in mobile preview onboarding

packages/amplication-client/src/OnboardingPreview/constants.ts
=> fix(client): shorten GCP title to allow icon to fit in

packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap
=> chore(dsg): update auth jwt snapshot based on latest plugin version changes

packages/amplication-client/src/OnboardingPreview/constants.ts
=> fix(client): fix spelling in onboarding preview

ee/packages/git-sync-manager/src/models.ts, libs/util/git/src/providers/git-cli.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20240325091122_split_lines_of_code/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/UsageInsights/usageInsights.service.spec.ts, packages/amplication-server/src/core/UsageInsights/usageInsights.service.ts, packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/build/dto/Build.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Part of: https://github.com/amplication/amplication/issues/8167
- split linesOfCode to: linesOfCodeDeleted and linesOfCodeAdded
- fix bug with diffstat
=> Fix(server): split insertions and deletions

packages/amplication-client/src/UsageInsights/UsageInsights.tsx, packages/amplication-client/src/UsageInsights/UsageInsightsDataBoxData.ts
=> chore(client): updates to usage analytics captions and line breaks

packages/amplication-client/src/ModuleDto/ModuleDto.tsx
Close: #7713
Hide toggle for disabling default dtos.
=> feat(client): hide toggle for disabling default dtos

packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/core/module/module.service.ts
Close: #7713 
Add module dto's validation before deleting an entity.
=> feat(server): add module dto validation before deleting an entity

packages/amplication-client/src/Components/BetaFeatureTag.tsx, packages/amplication-client/src/Modules/ModulesToolbar.tsx
Related to: #7713
Add beta indicator for custom actions
=> feat(client): add beta indicator for custom actions

packages/data-service-generator/src/server/resource/dto/create-dto-module.ts, packages/data-service-generator/src/server/resource/dto/custom-types/create-custom-dtos.ts, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-disabled-module.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-default-actions.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Relates to: #7713 
Fix relative path for importing InputJsonValue in custom DTO.
=> Fix relative path for importing InputJsonValue in custom DTOs

packages/amplication-server/jest.config.ts, packages/amplication-server/src/core/block/block.util.ts, packages/amplication-server/src/core/module/module.service.ts, packages/amplication-server/src/core/moduleAction/moduleAction.service.ts, packages/amplication-server/src/core/moduleDto/moduleDto.service.ts
Close: #7713 
Fix entitlement validation failed
=> fix(server): entitlement validation failed

packages/amplication-code-gen-types/package.json, packages/data-service-generator/package.json
Close: #8285
Fix dependency configuration and bump code-gen-types version
=> chore(dsg): dependencies issue

ee/packages/git-sync-manager/src/models.ts, libs/ui/design-system/src/lib/components/SelectField/SelectField.scss, libs/ui/design-system/src/lib/components/SelectField/SelectField.tsx, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Entity/SchemaField.tsx, packages/amplication-client/src/Entity/constants.ts, packages/amplication-client/src/models.ts, packages/amplication-code-gen-types/src/data-type-to-schema.ts, packages/amplication-code-gen-types/src/models.ts, packages/amplication-code-gen-types/src/schemas/file.json, packages/amplication-code-gen-types/src/schemas/index.ts, packages/amplication-prisma-db/prisma/migrations/20240331203055_add_file_to_enum_data_type/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/entity/constants.ts, packages/amplication-server/src/enums/EnumDataType.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/admin/entity/create-field-input.ts, packages/data-service-generator/src/models.ts, packages/data-service-generator/src/server/prisma/create-prisma-schema-fields.ts
This reverts the reversion of the earlier version of the PR at #8270.
Done by reverting the commit `33690f1a310963b75b0921d990e5be6eeaa862ac` and pushing it to the branch and opening a PR.
=> feat: initial changes for adoption of file dataType

packages/amplication-server/src/core/moduleDto/moduleDto.service.spec.ts
=> test(server): fix unit tests for custom and default module DTOs

package-lock.json, package.json, packages/amplication-client/src/Components/ResponsiveContainer.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/Workspaces/WorkspaceOverview.scss, packages/amplication-client/src/Workspaces/WorkspaceOverview.tsx
Close: #8297 
Add responsive container on pages with the insights panel to allow breakpoints on smaller screens
=> feat(client):responsive container

packages/amplication-client/src/User/constants.ts
Close: #8292
text **Node.js** is replaced with  text **backend**
=> fix(client): Update-the-login/signup-page

packages/amplication-server/src/core/block/block.service.ts
Close: #8313
Fix issue related to changes on moduleDto block not being correctly committed
=> fix(server): issue commit for migration changes

packages/amplication-server/src/core/user/user.service.ts, packages/notification-service/src/notification-packages/featureAnnouncement.ts
=> Add-custom-actions-notification

packages/amplication-code-gen-types/package.json, packages/amplication-code-gen-types/src/plugin-events-params.types.ts, packages/amplication-code-gen-types/src/plugin-events.types.ts, packages/amplication-code-gen-types/src/plugins.types.ts, packages/data-service-generator/src/server/create-main/create-main-file.ts, packages/data-service-generator/src/server/create-main/main.with-bigint.template.ts, packages/data-service-generator/src/tests/__snapshots__/create-data-service-custom-path.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-numeric-user-id.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-auth-jwt.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-disabled-module.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-grpc.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-with-kafka.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-admin-ui.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-default-actions.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-graphql.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service-without-restApi.spec.ts.snap, packages/data-service-generator/src/tests/__snapshots__/create-data-service.spec.ts.snap
Close: #7402
Adds createMainFile events.
=> feat(dsg): add create main file event

packages/amplication-client/src/Modules/NewModule.scss, packages/amplication-client/src/Modules/NewModule.tsx
Close: #8320 
Fix the new module component style.
=> fix(client): new module dialog style

packages/amplication-client/src/Modules/NewModule.tsx
Close: #8320 
Update newModule placeholder. 
=> fix(client): update newModule placeholder

packages/amplication-client/src/Assistant/Assistant.tsx, packages/amplication-client/src/Workspaces/WorkspaceForm.tsx, packages/amplication-server/src/core/assistant/assistant.service.ts
Close: https://github.com/amplication/private-issues/issues/180
=> Feat: Disable Jovu when AI-powered features are disabled

packages/amplication-client/src/Modules/Module.tsx
Close: #8321 
Fix the update module error.
=> fix(client): update module name/description

packages/amplication-code-gen-types/package.json
Fixes: https://github.com/amplication/private-issues/issues/132
Bump version to release new plugin event introduced here https://github.com/amplication/amplication/pull/8316
=> chore(code-gen-types): bump version for release

packages/amplication-server/src/core/assistant/graphqlSubscriptionPubSubKafka.service.ts
Close: #8303
Fix typo in kafka consumer group
=> refactor(server): fix typo in graphql subscription kafka consumer group

packages/amplication-server/src/core/assistant/assistant.service.ts
part of https://github.com/amplication/amplication/issues/8306
Create Action with Jovu
=> feat(server):create action with jovu

packages/local-data-service-generator-controller/src/code-gen/code-gen.controller.ts, packages/local-data-service-generator-controller/src/code-gen/types.ts
Part of: https://github.com/amplication/amplication/issues/8368
add the logic of multi-images to the local-dst-controller
=> feat(local-dsg): multi images

packages/data-service-generator-catalog/jest.config.ts, packages/data-service-generator-catalog/prisma/migrations/20240503134532_add_generator_model/migration.sql
Close: #8369
Add db migration for new generator model
=> chore(dsg-catalog): add missing db migration

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Assistant/hooks/useAssistant.tsx, packages/amplication-client/src/Entity/EntityERD/EntitiesERD.tsx, packages/amplication-client/src/models.ts, packages/amplication-server/src/core/assistant/assistant.service.spec.ts, packages/amplication-server/src/core/assistant/assistant.service.ts, packages/amplication-server/src/core/assistant/dto/EnumAssistantFunctions.ts, packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/amplication/issues/8388
Improve the way Jovu creates fields, especially relation fields.
Avoid the creation of relation fields with the FK format - instead of  customerId, use customer
Allo creation of single fields separately from entity creation
=> Feat(server): Jovu - Separate field creation from entity creation

.vscode/settings.json, packages/amplication-client/src/Workspaces/WorkspaceHeader/UpgradeCtaButton.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Close: #8395
Refactor client code - extract upgrade CTA to a new component
=> chore(client):extract upgrade button to a separate component

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceWelcome.tsx
Fixes: https://github.com/amplication/private-issues/issues/101
Add a message about the trial in the new service splash screen
=> feat(client): Add a message about the trial in the new service splash screen

packages/amplication-server/.env
Fixes: https://github.com/amplication/private-issues/issues/182
=> chore(server): update contact us link

packages/amplication-client/src/Assistant/AssistantMessage.tsx
Close: #8433
Open external links in Jovu in a new tab
=> fix(client):open external links from jovu in a new tab

.github/workflows/release.template.yml
Close: https://github.com/amplication/amplication/issues/8442
add enable-custom-tags input to be able to publish tags that are not latest
=> feat(workflow): add enable-custom-tags input to be able to publish tags that are not latest

.github/workflows/release.template.yml
Fixes: https://github.com/amplication/amplication-cluster-configuration/issues/221
=> chore(ci): fix gh syntax issue

packages/amplication-client/src/Assistant/CreateWithJovuButton.tsx, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/ModuleActions/NewModuleAction.tsx, packages/amplication-client/src/ModuleDto/NewModuleDto.tsx, packages/amplication-client/src/ModuleDto/NewModuleDtoEnum.tsx, packages/amplication-client/src/Modules/NewModuleChild.tsx, packages/amplication-client/src/style/mixin.scss
Close: #8308 
Add "Create with Jovu" button for Action, DTO, and Enum
=> feat(client):Create with Jovu button

packages/amplication-client/src/Entity/EntityList.scss, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/routes/resourceEntitiesRoutes.tsx, packages/amplication-server/src/core/assistant/assistantFunctions.service.spec.ts, packages/amplication-server/src/core/assistant/assistantFunctions.service.ts
Close: #8459
- Add a new route for ERD view
- Give Jovu the context after entity creation to go to the ERD view instead of the list view
-
=> feat: Direct users to ERD view when creating entities with Jovu

packages/amplication-server/src/core/module/module.service.spec.ts, packages/amplication-server/src/core/module/module.service.ts
Close: #8463
- Validate duplicate module names
=> feat(server):validate duplicate modules

README.md
Close: https://github.com/amplication/private-issues/issues/187
Further improve the README page to include AI content
=> Update README with AI content

nx.json
Close: #8478 
In order to avoid issues related to incorrectly cached generated models.ts
=> chore(server): remove gql schema and model generation from the nx cacheable targets

libs/util/code-gen-types/README.md, libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts, libs/util/code-gen-types/src/dotnet-plugin-events.types.ts, libs/util/code-gen-types/src/dotnet-plugins.types.ts, libs/util/code-gen-types/src/index.ts, package-lock.json, package.json
Close: #8467
Add DotNet plugin events and types.
=> feat(code-gen-types): add DotNet plugin events and types

packages/data-service-generator/package.json, packages/data-service-generator/project.json
Close: #8517
Add new `npx nx generate-local-code-docker` cli command
=> chore(generator): add script to generate local code through container

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts
=> chore(code-gen-types): update create program file dotnet plugin event params

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts
Close: https://github.com/amplication/amplication/issues/8446
=> feat(code-gen-types): dotnet create entity controller base params

packages/amplication-server/src/core/entity/entity.service.spec.ts, packages/amplication-server/src/core/entity/entity.service.ts
Close: #8521 
This PR is a cherry-pick PR to merge PR 8522 (already merged to next) into master for a hotfix.
=> feat(server):alter reserved name on creation

packages/amplication-client/src/Assistant/OnboardingWithJovu.tsx, packages/amplication-client/src/Resource/create-resource/wizardResourceSchema.ts, packages/amplication-client/src/util/analytics-events.types.ts, packages/amplication-server/src/core/assistant/assistantFunctions.service.ts, packages/amplication-server/src/core/moduleAction/moduleAction.service.ts, packages/amplication-server/src/core/moduleDto/moduleDto.service.ts, packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/core/workspace/workspace.service.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalyticsEventType.types.ts
Close: https://github.com/amplication/private-issues/issues/190
Add missing events for onboarding with Jovu
=> Feat(server+client): Jovu analytics

packages/amplication-server/src/core/entity/entity.service.ts
Close: #8356
Fix BTM apply changes failed.
=> (Fix): server 8356=> BTM apply changes failed

packages/amplication-client/src/ModuleActions/ModuleAction.tsx, packages/amplication-client/src/ModuleActions/ModuleActionForm.tsx, packages/amplication-client/src/ModuleActions/ModuleActionListItem.tsx, packages/amplication-server/src/core/module/module.service.ts, packages/amplication-server/src/core/moduleAction/moduleAction.service.spec.ts, packages/amplication-server/src/core/moduleAction/moduleAction.service.ts
Close: #8545
Fix models and models actions update data.
=> (Fix): 8545 models and models actions update data

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts, libs/util/code-gen-types/src/dotnet-plugin-events.types.ts, libs/util/code-gen-types/src/dotnet-plugins.types.ts
Close: #8567 
Add CreateEntityModel plugin event.
=> feat(code-gen-types): add CreateEntityModel plugin event

packages/amplication-client/src/Project/ProjectListItem.tsx
=> fix(client):project list link

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts
Close: #8566
Add properties to CreateServerCsprojParams to allow plugin modification of projects 
=> feat(code-gen-types): improve csproj event parameters for dotnet plugin event

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts, libs/util/code-gen-types/src/dotnet-plugin-events.types.ts, libs/util/code-gen-types/src/dotnet-plugins.types.ts
Close: #8577 
Add createResourceDbContextFile plugin event.
=> feat(code-gen-types): add createResourceDbContextFile plugin event

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/dotnet-plugin-events-params.types.ts, libs/util/code-gen-types/src/dotnet-plugin-events.types.ts, libs/util/code-gen-types/src/dotnet-plugins.types.ts
Close: #8594 
Add CreateSeedDevelopmentDataFile plugin event.
=> feat(code-gen-types): add CreateSeedDevelopmentDataFile plugin event

packages/amplication-client/src/Resource/codeGeneratorVersionSettings/CodeGeneratorVersion.tsx, packages/amplication-client/src/Resource/codeGeneratorVersionSettings/CodeGeneratorVersionForm.tsx, packages/amplication-client/src/Resource/codeGeneratorVersionSettings/queries.ts
Close: #8586
Filter DSG version list based on the service's code generator 
=> feat(client):filter code generator version list

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceAuth.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceDatabase.tsx
Close: #8608
Update labels for db and auth plugins in wizard pages
=> fix(client): wizard option labels for .NET services

packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Resource/ResourceOverview.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx
Close: #8547
Remove BTM button from project and resource pages
=> feat(client): remove btm button from entity overview

ee/packages/git-sync-manager/src/models.ts, libs/util/billing-types/src/lib/billing-addons.types.ts, libs/util/billing-types/src/lib/billing-plan.types.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Purchase/PurchasePage.scss, packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/UpgradeCtaButton.tsx, packages/amplication-client/src/Workspaces/WorkspaceOverview.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelector.scss, packages/amplication-client/src/Workspaces/WorkspaceSelector.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelectorList.tsx, packages/amplication-client/src/Workspaces/hooks/useUpgradeButtonData.ts, packages/amplication-client/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20240610145839_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts, packages/amplication-server/src/core/subscription/dto/EnumSubscriptionPlan.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
=> feat(server):add essential plan

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGenerationSettings.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/ImageLabelToggle.tsx, packages/amplication-client/src/Resource/resourceSettings/GenerationSettingsForm.tsx
Close: #8619
Disable adminui and graphql from resource settings in client  
=> feat(client): disable admin ui and graphql on resource settings page

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelectorListItem.tsx
=> feat(client):add link to purchase page

packages/amplication-client/src/Purchase/FAQ.tsx
Close: https://github.com/amplication/amplication/issues/8656
Update FAQ
=> feat(client):update FAQ

packages/amplication-client/src/Components/CreateResourceButton.tsx, packages/amplication-client/src/Components/FeatureIndicator.tsx, packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Project/AddNewProject.tsx, packages/amplication-client/src/Purchase/FAQ.tsx, packages/amplication-client/src/Resource/git/GitActions/GitProviderConnection.tsx, packages/amplication-client/src/Resource/git/GitActions/GitProviderConnectionList.tsx, packages/amplication-client/src/ServiceConnections/ServiceConnectionsPage.tsx, packages/amplication-client/src/VersionControl/hooks/useABTesting.ts, packages/amplication-client/src/Workspaces/InviteMember.tsx
Close: https://github.com/amplication/amplication/issues/8654
Update the CTA on the featureIndicatorContainer
=> feat(client):feature indicator CTA

packages/amplication-client/src/Components/CreateResourceButton.tsx, packages/amplication-client/src/Components/FeatureIndicator.tsx, packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Components/LicenseIndicatorContainer.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Project/AddNewProject.tsx, packages/amplication-client/src/Purchase/FAQ.tsx, packages/amplication-client/src/Resource/break-the-monolith/BtmButton.tsx, packages/amplication-client/src/Resource/git/GitActions/GitProviderConnection.tsx, packages/amplication-client/src/Resource/git/GitActions/GitProviderConnectionList.tsx, packages/amplication-client/src/ServiceConnections/ServiceConnectionsPage.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/hooks/useABTesting.ts, packages/amplication-client/src/Workspaces/InviteMember.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelectorList.tsx, packages/amplication-server/src/core/subscription/subscription.service.ts
Close: #8652
- Remove unused code paths and properties.
- Update tooltip text
- Update tooltip font size
=> refactor(client):LicenseIndicatorContainer component

packages/amplication-server/src/core/resource/resource.service.ts
Close: #8662 
Enforce code generator version for trial users
=> feat(server): code generation trial

libs/util/billing-types/src/lib/billing-addons.types.ts, packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts
Close: https://github.com/amplication/amplication/issues/8664
fix limitation on jovu requests while in trial
=> fix(server):jovu requests trial

packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Project/AddNewProject.tsx, packages/amplication-client/src/Workspaces/InviteMember.tsx
Close: https://github.com/amplication/amplication/issues/8665
Use CTA to ugrade with a link to pricing page on all feature tooltips
=> feat(client):change all CTA to pricing page

packages/amplication-client/src/Workspaces/ResourceList.scss
Close: https://github.com/amplication/amplication/issues/8667
=> style(client):show analytics below resource list on all screen sizes

packages/amplication-server/src/core/resource/resource.service.ts
=> fix(server):dotnet default settings without admin ui and gql

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Close: https://github.com/amplication/amplication/issues/8645
=> fix(client):fix clickable area

packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/amplication/issues/8669
Enforce service creation limitation
=> fix(service) enforce service limitation

packages/amplication-client/src/Project/ArchitectureConsole/ModelOrganizerToolbar.tsx
Close: #8547
rename AI helper button in Break the Monolith
=> chore(client): rename AI helper button in Break the Monolith

packages/amplication-server/src/core/entity/entity.service.spec.ts, packages/amplication-server/src/core/entity/entity.service.ts
Fixes: https://github.com/amplication/private-issues/issues/197
=> fix(server): issue related to billing features not being respected

packages/amplication-server/src/core/project/project.service.ts
Close: https://github.com/amplication/private-issues/issues/196
=> fix(server): issue related to missing validation of billing features on build

packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-server/jest.config.ts, packages/amplication-server/src/core/billing/billing.service.ts
Close: https://github.com/amplication/private-issues/issues/203
Upgrade from free to Essential without a trial
=> feat(server):upgrade from free to paid without a trial

.github/workflows/release.assistant-function-json.yml
closes [#amplication/private-issues/184](https://github.com/amplication/private-issues/issues/184)
=> feat(openai-assistant): add release workflow

packages/amplication-server/src/core/billing/billing.module.ts, packages/amplication-server/src/core/billing/billing.service.mock.ts, packages/amplication-server/src/core/billing/billing.service.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.module.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.service.spec.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.service.ts
Fixes: https://github.com/amplication/private-issues/issues/201
This PR adds the "planType" attribute to all the server Analytics events where possible (where we have a workspaceId)
=> feat(server): add planType to all server events

packages/amplication-server/src/core/commit/commit.module.ts, packages/amplication-server/src/core/moduleDto/moduleDto.module.ts, packages/amplication-server/src/core/moduleDto/moduleDto.service.spec.ts, packages/amplication-server/src/core/moduleDto/moduleDto.service.ts, packages/amplication-server/src/core/resource/resource.module.ts
=> Filter-nest-only-dtos

packages/amplication-server/src/core/assistant/assistant.service.ts
Close: https://github.com/amplication/private-issues/issues/206
Update the onboarding instructions so Jovu will use the current project
=> feat(server):update assistant for onboarding

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceDatabase.tsx
=> fix(client): fix title mismatch bug in dotnet DB plugins

packages/amplication-server/src/core/moduleDto/moduleDto.service.ts
=> fix(server): allow deleting custom enums

packages/amplication-server/src/core/module/module.service.ts
=> Do not search in custom Enums for DTO references

libs/util/git/src/providers/git-cli.ts
=> fix(git): fail gracefully and return a default empty diff stat if diff stat throws an exception

libs/ui/design-system/src/lib/components/List/List.scss, packages/amplication-client/src/Assistant/Assistant.tsx, packages/amplication-client/src/Components/PremiumFeatureHeader.tsx, packages/amplication-client/src/ModuleActions/ModuleActionsDisabled.tsx, packages/amplication-client/src/Project/ArchitectureConsole/ModuleOrganizerDisabled.tsx, packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/UsageInsights/UsageInsightsDataBox.tsx, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/DotNetPromotePage.tsx, packages/amplication-client/src/VersionControl/DotnetPromotePage.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader/UpgradeCtaButton.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/hooks/useContactUs.ts, packages/amplication-client/src/routes/appRoutes.tsx
Close: https://github.com/amplication/private-issues/issues/204
Show the user info about how to access the .NET version 
=> Feat(client): upgrade to dotnet

packages/amplication-client/src/ModuleDto/hooks/useModuleDto.tsx, packages/amplication-server/src/core/commit/commit.module.ts, packages/amplication-server/src/core/moduleDto/moduleDto.module.ts, packages/amplication-server/src/core/moduleDto/moduleDto.service.spec.ts, packages/amplication-server/src/core/moduleDto/moduleDto.service.ts, packages/amplication-server/src/core/resource/resource.module.ts
=> fix: filter DTOs for dotnet in the client rather than in the server

packages/amplication-server/src/core/assistant/functions/createService.json
Close: https://github.com/amplication/private-issues/issues/184
=> chore(server): change description of function to test workflow

packages/amplication-server/src/core/assistant/assistantFunctions.service.ts
Fixes: https://github.com/amplication/private-issues/issues/207
=> Private-207/add-transaction-mechanism-for-Jovu's-CreateModuleAction

packages/amplication-server/src/core/resource/resource.service.ts
=> Fix/8739: install correct default DB plugin for Dotnet services

packages/amplication-server/src/core/resource/resource.service.ts
=> fix(server): fix bug with choosing the correct default DB plugin by generator

packages/amplication-client/src/VersionControl/PendingChange.tsx, packages/amplication-client/src/VersionControl/PendingChangesListGroup.tsx
=> feat(client):collapse pending changes groups by default

libs/ui/design-system/src/lib/components/CodeEditor/CodeEditor.tsx, libs/ui/design-system/src/lib/components/TreeView/TreeView.scss, libs/ui/design-system/src/lib/components/TreeView/TreeView.tsx, packages/amplication-client/src/Resource/code-view/CodeViewPage.scss
=> style(client):fix code view style

packages/amplication-server/src/core/assistant/assistantFunctions.service.ts, packages/amplication-server/src/core/entity/entity.service.ts
Close: #8741
Jovu: error create entity limitation.
=> fix(server): Jovu: error create entity limitation

packages/amplication-server/src/core/assistant/assistant.module.ts, packages/amplication-server/src/core/assistant/assistant.service.spec.ts, packages/amplication-server/src/core/assistant/assistant.service.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalyticsEventType.types.ts
Close: https://github.com/amplication/private-issues/issues/209
Add event for StartJovuThread
=> feat(server):add event fro StartJovuThread

packages/amplication-client/src/Assistant/Assistant.scss, packages/amplication-client/src/Assistant/Assistant.tsx, packages/amplication-client/src/Assistant/AssistantChat.scss, packages/amplication-client/src/Assistant/AssistantChat.tsx, packages/amplication-client/src/Assistant/AssistantChatInput.scss, packages/amplication-client/src/Assistant/AssistantChatInput.tsx, packages/amplication-client/src/Assistant/AssistantMessage.tsx, packages/amplication-client/src/Assistant/OnboardingWithJovu.scss, packages/amplication-client/src/index.scss
Close: #8750 
Break the assistant component into multiple smaller components - no style or functionality changes 
=> refactor(client):break assistant to components

packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceCodeGeneration.tsx, packages/amplication-client/src/Resource/git/AuthWithGitProvider.tsx, packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx, packages/amplication-client/src/Resource/git/dialogs/GitDialogsContainer.tsx, packages/amplication-client/src/Resource/git/dialogs/GitRepos/GithubRepos.tsx, packages/amplication-client/src/Resource/git/useAuthWithGit.ts, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/hooks/useCommits.ts
Close: https://github.com/amplication/private-issues/issues/192
Add commit action to git sync page.
=> Feat(client): add commit action to git sync page

packages/amplication-client/src/VersionControl/DotNetPromotePage.tsx
Close: https://github.com/amplication/private-issues/issues/210
Add analytics to upgrade button: .NET promote.
=> feat(client): add analytics to upgrade button: .NET promote page

packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx
Close: https://github.com/amplication/private-issues/issues/192
Add another function for handleDone repo selected.
=> refactor(client): add another function for handleDone repo selected

packages/amplication-client/src/Entity/DeleteEntityField.tsx, packages/amplication-client/src/Entity/EntityField.tsx, packages/amplication-client/src/Entity/EntityListItem.tsx, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/Entity/NewEntityField.tsx, packages/amplication-client/src/ModuleActions/DeleteModuleAction.tsx, packages/amplication-client/src/ModuleActions/ModuleAction.tsx, packages/amplication-client/src/ModuleActions/NewModuleAction.tsx, packages/amplication-client/src/ModuleDto/DeleteModuleDto.tsx, packages/amplication-client/src/ModuleDto/ModuleDto.tsx, packages/amplication-client/src/ModuleDto/NewModuleDto.tsx, packages/amplication-client/src/OnboardingChecklist/OnboardingChecklist.tsx, packages/amplication-client/src/OnboardingChecklist/context/OnboardingChecklistContext.tsx, packages/amplication-client/src/Plugins/InstalledPlugins.tsx, packages/amplication-client/src/Plugins/PluginTree.tsx, packages/amplication-client/src/Plugins/PluginsCatalog.tsx, packages/amplication-client/src/Resource/create-message-broker/CreateMessageBroker.tsx, packages/amplication-client/src/Roles/NewRole.tsx, packages/amplication-client/src/VersionControl/BuildGitLink.tsx, packages/amplication-client/src/Workspaces/WorkspaceFooter.tsx, packages/amplication-client/src/Workspaces/hooks/useprojectResources.ts
=> feat(client): update the onboarding context with resourceId 

packages/data-service-generator/src/server/custom-module/custom-controller/create-controller.ts, packages/data-service-generator/src/server/custom-module/custom-module/create-module.ts, packages/data-service-generator/src/server/custom-module/custom-service/create-service.ts
Fixes: https://github.com/amplication/private-issues/issues/211
(partially - section 1 in the ticket)
=> fix(dsg): fix folder structure for custom modules to be all lowercase

.github/workflows/release.assistant-function-json.yml
Close: https://github.com/amplication/private-issues/issues/214
The pull request add the `delete-branch` option to the cross repository pull request, as well as some reviewers through a team and instructions.
=> chore(ci): improve openai assistant configuration update workflow

packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx, packages/amplication-client/src/VersionControl/Commit.scss, packages/amplication-client/src/VersionControl/Commit.tsx, packages/amplication-client/src/VersionControl/CommitButton.tsx, packages/amplication-client/src/VersionControl/CreateCommitStrategyButton.scss, packages/amplication-client/src/VersionControl/CreateCommitStrategyButtonItem.scss, packages/amplication-client/src/VersionControl/CreateCommitStrategyButtonItem.tsx, packages/amplication-client/src/VersionControl/hooks/commitQueries.ts, packages/amplication-client/src/VersionControl/hooks/useCommits.ts
Close: #8500 
Add options list for commit: 
- all services
- all changed services
- specific service
=> Feat(client): Add options list for commit

packages/amplication-client/src/VersionControl/CommitButton.tsx
Close: #8500 
Use bypassLimitationsRef.current.
=> fix(client): bypassLimitationsRef.current

packages/amplication-client/src/ModuleDtoProperty/DtoPropertyTypesSelectField.tsx
=> fix(client): fix bug with custom action screen creating errors

packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/entity/entity.service.ts
Consolidate sorting of entities and entity fields into the getOrderedEntities method
Close: #8789 
=> refactor(server): consolidate sorting of entities and entity fields into the getOrderedEntities method

packages/data-service-generator/src/server/custom-module/custom-resolver/create-resolver.ts
Fixes: https://github.com/amplication/private-issues/issues/211
=> fix(dsg): normalize folder name to all lowercase for the resolver as well

ee/packages/git-sync-manager/src/models.ts, libs/util/billing-types/src/lib/billing-feature.types.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Components/CreateResourceButton.tsx, packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx, packages/amplication-client/src/Plugins/InstalledPlugins.tsx, packages/amplication-client/src/Plugins/PluginTree.tsx, packages/amplication-client/src/Plugins/PluginsCatalog.tsx, packages/amplication-client/src/Plugins/hooks/usePluginCatalog.ts, packages/amplication-client/src/Plugins/hooks/usePlugins.ts, packages/amplication-client/src/PrivatePlugins/NewPrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePlugin.scss, packages/amplication-client/src/PrivatePlugins/PrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginList.tsx, packages/amplication-client/src/PrivatePlugins/hooks/privatePluginQueries.ts, packages/amplication-client/src/PrivatePlugins/hooks/usePrivatePlugin.tsx, packages/amplication-client/src/Resource/resourceMenuUtils.ts, packages/amplication-client/src/Resource/resourceSettings/ServiceSettingsPage.tsx, packages/amplication-client/src/models.ts, packages/amplication-client/src/routes/resourceTabRoutes.tsx, packages/amplication-server/src/core/pluginInstallation/dto/PluginInstallation.ts, packages/amplication-server/src/core/pluginInstallation/dto/PluginInstallationCreateInput.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.module.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.resolver.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Part of: https://github.com/amplication/amplication/issues/8810
Show and allow installation of private plugins in the plugins catalog
=> Feat: Install Private Plugins

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-build-manager/src/build-runner/build-runner.service.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/OnboardingPreview/OnboardingPreview.tsx, packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/models.ts, packages/amplication-server/src/core/pluginInstallation/dto/PluginInstallation.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/dynamic-package-installation.ts, packages/data-service-generator/src/models.ts, packages/data-service-generator/src/register-plugin.ts
=> feat:install private plugins

packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/resource/resource.service.ts
=> fix(server):filter deleted plugin resources

packages/amplication-server/src/core/assistant/assistantFunctions.service.ts
Close: https://github.com/amplication/amplication/issues/8760
Return seperate results for each field, so jovu can understand which field was created and which failed 
=> fix(server):return details about existing fields when jovu create new fields

packages/amplication-server/src/core/assistant/assistantFunctions.service.spec.ts, packages/amplication-server/src/core/assistant/assistantFunctions.service.ts
Close: https://github.com/amplication/amplication/issues/8729
Share the details of the default fields as part of the results property so jovu can understand they were created. 
=> fix(server):share the details of the default fields when creating an entity

packages/data-service-generator/src/server/resource/controller/create-controller-custom-actions.ts
=> fix(dsg): fix param types for custom actions

packages/amplication-server/src/core/entity/reservedNames.ts, packages/amplication-server/src/core/module/module.service.spec.ts, packages/amplication-server/src/core/module/module.service.ts
Close: https://github.com/amplication/amplication/issues/8873
prevent creation of modules with reserved names
=> feat(server):module reserved name

packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/pluginInstallation/pluginInstallation.service.ts
Close: #8913 
Fix pluginOrder in dsgResourceData.
=> fix(server): fix pluginOrder in dsgResourceData

packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/auth/auth.service.ts, packages/amplication-server/src/core/workspace/workspace.resolver.ts, packages/amplication-server/src/core/workspace/workspace.service.spec.ts, packages/amplication-server/src/core/workspace/workspace.service.ts, packages/amplication-server/src/schema.graphql
Fixes: https://github.com/amplication/private-issues/issues/219
=> fix(server): allow workspace creation for the first workspace (new user) regardless of entitlement

packages/data-service-generator/package.json
=> chore(dsg): align DSG package json with the monorepo main one

packages/amplication-client/src/Assistant/OnboardingWithJovu.tsx, packages/amplication-client/src/CommandPalette/CommandPalette.tsx, packages/amplication-client/src/Components/CreateResourceButtonItem.tsx, packages/amplication-client/src/Entity/Entity.tsx, packages/amplication-client/src/Entity/EntityERD/nodes/modelNode.tsx, packages/amplication-client/src/Entity/EntityField.tsx, packages/amplication-client/src/Entity/EntityFieldLinkList.tsx, packages/amplication-client/src/Entity/EntityFieldListItem.tsx, packages/amplication-client/src/Entity/EntityList.tsx, packages/amplication-client/src/Entity/EntityListItem.tsx, packages/amplication-client/src/Entity/EntityRelationFieldsChart.tsx, packages/amplication-client/src/Entity/ImportPrismaSchema/ImportSchemaSuccess.tsx, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/Resource/ResourceHome.tsx, packages/amplication-client/src/Resource/resourceSettings/ServiceSettingsPage.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/Workspaces/ResourceNameLink.tsx, packages/amplication-client/src/routes/resourceEntitiesRoutes.tsx, packages/amplication-client/src/routes/resourceTabRoutes.tsx, packages/amplication-client/src/util/useProjectBaseUrl.tsx, packages/amplication-client/src/util/useResourceBaseUrl.tsx
Part of: https://github.com/amplication/amplication/issues/8935
use the new hook for baseUrl
=> feat(client):use baseUrl

packages/amplication-client/src/Resource/constants.ts, packages/amplication-client/src/Resource/create-resource/CreateServiceWizard.tsx, packages/amplication-client/src/Resource/create-resource/ServiceWizard.tsx, packages/amplication-client/src/Resource/create-resource/constants.ts, packages/amplication-client/src/Resource/create-resource/types.ts, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGenerationSettings.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGithubSync.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceName.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceNextSteps.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/interfaces.ts, packages/amplication-client/src/Resource/create-resource/wizard-types/wizard-type-create-service-template.ts, packages/amplication-client/src/Resource/create-resource/wizard-types/wizard-type-create-service.ts, packages/amplication-client/src/Resource/create-resource/wizard-types/wizard-type-onboarding.ts, packages/amplication-client/src/ServiceTemplate/hooks/useServiceTemplate.ts
Close: https://github.com/amplication/amplication/issues/8963
=> feat(client):use dynamic text for the wizard steps

packages/amplication-client/src/Assistant/AskJovuButton.tsx, packages/amplication-client/src/Assistant/Assistant.tsx, packages/amplication-client/src/Components/BetaFeatureTag.tsx, packages/amplication-client/src/Components/PremiumFeatureHeader.scss, packages/amplication-client/src/Components/PremiumFeatureHeader.tsx, packages/amplication-client/src/Modules/ModulesToolbar.tsx, packages/amplication-client/src/Platform/ServiceTemplateList.tsx, packages/amplication-client/src/Plugins/PluginTree.tsx, packages/amplication-client/src/Plugins/PluginsCatalog.tsx, packages/amplication-client/src/Plugins/PrivatePluginsFeature.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginsPage.tsx, packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateServiceNextSteps.tsx, packages/amplication-client/src/VersionControl/BuildPage.tsx, packages/amplication-client/src/VersionControl/hooks/useCommits.ts, packages/amplication-client/src/Workspaces/WorkspaceHeader/PlatformBetaContent.tsx
Close: https://github.com/amplication/amplication/issues/8963
- Remove the entity box from the last step of the wizard when creating a template
- show a beta indication in the template list 
- show a premium CTA on the private plugin page
- fix the service URL in the build log
- remove beta indication for custom actions and jovu
=> fix(client)):service template fixes

packages/amplication-server/src/core/serviceSettings/serviceSettings.service.ts
Close: https://github.com/amplication/private-issues/issues/236
Clone the default service settings before merge 
=> fix(server):clone default settings before merge

ee/packages/git-sync-manager/src/models.ts, libs/ui/design-system/src/lib/components/DataGrid/DataGrid.tsx, libs/ui/design-system/src/lib/components/Pagination/Pagination.scss, libs/ui/design-system/src/lib/components/Pagination/Pagination.tsx, libs/ui/design-system/src/lib/components/UserAndTime/UserAndTime.tsx, libs/ui/design-system/src/lib/components/UserAvatar/UserAvatar.scss, libs/ui/design-system/src/lib/index.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Platform/ResourceVersionList.scss, packages/amplication-client/src/Platform/ResourceVersionList.tsx, packages/amplication-client/src/Platform/ResourceVersionListDataColumns.tsx, packages/amplication-client/src/Platform/hooks/resourceVersionQueries.ts, packages/amplication-client/src/Platform/hooks/useResourceVersion.ts, packages/amplication-client/src/Resource/resourceMenuUtils.ts, packages/amplication-client/src/Workspaces/ResourceLastBuild.tsx, packages/amplication-client/src/models.ts, packages/amplication-client/src/routes/resourceTabRoutes.tsx, packages/amplication-server/src/core/build/build.resolver.spec.ts, packages/amplication-server/src/core/build/build.resolver.ts, packages/amplication-server/src/core/entity/entity.service.spec.ts, packages/amplication-server/src/core/project/project.service.spec.ts, packages/amplication-server/src/core/resource/resource.resolver.spec.ts, packages/amplication-server/src/core/resourceVersion/resourceVersion.resolver.ts, packages/amplication-server/src/core/resourceVersion/resourceVersion.service.ts, packages/amplication-server/src/dto/MetaQueryPayload.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Part of: https://github.com/amplication/amplication/issues/8983
=> feat(client):template version list

packages/amplication-build-manager/src/build-runner/build-runner.controller.spec.ts, packages/amplication-build-manager/src/build-runner/build-runner.service.spec.ts, packages/amplication-build-manager/src/build-runner/build-runner.service.ts, packages/amplication-build-manager/src/build-runner/dto/CodeGenerationFailure.ts
Close: #8999 
Remove unused Error property from the message object
=> fix(build-manager):remove unused error object

packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx, packages/amplication-client/src/VersionControl/CommitButton.tsx, packages/amplication-client/src/VersionControl/hooks/useCommits.ts
Close: https://github.com/amplication/amplication/issues/9024
Use custom type 
=> fix(client):message is readonly

libs/util/dsg-utils/jest.config.ts, libs/util/dsg-utils/package.json, libs/util/dsg-utils/src/build-logger/build-logger.spec.ts, libs/util/dsg-utils/src/build-manager-notifier/notify-build-manager.spec.ts, libs/util/dsg-utils/src/build-manager-notifier/notify-build-manager.ts, libs/util/dsg-utils/src/dynamic-installation/DynamicPackageInstallationManager.ts, libs/util/dsg-utils/src/dynamic-installation/Tarball.ts, libs/util/dsg-utils/src/dynamic-installation/dynamic-package-installation.ts, packages/amplication-build-manager/src/build-runner/build-runner.service.spec.ts, packages/amplication-build-manager/src/build-runner/build-runner.service.ts, packages/data-service-generator/package.json
part of Close: https://github.com/amplication/amplication/issues/9021
report plugin version from dsg-util
=> feat(dsg-util):notify plugin version to build manager

packages/amplication-client/src/Resource/PluginsTile.tsx, packages/amplication-client/src/Resource/ResourceOverview.tsx, packages/amplication-client/src/VersionControl/hooks/useCommits.ts, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts
Close: #9010 
- Show the template version on the template overview page
- replace the order of installed plugins and available plugins on the overview page
- reload the resource list after commit to reload new versions when available 
=> feat(client):show template version

package-lock.json, package.json
=> chore(server):update deps to prevent issue on docker build

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20241004133918_add_outdated_version_alert/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/core.module.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/CreateOutdatedVersionAlertArgs.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/EnumOutdatedVersionAlertStatus.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/EnumOutdatedVersionAlertStatusFilter.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/EnumOutdatedVersionAlertType.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/EnumOutdatedVersionAlertTypeFilter.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/FindManyOutdatedVersionAlertArgs.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/FindOneOutdatedVersionAlertArgs.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/OutdatedVersionAlert.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/OutdatedVersionAlertCreateInput.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/OutdatedVersionAlertOrderByInput.ts, packages/amplication-server/src/core/outdatedVersionAlert/dto/OutdatedVersionAlertWhereInput.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.module.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.resolver.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts, packages/amplication-server/src/core/permissions/permissions.service.ts, packages/amplication-server/src/enums/AuthorizableOriginParameter.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/amplication/issues/9005
This is the epic PR for all the changes to support the new 'Outdated Version Alerts' model
=> Epic: Outdated Version Alerts

packages/amplication-server/src/core/build/build.resolver.spec.ts, packages/amplication-server/src/core/build/build.resolver.ts, packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/resource/serviceTemplate.service.ts
Close: https://github.com/amplication/amplication/issues/9045
=> feat(server):close stale builds

packages/amplication-server/src/core/build/build.service.ts
close https://github.com/amplication/amplication/issues/9053
=> fix(server): fix build status check

packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts
Fixes: https://github.com/amplication/private-issues/issues/238
=> feat(server): new users should be provisioned with Enterprise trial

ee/packages/git-sync-manager/src/models.ts, libs/util/billing-types/src/lib/billing-plan.types.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Resource/break-the-monolith/BtmButton.tsx, packages/amplication-client/src/Workspaces/WorkspaceOverview.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelector.tsx, packages/amplication-client/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20241009165833_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts, packages/amplication-server/src/core/subscription/dto/EnumSubscriptionPlan.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Fixes: https://github.com/amplication/private-issues/issues/238
=> feat: add new Team plan and set it as default plan for new user trial

ee/packages/git-sync-manager/src/models.ts, libs/util/billing-types/src/lib/billing-plan.types.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/Purchase/PurchasePage.tsx, packages/amplication-client/src/Resource/break-the-monolith/BtmButton.tsx, packages/amplication-client/src/Workspaces/WorkspaceOverview.tsx, packages/amplication-client/src/Workspaces/WorkspaceSelector.tsx, packages/amplication-client/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20241009165833_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/billing/billing.service.spec.ts, packages/amplication-server/src/core/billing/billing.service.ts, packages/amplication-server/src/core/subscription/dto/EnumSubscriptionPlan.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Fixes: https://github.com/amplication/private-issues/issues/238
=> Hotfix: new-pricing-plans

packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx, packages/amplication-client/src/Plugins/hooks/usePluginCatalog.ts, packages/amplication-client/src/Plugins/hooks/usePlugins.ts
Close: #9002 
Filter disabled versions.
=> feat(client): pp=> filter disabled versions

packages/amplication-client/src/OutdatedVersionAlerts/OutdatedVersionAlertListDataColumns.tsx
=> fix(client):resource not available

ee/packages/git-sync-manager/src/private-plugin/private-plugin.service.ts, libs/schema-registry/src/lib/download-private-plugins-request/value.ts, libs/util/git/src/git-client.service.ts, libs/util/git/src/types.ts, packages/amplication-server/src/core/build/build.service.ts
=> Private-plugins-versions

packages/amplication-client/src/Resource/create-plugin-repository/CreatePluginRepository.tsx
Close: https://github.com/amplication/amplication/issues/9090
update the text on the plugin repo creation page
=> client: update plugin repo text

packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts, packages/amplication-server/src/core/resourceVersion/resourceVersion.service.ts
Close: #9056
Publish template on first time undefined version error.
=> fix(server): publish template on first time undefined version error

packages/amplication-client/src/PrivatePlugins/hooks/privatePluginQueries.ts
Fixes: #9094
Fixes: #9069 
Fix apollo error on createPrivatePlugin mutation.
=> fix(client): createPrivatePlugin apollo error

packages/amplication-client/src/OutdatedVersionAlerts/hooks/useOutdatedVersionAlerts.ts, packages/amplication-client/src/Platform/ServiceTemplateList.tsx, packages/amplication-client/src/ServiceTemplate/hooks/useServiceTemplate.ts, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts
Close: https://github.com/amplication/amplication/issues/9126
Keep existing data of list in view while loading
=> Fix(client): list loading display issues

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/PrivatePlugins/NewPrivatePlugin.scss, packages/amplication-client/src/PrivatePlugins/NewPrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginForm.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginList.tsx, packages/amplication-client/src/PrivatePlugins/hooks/privatePluginQueries.ts, packages/amplication-client/src/PrivatePlugins/hooks/usePrivatePlugin.tsx, packages/amplication-client/src/models.ts, packages/amplication-server/src/core/privatePlugin/dto/PrivatePlugin.ts, packages/amplication-server/src/core/privatePlugin/dto/PrivatePluginCreateInput.ts, packages/amplication-server/src/core/privatePlugin/dto/PrivatePluginUpdateInput.ts, packages/amplication-server/src/core/privatePlugin/dto/PrivatePluginWhereInput.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.resolver.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.spec.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts, packages/amplication-server/src/core/resource/dto/EnumCodeGeneratorFilter.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/amplication/issues/9128
Add CodeGenerator property to Private Plugins
=> feat(client):private plugin codeGenerator

packages/amplication-client/src/PrivatePlugins/PrivatePlugin.tsx
Fixes: https://github.com/amplication/private-issues/issues/240
=> chore(client): temporarily hide PP versions section

libs/ui/design-system/src/lib/components/DataGrid/DataGrid.scss, libs/ui/design-system/src/lib/components/DataGrid/DataGrid.tsx, libs/ui/design-system/src/lib/components/DataGrid/DataGridColumnFilter.tsx, libs/ui/design-system/src/lib/components/SelectMenu/SelectMenu.scss, libs/ui/design-system/src/lib/index.ts, packages/amplication-client/src/Layout/useDataGridColumnFilter.ts, packages/amplication-client/src/Platform/ServiceTemplateList.tsx, packages/amplication-client/src/Resource/git/GitActions/ExistingConnectionsMenu.scss, packages/amplication-client/src/Resource/git/GitActions/ExistingConnectionsMenu.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx
Close: https://github.com/amplication/amplication/issues/9146
Add columns selector for data grid + use it on catalog and template list
Align the style of the git org selector 
=> feat(design-system):data grid columns filter

libs/ui/design-system/src/lib/components/UserAvatar/UserAvatar.scss, packages/amplication-client/src/Components/TeamInfo.tsx, packages/amplication-client/src/Project/ProjectPage.scss, packages/amplication-client/src/Resource/ResourceOverview.tsx, packages/amplication-client/src/Workspaces/ResourceListDataColumns.tsx, packages/amplication-client/src/Workspaces/ResourceOwner.tsx, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts
Close: https://github.com/amplication/amplication/issues/9179
Show resource owner
=> feat(client):show resource owner

ee/packages/git-sync-manager/src/models.ts, libs/ui/design-system/src/lib/components/UserAvatar/UserAvatar.scss, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Components/TeamInfo.tsx, packages/amplication-client/src/Project/ProjectPage.scss, packages/amplication-client/src/Resource/ResourceOverview.tsx, packages/amplication-client/src/Workspaces/ResourceListDataColumns.tsx, packages/amplication-client/src/Workspaces/ResourceOwner.tsx, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20241026064420_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/ownership/dto/EnumOwnershipType.ts, packages/amplication-server/src/core/ownership/dto/Owner.ts, packages/amplication-server/src/core/ownership/dto/Ownership.ts, packages/amplication-server/src/core/ownership/ownership.module.ts, packages/amplication-server/src/core/ownership/ownership.service.spec.ts, packages/amplication-server/src/core/ownership/ownership.service.ts, packages/amplication-server/src/core/resource/resource.module.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/models/Resource.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/amplication/issues/9176
- Add a new generic service Ownership 
- Add support for settings ownership for resources
=> feat(server):resource ownership

ee/packages/git-sync-manager/src/models.ts, libs/ui/design-system/src/lib/components/Dialog/Dialog.scss, libs/ui/design-system/src/lib/components/UserAvatar/UserAvatar.scss, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Components/TeamInfo.tsx, packages/amplication-client/src/Project/ProjectPage.scss, packages/amplication-client/src/Resource/ResourceOverview.tsx, packages/amplication-client/src/ServiceTemplate/NewServiceFromTemplate.tsx, packages/amplication-client/src/ServiceTemplate/NewServiceFromTemplateDialogWithUrlTrigger.tsx, packages/amplication-client/src/Workspaces/ResourceListDataColumns.tsx, packages/amplication-client/src/Workspaces/ResourceOwner.tsx, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20241026064420_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/ownership/dto/EnumOwnershipType.ts, packages/amplication-server/src/core/ownership/dto/Owner.ts, packages/amplication-server/src/core/ownership/dto/Ownership.ts, packages/amplication-server/src/core/ownership/ownership.module.ts, packages/amplication-server/src/core/ownership/ownership.service.spec.ts, packages/amplication-server/src/core/ownership/ownership.service.ts, packages/amplication-server/src/core/resource/resource.module.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/models/Resource.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/amplication/issues/9173
=> style(client):update the style of new service from template modal

libs/ui/design-system/src/lib/components/Tabs/Tabs.scss, packages/amplication-client/src/Assistant/Assistant.tsx
Close: https://github.com/amplication/amplication/issues/9185
=> feat(client):update navigation

libs/schema-registry/src/index.ts, libs/schema-registry/src/lib/tech-debt/index.ts, libs/schema-registry/src/lib/tech-debt/key.ts, libs/schema-registry/src/lib/tech-debt/value.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.module.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.spec.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts, packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/core/resourceVersion/resourceVersion.service.ts, packages/notification-service/src/app.controller.ts, packages/notification-service/src/app.service.ts, packages/notification-service/src/notification-packages/techDebtAlert.ts
Close: #9229 #9230 
Add novu notifications for tech-debt alerts: 
- templates
- private-plugins
=> feat(server/notification-service): add novu notifications

libs/util/git/src/git-client.service.ts, packages/amplication-client/src/PrivatePluginVersion/NewPrivatePluginVersion.tsx, packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts
Close: #9006 
Add support to pp dev version.
=> feat(client/server): add support to pp dev version

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Project/ProjectAccessForm.tsx, packages/amplication-client/src/Project/ProjectPlatformSettingsPage.tsx, packages/amplication-client/src/Project/useProjectConfigSettingsHook.tsx, packages/amplication-client/src/Workspaces/queries/projectQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-client/src/routes/appRoutes.tsx, packages/amplication-prisma-db/prisma/migrations/20241110135627_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/project/dto/ProjectUpdateInput.ts, packages/amplication-server/src/models/Project.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/amplication/issues/9276
=> feat(client):update platform access settings

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Catalog/CatalogDataColumns.tsx, packages/amplication-client/src/Catalog/OwnerFilter.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts, packages/amplication-client/src/Project/ProjectAccessForm.tsx, packages/amplication-client/src/Project/ProjectPlatformSettingsPage.tsx, packages/amplication-client/src/Project/useProjectConfigSettingsHook.tsx, packages/amplication-client/src/Workspaces/queries/projectQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-client/src/routes/appRoutes.tsx, packages/amplication-prisma-db/prisma/migrations/20241110135627_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/ownership/dto/OwnershipWhereInput.ts, packages/amplication-server/src/core/project/dto/ProjectUpdateInput.ts, packages/amplication-server/src/core/resource/dto/ResourceWhereInput.ts, packages/amplication-server/src/models/Project.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/amplication/issues/9274
=> feat(client):catalog owner filter

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Catalog/CatalogDataColumns.tsx, packages/amplication-client/src/Catalog/OwnerFilter.tsx, packages/amplication-client/src/Catalog/ResourceTypeFilter.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts, packages/amplication-client/src/Project/ProjectAccessForm.tsx, packages/amplication-client/src/Project/ProjectPlatformSettingsPage.tsx, packages/amplication-client/src/Project/useProjectConfigSettingsHook.tsx, packages/amplication-client/src/Workspaces/queries/projectQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-client/src/routes/appRoutes.tsx, packages/amplication-prisma-db/prisma/migrations/20241110135627_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/ownership/dto/OwnershipWhereInput.ts, packages/amplication-server/src/core/project/dto/ProjectUpdateInput.ts, packages/amplication-server/src/core/resource/dto/ResourceWhereInput.ts, packages/amplication-server/src/models/Project.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts
Close: https://github.com/amplication/amplication/issues/9272
Resource type filter
=> feat(client):catalog resource type filter

packages/amplication-client/src/PrivatePluginVersion/NewPrivatePluginVersion.tsx, packages/amplication-client/src/PrivatePluginVersion/PrivatePluginDevVersion.tsx, packages/amplication-client/src/PrivatePluginVersion/PrivatePluginVersionList.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginForm.tsx, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts
Close: https://github.com/amplication/amplication/issues/9286
=> feat(client):use a separate section for the dev version

ee/packages/git-sync-manager/src/models.ts, libs/ui/design-system/src/lib/components/DataGrid/DataGrid.tsx, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Catalog/Catalog.scss, packages/amplication-client/src/Catalog/Catalog.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts, packages/amplication-client/src/Catalog/queries/catalogQueries.ts, packages/amplication-client/src/VersionControl/hooks/useCommits.ts, packages/amplication-client/src/models.ts, packages/amplication-client/src/util/useQueryPagination.tsx, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.spec.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/dto/PaginatedQueryResult.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
=> fix(server):trigger alerts for templates

ee/packages/git-sync-manager/src/models.ts, libs/ui/design-system/src/lib/components/DataGrid/DataGrid.tsx, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Catalog/Catalog.scss, packages/amplication-client/src/Catalog/Catalog.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts, packages/amplication-client/src/Catalog/queries/catalogQueries.ts, packages/amplication-client/src/OutdatedVersionAlerts/OutdatedVersionAlertList.tsx, packages/amplication-client/src/OutdatedVersionAlerts/hooks/useOutdatedVersionAlerts.ts, packages/amplication-client/src/VersionControl/hooks/useCommits.ts, packages/amplication-client/src/models.ts, packages/amplication-client/src/util/useQueryPagination.tsx, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.spec.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/dto/PaginatedQueryResult.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
Close: https://github.com/amplication/amplication/issues/9338
=> feat(client):use query pagination

packages/amplication-client/src/Catalog/ResourceTypeFilter.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts
Close: https://github.com/amplication/amplication/issues/9345
=> feat(client):exclude the project resources from the catalog

libs/ui/design-system/src/lib/components/Toggle/Toggle.scss, packages/amplication-client/src/Resource/git/ServiceConfigurationGitSettings.tsx, packages/amplication-client/src/Resource/git/ServiceWizardConfigurationGitSettings.tsx, packages/amplication-client/src/Resource/git/SyncWithGithubPage.tsx
Close:https://github.com/amplication/amplication/issues/9347
=> style(client):redesign override project settings

packages/generator-blueprints/src/utils/read-static-files.ts
Close: https://github.com/amplication/amplication/issues/9352
=> fix(bpg):remove filter readPluginStaticFiles

packages/amplication-server/src/core/privatePlugin/privatePlugin.module.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.spec.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts, packages/amplication-server/src/core/resource/dto/ResourceInclude.ts, packages/amplication-server/src/core/resource/dto/ResourceWhereInput.ts, packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/amplication/issues/9355
=> feat(server):return plugins from shared platform projects

packages/amplication-client/src/Workspaces/hooks/useResources.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.module.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.spec.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts, packages/amplication-server/src/core/resource/dto/ResourceInclude.ts, packages/amplication-server/src/core/resource/dto/ResourceWhereInput.ts, packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/amplication/issues/9353
=> fix(client):update catalog after resource creation

.github/workflows/release.blueprint-dsg.production.yml
Close: https://github.com/amplication/amplication/issues/9360
=> chore(bpg):update workflow

packages/amplication-client/src/PrivatePlugins/AvailableRemotePrivatePluginList.tsx, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.spec.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts
Close: https://github.com/amplication/amplication/issues/9364
=> feat(server):validate pluginId

packages/amplication-client/src/VersionControl/hooks/commitQueries.ts, packages/amplication-client/src/VersionControl/hooks/useCommits.ts, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts
=> perf(client):improve resources and commits queries

packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx, packages/amplication-client/src/Plugins/InstalledPluginVersionIndicator.tsx, packages/amplication-client/src/Plugins/hooks/usePluginCatalog.ts, packages/amplication-client/src/Plugins/hooks/usePlugins.ts
Close: https://github.com/amplication/amplication/issues/9376
=> feat(client):show last build version

.vscode/launch.json, packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx, packages/amplication-client/src/Plugins/InstalledPluginVersionIndicator.tsx, packages/amplication-client/src/Plugins/hooks/usePluginCatalog.ts, packages/amplication-client/src/Plugins/hooks/usePlugins.ts, packages/amplication-plugin-api/src/plugin/plugin.resolver.ts, packages/amplication-plugin-api/src/plugin/plugin.service.ts, packages/amplication-plugin-api/src/pluginVersion/npm-plugin-version.service.ts, packages/amplication-plugin-api/src/pluginVersion/pluginVersion.service.ts
Close: https://github.com/amplication/amplication/issues/9375
=> perf(plugin-api): do not update settings for existing versions

packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts
Close: https://github.com/amplication/amplication/issues/9377
=> feat(server):use last build plugin version for tech debt alert

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-server/src/core/git/dto/inputs/GitOrganizationOrderByInput.ts, packages/amplication-server/src/core/git/dto/inputs/GitRepositoryOrderByInput.ts, packages/amplication-server/src/core/resource/dto/ResourceOrderByInput.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
=> feat(server):catalog server side sorting

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/OutdatedVersionAlerts/OutdatedVersionAlertList.tsx, packages/amplication-client/src/OutdatedVersionAlerts/OutdatedVersionAlertListDataColumns.tsx, packages/amplication-server/src/core/git/dto/inputs/GitOrganizationOrderByInput.ts, packages/amplication-server/src/core/git/dto/inputs/GitRepositoryOrderByInput.ts, packages/amplication-server/src/core/resource/dto/ResourceOrderByInput.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
Close: https://github.com/amplication/amplication/issues/9381
=> style(client):tech debt list and columns width

packages/amplication-client/src/Blueprints/ResourceSelectField.tsx
Close: https://github.com/amplication/amplication/issues/9399
=> fix(client):resource select field page size

libs/util/code-gen-types/README.md, libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/code-gen-types.ts, libs/util/code-gen-types/src/dsg-resource-data.ts, packages/amplication-server/src/core/build/build.module.ts, packages/amplication-server/src/core/build/build.service.spec.ts, packages/amplication-server/src/core/build/build.service.ts, packages/generator-blueprints/src/dsg-context.ts, packages/generator-blueprints/src/prepare-context.ts
Close: https://github.com/amplication/amplication/issues/9405
=> feat(bpg):use resource settings

packages/amplication-client/src/Catalog/CatalogDataColumns.tsx, packages/amplication-client/src/Catalog/CatalogGrid.tsx, packages/amplication-client/src/Catalog/ResourceTypeFilter.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts
Close: https://github.com/amplication/amplication/issues/9414
=> feat(client):blueprint filter

libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.scss, libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.stories.tsx, libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.tsx, libs/ui/design-system/src/lib/index.ts
Close: https://github.com/amplication/amplication/issues/9418
=> feat(design-system):select panel

libs/ui/design-system/src/lib/components/DataGrid/DataGridColumnFilter.tsx, libs/ui/design-system/src/lib/components/DataGrid/DataGridFilters.tsx, packages/amplication-client/src/Catalog/CatalogGraph/CatalogGraph.tsx, packages/amplication-client/src/Catalog/CatalogGraph/CatalogGroupBySelector.tsx, packages/amplication-client/src/Catalog/CatalogGraph/LayoutSettings.scss, packages/amplication-client/src/Catalog/CatalogGraph/LayoutSettings.tsx, packages/amplication-client/src/Catalog/CatalogGraph/helpers.ts, packages/amplication-client/src/Catalog/CatalogGraph/hooks/useCatalogGraph.tsx, packages/amplication-client/src/Catalog/CatalogGraph/layout.ts, packages/amplication-client/src/Catalog/CatalogGraph/types.ts
Close:  https://github.com/amplication/amplication/issues/9424
=> feat(client):layout settings

libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.tsx, packages/amplication-client/src/Catalog/CatalogGraph/CatalogGraph.tsx, packages/amplication-client/src/Catalog/CatalogGraph/CatalogGroupBySelector.tsx, packages/amplication-client/src/Catalog/CatalogGraph/hooks/useCatalogGraph.tsx, packages/amplication-client/src/Catalog/CatalogGraph/nodes/GroupNode.scss, packages/amplication-client/src/Catalog/CatalogGraph/types.ts, packages/amplication-client/src/util/useLocalStorageData.tsx
Close: https://github.com/amplication/amplication/issues/9426
=> feat(client):catalog graph save state

packages/amplication-client/src/Catalog/CatalogGraph/nodes/GroupNode.tsx
Close: https://github.com/amplication/amplication/issues/9428
=> fix(client):blueprint group color

packages/amplication-client/src/Catalog/CatalogGrid.tsx
Close: https://github.com/amplication/amplication/issues/9432
=> fix(client):catalog cols order

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/code-gen-types.ts, packages/amplication-client/src/Catalog/CatalogGraph/nodes/GroupNode.tsx, packages/amplication-server/src/core/build/build.service.ts
Close: https://github.com/amplication/amplication/issues/9430
=> feat(server):send resource properties to DSG

packages/amplication-client/src/Blueprints/BlueprintsGraph/helpers.ts, packages/amplication-client/src/Catalog/CatalogGraph/hooks/useCatalogGraph.tsx, packages/amplication-client/src/Catalog/CatalogGraph/layout.ts, packages/amplication-client/src/Plugins/InstalledPluginVersionIndicator.tsx, packages/amplication-client/src/PrivatePlugins/AvailableRemotePrivatePluginList.tsx, packages/amplication-client/src/VersionControl/PublishChangesPage.tsx, packages/amplication-client/src/util/useQueryPagination.tsx
Close: https://github.com/amplication/amplication/issues/9434
=> chore(client):remove console.log

packages/amplication-client/src/Catalog/CatalogGraph/helpers.ts, packages/amplication-client/src/Catalog/CatalogGraph/nodes/GroupNode.scss, packages/amplication-client/src/Catalog/CatalogGraph/nodes/GroupNode.tsx, packages/amplication-client/src/Catalog/CatalogGraph/types.ts
Close: https://github.com/amplication/amplication/issues/9439
=> feat(client):add toolbar with title for group nodes

packages/amplication-client/src/Catalog/CatalogGraph/CatalogGroupBySelector.tsx, packages/amplication-client/src/Catalog/ResourceTypeFilter.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts
Close: https://github.com/amplication/amplication/issues/9442
=> feat(client): exclude resource types from the catalog

packages/amplication-client/src/Catalog/CatalogGraph/CatalogGroupBySelector.tsx
Close: https://github.com/amplication/amplication/issues/9444
=> fix(client):show the group name

libs/ui/design-system/src/lib/components/Breadcrumbs/Breadcrumbs.scss, libs/ui/design-system/src/lib/components/Breadcrumbs/Breadcrumbs.tsx, libs/ui/design-system/src/lib/components/DataGrid/DataGrid.tsx, libs/ui/design-system/src/lib/components/DataGrid/DataGridFilters.tsx, libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.tsx, packages/amplication-client/src/Catalog/CatalogGrid.tsx, packages/amplication-client/src/Components/ProjectSelector.tsx, packages/amplication-client/src/CustomProperties/CustomPropertyFilter.tsx, packages/amplication-client/src/Platform/ProjectPlatformPage.tsx, packages/amplication-client/src/Project/ProjectPage.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Close: https://github.com/amplication/amplication/issues/9445
=> feat(client):project selector

libs/ui/design-system/src/lib/components/DataGrid/DataGridFilters.tsx, packages/amplication-client/src/Catalog/Catalog.tsx, packages/amplication-client/src/Catalog/CatalogGraph/CatalogGraph.tsx, packages/amplication-client/src/Catalog/CatalogGrid.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx
=> fix(client):project switch

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/code-gen-types.ts, libs/util/code-gen-types/src/dsg-resource-data.ts, packages/amplication-server/src/core/build/build.service.spec.ts, packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/generator-blueprints/src/dsg-context.ts, packages/generator-blueprints/src/prepare-context.ts
Close: https://github.com/amplication/amplication/issues/9452
=> feat(bpg):read relations data

packages/amplication-client/src/Components/ProjectSelector.tsx, packages/amplication-client/src/Components/ResourceSelector2.tsx, packages/amplication-client/src/Resource/ResourceHome.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx
Close: https://github.com/amplication/amplication/issues/9457
=> feat(client):resource selector

packages/amplication-client/src/Blueprints/ResourceSelectField.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts
Close: https://github.com/amplication/amplication/issues/9461
=> fix(client):filter relation by blueprint

packages/amplication-client/src/Catalog/CatalogGraph/CatalogGraph.tsx, packages/amplication-client/src/Catalog/CatalogGraph/hooks/useCatalogGraph.tsx, packages/amplication-client/src/Components/ProjectSelector.tsx, packages/amplication-client/src/Components/ResourceSelector2.tsx
Close: https://github.com/amplication/amplication/issues/9459
=> feat(client):refresh graph data

packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.module.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.service.spec.ts, packages/amplication-server/src/services/segmentAnalytics/segmentAnalytics.service.ts
Close: https://github.com/amplication/amplication/issues/9464
=> perf(server):remove subscription info from analytics

packages/amplication-server/src/core/block/block.module.ts, packages/amplication-server/src/core/module/module.module.ts, packages/amplication-server/src/core/moduleAction/moduleAction.module.ts, packages/amplication-server/src/core/moduleDto/moduleDto.module.ts
Close: https://github.com/amplication/amplication/issues/9466
=> refactor(server):import billing module instead of using billing service directly

libs/ui/design-system/src/lib/components/SelectField/SelectField.tsx, libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.tsx, packages/amplication-client/src/Catalog/Catalog.tsx, packages/amplication-client/src/Components/ProjectSelector.tsx, packages/amplication-client/src/CustomProperties/CustomPropertiesFormFields.tsx, packages/amplication-client/src/Platform/ServiceTemplateList.tsx, packages/amplication-client/src/Resource/create-resource-page/CreateResourceForm.tsx, packages/amplication-client/src/Workspaces/ResourceList.tsx
Close: https://github.com/amplication/amplication/issues/9470
=> feat(client):create resource from workspace

libs/util/roles-types/.eslintrc.json, libs/util/roles-types/README.md, libs/util/roles-types/package.json, libs/util/roles-types/project.json, libs/util/roles-types/src/index.ts, libs/util/roles-types/src/lib/roles-permissions.types.ts, libs/util/roles-types/tsconfig.json, libs/util/roles-types/tsconfig.lib.json, packages/amplication-client/src/Roles/AddRolePermission.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/Roles/RolePermissionList.tsx, packages/amplication-client/src/Roles/hooks/useRoles.tsx, tsconfig.base.json
Close: https://github.com/amplication/amplication/issues/9479
=> feat(client):show permissions list

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, libs/util/roles-types/src/lib/roles-permissions.types.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/CustomProperties/CustomPropertyList.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/Teams/Members/AddTeamMember.tsx, packages/amplication-client/src/Teams/Members/AddTeamMemberButton.tsx, packages/amplication-client/src/Teams/Members/TeamMemberList.tsx, packages/amplication-client/src/Teams/Roles/AddTeamRole.tsx, packages/amplication-client/src/Teams/Roles/AddTeamRoleButton.tsx, packages/amplication-client/src/Teams/Roles/TeamRoleList.tsx, packages/amplication-client/src/Teams/Team.tsx, packages/amplication-client/src/Teams/hooks/useTeams.tsx, packages/amplication-client/src/Teams/queries/teamsQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20241228070938_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/team/dto/AddRolesToTeamArgs.ts, packages/amplication-server/src/core/team/dto/RemoveRolesFromTeamArgs.ts, packages/amplication-server/src/core/team/dto/TeamUpdateRolesInput.ts, packages/amplication-server/src/core/team/team.resolver.ts, packages/amplication-server/src/core/team/team.service.ts, packages/amplication-server/src/models/Team.ts, packages/amplication-server/src/schema.graphql, packages/amplication-server/src/services/segmentAnalytics/segmentAnalyticsEventType.types.ts, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
Close: https://github.com/amplication/amplication/issues/9482
=> feat(client):team roles

libs/util/roles-types/src/lib/roles-permissions.types.ts, packages/amplication-client/src/Catalog/CatalogGraph/hooks/useCatalogGraph.tsx, packages/amplication-client/src/Components/OwnerSelector.tsx, packages/amplication-client/src/Resource/hooks/useResource.tsx, packages/amplication-client/src/Teams/hooks/useTeams.tsx, packages/amplication-server/src/core/auth/auth.service.spec.ts, packages/amplication-server/src/core/auth/auth.service.ts, packages/amplication-server/src/core/auth/dto/jwt.dto.ts, packages/amplication-server/src/core/auth/types.ts, packages/amplication-server/src/core/blueprint/blueprint.resolver.ts, packages/amplication-server/src/core/customProperty/customProperty.resolver.ts, packages/amplication-server/src/core/project/project.resolver.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/resource/serviceTemplate.resolver.ts, packages/amplication-server/src/core/role/role.resolver.ts, packages/amplication-server/src/core/team/team.resolver.ts, packages/amplication-server/src/core/user/user.service.ts, packages/amplication-server/src/core/workspace/workspace.service.ts, packages/amplication-server/src/decorators/permissions.decorator.ts, packages/amplication-server/src/decorators/roles.decorator.ts, packages/amplication-server/src/guards/gql-auth.guard.spec.ts, packages/amplication-server/src/guards/gql-auth.guard.ts
Close: https://github.com/amplication/amplication/issues/9486
=> feat(server):check resource permissions

packages/amplication-server/migration-scripts/create-default-team-and-role.ts, packages/amplication-server/src/core/workspace/workspace.service.spec.ts, packages/amplication-server/src/core/workspace/workspace.service.ts
Close: https://github.com/amplication/amplication/issues/9488
=> chore(migration):add data migration for default team and role for existing workspaces

packages/amplication-server/migration-scripts/create-default-team-and-role.ts
Close: https://github.com/amplication/amplication/issues/9490
=> chore(migration):update migration script

packages/amplication-server/src/core/assistant/assistant.resolver.ts, packages/amplication-server/src/core/assistant/assistant.service.spec.ts, packages/amplication-server/src/core/assistant/assistantFunctions.service.spec.ts, packages/amplication-server/src/core/assistant/dto/AssistantContext.ts, packages/amplication-server/src/core/permissions/permissions.service.spec.ts, packages/amplication-server/src/core/permissions/permissions.service.ts, packages/amplication-server/src/core/permissions/validation-functions.ts, packages/amplication-server/src/decorators/authorizeContext.decorator.ts, packages/amplication-server/src/guards/gql-auth.guard.ts
Close: https://github.com/amplication/amplication/issues/9499
=> refactor(server):refactor permissions service

packages/amplication-server/src/core/assistant/assistantFunctions.service.spec.ts, packages/amplication-server/src/core/assistant/assistantFunctions.service.ts, packages/amplication-server/src/core/customProperty/customProperty.resolver.ts, packages/amplication-server/src/core/permissions/permissions.service.spec.ts, packages/amplication-server/src/core/permissions/permissions.service.ts, packages/amplication-server/src/core/permissions/validation-functions.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/decorators/authorizeContext.decorator.ts, packages/amplication-server/src/decorators/injectContextValue.decorator.ts, packages/amplication-server/src/decorators/permissions.decorator.ts, packages/amplication-server/src/enums/AuthorizableOriginParameter.ts, packages/amplication-server/src/guards/gql-auth.guard.spec.ts, packages/amplication-server/src/guards/gql-auth.guard.ts
Close: https://github.com/amplication/amplication/issues/9504
=> feat(server):validate access on resource level

packages/amplication-server/src/core/assistant/assistantFunctions.service.spec.ts, packages/amplication-server/src/core/assistant/assistantFunctions.service.ts, packages/amplication-server/src/core/customProperty/customProperty.resolver.ts, packages/amplication-server/src/core/permissions/permissions.service.spec.ts, packages/amplication-server/src/core/permissions/permissions.service.ts, packages/amplication-server/src/core/permissions/validation-functions.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/user/user.resolver.ts, packages/amplication-server/src/decorators/authorizeContext.decorator.ts, packages/amplication-server/src/decorators/injectContextValue.decorator.ts, packages/amplication-server/src/decorators/permissions.decorator.ts, packages/amplication-server/src/enums/AuthorizableOriginParameter.ts, packages/amplication-server/src/guards/gql-auth.guard.spec.ts, packages/amplication-server/src/guards/gql-auth.guard.ts
Close: https://github.com/amplication/amplication/issues/9501
=> feat(server):validate access per user ID

packages/amplication-client/src/Resource/create-resource-page/CreateResourceForm.tsx
Close: https://github.com/amplication/amplication/issues/9505
=> fix(client):handle errors

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Teams/Members/TeamMemberList.tsx, packages/amplication-client/src/Teams/hooks/useTeams.tsx, packages/amplication-client/src/Teams/queries/teamsQueries.ts, packages/amplication-client/src/User/User.tsx, packages/amplication-client/src/User/UserAddTeams.tsx, packages/amplication-client/src/User/UserAddTeamsButton.tsx, packages/amplication-client/src/models.ts, packages/amplication-server/src/core/team/dto/AddMemberToTeamsArgs.ts, packages/amplication-server/src/core/team/dto/AddMemberToTeamsInput.ts, packages/amplication-server/src/core/team/team.resolver.ts, packages/amplication-server/src/core/team/team.service.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
Close:https://github.com/amplication/amplication/issues/9507
=> feat(client):add user to teams

libs/util/roles-types/src/lib/roles-permissions.types.ts, packages/amplication-client/src/Components/FeatureIndicatorContainer.tsx, packages/amplication-client/src/CustomProperties/CustomProperty.tsx, packages/amplication-client/src/CustomProperties/CustomPropertyList.tsx, packages/amplication-client/src/CustomProperties/CustomPropertyOptions/CustomPropertyOption.tsx, packages/amplication-client/src/CustomProperties/CustomPropertyOptions/CustomPropertyOptionForm.tsx, packages/amplication-client/src/CustomProperties/CustomPropertyOptions/CustomPropertyOptionList.tsx, packages/amplication-client/src/Project/AddNewProject.tsx, packages/amplication-client/src/Project/NewProject.tsx, packages/amplication-client/src/Resource/git/GitActions/ExistingConnectionsMenu.tsx, packages/amplication-client/src/Teams/Members/TeamMemberList.tsx, packages/amplication-client/src/Teams/Roles/TeamRoleList.tsx, packages/amplication-client/src/Teams/Team.tsx, packages/amplication-client/src/Teams/TeamForm.tsx, packages/amplication-client/src/Workspaces/InviteMember.tsx, packages/amplication-client/src/Workspaces/MemberList.tsx, packages/amplication-client/src/Workspaces/MemberListItem.tsx, packages/amplication-client/src/Workspaces/hooks/usePermissions.ts, packages/amplication-server/src/core/git/git.resolver.ts, packages/amplication-server/src/core/project/project.resolver.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/team/team.resolver.ts, packages/amplication-server/src/core/workspace/workspace.resolver.spec.ts, packages/amplication-server/src/core/workspace/workspace.resolver.ts, packages/amplication-server/src/core/workspace/workspace.service.spec.ts, packages/amplication-server/src/core/workspace/workspace.service.ts
https://github.com/amplication/amplication/issues/9509
=> feat:validate permissions

packages/amplication-client/src/Resource/git/queries/gitProvider.ts, packages/amplication-client/src/Resource/git/useResourceGitSettings.ts, packages/amplication-server/src/core/git/dto/args/CreateGitRepositoryBaseArgs.ts, packages/amplication-server/src/core/git/git.provider.service.ts, packages/amplication-server/src/core/git/git.resolver.ts
Close: https://github.com/amplication/amplication/issues/9512
=> refactor:rename mutation name connectResourceToNewRemoteGitRepository

libs/util/roles-types/src/lib/roles-permissions.types.ts, packages/amplication-client/src/Project/ProjectFormPage.tsx, packages/amplication-server/src/core/git/git.resolver.ts, packages/amplication-server/src/core/project/project.resolver.ts, packages/amplication-server/src/core/resource/resource.service.ts
=> feat(server):enforce git.repo.select

libs/util/roles-types/src/lib/roles-permissions.types.ts, packages/amplication-client/src/CustomProperties/CustomPropertiesFormField.tsx, packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldLink.tsx, packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldMultiSelect.tsx, packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldSelect.tsx, packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldText.tsx, packages/amplication-client/src/CustomProperties/CustomPropertiesFormFields.tsx, packages/amplication-client/src/Project/ProjectFormPage.tsx, packages/amplication-client/src/Resource/ResourceForm.tsx, packages/amplication-client/src/Resource/ResourceFormPage.tsx, packages/amplication-client/src/Resource/create-resource-page/CreateResourceForm.tsx, packages/amplication-client/src/ResourceSettings/ResourceSettingsFormFields.tsx, packages/amplication-server/src/core/auth/auth.resolver.spec.ts, packages/amplication-server/src/core/project/project.resolver.ts
=> feat(client):project edit permissions

packages/amplication-server/src/core/workspace/workspace.service.spec.ts, packages/amplication-server/src/core/workspace/workspace.service.ts
Close: #9520 
- Refactored `createDefaultTeam()` function into `createDefaultTeams()`
- Removed `DEFAULT_ADMINS_TEAM` and `DEFAULT_ADMINS_ROLE` arrays in favor of `DEFAULT_TEAMS_AND_ROLES` array
=> feat(server): refactor createDefaultTeam() to accept multiple teams and roles

libs/util/roles-types/src/lib/roles-permissions.types.ts, packages/amplication-client/src/Project/ProjectAccessForm.tsx, packages/amplication-client/src/Resource/hooks/useResourcePermissions.ts
Close: https://github.com/amplication/amplication/issues/9510
=> feat(client):validate edit platform settings 

packages/amplication-client/src/Catalog/CatalogDataColumns.tsx, packages/amplication-client/src/Platform/ServiceTemplateListDataColumns.tsx, packages/amplication-client/src/Resource/ResourceFormPage.tsx, packages/amplication-client/src/Workspaces/DeleteResourceButton.tsx
part of https://github.com/amplication/amplication/issues/9510
=> feat(client):move delete into resource and enforce permissions

packages/amplication-client/src/Resource/git/GitActions/RepositoryActions/RepositoryActions.tsx
Close: https://github.com/amplication/amplication/issues/9524
=> feat(client):validate git select

libs/util/roles-types/src/lib/roles-permissions.types.ts, packages/amplication-client/src/ResourceSettings/ResourceSettingsForm.tsx, packages/amplication-client/src/routes/appRoutes.tsx, packages/amplication-server/src/core/auth/auth.resolver.ts, packages/amplication-server/src/core/block/blockType.resolver.ts, packages/amplication-server/src/core/blueprint/blueprint.resolver.ts, packages/amplication-server/src/core/dbSchemaImport/dbSchemaImport.resolver.ts, packages/amplication-server/src/core/entity/entity.resolver.ts, packages/amplication-server/src/core/moduleDto/moduleDto.resolver.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.resolver.ts, packages/amplication-server/src/core/pluginInstallation/pluginInstallation.resolver.ts, packages/amplication-server/src/core/privatePlugin/privatePlugin.resolver.ts, packages/amplication-server/src/core/projectConfigurationSettings/projectConfigurationSettings.resolver.ts, packages/amplication-server/src/core/relation/relation.resolver.ts, packages/amplication-server/src/core/resource/resourceBtm.resolver.ts, packages/amplication-server/src/core/resource/serviceTemplate.resolver.ts, packages/amplication-server/src/core/resourceRole/resourceRole.resolver.ts, packages/amplication-server/src/core/resourceSettings/resourceSettings.resolver.ts, packages/amplication-server/src/core/role/role.resolver.ts, packages/amplication-server/src/core/serviceSettings/serviceSettings.resolver.ts, packages/amplication-server/src/core/team/team.resolver.ts, packages/amplication-server/src/core/team/team.service.ts
Close: https://github.com/amplication/amplication/issues/9509
=> feat(server):add permissions validations on all mutations

packages/amplication-client/src/Roles/Role.tsx, packages/amplication-client/src/Roles/RoleForm.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-client/src/Roles/RolePermissionList.tsx, packages/amplication-client/src/Teams/TeamList.tsx, packages/amplication-client/src/User/User.tsx, packages/amplication-client/src/User/UserAddTeamsButton.tsx
Close: https://github.com/amplication/amplication/issues/9510
=> feat(client):validate role and team permissions

packages/amplication-client/src/Components/BetaFeatureTag.tsx, packages/amplication-client/src/CustomProperties/DeleteCustomProperty.tsx, packages/amplication-client/src/Platform/ProjectPlatformPage.tsx, packages/amplication-client/src/Project/ProjectPage.tsx, packages/amplication-client/src/Roles/RoleList.tsx, packages/amplication-server/src/core/git/git.provider.service.ts, packages/amplication-server/src/core/git/git.resolver.ts, packages/amplication-server/src/core/ownership/ownership.service.spec.ts, packages/amplication-server/src/core/ownership/ownership.service.ts
Close: https://github.com/amplication/amplication/issues/9538
=> feat: add beta indicator for roles module

packages/amplication-client/src/VersionControl/ChangesPage.tsx, packages/amplication-client/src/VersionControl/CommitPage.tsx, packages/amplication-client/src/VersionControl/CommitResourceList.tsx, packages/amplication-client/src/VersionControl/CommitResourceListItem.tsx, packages/amplication-client/src/VersionControl/hooks/commitQueries.ts, packages/amplication-client/src/VersionControl/hooks/useCommitChanges.ts, packages/amplication-client/src/VersionControl/hooks/useCommits.ts, packages/amplication-client/src/context/appContext.tsx, packages/amplication-server/src/core/build/build.resolver.ts, packages/amplication-server/src/core/commit/commit.resolver.spec.ts, packages/amplication-server/src/core/commit/commit.resolver.ts, packages/amplication-server/src/core/commit/commit.service.spec.ts, packages/amplication-server/src/core/commit/commit.service.ts, packages/amplication-server/src/core/permissions/validation-functions.ts, packages/amplication-server/src/core/user/user.resolver.ts
Close: https://github.com/amplication/amplication/issues/9541
=> perf:improve commits query performance

packages/amplication-server/jest.config.ts
=> test(server):update coverage

packages/amplication-client/src/Catalog/hooks/useCatalog.ts
Close: https://github.com/amplication/amplication/issues/9557
=> fix(client):show services based on resource type

packages/amplication-server/src/core/build/build.resolver.ts, packages/amplication-server/src/core/user/user.resolver.ts
Close: https://github.com/amplication/amplication/issues/9561
=> fix(server):change condition to handle undefined properties

packages/amplication-client/src/Components/CodeGeneratorImage.tsx, packages/amplication-client/src/Components/CreateResourceButton.tsx, packages/amplication-client/src/Components/ResourceTypeBadge.tsx, packages/amplication-client/src/Resource/CreateTemplateFromResourceButton.tsx, packages/amplication-client/src/Resource/ResourceOverview/ComponentOverview.tsx, packages/amplication-client/src/Resource/ResourceOverview/ResourceOverview.tsx, packages/amplication-client/src/Resource/resourceSettings/ServiceSettingsPage.tsx, packages/amplication-client/src/ServiceTemplate/hooks/serviceTemplateQueries.ts, packages/amplication-client/src/ServiceTemplate/hooks/useServiceTemplate.ts, packages/amplication-client/src/VersionControl/PendingChange.tsx
Part of: https://github.com/amplication/amplication/issues/9568
=> feat(client):create template from resource

packages/amplication-client/src/Catalog/ResourceTypeFilter.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts, packages/amplication-client/src/Platform/ServiceTemplateChip.tsx
Close: https://github.com/amplication/amplication/issues/9571
=> feat(client):exclude templates from catalog

packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.scss, packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/GitCreateRepo.tsx, packages/amplication-client/src/Resource/git/dialogs/GitCreateRepo/WizardGitCreateRepo.tsx
Close: https://github.com/amplication/amplication/issues/9573
=> feat(client):set repo as private by default

packages/amplication-client/src/ServiceTemplate/NewServiceFromTemplate.tsx, packages/amplication-client/src/Workspaces/hooks/useResources.ts, packages/amplication-client/src/context/appContext.tsx
Close: https://github.com/amplication/amplication/issues/9575
=> feat(client):reload catalog after creating a resource from template

packages/amplication-client/src/Plugins/InstalledPlugins.tsx, packages/amplication-client/src/Plugins/PluginTree.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginEditCodeButton.tsx
Close: https://github.com/amplication/amplication/issues/9577
=> feat(client):show installed plugins tab first

libs/ui/design-system/src/lib/components/LabelValuePairsBlock/LabelValuePairsBlock.scss, libs/ui/design-system/src/lib/components/LabelValuePairsBlock/LabelValuePairsBlock.stories.tsx, libs/ui/design-system/src/lib/components/LabelValuePairsBlock/LabelValuePairsBlock.tsx, libs/ui/design-system/src/lib/components/LabelValuePairsBlock/LabelValuePairsBlockItem.tsx, libs/ui/design-system/src/lib/index.ts, packages/amplication-client/src/CustomProperties/CustomPropertyValue.tsx, packages/amplication-client/src/CustomProperties/ResourcePropertiesBlock.tsx, packages/amplication-client/src/Relation/ResourceRelationForm.tsx, packages/amplication-client/src/Relation/ResourceRelations.tsx, packages/amplication-client/src/Resource/ResourceOverview/ComponentOverview.tsx, packages/amplication-client/src/Resource/ResourceOverview/ResourceOverview.tsx
Close: https://github.com/amplication/amplication/issues/9581
=> feat(client):show resource properties and settings in overview tab

packages/amplication-prisma-db/prisma/migrations/20250119075149_migrate_templae_version_data/migration.sql
Close: https://github.com/amplication/amplication/issues/9588
=> migrate(db):date migration for the new template version block

packages/amplication-server/src/core/assistant/assistantFunctions.service.ts
Close: https://github.com/amplication/amplication/issues/9612
=> feat(server):jovu plugins

packages/amplication-client/src/CustomProperties/CustomPropertiesFormFieldSelect.tsx, packages/amplication-client/src/CustomProperties/getPropertiesValidationSchemaUtil.ts, packages/amplication-client/src/Resource/ResourceForm.tsx, packages/amplication-client/src/Resource/create-resource-page/CreateResourceForm.tsx
Close: https://github.com/amplication/amplication/issues/9614
=> fix(client):set properties requirement

packages/amplication-server/src/core/outdatedVersionAlert/dto/OutdatedVersionAlertWhereInput.ts, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.resolver.ts
Close: https://github.com/amplication/amplication/issues/9616
=> feat(server):allow fetching alerts per workspace

packages/amplication-client/src/Components/TemplateSelectField.tsx, packages/amplication-client/src/ServiceTemplate/hooks/serviceTemplateQueries.ts, packages/amplication-server/src/core/resource/serviceTemplate.service.ts
=> feat(client):do not show disabled templates

packages/amplication-client/src/Blueprints/BlueprintSelectField.tsx, packages/amplication-server/src/core/resource/resource.service.ts
=> feat(client):do not show blueprints of disabled templates

libs/ui/design-system/src/lib/components/DataGrid/DataGridFilter.tsx, libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.tsx
Close: https://github.com/amplication/amplication/issues/9630
=> feat(design-system):auto open filter when added

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/Plugins/InstalledPlugins.tsx, packages/amplication-client/src/Plugins/PluginInstallConfirmationDialog.tsx, packages/amplication-client/src/Plugins/PluginsCatalog.tsx, packages/amplication-client/src/Workspaces/queries/entitiesQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-server/src/core/assistant/assistantFunctions.service.spec.ts, packages/amplication-server/src/core/assistant/assistantFunctions.service.ts, packages/amplication-server/src/core/entity/constants.ts, packages/amplication-server/src/core/entity/entity.resolver.ts, packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/core/resource/resource.service.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
Close: https://github.com/amplication/amplication/issues/9637
Update the auth entity when creating the default user entity
=> feat(client):update mutation name

packages/amplication-client/src/Assistant/hooks/useAssistant.tsx, packages/amplication-client/src/Entity/NewEntity.tsx, packages/amplication-client/src/Plugins/InstalledPlugins.tsx, packages/amplication-client/src/Plugins/PluginsCatalog.tsx, packages/amplication-client/src/VersionControl/DiscardChanges.tsx
Close: https://github.com/amplication/amplication/issues/9638
=> fix(client):update-cache

libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.scss, libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.tsx, packages/amplication-client/src/Resource/create-resource-page/CreateResourceForm.tsx
Close: https://github.com/amplication/amplication/issues/9640
=> feat(client):improve create resource flow

libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.tsx
Close: https://github.com/amplication/amplication/issues/9643
=> fix(design-system): Add optional chaining to prevent potential null options error

packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts, packages/amplication-server/src/core/git/git.provider.service.ts
Close: https://github.com/amplication/amplication/issues/9648
=> fix(server):disconnect repo when overriding project settings

libs/ui/design-system/src/lib/components/SelectPanel/SelectPanelField.scss, libs/ui/design-system/src/lib/components/SelectPanel/SelectPanelField.tsx, libs/ui/design-system/src/lib/components/TextInput/TextInput.scss
Close: https://github.com/amplication/amplication/issues/9650
=> fix(client):show validation message for SelectPanelField

packages/amplication-client/src/CustomProperties/getPropertiesValidationSchemaUtil.ts, packages/amplication-server/src/core/customProperty/customProperty.service.ts
Close: https://github.com/amplication/amplication/issues/9652
=> fix: allow null for non required fields

libs/ui/design-system/src/lib/components/DataGrid/DataGrid.tsx, libs/ui/design-system/src/lib/components/DataGrid/DataGridFilter.tsx, libs/ui/design-system/src/lib/components/DataGrid/DataGridFilters.tsx, packages/amplication-client/src/Blueprints/Blueprint.tsx, packages/amplication-client/src/Catalog/BlueprintFilter.tsx, packages/amplication-client/src/Catalog/OwnerFilter.tsx, packages/amplication-client/src/Catalog/ProjectFilter.tsx, packages/amplication-client/src/CustomProperties/CustomPropertyFilter.tsx
Close: https://github.com/amplication/amplication/issues/9655
=> feat(client):view blueprint resources

libs/ui/design-system/src/lib/components/DataGrid/DataGridFilters.tsx
=> fix(client):fix initial filters value

ee/packages/git-sync-manager/src/models.ts, libs/ui/design-system/src/lib/components/SelectPanel/SelectPanel.tsx, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Blueprints/BlueprintForm.tsx, packages/amplication-client/src/Blueprints/queries/blueprintsQueries.ts, packages/amplication-client/src/Components/ResourceSelector2.tsx, packages/amplication-client/src/Resource/ResourceHome.tsx, packages/amplication-client/src/Resource/ResourceOverview/ComponentOverview.tsx, packages/amplication-client/src/Resource/ResourceOverview/ResourceOverview.tsx, packages/amplication-client/src/Resource/resourceMenuUtils.ts, packages/amplication-client/src/Workspaces/queries/resourcesQueries.ts, packages/amplication-client/src/models.ts, packages/amplication-prisma-db/prisma/migrations/20250206175021_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/blueprint/blueprint.resolver.ts, packages/amplication-server/src/core/blueprint/blueprint.service.spec.ts, packages/amplication-server/src/core/blueprint/blueprint.service.ts, packages/amplication-server/src/core/blueprint/dto/BlueprintUpdateInput.ts, packages/amplication-server/src/core/resource/serviceTemplate.service.spec.ts, packages/amplication-server/src/core/workspace/constants.ts, packages/amplication-server/src/models/Blueprint.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
Close: https://github.com/amplication/amplication/issues/9660
=> feat: blueprint business domain features

libs/util/code-gen-types/package.json, libs/util/code-gen-types/src/blueprint-types/blueprint-plugin-events-params.types.ts, libs/util/code-gen-types/src/blueprint-types/blueprint-plugin-events.types.ts, libs/util/code-gen-types/src/blueprint-types/blueprint-plugins.types.ts, packages/amplication-server/src/core/entity/entity.service.ts, packages/amplication-server/src/core/serviceSettings/serviceSettings.service.ts, packages/generator-blueprints/jest.config.ts, packages/generator-blueprints/package.json, packages/generator-blueprints/src/blueprint/create-blueprint.ts, packages/generator-blueprints/src/blueprint/create-module.ts, packages/generator-blueprints/src/blueprint/create-modules.ts, packages/generator-blueprints/src/create-data-service.ts, packages/generator-blueprints/src/dsg-context.ts, packages/generator-blueprints/src/utils/read-static-files.ts
Close: #9660
add implementation for the new plugin events per module
=> feat(bpg):generate blueprint modules

.github/workflows/ci.yml, .github/workflows/deployment.container.template.yml, .github/workflows/deployment.production.yml, .github/workflows/deployment.static.template.yml, .github/workflows/dsg-release-notes-generator.yml, .github/workflows/nx.template.yml, .github/workflows/release.blueprint-dsg.production.yml, .github/workflows/release.dsg.production.yml, .github/workflows/release.template.yml
=> chore(ci): upgrade runner image to 22.04 and github actions to v4

packages/amplication-client/src/Resource/git/ResourceGitSettingsPage.tsx
Close: https://github.com/amplication/amplication/issues/9684
=> feat(client):remove sync dialog after connecting to git repo

packages/amplication-client/src/PrivatePluginVersion/NewPrivatePluginVersion.tsx, packages/amplication-client/src/PrivatePluginVersion/PrivatePluginDevVersion.tsx, packages/amplication-client/src/PrivatePluginVersion/PrivatePluginVersion.tsx, packages/amplication-client/src/PrivatePluginVersion/PrivatePluginVersionForm.tsx, packages/amplication-client/src/PrivatePluginVersion/PrivatePluginVersionList.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginForm.tsx, packages/amplication-client/src/PrivatePlugins/hooks/privatePluginQueries.ts, packages/amplication-server/src/core/block/block.service.ts
Close: https://github.com/amplication/amplication/issues/9681
=> feat(client): lock private plugin

packages/amplication-client/src/Components/UserBadge.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/hooks/privatePluginQueries.ts, packages/amplication-client/src/User/hooks/useCurrentUser.ts, packages/amplication-client/src/User/queries/userQueries.ts, packages/amplication-client/src/Workspaces/WorkspaceLayout.tsx, packages/amplication-client/src/context/appContext.tsx
Close: https://github.com/amplication/amplication/issues/9698
=> fix(client):only disable form when locked by other users

packages/amplication-client/src/PrivatePlugins/PrivatePluginForm.tsx
=> fix(client):exclude non input fields and disable plugin id

packages/amplication-client/src/CustomProperties/ResourcePropertiesBlock.tsx, packages/amplication-client/src/Platform/PlatformDashboard.scss, packages/amplication-client/src/Platform/PlatformDashboard.tsx, packages/amplication-client/src/Platform/PrivatePluginsTile.tsx, packages/amplication-client/src/Platform/TechDebtTile.tsx, packages/amplication-client/src/Platform/TemplatesTile.tsx, packages/amplication-client/src/Project/ProjectLayoutPage.tsx, packages/amplication-client/src/Resource/OverviewSecondaryTile/OverviewSecondaryTile.tsx, packages/amplication-client/src/routes/appRoutes.tsx
Close: #9702 
Add Platform Dashboard
=> feat(client):add platform dashboard

libs/ui/design-system/src/lib/components/Icon/Icon.tsx, libs/ui/design-system/src/lib/style/icon.scss, packages/amplication-client/src/Platform/PlatformDashboard.tsx, packages/amplication-client/src/Resource/OverviewSecondaryTile/OverviewSecondaryTile.tsx
=> style(client):update overview tiles

packages/amplication-client/src/PrivatePlugins/NewPrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePlugin.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginGitSettings.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginList.tsx, packages/amplication-client/src/PrivatePlugins/PrivatePluginsPage.tsx, packages/amplication-client/src/PrivatePlugins/hooks/usePrivatePlugin.tsx, packages/amplication-client/src/Resource/OverviewSecondaryTile/OverviewSecondaryTile.tsx, packages/amplication-client/src/routes/appRoutes.tsx
Close: https://github.com/amplication/amplication/issues/9706
=> feat(client):add tabs to private plugins

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceHeader.tsx, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceNavigation.scss, packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceNavigation.tsx
Close: https://github.com/amplication/amplication/issues/9708
=> feat(client):do not show resource selector and breadcrumbs on platform console

packages/amplication-client/src/OutdatedVersionAlerts/AlertLink.tsx, packages/amplication-client/src/OutdatedVersionAlerts/OutdatedVersionAlertListDataColumns.tsx, packages/amplication-client/src/OutdatedVersionAlerts/hooks/useOutdatedVersionAlerts.ts
=> feat(client): Add tech debt routing and project context support

packages/amplication-client/src/Workspaces/WorkspaceHeader/WorkspaceNavigation.tsx, packages/amplication-server/src/core/outdatedVersionAlert/outdatedVersionAlert.service.ts
Close: https://github.com/amplication/amplication/issues/9716
=> style(client):no wrap for workspace name

packages/amplication-client/src/Catalog/queries/catalogQueries.ts, packages/amplication-client/src/Resource/ResourceFormPage.tsx, packages/amplication-client/src/Workspaces/DeleteResourceButton.tsx, packages/amplication-client/src/util/version.ts, packages/amplication-server/src/util/version.ts
=> feat(client): Add resource template deletion validation

packages/generator-blueprints/Dockerfile, packages/generator-blueprints/Dockerfile.dev
Close: https://github.com/amplication/amplication/issues/9727
=> feat(bpg):add csharpier to the docker image to be available for plugin usage

packages/amplication-server/src/core/project/project.service.ts, packages/amplication-server/src/core/resource/resource.resolver.ts, packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/amplication/issues/9731
=> fix(server):use unique project name to avoid conflict with resources

packages/amplication-server/src/core/blueprint/blueprint.service.ts
Close: https://github.com/amplication/amplication/issues/9733
=> fix(server): delete blueprint when project is deleted

packages/amplication-server/src/core/privatePlugin/privatePlugin.service.ts
Close: https://github.com/amplication/amplication/issues/9742
=> fix(server):do not filter by blueprint for other engines

packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx
Close: https://github.com/amplication/amplication/issues/9746
=> fix(client):disable button after save

packages/amplication-client/src/Plugins/InstalledPluginSettings.tsx, packages/generator-blueprints/package.json
=> Version 3.12.4

packages/amplication-client/src/Blueprints/ResourceSelectField.tsx, packages/amplication-client/src/Catalog/CatalogContext.tsx, packages/amplication-client/src/Catalog/CatalogGrid.tsx, packages/amplication-client/src/Catalog/hooks/useCatalog.ts
Close: https://github.com/amplication/amplication/issues/9740
=> feat(client):use resourceSelectField without cache

ee/packages/git-sync-manager/src/models.ts, libs/util/code-gen-types/src/models.ts, packages/amplication-cli/src/models.ts, packages/amplication-client/src/Blueprints/BlueprintRelationAddButton.tsx, packages/amplication-client/src/Blueprints/BlueprintRelationForm.tsx, packages/amplication-client/src/Blueprints/ResourceSelectField.tsx, packages/amplication-client/src/Blueprints/queries/blueprintsQueries.ts, packages/amplication-client/src/Relation/ResourceRelationForm.tsx, packages/amplication-client/src/Relation/ResourceRelations.tsx, packages/amplication-client/src/Relation/hooks/useResourceRelations.tsx, packages/amplication-client/src/models.ts, packages/amplication-server/src/core/blueprint/blueprint.service.ts, packages/amplication-server/src/core/blueprint/dto/BlueprintRelationUpsertInput.ts, packages/amplication-server/src/models/BlueprintRelation.ts, packages/amplication-server/src/schema.graphql, packages/data-service-generator/src/models.ts, packages/generator-blueprints/src/models.ts
Close: https://github.com/amplication/amplication/issues/9738
=> feat(client): Add project and build constraints to blueprint relations

packages/amplication-server/src/core/build/build.service.spec.ts, packages/amplication-server/src/core/build/build.service.ts, packages/amplication-server/src/core/resource/resource.service.spec.ts, packages/amplication-server/src/core/resource/resource.service.ts
Close: https://github.com/amplication/amplication/issues/9735
=> feat(server): include resource data from all related resources recursively 

packages/amplication-prisma-db/prisma/migrations/20250311123220_migration/migration.sql, packages/amplication-prisma-db/prisma/schema.prisma, packages/amplication-server/src/core/blueprint/blueprint.module.ts, packages/amplication-server/src/core/blueprint/blueprint.service.spec.ts, packages/amplication-server/src/core/blueprint/blueprint.service.ts, packages/amplication-server/src/core/relation/relation.module.ts, packages/amplication-server/src/core/relation/relation.service.ts
Close: https://github.com/amplication/amplication/issues/9758
=> feat(server):add relation cache table

.github/workflows/deployment.container.template.yml, .github/workflows/deployment.static.template.yml, .github/workflows/release.template.yml
https://github.com/amplication/amplication/issues/9770
This pull request changes the strategy around which branch deploys to what environment.
=> chore(ci): update deployment templates for environments

.github/workflows/deployment.container.template.yml, packages/amplication-plugin-api/src/pluginVersion/pluginVersion.service.ts
Remove extra logging, and test new CI/CD workflows for hotfix
=> refactor(pluginVersion): remove debug logging for existing versions

packages/data-service-generator/package.json
=> chore: add @amplication/ast-types dependency to data-service-generator
